### ISSUE TITLE
Support :restart across updates with new arguments added

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1237]
When `:restart` is used across an update, we get an `AttributeError` as the `Namespace` passed via `--json-args` doesn't have that attribute yet:

```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.5.0', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 153, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 97, in run
    server = ipc.send_or_listen(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/ipc.py", line 505, in send_or_listen
    args.target,
AttributeError: 'Namespace' object has no attribute 'target'
```

```
==== Commandline args ====
--json-args {"loglines": 2000, "qt_qmljsdebugger": null, "datadir": null, "session": null, "url": [], "debug_exit": false, "nowindow": false, "temp_settings": [], "command": [], "loglevel": "info", "basedir": null, "logfilter": null, "qt_style": null, "cachedir": null, "no_err_windows": false, "debug": false, "qt_stylesheet": null, "color": true, "json_args": null, "pdb_postmortem": false, "qt_reverse": null, "confdir": null, "qt_name": null, "harfbuzz": "auto", "relaxed_config": false, "qt_widgetcount": null, "version": false, "override_restore": true, "temp_basedir": false}
```

**Comment by The-Compiler** [comment]
Duplicate of #6091, fixed in 44042358f722775648e7f0ff361aa4dfbe7517d7.
