### ISSUE TITLE
"ValueError: No valid config value found" when setting ValueList via -s

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1283]
on 67efd1c5e0ec39ec0cf1ee6eba9d025f50ee2c80:

```
$ qutebrowser --debug --temp-basedir -s 'searchengines' 'DEFAULT' 'foo{}' :quit`
[...]
20:31:29 DEBUG    destroy    config:save:785 Saving config to /tmp/qutebrowser-basedir-7xcke_je/config/qutebrowser.conf
20:31:29 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 200, in _process_args
    process_pos_args(args.command)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 265, in process_pos_args
    commandrunner.run_safely_init(cmd[1:])
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 266, in run_safely_init
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 249, in run
    result.cmd.run(self._win_id, args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 505, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 669, in shutdown
    self._shutdown(status, restart=restart)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 699, in _shutdown
    save_manager.save(key, is_exit=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/savemanager.py", line 175, in save
    silent=silent, force=force)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/savemanager.py", line 100, in save
    self._save_handler()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 787, in save
    f.write(str(self))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 391, in __str__
    lines += self._str_items(sect)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 445, in _str_items
    value = option.value(startlayer='conf')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/value.py", line 81, in value
    raise ValueError("No valid config value found!")
```

**Comment by The-Compiler** [comment]
This will be fixed with the new config.
