### ISSUE TITLE
Crash when unbinding <Esc> in passthrough mode

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1340]
When adding this to `keys.conf`:

``` ini
[passthrough]
<unbound>
    <Escape>
```

We get:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 206, in unbind
    del sect[key]
KeyError: '<Escape>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 155, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 110, in run
    init(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 137, in init
    _init_modules(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 402, in _init_modules
    config.init(qApp)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 254, in init
    _init_key_config(parent)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 187, in _init_key_config
    parent=parent)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 99, in __init__
    self._read(relaxed)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 298, in _read
    self._read_keybinding(line)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 361, in _read_keybinding
    self._add_binding(self._cur_section, line, self._cur_command)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 371, in _add_binding
    self.unbind(keychain, mode=sectname)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 209, in unbind
    "'{}'!".format(key, mode))
qutebrowser.commands.cmdexc.CommandError: Can't find binding '<Escape>' in section 'passthrough'!
```

**Comment by Carpetsmoker** [comment]
Can no longer reproduce this in 9cd2c9a

**Comment by The-Compiler** [comment]
I can reproduce this with `<Escape>` (not `<Esc>` like mentioned above earlier).
