### ISSUE TITLE
:open -t without URL crashes when general -> startpage is set to multiple URLs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1358]
```
$ qutebrowser --temp-basedir -s general startpage https://duckduckgo.com,qutebrowser.org  ':open -t'
15:41:59 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 200, in _process_args
    process_pos_args(args.command)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 265, in process_pos_args
    commandrunner.run_safely_init(cmd[1:])
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 266, in run_safely_init
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 249, in run
    result.cmd.run(self._win_id, args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 505, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 243, in openurl
    url = config.get('general', 'default-page')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 128, in get
    return objreg.get('config').get(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.4/functools.py", line 458, in wrapper
    result = user_function(*args, **kwds)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 672, in get
    newval = val.typ.transform(newval)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1234, in transform
    return urlutils.fuzzy_url(value, do_search=False)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/urlutils.py", line 195, in fuzzy_url
    raise InvalidUrlError(url)
qutebrowser.utils.urlutils.InvalidUrlError: Invalid URL
```

This is due to `default-page` (or substitutions in general) not being re-validated when the value being substituted changes.

**Comment by The-Compiler** [comment]
This will be fixed by the new config.
