### ISSUE TITLE
Segfault when answering SSL question with context menu open

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1644]
On Qt 5.7 with current git head, this segfaults:
- Open www.badssl.com
- Click "expired"
- Open a context menu
- Press esc to answer the question

stacktrace:

```
#0  QEventLoop::processEvents (this=this@entry=0x1dd8190, flags=flags@entry=...) at kernel/qeventloop.cpp:132
#1  0x00007ffff25230ea in QEventLoop::exec (this=0x1dd8190, flags=...) at kernel/qeventloop.cpp:210
#2  0x00007ffff2ae13f0 in meth_QEventLoop_exec_ (sipSelf=0x7fff79734828, sipArgs=0x7fffd5817978, sipKwds=0x0) at sipQtCoreQEventLoop.cpp:359
#3  0x00007ffff79ba8c9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#4  0x00007ffff7a3247b in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#5  0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#6  0x00007ffff7a2fb0e in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#7  0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#8  0x00007ffff7a333a3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#9  0x00007ffff799e008 in ?? () from /usr/lib/libpython3.5m.so.1.0
#10 0x00007ffff79732d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#11 0x00007ffff7989d44 in ?? () from /usr/lib/libpython3.5m.so.1.0
#12 0x00007ffff79732d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#13 0x00007ffff7a29a87 in PyEval_CallObjectWithKeywords () from /usr/lib/libpython3.5m.so.1.0
#14 0x00007ffff2beee2c in PyQtSlot::call (this=0xf5fae0, callable=0x7fffd5949508, args=0x7fffd58f3248) at ../qpy/QtCore/qpycore_pyqtslot.cpp:237
#15 0x00007ffff2beeb09 in PyQtSlot::invoke (this=0xf5fae0, qargs=0x1d32ce0, self=0x7fffc2e17708, result=0x0, no_receiver_check=false) at ../qpy/QtCore/qpycore_pyqtslot.cpp:153
#16 0x00007ffff2bee856 in PyQtSlot::invoke (this=0xf5fae0, qargs=0x1d32cd0, self=0x7fffc2e17708, result=0x0) at ../qpy/QtCore/qpycore_pyqtslot.cpp:83
#17 0x00007ffff2bea379 in qt_metacall_worker (pySelf=0x7fffc2e17708, pytype=0xf60188, base=0x7ffff2e82880 <sipTypeDef_QtCore_QObject>, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x1d32cd0)
    at ../qpy/QtCore/qpycore_qobject_helpers.cpp:110
#18 0x00007ffff2bea19c in qpycore_qobject_qt_metacall (pySelf=0x7fffc2e17708, base=0x7ffff2e82880 <sipTypeDef_QtCore_QObject>, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x1d32cd0)
    at ../qpy/QtCore/qpycore_qobject_helpers.cpp:69
#19 0x00007ffff2a7fd06 in sipQObject::qt_metacall (this=0x1dd2b70, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x1d32cd0) at sipQtCoreQObject.cpp:407
#20 0x00007ffff2550694 in QMetaObject::activate (sender=0x181a960, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3755
#21 0x00007ffff2bf45f9 in do_emit (qtx=0x181a960, signal_index=6, parsed_signature=0xda0b30, docstring=0xdc66b8 "MessageBridge.s_question[Question, bool]", sigargs=0x7fffd58d0808)
    at ../qpy/QtCore/qpycore_pyqtboundsignal.cpp:723
#22 0x00007ffff2bf430a in pyqtBoundSignal_emit (self=0x7fffd57cf288, args=0x7fffd58d0808) at ../qpy/QtCore/qpycore_pyqtboundsignal.cpp:664
#23 0x00007ffff79ba8a9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#24 0x00007ffff7a3247b in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#25 0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#26 0x00007ffff7a2fb0e in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#27 0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#28 0x00007ffff7a2fb0e in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#29 0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#30 0x00007ffff7a333a3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#31 0x00007ffff799e008 in ?? () from /usr/lib/libpython3.5m.so.1.0
#32 0x00007ffff79732d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#33 0x00007ffff7989d44 in ?? () from /usr/lib/libpython3.5m.so.1.0
#34 0x00007ffff79732d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#35 0x00007ffff7a29a87 in PyEval_CallObjectWithKeywords () from /usr/lib/libpython3.5m.so.1.0
#36 0x00007ffff2beee2c in PyQtSlot::call (this=0xe3bfd0, callable=0x7fffd5949a48, args=0x7fffd58cd1c8) at ../qpy/QtCore/qpycore_pyqtslot.cpp:237
#37 0x00007ffff2beeb09 in PyQtSlot::invoke (this=0xe3bfd0, qargs=0x7fffffffc890, self=0x7fffc2dd8828, result=0x0, no_receiver_check=false) at ../qpy/QtCore/qpycore_pyqtslot.cpp:153
#38 0x00007ffff2bee856 in PyQtSlot::invoke (this=0xe3bfd0, qargs=0x7fffffffc880, self=0x7fffc2dd8828, result=0x0) at ../qpy/QtCore/qpycore_pyqtslot.cpp:83
#39 0x00007ffff2bea379 in qt_metacall_worker (pySelf=0x7fffc2dd8828, pytype=0xf1fc28, base=0x7fffe7c4a520 <sipTypeDef_QtNetwork_QNetworkAccessManager>, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffc880)
    at ../qpy/QtCore/qpycore_qobject_helpers.cpp:110
#40 0x00007ffff2bea19c in qpycore_qobject_qt_metacall (pySelf=0x7fffc2dd8828, base=0x7fffe7c4a520 <sipTypeDef_QtNetwork_QNetworkAccessManager>, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffc880)
    at ../qpy/QtCore/qpycore_qobject_helpers.cpp:69
#41 0x00007fffe79d45c2 in sipQNetworkAccessManager::qt_metacall (this=0x1e56c00, _c=QMetaObject::InvokeMetaMethod, _id=2, _a=0x7fffffffc880) at sipQtNetworkQNetworkAccessManager.cpp:182
#42 0x00007ffff2550694 in QMetaObject::activate (sender=0x1e56c00, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffc880) at kernel/qobject.cpp:3755
#43 0x00007ffff2550e17 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7fffe7935680 <QNetworkAccessManager::staticMetaObject>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffc880)
    at kernel/qobject.cpp:3602
#44 0x00007fffe7632177 in QNetworkAccessManager::sslErrors (this=<optimized out>, _t1=<optimized out>, _t2=...) at .moc/moc_qnetworkaccessmanager.cpp:387
#45 0x00007fffe7632cbd in QNetworkAccessManagerPrivate::_q_replySslErrors (this=<optimized out>, errors=...) at access/qnetworkaccessmanager.cpp:1364
#46 0x00007fffe763608d in QNetworkAccessManager::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qnetworkaccessmanager.cpp:179
#47 0x00007ffff25504f9 in QMetaObject::activate (sender=0x274a370, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffca00) at kernel/qobject.cpp:3740
#48 0x00007ffff2550e17 in QMetaObject::activate (sender=<optimized out>, m=m@entry=0x7fffe79381a0 <QNetworkReply::staticMetaObject>, local_signal_index=local_signal_index@entry=4, argv=argv@entry=0x7fffffffca00)
    at kernel/qobject.cpp:3602
#49 0x00007fffe76ebe25 in QNetworkReply::sslErrors (this=<optimized out>, _t1=...) at .moc/moc_qnetworkreply.cpp:387
#50 0x00007fffe7653caa in QNetworkReplyHttpImplPrivate::replySslErrors (this=0x3213420, list=..., ignoreAll=0x7fff7baf233f, toBeIgnored=0x7fff7baf2340) at access/qnetworkreplyhttpimpl.cpp:1350
#51 0x00007fffe76ecc7b in QNetworkReplyHttpImpl::qt_static_metacall (_o=<optimized out>, _c=<optimized out>, _id=<optimized out>, _a=<optimized out>) at .moc/moc_qnetworkreplyhttpimpl_p.cpp:260
#52 0x00007ffff2551359 in QObject::event (this=0x274a370, e=<optimized out>) at kernel/qobject.cpp:1263
#53 0x00007fffeadc2e3c in QApplicationPrivate::notify_helper (this=<optimized out>, receiver=0x274a370, e=0x7fff5c0c4650) at kernel/qapplication.cpp:3799
#54 0x00007fffeadca5b1 in QApplication::notify (this=0x1288830, receiver=0x274a370, e=0x7fff5c0c4650) at kernel/qapplication.cpp:3556
#55 0x00007fffeb68cffe in sipQApplication::notify (this=0x1288830, a0=0x274a370, a1=0x7fff5c0c4650) at sipQtWidgetsQApplication.cpp:352
#56 0x00007ffff2524c90 in QCoreApplication::notifyInternal2 (receiver=0x274a370, event=event@entry=0x7fff5c0c4650) at kernel/qcoreapplication.cpp:988
#57 0x00007ffff252740d in QCoreApplication::sendEvent (event=0x7fff5c0c4650, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#58 QCoreApplicationPrivate::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xd4cc50) at kernel/qcoreapplication.cpp:1649
#59 0x00007ffff2527878 in QCoreApplication::sendPostedEvents (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1503
#60 0x00007ffff2579183 in postEventSourceDispatch (s=0x12b5180) at kernel/qeventdispatcher_glib.cpp:276
#61 0x00007ffff366ddd7 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#62 0x00007ffff366e040 in ?? () from /usr/lib/libglib-2.0.so.0
#63 0x00007ffff366e0ec in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#64 0x00007ffff257958f in QEventDispatcherGlib::processEvents (this=0x12b4430, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#65 0x00007ffff25230ea in QEventLoop::exec (this=this@entry=0x7fffffffd060, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#66 0x00007ffff252b5dc in QCoreApplication::exec () at kernel/qcoreapplication.cpp:1261
#67 0x00007fffeb68f78e in meth_QApplication_exec_ (sipArgs=0x7ffff7fb7048) at sipQtWidgetsQApplication.cpp:1506
#68 0x00007ffff79ba8a9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#69 0x00007ffff7a3247b in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#70 0x00007ffff7a3264a in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#71 0x00007ffff7a3264a in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#72 0x00007ffff7a3264a in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#73 0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#74 0x00007ffff7a333a3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#75 0x00007ffff7a333cb in PyEval_EvalCode () from /usr/lib/libpython3.5m.so.1.0
#76 0x00007ffff7a2763d in ?? () from /usr/lib/libpython3.5m.so.1.0
#77 0x00007ffff79ba8a9 in PyCFunction_Call () from /usr/lib/libpython3.5m.so.1.0
#78 0x00007ffff7a3247b in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#79 0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#80 0x00007ffff7a2fb0e in PyEval_EvalFrameEx () from /usr/lib/libpython3.5m.so.1.0
#81 0x00007ffff7a332c3 in ?? () from /usr/lib/libpython3.5m.so.1.0
#82 0x00007ffff7a333a3 in PyEval_EvalCodeEx () from /usr/lib/libpython3.5m.so.1.0
#83 0x00007ffff799e008 in ?? () from /usr/lib/libpython3.5m.so.1.0
#84 0x00007ffff79732d7 in PyObject_Call () from /usr/lib/libpython3.5m.so.1.0
#85 0x00007ffff7a6a491 in ?? () from /usr/lib/libpython3.5m.so.1.0
#86 0x00007ffff7a6ad71 in Py_Main () from /usr/lib/libpython3.5m.so.1.0
#87 0x0000000000400af0 in main ()
```

**Comment by amacfie** [comment]
Fixed?

**Comment by The-Compiler** [comment]
Can't reproduce anymore - I guess this got fixed in Qt at some point.
