### ISSUE TITLE
configparser InterpolationDepthError is not handled

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1695]
```
$ qutebrowser --temp-basedir -s colors tabs.bg.selected.odd '${tabs.bg.selected.even}' -s colors tabs.bg.selected.even '${tabs.bg.selected.odd}'
18:03:38 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 192, in _process_args
    window = mainwindow.MainWindow()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/mainwindow.py", line 139, in __init__
    self._downloadview = downloadview.DownloadView(self.win_id)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloadview.py", line 78, in __init__
    style.set_register_stylesheet(self)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/style.py", line 58, in set_register_stylesheet
    qss = get_stylesheet(obj.STYLESHEET)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/style.py", line 43, in get_stylesheet
    colordict = ColorDict(config.section('colors'))
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/collections/__init__.py", line 977, in __init__
    self.update(dict)
  File "/home/florian/proj/qutebrowser/git/.venv/lib/python3.5/_collections_abc.py", line 773, in update
    self[key] = other[key]
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 842, in __getitem__
    return self.conf.get(self.name, key)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 675, in get
    val.value(), mapping)
  File "/usr/lib64/python3.5/configparser.py", line 454, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 510, in _interpolate_some
    depth + 1)
  File "/usr/lib64/python3.5/configparser.py", line 469, in _interpolate_some
    raise InterpolationDepthError(option, section, rawval)
configparser.InterpolationDepthError: Recursion limit exceeded in value substitution: option 'tabs.bg.selected.odd' in section 'colors' contains an interpolation key which cannot be substituted in 10 steps. Raw value: '${tabs.bg.selected.even}'
```

**Comment by mbjd** [comment]
Seems like I had the same bug (https://github.com/The-Compiler/qutebrowser/issues/1696). Feel free to delete it it it's of no use

**Comment by The-Compiler** [comment]
Not an issue anymore with the new config.
