### ISSUE TITLE
Deleted C++ object: NetworkManager in NetworkManager._set_cookiejar (after setting private-browsing after closing tab with Qt 5.2)

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#1774]
This tests reproduces the issue on Qt 5.2:

``` bdd
    Scenario: Setting private browsing after opening/closing tabs
        Given I have a fresh instance
        When I open data/hello.txt
        And I open data/hello.txt in a new tab
        And I run :tab-close
        And I set general -> private-browsing to true
        Then no crash should happen
```

```
15:47:22 DEBUG    config     config:_changed:551 Config option changed: general -> private-browsing
15:47:22 DEBUG    save       savemanager:mark_dirty:72 Marking config as dirty.
15:47:22 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/UX/pnagyux/code/qutebrowser/qutebrowser/config/config.py", line 119, in wrapper
    return func(wrapper_self)
  File "/home/UX/pnagyux/code/qutebrowser/qutebrowser/browser/webkit/network/networkmanager.py", line 378, in on_config_changed
    self._set_cookiejar(private=True)
  File "/home/UX/pnagyux/code/qutebrowser/qutebrowser/browser/webkit/network/networkmanager.py", line 192, in _set_cookiejar
    self.setCookieJar(cookie_jar)
RuntimeError: wrapped C/C++ object of type NetworkManager has been deleted
```

**Comment by The-Compiler** [comment]
Qt 5.2 support has been dropped.
