### ISSUE TITLE
Unhandled CommandError when unbinding binding from another section

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2079]
When adding this to the default config:

``` ini
[passthrough]
<unbound>
    <Escape>
```

we get:

```
20:30:58 ERROR: Uncaught exception     
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 223, in unbind
    del sect[key]
KeyError: '<escape>'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 162, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 110, in run
    init(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 137, in init
    _init_modules(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 389, in _init_modules
    config.init(qApp)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 255, in init
    _init_key_config(parent)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 188, in _init_key_config
    parent=parent)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 99, in __init__
    self._read(relaxed)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 315, in _read
    self._read_keybinding(line)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 392, in _read_keybinding
    self._add_binding(self._cur_section, line, self._cur_command)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 405, in _add_binding
    self.unbind(keychain, mode=sectname)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 226, in unbind
    "'{}'!".format(key, mode))
qutebrowser.commands.cmdexc.CommandError: Can't find binding '<escape>' in section 'passthrough'!
```

**Comment by The-Compiler** [comment]
`<unbound>` doesn't exist with the new config anymore
