### ISSUE TITLE
Multiple issues when smashing df

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2098]
With QtWebEngine with multiple tabs open, when doing `dfdfdfdfdf` we get this:

```
10:38:55 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginetab.py", line 398, in _js_cb_multiple
    for js_elem in js_elems:
TypeError: 'NoneType' object is not iterable
```

And then a segfault in the exception handler and a giant stack:

```
#0  0x00007fc55cc9bf5f in raise () at /usr/lib/libpthread.so.0
#1  0x00007fc55cc9c080 in <signal handler called> () at /usr/lib/libpthread.so.0
#2  0x00007fc55cf1029e in PyObject_Call () at /usr/lib/libpython3.5m.so.1.0
#3  0x00007fc55cfc6a87 in PyEval_CallObjectWithKeywords () at /usr/lib/libpython3.5m.so.1.0
#4  0x00007fc5566a5b94 in  () at /home/florian/proj/qutebrowser/git/.venv/lib/python3.5/site-packages/sip.so
#5  0x00007fc54d13c661 in <lambda(const QVariant&)>::operator()(const QVariant &) const (__closure=0xfa917f0, arg=...) at /tmp/makepkg/pyqt5-debug/src/PyQt5_gpl-5.7/sip/QtWebEngineWidgets/qwebenginepage.sip:283
#6  0x00007fc54d13f7fd in QtWebEnginePrivate::QWebEngineCallbackPrivate<const QVariant&, meth_QWebEnginePage_runJavaScript(PyObject*, PyObject*)::<lambda(const QVariant&)> >::operator()(const QVariant &) (this=0xfa917e0, value=...)
    at /usr/include/qt/QtWebEngineCore/qwebenginecallback.h:72
#7  0x00007fc54cebe901 in QtWebEngineCore::CallbackDirectory::invokeInternal<QVariant const&>(unsigned long long, QVariant const&) (result=..., callbackId=<optimized out>, this=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/api/qwebenginecallback_p.h:173
#8  0x00007fc54cebe901 in QtWebEngineCore::CallbackDirectory::invoke(unsigned long long, QVariant const&) (result=..., callbackId=<optimized out>, this=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/api/qwebenginecallback_p.h:113
#9  0x00007fc54cebe901 in QWebEnginePagePrivate::didRunJavaScript(unsigned long long, QVariant const&) (this=this@entry=0x39288e0, requestId=requestId@entry=6, result=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/webenginewidgets/api/qwebenginepage.cpp:304
#10 0x00007fc5480d68d6 in QtWebEngineCore::callbackOnEvaluateJS(QtWebEngineCore::WebContentsAdapterClient*, quint64, base::Value const*) (adapterClient=0x39288e0, requestId=6, result=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/web_contents_adapter.cpp:181
#11 0x00007fc548c750fe in base::Callback<void (base::Value const*)>::Run(base::Value const* const&) const (args#0=@0x7ffc96272b40: 0xb99e350, this=0xe4f3998)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/callback.h:394
#12 0x00007fc548c750fe in content::RenderFrameHostImpl::OnJavaScriptExecuteResponse(int, base::ListValue const&) (this=this@entry=0x392df70, id=13, result=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_impl.cc:1341
#13 0x00007fc548c831d9 in base::DispatchToMethodImpl<content::RenderFrameHostImpl, void (content::RenderFrameHostImpl::*)(int, base::ListValue const&), int, base::ListValue, 0ul, 1ul>(content::RenderFrameHostImpl*, void (content::RenderFrameHostImpl::*)(int, base::ListValue const&), base::Tuple<int, base::ListValue> const&, base::IndexSequence<0ul, 1ul>) (arg=..., method=<optimized out>, obj=0x392df70)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/tuple.h:252
#14 0x00007fc548c831d9 in base::DispatchToMethod<content::RenderFrameHostImpl, void (content::RenderFrameHostImpl::*)(int, base::ListValue const&), int, base::ListValue>(content::RenderFrameHostImpl*, void (content::RenderFrameHostImpl::*)(int, base::ListValue const&), base::Tuple<int, base::ListValue> const&) (arg=..., method=
    (void (content::RenderFrameHostImpl::*)(content::RenderFrameHostImpl * const, int, const base::ListValue &)) 0x7fc548c75080 <content::RenderFrameHostImpl::OnJavaScriptExecuteResponse(int, base::ListValue const&)>, obj=0x392df70) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/tuple.h:259
#15 0x00007fc548c831d9 in FrameHostMsg_JavaScriptExecuteResponse::Dispatch<content::RenderFrameHostImpl, content::RenderFrameHostImpl, void, void (content::RenderFrameHostImpl::*)(int, base::ListValue const&)>(IPC::Message const*, content::RenderFrameHostImpl*, content::RenderFrameHostImpl*, void*, void (content::RenderFrameHostImpl::*)(int, base::ListValue const&)) (sender=0x392df70, parameter=0x0, func=<optimized out>, obj=0x392df70, msg=0x7fc5045613c0)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/content/common/frame_messages.h:1201
#16 0x00007fc548c831d9 in content::RenderFrameHostImpl::OnMessageReceived(IPC::Message const&) (this=0x392df70, msg=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_impl.cc:524
#17 0x00007fc548d06686 in content::RenderProcessHostImpl::OnMessageReceived(IPC::Message const&) (this=0x35935a0, msg=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/content/browser/renderer_host/render_process_host_impl.cc:1723
#18 0x00007fc5496ebe24 in IPC::ChannelProxy::Context::OnDispatchMessage(IPC::Message const&) (this=0x3933180, message=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/ipc/ipc_channel_proxy.cc:293
#19 0x00007fc549add7e9 in base::Callback<void ()>::Run() const (this=0x7ffc962734b8) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/callback.h:394
#20 0x00007fc549add7e9 in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask const&) (this=this@entry=0x1b255e8, queue_function=queue_function@entry=0x7fc54bb067ad "MessageLoop::PostTask", pending_task=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/debug/task_annotator.cc:51
#21 0x00007fc549a86bb8 in base::MessageLoop::RunTask(base::PendingTask const&) (this=this@entry=0x1b25470, pending_task=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:486
#22 0x00007fc549a87829 in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) (this=this@entry=0x1b25470, pending_task=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:495
#23 0x00007fc549a87cf2 in base::MessageLoop::DoWork() (this=0x1b25470) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:607
#24 0x00007fc5480924a5 in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::handleScheduledWork (this=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/content_browser_client_qt.cpp:193
#25 0x00007fc5480924a5 in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::customEvent(QEvent*) (this=0x1b25dd0, ev=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/content_browser_client_qt.cpp:175
#26 0x00007fc55adb5483 in QObject::event(QEvent*) (this=0x1b25dd0, e=<optimized out>) at kernel/qobject.cpp:1285
#27 0x00007fc54fcdbe0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x1b25dd0, e=0xfab4200) at kernel/qapplication.cpp:3799
#28 0x00007fc54fce3581 in QApplication::notify(QObject*, QEvent*) (this=0x11b6e70, receiver=0x1b25dd0, e=0xfab4200) at kernel/qapplication.cpp:3556
#29 0x00007fc5505a755c in sipQApplication::notify(QObject*, QEvent*) (this=0x11b6e70, a0=0x1b25dd0, a1=0xfab4200) at sipQtWidgetsQApplication.cpp:352
#30 0x00007fc55ad88df0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x1b25dd0, event=event@entry=0xfab4200) at kernel/qcoreapplication.cpp:988
#31 0x00007fc55ad8b57d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0xfab4200, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#32 0x00007fc55ad8b57d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xfc5d10) at kernel/qcoreapplication.cpp:1649
#33 0x00007fc55ad8b9e8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1503
#34 0x00007fc55addd313 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x167a8e0) at kernel/qeventdispatcher_glib.cpp:276
#35 0x00007fc5595f9587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#36 0x00007fc5595f97f0 in  () at /usr/lib/libglib-2.0.so.0
#37 0x00007fc5595f989c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#38 0x00007fc55addd71f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x167afa0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#39 0x00007fc55ad8724a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffc96273b80, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#40 0x00007fc54fec86b7 in QDialog::exec() (this=0xcf3af80) at dialogs/qdialog.cpp:552
#41 0x00007fc5505c2b3c in meth_QDialog_exec_(PyObject*, PyObject*) (sipSelf=0x7fc4d4e61e58, sipArgs=0x7fc55d558048) at /tmp/makepkg/pyqt5-debug/src/PyQt5_gpl-5.7/sip/QtWidgets/qdialog.sip:57
#42 0x00007fc55cf578a9 in PyCFunction_Call () at /usr/lib/libpython3.5m.so.1.0
#43 0x00007fc55cfcf47b in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#44 0x00007fc55cfd02c3 in  () at /usr/lib/libpython3.5m.so.1.0
#45 0x00007fc55cfd03a3 in PyEval_EvalCodeEx () at /usr/lib/libpython3.5m.so.1.0
#46 0x00007fc55cf3b008 in  () at /usr/lib/libpython3.5m.so.1.0
#47 0x00007fc55cf102d7 in PyObject_Call () at /usr/lib/libpython3.5m.so.1.0
#48 0x00007fc55cf26d44 in  () at /usr/lib/libpython3.5m.so.1.0
#49 0x00007fc55cf102d7 in PyObject_Call () at /usr/lib/libpython3.5m.so.1.0
#50 0x00007fc55cfc6a87 in PyEval_CallObjectWithKeywords () at /usr/lib/libpython3.5m.so.1.0
#51 0x00007fc55cff08bd in PyErr_PrintEx () at /usr/lib/libpython3.5m.so.1.0
#52 0x00007fc55b4591f2 in pyqt5_err_print() () at ../qpy/QtCore/qpycore_public_api.cpp:66
#53 0x00007fc54d13c6bb in <lambda(const QVariant&)>::operator()(const QVariant &) const (__closure=0xfa917f0, arg=...) at /tmp/makepkg/pyqt5-debug/src/PyQt5_gpl-5.7/sip/QtWebEngineWidgets/qwebenginepage.sip:288
#54 0x00007fc54d13f7fd in QtWebEnginePrivate::QWebEngineCallbackPrivate<const QVariant&, meth_QWebEnginePage_runJavaScript(PyObject*, PyObject*)::<lambda(const QVariant&)> >::operator()(const QVariant &) (this=0xfa917e0, value=...)
    at /usr/include/qt/QtWebEngineCore/qwebenginecallback.h:72
#55 0x00007fc54cec0691 in QtWebEngineCore::CallbackDirectory::invokeEmptyInternal<QVariant const&>(QtWebEnginePrivate::QWebEngineCallbackPrivateBase<QVariant const&>*) (this=<optimized out>, callback=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/api/qwebenginecallback_p.h:185
#56 0x00007fc54cec0691 in QtWebEngineCore::CallbackDirectory::CallbackSharedDataPointer<QVariant const&>::invokeEmpty() (this=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/api/qwebenginecallback_p.h:242
#57 0x00007fc54cebe7c6 in QtWebEngineCore::CallbackDirectory::~CallbackDirectory() (this=0x3928968, __in_chrg=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/core/api/qwebenginecallback_p.h:87
#58 0x00007fc54cebe7c6 in QWebEnginePagePrivate::~QWebEnginePagePrivate() (this=0x39288e0, __in_chrg=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/webenginewidgets/api/qwebenginepage.cpp:123
#59 0x00007fc54cebe8a9 in QWebEnginePagePrivate::~QWebEnginePagePrivate() (this=0x39288e0, __in_chrg=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/webenginewidgets/api/qwebenginepage.cpp:127
#60 0x00007fc54ceb9e20 in QScopedPointerDeleter<QWebEnginePagePrivate>::cleanup(QWebEnginePagePrivate*) (pointer=<optimized out>) at /usr/include/qt/QtCore/qscopedpointer.h:60
#61 0x00007fc54ceb9e20 in QScopedPointer<QWebEnginePagePrivate, QScopedPointerDeleter<QWebEnginePagePrivate> >::~QScopedPointer() (this=0x39280b0, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qscopedpointer.h:107
#62 0x00007fc54ceb9e20 in QWebEnginePage::~QWebEnginePage() (this=0x39280a0, __in_chrg=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.7.0/src/webenginewidgets/api/qwebenginepage.cpp:620
#63 0x00007fc54d139a54 in sipQWebEnginePage::~sipQWebEnginePage() (this=0x39280a0, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEnginePage.cpp:196
#64 0x00007fc54d139a70 in sipQWebEnginePage::~sipQWebEnginePage() (this=0x39280a0, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEnginePage.cpp:199
#65 0x00007fc55adb2dd1 in QObjectPrivate::deleteChildren() (this=this@entry=0x39284a0) at kernel/qobject.cpp:1970
#66 0x00007fc54fd1e89b in QWidget::~QWidget() (this=0x3928420, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1687
#67 0x00007fc54d146ade in sipQWebEngineView::~sipQWebEngineView() (this=0x3928420, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEngineView.cpp:326
#68 0x00007fc54d146b00 in sipQWebEngineView::~sipQWebEngineView() (this=0x3928420, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEngineView.cpp:329
#69 0x00007fc55adb2dd1 in QObjectPrivate::deleteChildren() (this=this@entry=0x349a8e0) at kernel/qobject.cpp:1970
#70 0x00007fc54fd1e89b in QWidget::~QWidget() (this=0x35675b0, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1687
#71 0x00007fc55056356c in sipQWidget::~sipQWidget() (this=0x35675b0, __in_chrg=<optimized out>) at sipQtWidgetsQWidget.cpp:347
#72 0x00007fc55056358e in sipQWidget::~sipQWidget() (this=0x35675b0, __in_chrg=<optimized out>) at sipQtWidgetsQWidget.cpp:350
#73 0x00007fc55adb5500 in QObject::event(QEvent*) (this=this@entry=0x35675b0, e=e@entry=0xe459550) at kernel/qobject.cpp:1254
#74 0x00007fc54fd230eb in QWidget::event(QEvent*) (this=0x35675b0, event=0xe459550) at kernel/qwidget.cpp:9208
#75 0x00007fc5505650b0 in sipQWidget::event(QEvent*) (this=0x35675b0, a0=0xe459550) at sipQtWidgetsQWidget.cpp:1066
#76 0x00007fc54fcdbe0c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x35675b0, e=0xe459550) at kernel/qapplication.cpp:3799
#77 0x00007fc54fce3581 in QApplication::notify(QObject*, QEvent*) (this=0x11b6e70, receiver=0x35675b0, e=0xe459550) at kernel/qapplication.cpp:3556
#78 0x00007fc5505a755c in sipQApplication::notify(QObject*, QEvent*) (this=0x11b6e70, a0=0x35675b0, a1=0xe459550) at sipQtWidgetsQApplication.cpp:352
#79 0x00007fc55ad88df0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x35675b0, event=event@entry=0xe459550) at kernel/qcoreapplication.cpp:988
#80 0x00007fc55ad8b57d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0xe459550, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#81 0x00007fc55ad8b57d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xfc5d10) at kernel/qcoreapplication.cpp:1649
#82 0x00007fc55ad8b9e8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1503
#83 0x00007fc55addd313 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x167a8e0) at kernel/qeventdispatcher_glib.cpp:276
#84 0x00007fc5595f9587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#85 0x00007fc5595f97f0 in  () at /usr/lib/libglib-2.0.so.0
#86 0x00007fc5595f989c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#87 0x00007fc55addd71f in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x167afa0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#88 0x00007fc55ad8724a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffc96274ae0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:210
#89 0x00007fc55ad8f74c in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1261
#90 0x00007fc5505a9b5c in meth_QApplication_exec_(PyObject*, PyObject*) (sipArgs=0x7fc55d558048) at sipQtWidgetsQApplication.cpp:1506
#91 0x00007fc55cf578a9 in PyCFunction_Call () at /usr/lib/libpython3.5m.so.1.0
#92 0x00007fc55cfcf47b in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#93 0x00007fc55cfcf64a in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#94 0x00007fc55cfcf64a in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#95 0x00007fc55cfcf64a in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#96 0x00007fc55cfd02c3 in  () at /usr/lib/libpython3.5m.so.1.0
#97 0x00007fc55cfd03a3 in PyEval_EvalCodeEx () at /usr/lib/libpython3.5m.so.1.0
#98 0x00007fc55cfd03cb in PyEval_EvalCode () at /usr/lib/libpython3.5m.so.1.0
#99 0x00007fc55cfc463d in  () at /usr/lib/libpython3.5m.so.1.0
#100 0x00007fc55cf578a9 in PyCFunction_Call () at /usr/lib/libpython3.5m.so.1.0
#101 0x00007fc55cfcf47b in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#102 0x00007fc55cfd02c3 in  () at /usr/lib/libpython3.5m.so.1.0
#103 0x00007fc55cfccb0e in PyEval_EvalFrameEx () at /usr/lib/libpython3.5m.so.1.0
#104 0x00007fc55cfd02c3 in  () at /usr/lib/libpython3.5m.so.1.0
#105 0x00007fc55cfd03a3 in PyEval_EvalCodeEx () at /usr/lib/libpython3.5m.so.1.0
#106 0x00007fc55cf3b008 in  () at /usr/lib/libpython3.5m.so.1.0
#107 0x00007fc55cf102d7 in PyObject_Call () at /usr/lib/libpython3.5m.so.1.0
#108 0x00007fc55d007491 in  () at /usr/lib/libpython3.5m.so.1.0
#109 0x00007fc55d007d71 in Py_Main () at /usr/lib/libpython3.5m.so.1.0
#110 0x0000000000400af0 in main ()
```

**Comment by The-Compiler** [comment]
Another one:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 255, in on_keystring_updated
    hintmanager.handle_partial_key(keystr)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 754, in handle_partial_key
    for string, label in self._context.labels.items():
AttributeError: 'NoneType' object has no attribute 'labels'
```

**Comment by The-Compiler** [comment]
5bdd74138d897b034913d072f27dc9d5a496e865 fixed the first part, and the pushed commit should fix the rest.
