### ISSUE TITLE
Segfaults when showing download overwrite prompt with QtWebEngine mhtml downloads

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2288]
This seems to be quite rare, and the fix in d13809089fc62aea7ce063d1d809930a386d5a2c helped a lot. Stack with it reverted:

```
#0  0x00007f93c27a9f5f in raise () at /usr/lib/libpthread.so.0
#1  0x00007f93c27aa080 in <signal handler called> () at /usr/lib/libpthread.so.0
#2  0x00007f93a20aa8e2 in QQmlData::isSignalConnected(QAbstractDeclarativeData*, QObject const*, int) () at /usr/lib/libQt5Qml.so.5
#3  0x00007f93c0387be5 in QObjectPrivate::isDeclarativeSignalConnected(unsigned int) const (signal_index=4, this=<optimized out>) at kernel/qobject_p.h:265
#4  0x00007f93c0387be5 in QMetaObject::activate(QObject*, int, int, void**) (sender=0x22e04f8, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fff82709d40) at kernel/qobject.cpp:3615
#5  0x00007f93c0388ad7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=<optimized out>, m=m@entry=0x7f93c07a8ec0 <QIODevice::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7fff82709d40) at kernel/qobject.cpp:3602
#6  0x00007f93c03fe601 in QIODevice::channelReadyRead(int) (this=<optimized out>, _t1=<optimized out>) at .moc/moc_qiodevice.cpp:193
#7  0x00007f93b25f5b7c in QAbstractSocketPrivate::canReadNotification() (this=0x225a740) at socket/qabstractsocket.cpp:733
#8  0x00007f93b2601131 in QReadNotifier::event(QEvent*) (this=<optimized out>, e=<optimized out>) at socket/qnativesocketengine.cpp:1241
#9  0x00007f93aab883dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x21f7370, e=0x7fff8270a010) at kernel/qapplication.cpp:3745
#10 0x00007f93aab8fbf1 in QApplication::notify(QObject*, QEvent*) (this=0x1059710, receiver=0x21f7370, e=0x7fff8270a010) at kernel/qapplication.cpp:3502
#11 0x00007f93ab406bfe in sipQApplication::notify(QObject*, QEvent*) (this=0x1059710, a0=0x21f7370, a1=0x7fff8270a010) at sipQtWidgetsQApplication.cpp:232
#12 0x00007f93c035c8b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x21f7370, event=event@entry=0x7fff8270a010) at kernel/qcoreapplication.cpp:988
#13 0x00007f93c03b196d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fff8270a010, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#14 0x00007f93c03b196d in socketNotifierSourceDispatch(GSource*, GSourceFunc, gpointer) (source=0x10e8f80) at kernel/qeventdispatcher_glib.cpp:106
#15 0x00007f93bcc31587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#16 0x00007f93bcc317f0 in  () at /usr/lib/libglib-2.0.so.0
#17 0x00007f93bcc3189c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#18 0x00007f93c03b14bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x10e7b10, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#19 0x00007f93c035ad0a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x2367bb0, flags=...) at kernel/qeventloop.cpp:212
#20 0x00007f93c08ce9be in meth_QEventLoop_exec_(PyObject*, PyObject*, PyObject*) (sipSelf=0x7f9354053f78, sipArgs=0x7f9354055fd0, sipKwds=0x0) at sipQtCoreQEventLoop.cpp:352
#21 0x00007f93c1ff49bc in _PyCFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#22 0x00007f93c2003a0f in  () at /usr/lib/libpython3.6m.so.1.0
#23 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#24 0x00007f93c2002629 in  () at /usr/lib/libpython3.6m.so.1.0
#25 0x00007f93c200378a in  () at /usr/lib/libpython3.6m.so.1.0
#26 0x00007f93c2003af3 in  () at /usr/lib/libpython3.6m.so.1.0
#27 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#28 0x00007f93c2002629 in  () at /usr/lib/libpython3.6m.so.1.0
#29 0x00007f93c200301c in _PyFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#30 0x00007f93c2058a4e in _PyObject_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#31 0x00007f93c2059852 in _PyObject_Call_Prepend () at /usr/lib/libpython3.6m.so.1.0
#32 0x00007f93c205991b in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#33 0x00007f93c09cef56 in PyQtSlot::call(_object*, _object*) const (this=0xff3920, callable=0x7f93841d8048, args=0x7f938413b708) at ../qpy/QtCore/qpycore_pyqtslot.cpp:247
#34 0x00007f93c09cec51 in PyQtSlot::invoke(void**, _object*, void*, bool) const (this=0xff3920, qargs=0x225a670, self=0x7f9395d523a8, result=0x0, no_receiver_check=false) at ../qpy/QtCore/qpycore_pyqtslot.cpp:159
#35 0x00007f93c09ce98e in PyQtSlot::invoke(void**, _object*, void*) const (this=0xff3920, qargs=0x225a660, self=0x7f9395d523a8, result=0x0) at ../qpy/QtCore/qpycore_pyqtslot.cpp:85
#36 0x00007f93c09ca61c in qt_metacall_worker(sipSimpleWrapper*, PyTypeObject*, sipTypeDef*, QMetaObject::Call, int, void**) (pySelf=0x7f9395d523a8, pytype=0xff2e58, base=0x7f93c0c60fa0 <sipTypeDef_QtCore_QObject>, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x225a660) at ../qpy/QtCore/qpycore_qobject_helpers.cpp:118
#37 0x00007f93c09ca431 in qpycore_qobject_qt_metacall(_sipSimpleWrapper*, _sipTypeDef*, QMetaObject::Call, int, void**) (pySelf=0x7f9395d523a8, base=0x7f93c0c60fa0 <sipTypeDef_QtCore_QObject>, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x225a660) at ../qpy/QtCore/qpycore_qobject_helpers.cpp:68
#38 0x00007f93c0870ccd in sipQObject::qt_metacall(QMetaObject::Call, int, void**) (this=0x13591b0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x225a660) at sipQtCoreQObject.cpp:407
#39 0x00007f93c0388354 in QMetaObject::activate(QObject*, int, int, void**) (sender=0xee73f0, signalOffset=<optimized out>, local_signal_index=<optimized out>, argv=<optimized out>) at kernel/qobject.cpp:3755
#40 0x00007f93c09d45cc in do_emit(QObject*, int, Chimera::Signature const*, char const*, PyObject*) (qtx=0xee73f0, signal_index=7, parsed_signature=0xee4160, docstring=0xeee1d8 "GlobalMessageBridge.ask_question[Question, bool]", sigargs=0x7f938704d308) at ../qpy/QtCore/qpycore_pyqtboundsignal.cpp:770
#41 0x00007f93c09d42be in pyqtBoundSignal_emit(PyObject*, PyObject*) (self=0x7f938414c6e8, args=0x7f938704d308) at ../qpy/QtCore/qpycore_pyqtboundsignal.cpp:711
#42 0x00007f93c1ff491f in _PyCFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#43 0x00007f93c2003a0f in  () at /usr/lib/libpython3.6m.so.1.0
#44 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#45 0x00007f93c2002629 in  () at /usr/lib/libpython3.6m.so.1.0
#46 0x00007f93c200378a in  () at /usr/lib/libpython3.6m.so.1.0
#47 0x00007f93c2003af3 in  () at /usr/lib/libpython3.6m.so.1.0
#48 0x00007f93c1fc0ba9 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#49 0x00007f93c2002f9a in _PyFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#50 0x00007f93c2058a4e in _PyObject_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#51 0x00007f93c2059852 in _PyObject_Call_Prepend () at /usr/lib/libpython3.6m.so.1.0
#52 0x00007f93c205991b in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#53 0x00007f93c09cef56 in PyQtSlot::call(_object*, _object*) const (this=0x14123b0, callable=0x7f9384165708, args=0x7f9386f72e48) at ../qpy/QtCore/qpycore_pyqtslot.cpp:247
#54 0x00007f93c09cec51 in PyQtSlot::invoke(void**, _object*, void*, bool) const (this=0x14123b0, qargs=0x7fff8270bb88, self=0x7f9386f6d4c8, result=0x0, no_receiver_check=false) at ../qpy/QtCore/qpycore_pyqtslot.cpp:159
#55 0x00007f93c09ce98e in PyQtSlot::invoke(void**, _object*, void*) const (this=0x14123b0, qargs=0x7fff8270bb80, self=0x7f9386f6d4c8, result=0x0) at ../qpy/QtCore/qpycore_pyqtslot.cpp:85
#56 0x00007f93c09ca61c in qt_metacall_worker(sipSimpleWrapper*, PyTypeObject*, sipTypeDef*, QMetaObject::Call, int, void**) (pySelf=0x7f9386f6d4c8, pytype=0x13c4b08, base=0x7f93c0c60fa0 <sipTypeDef_QtCore_QObject>, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fff8270bb80)
    at ../qpy/QtCore/qpycore_qobject_helpers.cpp:118
#57 0x00007f93c09ca431 in qpycore_qobject_qt_metacall(_sipSimpleWrapper*, _sipTypeDef*, QMetaObject::Call, int, void**) (pySelf=0x7f9386f6d4c8, base=0x7f93c0c60fa0 <sipTypeDef_QtCore_QObject>, _c=QMetaObject::InvokeMetaMethod, _id=9, _a=0x7fff8270bb80) at ../qpy/QtCore/qpycore_qobject_helpers.cpp:68
#58 0x00007f93c0870ccd in sipQObject::qt_metacall(QMetaObject::Call, int, void**) (this=0x13b9b50, _c=QMetaObject::InvokeMetaMethod, _id=9, _a=0x7fff8270bb80) at sipQtCoreQObject.cpp:407
#59 0x00007f93c0388354 in QMetaObject::activate(QObject*, int, int, void**) (sender=sender@entry=0x140e100, signalOffset=<optimized out>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fff8270bb80) at kernel/qobject.cpp:3755
#60 0x00007f93c0388ad7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=sender@entry=0x140e100, m=m@entry=0x7f93a8b9a460 <QWebEngineProfile::staticMetaObject>, local_signal_index=local_signal_index@entry=0, argv=argv@entry=0x7fff8270bb80) at kernel/qobject.cpp:3602
#61 0x00007f93a898f12f in QWebEngineProfile::downloadRequested(QWebEngineDownloadItem*) (this=this@entry=0x140e100, _t1=<optimized out>, _t1@entry=0x14b67e0) at .moc/moc_qwebengineprofile.cpp:142
#62 0x00007f93a898679b in QWebEngineProfilePrivate::downloadRequested(QtWebEngineCore::BrowserContextAdapterClient::DownloadItemInfo&) (this=0x1408990, info=...) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/webenginewidgets/api/qwebengineprofile.cpp:199
#63 0x00007f93a35c4d50 in QtWebEngineCore::DownloadManagerDelegateQt::ChooseSavePath(content::WebContents*, base::FilePath const&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&, bool, base::Callback<void (base::FilePath const&, content::SavePageType, base::Callback<void (content::DownloadItem*), (base::internal::CopyMode)1> const&), (base::internal::CopyMode)1> const&) (this=this@entry=0x14e6b90, web_contents=<optimized out>, suggested_path=..., default_extension="html", can_save_as_complete=can_save_as_complete@entry=true, callback=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/core/download_manager_delegate_qt.cpp:261
#64 0x00007f93a3f44dba in content::SavePackage::ContinueGetSaveInfo(bool, base::FilePath const&) (this=0x14e67f0, can_save_as_complete=<optimized out>, suggested_path=...) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/content/browser/download/save_package.cc:1427
#65 0x00007f93a519446a in base::Callback<void (), (base::internal::CopyMode)1>::Run() const (this=0x14b7978) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/callback.h:389
#66 0x00007f93a519446a in base::(anonymous namespace)::PostTaskAndReplyRelay::RunReplyAndSelfDestruct() (this=0x14b7950) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/threading/post_task_and_reply_impl.cc:58
#67 0x00007f93a51c01bd in base::Callback<void (), (base::internal::CopyMode)1>::Run() const (this=0x7fff8270c048) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/callback.h:389
#68 0x00007f93a51c01bd in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask const&) (this=this@entry=0x13490f0, queue_function=queue_function@entry=0x7f93a73d617c "MessageLoop::PostTask", pending_task=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/debug/task_annotator.cc:51
#69 0x00007f93a5166a4d in base::MessageLoop::RunTask(base::PendingTask const&) (this=this@entry=0x1348f70, pending_task=...) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:493
#70 0x00007f93a516765d in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask const&) (this=this@entry=0x1348f70, pending_task=...) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:502
#71 0x00007f93a5167948 in base::MessageLoop::DoWork() (this=0x1348f70) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/3rdparty/chromium/base/message_loop/message_loop.cc:624
#72 0x00007f93a35ba5f5 in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::handleScheduledWork (this=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/core/content_browser_client_qt.cpp:207
#73 0x00007f93a35ba5f5 in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::customEvent(QEvent*) (this=0x1345c90, ev=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-opensource-src-5.8.0/src/core/content_browser_client_qt.cpp:189
#74 0x00007f93c0388fd3 in QObject::event(QEvent*) (this=0x1345c90, e=<optimized out>) at kernel/qobject.cpp:1285
#75 0x00007f93aab883dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x1345c90, e=0x7f9360002d30) at kernel/qapplication.cpp:3745
#76 0x00007f93aab8fbf1 in QApplication::notify(QObject*, QEvent*) (this=0x1059710, receiver=0x1345c90, e=0x7f9360002d30) at kernel/qapplication.cpp:3502
#77 0x00007f93ab406bfe in sipQApplication::notify(QObject*, QEvent*) (this=0x1059710, a0=0x1345c90, a1=0x7f9360002d30) at sipQtWidgetsQApplication.cpp:232
#78 0x00007f93c035c8b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x1345c90, event=event@entry=0x7f9360002d30) at kernel/qcoreapplication.cpp:988
#79 0x00007f93c035f03d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7f9360002d30, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#80 0x00007f93c035f03d in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0xf17ab0) at kernel/qcoreapplication.cpp:1648
#81 0x00007f93c035f4a8 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1502
#82 0x00007f93c03b10b3 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x10e8bc0) at kernel/qeventdispatcher_glib.cpp:276
#83 0x00007f93bcc31587 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#84 0x00007f93bcc317f0 in  () at /usr/lib/libglib-2.0.so.0
#85 0x00007f93bcc3189c in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#86 0x00007f93c03b14bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x10e7b10, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#87 0x00007f93c035ad0a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fff8270c710, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#88 0x00007f93c0363254 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1261
#89 0x00007f93ab4094a1 in meth_QApplication_exec_(PyObject*, PyObject*) (sipArgs=0x7f93c2b62048) at sipQtWidgetsQApplication.cpp:1506
#90 0x00007f93c1ff491f in _PyCFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#91 0x00007f93c2003a0f in  () at /usr/lib/libpython3.6m.so.1.0
#92 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#93 0x00007f93c200353a in  () at /usr/lib/libpython3.6m.so.1.0
#94 0x00007f93c2003af3 in  () at /usr/lib/libpython3.6m.so.1.0
#95 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#96 0x00007f93c200353a in  () at /usr/lib/libpython3.6m.so.1.0
#97 0x00007f93c2003af3 in  () at /usr/lib/libpython3.6m.so.1.0
#98 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#99 0x00007f93c200353a in  () at /usr/lib/libpython3.6m.so.1.0
#100 0x00007f93c2003af3 in  () at /usr/lib/libpython3.6m.so.1.0
#101 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#102 0x00007f93c2003f47 in PyEval_EvalCodeEx () at /usr/lib/libpython3.6m.so.1.0
#103 0x00007f93c1fbfa5b in PyEval_EvalCode () at /usr/lib/libpython3.6m.so.1.0
#104 0x00007f93c1fb7871 in  () at /usr/lib/libpython3.6m.so.1.0
#105 0x00007f93c1ff491f in _PyCFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#106 0x00007f93c2003a0f in  () at /usr/lib/libpython3.6m.so.1.0
#107 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#108 0x00007f93c2002291 in  () at /usr/lib/libpython3.6m.so.1.0
#109 0x00007f93c200378a in  () at /usr/lib/libpython3.6m.so.1.0
#110 0x00007f93c2003af3 in  () at /usr/lib/libpython3.6m.so.1.0
#111 0x00007f93c1fbfd77 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#112 0x00007f93c2003f47 in PyEval_EvalCodeEx () at /usr/lib/libpython3.6m.so.1.0
#113 0x00007f93c201e838 in  () at /usr/lib/libpython3.6m.so.1.0
#114 0x00007f93c205991b in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#115 0x00007f93c207fcbd in  () at /usr/lib/libpython3.6m.so.1.0
#116 0x00007f93c20803aa in Py_Main () at /usr/lib/libpython3.6m.so.1.0
#117 0x0000000000400a5d in main ()
```

However, it seems to happen a lot more on Travis, so I'm just skipping the test for now.

**Comment by The-Compiler** [comment]
This probably was fixed in d13809089fc62aea7ce063d1d809930a386d5a2c.
