### ISSUE TITLE
Searchengines aren't validated to be valid URLs

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2299]
```
:set searchengines DEFAULT foo{}
:open -t asfj aspfj asf
```

```
21:59:11 DEBUG    commands   command:run:509 command called: open ['-t', 'asfj aspfj asf']
21:59:11 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.openurl(<qutebrowser.browser.commands.CommandDispatcher>, 'asfj aspfj asf', False, False, True, False, None)
21:59:11 DEBUG    url        urlutils:get_path_if_valid:360 Checking if 'asfj aspfj asf' is a path
21:59:11 DEBUG    url        urlutils:is_url:245 Checking if 'asfj aspfj asf' is a URL (autosearch=naive).
21:59:11 DEBUG    url        urlutils:fuzzy_url:187 URL is a fuzzy search term
21:59:11 DEBUG    url        urlutils:_get_search_url:98 Finding search engine for 'asfj aspfj asf'
21:59:11 DEBUG    url        urlutils:_parse_search_term:85 engine None, term 'asfj aspfj asf'
21:59:11 DEBUG    url        urlutils:fuzzy_url:196 Converting fuzzy term 'asfj aspfj asf' to URL -> 
21:59:11 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 289, in _parse_url
    return objreg.get('quickmark-manager').get(url)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/urlmarks.py", line 227, in get
    "Quickmark '{}' does not exist!".format(name))
qutebrowser.browser.urlmarks.DoesNotExistError: Quickmark 'asfj aspfj asf' does not exist!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 295, in run_safely
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 274, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 258, in openurl
    for i, cur_url in enumerate(urls):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 316, in _parse_url_input
    parsed = self._parse_url(cur_url, force_search=force_search)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/commands.py", line 292, in _parse_url
    return urlutils.fuzzy_url(url, force_search=force_search)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/urlutils.py", line 198, in fuzzy_url
    qtutils.ensure_valid(url)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/qtutils.py", line 162, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: PyQt5.QtCore.QUrl('') is not valid
```

**Comment by The-Compiler** [comment]
Duplicate of #970.
