### ISSUE TITLE
Segfault from _call_with_frames_removed

### ISSUE THREAD

**Issue by danr** [qutebrowser/qutebrowser#2300]
I have no idea what's going on, but here goes:

    $ qutebrowser
    Fatal Python error: Segmentation fault

    Current thread 0x00007f7ae6548400 (most recent call first):
      File "<frozen importlib._bootstrap>", line 205 in _call_with_frames_removed
      File "<frozen importlib._bootstrap_external>", line 922 in create_module
      File "<frozen importlib._bootstrap>", line 560 in module_from_spec
      File "<frozen importlib._bootstrap>", line 648 in _load_unlocked
      File "<frozen importlib._bootstrap>", line 950 in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 961 in _find_and_load
      File "<frozen importlib._bootstrap>", line 978 in _gcd_import
      File "/usr/lib/python3.6/importlib/__init__.py", line 126 in import_module
      File "/home/dan/build/qutebrowser/qutebrowser/misc/earlyinit.py", line 338 in check_libraries
      File "/home/dan/build/qutebrowser/qutebrowser/misc/earlyinit.py", line 407 in earlyinit
      File "/home/dan/build/qutebrowser/qutebrowser/qutebrowser.py", line 165 in main
      File "/usr/bin/qutebrowser", line 11 in <module>
    Segmentation fault (core dumped)
    
Same error is given with `qutebrowser --version`, but I can get it from the python repl:

    >>> qutebrowser.__version__
    '0.9.1'

    $ git show --pretty=oneline | head -n1
    af40439f4a1a410170a4edf2f5a7b3b66fbcd53c tests: Ignore more QPainter::end warnings

I'm on Arch Linux, not sure which packages are relevant, but here are some:

    $ pacman -Q | grep qt5-web
    qt5-webchannel 5.8.0-1
    qt5-webengine 5.8.0-1
    qt5-webkit 5.8.0-1
    
    $ pacman -Q | grep pyqt5
    pyqt5-common 5.7.1-3
    python-pyqt5 5.7.1-3

**Comment by The-Compiler** [comment]
What about `qt5-base`? Does `python3 -c "import PyQt5.QtWebKitWidgets"` segfault? Can you run `coredumpctl info`, verify it's the qutebrowser crash, and show the stacktrace there?

**Comment by danr** [comment]
Thanks for the quick reply, here is more info:

      Command Line: /usr/bin/python /usr/bin/qutebrowser
        Executable: /usr/bin/python3.6
           Storage: /var/lib/systemd/coredump/core.qutebrowser.1000.06222739b08
           Message: Process 15810 (qutebrowser) of user 1000 dumped core.
                    
                    Stack trace of thread 15810:
                    #0  0x00007f7ae6158f5f raise (libpthread.so.0)
                    #1  0x00007f7ae6159080 __restore_rt (libpthread.so.0)
                    #2  0x0000000000001b90 n/a (n/a)
                    
    $ pacman -Q | grep qt5-base
    qt5-base 5.8.0-3

    $ python3 -c "import PyQt5.QtWebKitWidgets"; echo $?
    0

**Comment by The-Compiler** [comment]
That's odd... Unfortunately the Python stack doesn't make much sense either.

Can you please do the following?

- In `/home/dan/build/qutebrowser/qutebrowser/misc/earlyinit.py`, after `for name, text in modules.items():` insert a `print(name)` so we can see where it crashes
- Run `coredumpctl gdb`, and show `bt all` in the gdb shell

**Comment by danr** [comment]
Thanks, I added `print(name)` and it crashes at `PyQt5.QtWebKit`.

I then changed the `ImportError` handling to:

    except ImportError as e:
        import traceback as tb
        import sys
        tb.print_exc()
        sys.exit(-1)
        # _die(text, e)

and I get this trace back:

    Traceback (most recent call last):
      File "/home/dan/build/qutebrowser/qutebrowser/misc/earlyinit.py", line 340, in check_libraries
        importlib.import_module(name)
      File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
      File "<frozen importlib._bootstrap>", line 978, in _gcd_import
      File "<frozen importlib._bootstrap>", line 961, in _find_and_load
      File "<frozen importlib._bootstrap>", line 950, in _find_and_load_unlocked
      File "<frozen importlib._bootstrap>", line 648, in _load_unlocked
      File "<frozen importlib._bootstrap>", line 560, in module_from_spec
      File "<frozen importlib._bootstrap_external>", line 922, in create_module
      File "<frozen importlib._bootstrap>", line 205, in _call_with_frames_removed
    ImportError: /usr/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/python3.6/site-packages/PyQt5/QtWebKit.so)

Though I have the entire qt5 group in Arch installed and pyqt5 installed.

These python imports seem a bit magical though, or at least not idempotent.

Here WebEngine first, then WebKit:

    $ python
    Python 3.6.0 (default, Jan 16 2017, 12:12:55)
    [GCC 6.3.1 20170109] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import PyQt5.QtWebEngine
    >>> import PyQt5.QtWebEngine
    >>> import PyQt5.QtWebEngine
    >>> import PyQt5.QtWebKit
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: /usr/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/python3.6/site-packages/PyQt5/QtWebKit.so)
    >>> import PyQt5.QtWebKit
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: /usr/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5: version `Qt_5.8' not found (required by /usr/lib/python3.6/site-packages/PyQt5/QtWebKit.so)

Here is a run importing WebKit first, then WebEngine:

    $ python
    Python 3.6.0 (default, Jan 16 2017, 12:12:55)
    [GCC 6.3.1 20170109] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import PyQt5.QtWebKit
    >>> import PyQt5.QtWebEngine
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
    ImportError: /usr/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5: symbol _ZSt25__throw_bad_function_callv, version Qt_5 not defined in file libQt5Qml.so.5 with link time reference
    >>> import PyQt5.QtWebEngine
    Segmentation fault (core dumped)

**Comment by The-Compiler** [comment]
It seems like you have two Qt/PyQt installs, one of them installed via `pip` (judging from the `/usr/lib/python3.6/site-packages/PyQt5/Qt/lib/libQt5Core.so.5` path above), and they're probably conflicting with each other in some funny way. Can you try uninstalling one of them, e.g. by doing `sudo pip uninstall PyQt5` (and then use [virtualenv](https://virtualenv.pypa.io/en/stable/) for non-pacman stuff, and never use `sudo pip install` again :wink:)

**Comment by danr** [comment]
Ha, that's really sage advice. I've now cleaned up my installations and qutebrowser runs well on this computer too. Thanks for all the help and your efforts in making qutebrowser!
