### ISSUE TITLE
UnicodeDecodeError with invalid UTF-8 in adblock list

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2301]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 295, in run_safely
    self.run(text, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 274, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/adblock.py", line 197, in adblock_update
    self.on_download_finished(download)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/adblock.py", line 285, in on_download_finished
    self._merge_file(download.fileobj)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/adblock.py", line 226, in _merge_file
    for line in f:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa6 in position 243: invalid start byte
```

**Comment by The-Compiler** [comment]
http://winhelp2002.mvps.org/hosts.zip is causing this reproducibly right now.

Current file: 
[hosts.zip](https://github.com/qutebrowser/qutebrowser/files/823968/hosts.zip)

**Comment by HolySmoke86** [comment]
As the ZIP format seems to not store the encoding of contained text files, switching from ```hosts.zip``` to ```hosts.txt``` may mitigate this, provided the underlying HTTP client (and server ^^) correctly deal with those.

**Comment by The-Compiler** [comment]
The file is latin1-encoded.

With this:

```python
with open('HOSTS', 'rb') as f:
    for line in f:
        try:
            print(line.decode('utf-8').strip())
        except UnicodeDecodeError as e:
            print(line)
            raise
```

we get:

```
...
0.0.0.0 ws.yellowpages.ca
b'# [Online S.a.s][AS12876][163.172.0.0\xa0-\xa0163.172.255.255]\r\n'
Traceback (most recent call last):
  File "h.py", line 4, in <module>
    print(line.decode('utf-8').strip())
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 37: invalid start byte
```

That `\xa0` is a non-breaking space.

Various things we can do about that:

- Use the correct encoding if we can get it from somewhere
- Read the file as binary and ignore comments before decoding stuff
- If a `UnicodeDecodeError` happens with the real data, show an error.

**Comment by pkill-nine** [comment]
just to note, the test for this fails in master

**Comment by The-Compiler** [comment]
@pkill-nine what makes you think so?
