### ISSUE TITLE
UnicodeDecodeError when reading editor text

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2302]
On v0.8.4

```
14:32:28 DEBUG    procs      guiprocess:on_finished:101 Process finished with code 0, status 0.
14:32:28 DEBUG    procs      editor:on_proc_closed:73 Editor closed
14:32:28 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "scripts/dev\..\..\scripts\..\qutebrowser\misc\editor.py", line 84, in on_proc_closed
  File "c:\Python\64-bit\3.4\lib\codecs.py", line 313, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 207: invalid continuation byte
```

**Comment by The-Compiler** [comment]
Abandoned patch from #2506:

```patch
From f9ca5b0259a83b7d3caab9905dfb755f6553ade4 Mon Sep 17 00:00:00 2001
From: Martin Tournoij <martin@arp242.net>
Date: Mon, 3 Apr 2017 01:43:45 +0100
Subject: [PATCH 1/2] Don't error out on unicode errors when reading the edit
 file

Also don't delete the temp file when there is an error reading the file.
IMHO it's a lot better to leave some files in `/tmp/` than delete that
long essay you've been writing for the last 30 minutes.

Fixes #2302
---
 CHANGELOG.asciidoc         |  3 +++
 qutebrowser/misc/editor.py | 40 ++++++++++++++++++----------------------
 2 files changed, 21 insertions(+), 22 deletions(-)

diff --git a/CHANGELOG.asciidoc b/CHANGELOG.asciidoc
index 5ac5f94608..d4405a338d 100644
--- a/CHANGELOG.asciidoc
+++ b/CHANGELOG.asciidoc
@@ -39,6 +39,9 @@ Changed
   options instead of being before sections.
 - The HTTP cache is disabled with QtWebKit on Qt 5.8 now as it leads to frequent
   crashes due to a Qt bug.
+- Don't remove temporary `/tmp/qutebrowser-editor-*` files when there was a
+  problem reading back this text. This allows users to recover test from those
+  files.
 
 Fixed
 ~~~~~
diff --git a/qutebrowser/misc/editor.py b/qutebrowser/misc/editor.py
index a6f2854d8b..cc6f91b319 100644
--- a/qutebrowser/misc/editor.py
+++ b/qutebrowser/misc/editor.py
@@ -68,29 +68,26 @@ def on_proc_closed(self, exitcode, exitstatus):
         Callback for QProcess when the editor was closed.
         """
         log.procs.debug("Editor closed")
-        if exitstatus != QProcess.NormalExit:
-            # No error/cleanup here, since we already handle this in
-            # on_proc_error.
+        if exitstatus != QProcess.NormalExit or exitcode != 0:
+            message.error("Editor processed failed to exit cleanly."
+                          "The file is still available at {}".format(
+                              self._file.name))
             return
+
+        encoding = config.get('general', 'editor-encoding')
         try:
-            if exitcode != 0:
-                return
-            encoding = config.get('general', 'editor-encoding')
-            try:
-                with open(self._file.name, 'r', encoding=encoding) as f:
-                    text = f.read()
-            except OSError as e:
-                # NOTE: Do not replace this with "raise CommandError" as it's
-                # executed async.
-                message.error("Failed to read back edited file: {}".format(e))
-                return
-            log.procs.debug("Read back: {}".format(text))
-            self.editing_finished.emit(text)
-        finally:
-            self._cleanup()
-
-    @pyqtSlot(QProcess.ProcessError)
-    def on_proc_error(self, _err):
+            with open(self._file.name, 'r', encoding=encoding) as f:
+                text = f.read()
+        except (OSError, UnicodeError, UnicodeDecodeError) as e:
+            # NOTE: Do not replace this with "raise CommandError" as it's
+            # executed async.
+            message.error("Failed to read back edited file: {}\n"
+                          "The file is still available at {}".format(
+                              e, self._file.name))
+            return
+        log.procs.debug("Read back: {}".format(text))
+        self.editing_finished.emit(text)
+
         self._cleanup()
 
     def edit(self, text):
@@ -119,7 +116,6 @@ def edit(self, text):
             return
         self._proc = guiprocess.GUIProcess(what='editor', parent=self)
         self._proc.finished.connect(self.on_proc_closed)
-        self._proc.error.connect(self.on_proc_error)
         editor = config.get('general', 'editor')
         executable = editor[0]
         args = [arg.replace('{}', self._file.name) for arg in editor[1:]]

From 334a69ccf14384a416b6ef79407e716a93c2c742 Mon Sep 17 00:00:00 2001
From: Martin Tournoij <martin@arp242.net>
Date: Tue, 4 Apr 2017 09:21:15 +0100
Subject: [PATCH 2/2] Fix PR feedback

---
 CHANGELOG.asciidoc         |  2 +-
 qutebrowser/misc/editor.py | 17 +++++++++--------
 2 files changed, 10 insertions(+), 9 deletions(-)

diff --git a/CHANGELOG.asciidoc b/CHANGELOG.asciidoc
index d4405a338d..664bd042aa 100644
--- a/CHANGELOG.asciidoc
+++ b/CHANGELOG.asciidoc
@@ -40,7 +40,7 @@ Changed
 - The HTTP cache is disabled with QtWebKit on Qt 5.8 now as it leads to frequent
   crashes due to a Qt bug.
 - Don't remove temporary `/tmp/qutebrowser-editor-*` files when there was a
-  problem reading back this text. This allows users to recover test from those
+  problem reading back this text. This allows users to recover text from those
   files.
 
 Fixed
diff --git a/qutebrowser/misc/editor.py b/qutebrowser/misc/editor.py
index cc6f91b319..12b94ff5c9 100644
--- a/qutebrowser/misc/editor.py
+++ b/qutebrowser/misc/editor.py
@@ -54,12 +54,11 @@ def _cleanup(self):
             # Could not create initial file.
             return
         try:
-            if self._proc.exit_status() != QProcess.CrashExit:
-                os.remove(self._file.name)
+            os.remove(self._file.name)
         except OSError as e:
             # NOTE: Do not replace this with "raise CommandError" as it's
             # executed async.
-            message.error("Failed to delete tempfile... ({})".format(e))
+            message.error("Failed to delete tempfile: {}".format(e))
 
     @pyqtSlot(int, QProcess.ExitStatus)
     def on_proc_closed(self, exitcode, exitstatus):
@@ -67,18 +66,20 @@ def on_proc_closed(self, exitcode, exitstatus):
 
         Callback for QProcess when the editor was closed.
         """
-        log.procs.debug("Editor closed")
+        log.procs.debug("Editor closed; exitcode: {}; exitstatus: {}".format(
+            exitcode, exitstatus))
         if exitstatus != QProcess.NormalExit or exitcode != 0:
-            message.error("Editor processed failed to exit cleanly."
-                          "The file is still available at {}".format(
-                              self._file.name))
+            # guiprocess already gives a "Editor exited with status X", so we
+            # don't need to repeat that here.
+            message.error("The file is still available at {}".format(
+                          self._file.name))
             return
 
         encoding = config.get('general', 'editor-encoding')
         try:
             with open(self._file.name, 'r', encoding=encoding) as f:
                 text = f.read()
-        except (OSError, UnicodeError, UnicodeDecodeError) as e:
+        except (OSError, UnicodeError) as e:
             # NOTE: Do not replace this with "raise CommandError" as it's
             # executed async.
             message.error("Failed to read back edited file: {}\n"
```

**Comment by The-Compiler** [comment]
https://crashes.qutebrowser.org/view/3ff95e08 has something similar on v1.0.2 for `youtube-dl`:

```
15:03:44 DEBUG    procs      commands:spawn:1182 Executing youtube-dl with args ['-o', '-', 'https://www.youtube.com/watch?v=KnQaS-uLfWY', '|', 'tee', '~/videos/test.mp4', '|', 'mpv', '-'], userscript=False
[...]
15:03:57 DEBUG    procs      guiprocess:on_finished:98 Process finished with code 1, status 0.
15:03:57 DEBUG    message    message:_log_stack:46 Stack for error message:
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/bin/..qutebrowser-wrapped-wrapped", line 12, in <module>
    sys.exit(main())
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 186, in main
    return app.run(args)
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/lib/python3.6/site-packages/qutebrowser/app.py", line 138, in run
    ret = qt_mainloop()
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/lib/python3.6/site-packages/qutebrowser/app.py", line 148, in qt_mainloop
    return qApp.exec_()
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/lib/python3.6/site-packages/qutebrowser/misc/guiprocess.py", line 110, in on_finished
    self._what.capitalize(), code))
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/lib/python3.6/site-packages/qutebrowser/utils/message.py", line 58, in error
    stack = traceback.format_stack()
15:03:57 ERROR    message    message:error:63 Command exited with status 1.
[...]
15:03:57 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/nix/store/rwjvq1rn61l4ba29h38jjb7hakmpd99i-qutebrowser-1.0.2/lib/python3.6/site-packages/qutebrowser/misc/guiprocess.py", line 113, in on_finished
    stdout = bytes(self._proc.readAllStandardOutput()).decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd2 in position 27: invalid continuation byte
```

**Comment by gebulmer** [comment]
I think the most straightforward way to handle this would be to pass `error='surrogateescape'` or similar to the `open` call.

Presumably for this to trigger, the user had set an incorrect encoding in their config relative to the contents file. When reading it back, we shouldn't simply crash. 

I can't right now see the problem with continuing when there's a decode error with substitution. If we later write the string somehow we can reclaim the data if we use surrogateescape.

Obviously as you're busy right now irl I'll wait for some discussion perhaps on irc before issuing a PR in case I'm barking up the wrong tree

**Comment by gebulmer** [comment]
Maybe I'm misunderstanding, but when writing with `surrogateescape` something which has been read with `surrogateescape` the erroneous characters get written back as what they were before attempting to read. This is presumably the text the user wanted to input to the file to begin with when editing.

Isn't that what we want? If there's a mismatch between the config and the file, the file gets left as is

**Comment by The-Compiler** [comment]
There are actually two situations in which an UnicodeError can happen:

- When writing the text we got from the website to a file. Here, `surrogateescape` could in theory help, but I'm not sure it's a good idea. After all, we'll pass the data to a text editor, and that'll probably not be able to handle surrogate escapes properly (if I'm understanding things properly, those are for OS interfaces handling things as bytes).
- When getting the edited text back, such as in the exception above. Note we're *decoding* here, so if the editor provided characters which are (e.g.) invalid UTF-8 but not surrogate escape, we get something quite random here.

In both cases, we should IMHO refuse the temptation to guess, just display an error, and make sure we don't lose data.

**Comment by The-Compiler** [comment]
Another similar one: https://crashes.qutebrowser.org/view/3ff03e0d

```
Traceback (most recent call last):
  File "qutebrowser\misc\editor.py", line 171, in _on_file_changed
  File "codecs.py", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xa0 in position 449: invalid start byte
```

Increasing the priority for this, as it can cause data loss probably, or at least frustration.
