### ISSUE TITLE
:debug-log-filter webview crashes

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2303]
```
Traceback (most recent call last):
  File "/home/miles/packages/repos/qutebrowser/qutebrowser/commands/runners.py", line 295, in run_safely
    self.run(text, count)
  File "/home/miles/packages/repos/qutebrowser/qutebrowser/commands/runners.py", line 274, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/miles/packages/repos/qutebrowser/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/home/miles/packages/repos/qutebrowser/qutebrowser/misc/utilcmds.py", line 290, in debug_log_filter
    log.console_filter.names = filters.split(',')
AttributeError: 'NoneType' object has no attribute 'names'
```

**Comment by Carpetsmoker** [comment]
Running `:debug-log-level webview`gives me `level: Invalid value webview - expected one of: vdebug, debug, info, warning, error, critical` with 9cd2c9a. Doesn't seem to crash?

Tested in WebKit and WebEngine.

**Comment by The-Compiler** [comment]
Sorry - that should be `:debug-log-filter`, not `:debug-log-level`.
