### ISSUE TITLE
Rapid hints broken with hide-unmatched-rapid-hints set

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2365]
It seems rapid hints aren't followed anymore at all with `hints -> hide-unmatched-rapid-hints` set.

Logs:

```08:14:14 DEBUG    commands   command:run:509 command called: hint ['--rapid', 'links', 'tab-bg']
08:14:14 DEBUG    commands   command:run:524 Calling qutebrowser.browser.hints.HintManager.start(<qutebrowser.browser.hints.HintManager object at 0x7fd95d88c9d8>, True, <Group.links: 2>, <Target.tab_bg: 5>, win_id=0, mode=None, add_history=False)
08:14:14 DEBUG    hints      hints:_start_cb:589 hints: a, hg, jg, kg, s, hh, jh, kh, d, hj, jj, f, hk, jk, g, hl, jl, ha, ja, ka, hs, js, ks, hd, jd, kd, hf, jf, kf
08:14:14 DEBUG    message    message:set_text:260 Follow hint in background tab (rapid mode)...
08:14:14 DEBUG    statusbar  text:set_text:55 Setting normal text to 'Follow hint in background tab (rapid mode)...'.
08:14:14 DEBUG    modes      modeman:enter:238 Entering mode KeyMode.hint (reason: HintManager.start)
08:14:14 DEBUG    modes      modeman:_eventFilter_keypress:192 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=0 url='https://www.heise.de/'>)
08:14:14 DEBUG    modes      modeman:_eventFilter_keyrelease:212 filter: True
08:14:15 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
08:14:15 DEBUG    keyboard   basekeyparser:_debug_log:112 Got key: 0x4a / text: 'j'
08:14:15 DEBUG    keyboard   basekeyparser:_debug_log:112 No match for 'j' (added j)
08:14:15 DEBUG    hints      hints:handle_partial_key:765 Handling new keystring: 'j'
08:14:15 DEBUG    modes      modeman:_eventFilter_keypress:192 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=0 url='https://www.heise.de/'>)
08:14:15 DEBUG    modes      modeman:_eventFilter_keyrelease:212 filter: True
08:14:15 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.hint - delegating to <qutebrowser.keyinput.modeparsers.HintKeyParser supports_chains=True supports_count=False>
08:14:15 DEBUG    keyboard   basekeyparser:_debug_log:112 Got key: 0x41 / text: 'a'
08:14:15 DEBUG    keyboard   basekeyparser:_debug_log:112 Definitive match for 'ja'.
08:14:15 DEBUG    keyboard   basekeyparser:_debug_log:112 discarding keystring 'ja'.
08:14:15 DEBUG    hints      hints:handle_partial_key:765 Handling new keystring: ''
08:14:15 DEBUG    hints      hints:handle_partial_key:765 Handling new keystring: 'ja'
08:14:15 DEBUG    modes      modeman:_eventFilter_keypress:192 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=0 url='https://www.heise.de/'>)
08:14:15 DEBUG    modes      modeman:_eventFilter_keyrelease:212 filter: True
```

```
08:14:19 DEBUG    commands   command:run:509 command called: follow-hint
08:14:19 DEBUG    commands   command:run:524 Calling qutebrowser.browser.hints.HintManager.follow_hint(<qutebrowser.browser.hints.HintManager object at 0x7fd95d88c9d8>, None)
08:14:19 DEBUG    message    message:_log_stack:46 Stack for error (from exception) message:
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyparser.py", line 44, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 274, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/hints.py", line 909, in follow_hint
    raise cmdexc.CommandError("No hint to follow")
qutebrowser.commands.cmdexc.CommandError: No hint to follow
08:14:19 ERROR    message    message:error:63 No hint to follow
```

The option was added in 7271955c56633b7d83c2f787d33975e0b830254c, and in b6195d4e77e1309b4b4ecf77508a9ad65b007fcc (the earliest I can test right now) it's broken already.

cc @pkill-nine @lahwaacz

**Comment by The-Compiler** [comment]
I tried fixing this but ran out of time, and my fix seems to break other stuff in `hints.feature`:

```diff
diff --git a/qutebrowser/browser/hints.py b/qutebrowser/browser/hints.py
index 3cc70f434..b5de6fd13 100644
--- a/qutebrowser/browser/hints.py
+++ b/qutebrowser/browser/hints.py
@@ -78,6 +78,7 @@ class HintLabel(QLabel):
         super().__init__(parent=context.tab)
         self._context = context
         self.elem = elem
+        self.does_match = False
 
         self.setAttribute(Qt.WA_StyledBackground, True)
         style.set_register_stylesheet(self)
@@ -113,6 +114,16 @@ class HintLabel(QLabel):
             match_color, matched, unmatched))
         self.adjustSize()
 
+    def match(self, does_match):
+        """Mark the label is matching/not matching."""
+        self.does_match = does_match
+        if does_match:
+            self.show()
+        else:
+            if (not self._context.rapid or
+                    config.get('hints', 'hide-unmatched-rapid-hints')):
+                self.hide()
+
     @pyqtSlot()
     def _move_to_elem(self):
         """Reposition the label to its element."""
@@ -719,14 +730,20 @@ class HintManager(QObject):
 
         return self._context.hint_mode
 
-    def _handle_auto_follow(self, keystr="", filterstr="", visible=None):
-        """Handle the auto-follow option."""
-        if visible is None:
-            visible = {string: label
+    def _handle_auto_follow(self, keystr="", filterstr="", matches=None):
+        """Handle the auto-follow option.
+
+        Args:
+            keystr: The key string currently entered.
+            filterstr: The filter string for number hints.
+            matches: A list of labels which currently match.
+        """
+        if matches is None:
+            matches = {string: label
                        for string, label in self._context.labels.items()
-                       if label.isVisible()}
+                       if label.does_match}
 
-        if len(visible) != 1:
+        if len(matches) != 1:
             return
 
         auto_follow = config.get('hints', 'auto-follow')
@@ -736,14 +753,14 @@ class HintManager(QObject):
         elif auto_follow == "unique-match":
             follow = keystr or filterstr
         elif auto_follow == "full-match":
-            elemstr = str(list(visible.values())[0].elem)
+            elemstr = str(list(matches.values())[0].elem)
             filter_match = self._filter_matches_exactly(filterstr, elemstr)
-            follow = (keystr in visible) or filter_match
+            follow = (keystr in matches) or filter_match
         else:
             follow = False
-            # save the keystr of the only one visible hint to be picked up
+            # save the keystr of the only one matches hint to be picked up
             # later by self.follow_hint
-            self._context.to_follow = list(visible.keys())[0]
+            self._context.to_follow = list(matches.keys())[0]
 
         if follow:
             # apply auto-follow-timeout
@@ -753,7 +770,7 @@ class HintManager(QObject):
             normal_parser = keyparsers[usertypes.KeyMode.normal]
             normal_parser.set_inhibited_timeout(timeout)
             # unpacking gets us the first (and only) key in the dict.
-            self._fire(*visible)
+            self._fire(*matches)
 
     def handle_partial_key(self, keystr):
         """Handle a new partial keypress."""
@@ -768,13 +785,9 @@ class HintManager(QObject):
                     rest = string[len(keystr):]
                     label.update_text(matched, rest)
                     # Show label again if it was hidden before
-                    label.show()
+                    label.match(True)
                 else:
-                    # element doesn't match anymore -> hide it, unless in rapid
-                    # mode and hide-unmatched-rapid-hints is false (see #1799)
-                    if (not self._context.rapid or
-                            config.get('hints', 'hide-unmatched-rapid-hints')):
-                        label.hide()
+                    label.match(False)
             except webelem.Error:
                 pass
         self._handle_auto_follow(keystr=keystr)
@@ -793,20 +806,20 @@ class HintManager(QObject):
         else:
             self._context.filterstr = filterstr
 
-        visible = []
+        matches = []
         for label in self._context.all_labels:
             try:
                 if self._filter_matches(filterstr, str(label.elem)):
-                    visible.append(label)
+                    matches.append(label)
                     # Show label again if it was hidden before
-                    label.show()
+                    label.match(True)
                 else:
                     # element doesn't match anymore -> hide it
-                    label.hide()
+                    label.match(False)
             except webelem.Error:
                 pass
 
-        if not visible:
+        if not matches:
             # Whoops, filtered all hints
             modeman.leave(self._win_id, usertypes.KeyMode.hint,
                           'all filtered')
@@ -814,9 +827,9 @@ class HintManager(QObject):
 
         if self._context.hint_mode == 'number':
             # renumber filtered hints
-            strings = self._hint_strings(visible)
+            strings = self._hint_strings(matches)
             self._context.labels = {}
-            for label, string in zip(visible, strings):
+            for label, string in zip(matches, strings):
                 label.update_text('', string)
                 self._context.labels[string] = label
             keyparsers = objreg.get('keyparsers', scope='window',
@@ -827,9 +840,9 @@ class HintManager(QObject):
             # Note: filter_hints can be called with non-None filterstr only
             # when number mode is active
             if filterstr is not None:
-                # pass self._context.labels as the dict of visible hints
+                # pass self._context.labels as the dict of matching hints
                 self._handle_auto_follow(filterstr=filterstr,
-                                         visible=self._context.labels)
+                                         matches=self._context.labels)
 
     def _fire(self, keystr):
         """Fire a completed hint.
diff --git a/tests/end2end/data/hints/rapid.html b/tests/end2end/data/hints/rapid.html
index b8184b383..81a1274fb 100644
--- a/tests/end2end/data/hints/rapid.html
+++ b/tests/end2end/data/hints/rapid.html
@@ -8,5 +8,15 @@
     <body>
         <a href="/data/hello.txt" id="link">Hello</a>
         <a href="/data/hello2.txt" id="link">Hello 2</a>
+        <a href="/data/numbers/1.txt" id="link">1</a>
+        <a href="/data/numbers/2.txt" id="link">2</a>
+        <a href="/data/numbers/3.txt" id="link">3</a>
+        <a href="/data/numbers/4.txt" id="link">4</a>
+        <a href="/data/numbers/5.txt" id="link">5</a>
+        <a href="/data/numbers/6.txt" id="link">6</a>
+        <a href="/data/numbers/7.txt" id="link">7</a>
+        <a href="/data/numbers/8.txt" id="link">8</a>
+        <a href="/data/numbers/9.txt" id="link">9</a>
+        <a href="/data/numbers/10.txt" id="link">10</a>
     </body>
 </html>
diff --git a/tests/end2end/features/hints.feature b/tests/end2end/features/hints.feature
index 4fbd17720..a0fd50ad1 100644
--- a/tests/end2end/features/hints.feature
+++ b/tests/end2end/features/hints.feature
@@ -5,6 +5,7 @@ Feature: Using hints
     # https://bugreports.qt.io/browse/QTBUG-58381
     Background:
         Given I clean up open tabs
+        And I set hints -> scatter to false
 
     Scenario: Using :follow-hint outside of hint mode (issue 1105)
         When I run :follow-hint
@@ -124,8 +125,31 @@ Feature: Using hints
         When I open data/hints/rapid.html in a new tab
         And I run :tab-only
         And I hint with args "all tab-bg --rapid"
-        And I run :follow-hint a
-        And I run :follow-hint s
+        And I run :follow-hint aa
+        And I run :follow-hint as
+        And I run :leave-mode
+        And I wait until data/hello.txt is loaded
+        And I wait until data/hello2.txt is loaded
+        # We should check what the active tab is, but for some reason that makes
+        # the test flaky
+        Then the session should look like:
+          windows:
+          - tabs:
+            - history:
+              - url: http://localhost:*/data/hints/rapid.html
+            - history:
+              - url: http://localhost:*/data/hello.txt
+            - history:
+              - url: http://localhost:*/data/hello2.txt
+
+    Scenario: Rapid hinting with hide-unmatched-rapid-hints = false
+        When I open data/hints/rapid.html in a new tab
+        And I set hints -> auto-follow to unique-match
+        And I set hints -> hide-unmatched-rapid-hints to false
+        And I run :tab-only
+        And I hint with args "all tab-bg --rapid"
+        And I press the keys "aa"
+        And I press the keys "as"
         And I run :leave-mode
         And I wait until data/hello.txt is loaded
         And I wait until data/hello2.txt is loaded
```

**Comment by d-nnis** [comment]
Hints in rapid mode are followed if ``hints.hide_unmatched_rapid_hints`` is set to ``true``. It does not work if set to ``false`` (as mentioned above). This seems to be the only crucial setting to reproduce the bug!(?)

At least with my setup:
-------
Git commit:
Backend: QtWebEngine (Chromium 49.0.2623.111)

CPython: 3.5.3
Qt: 5.7.1
PyQt: 5.7

sip: 4.18.1
colorama: no
pypeg2: 2.15
jinja2: 2.8
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 16.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.16.2
QtNetwork SSL: OpenSSL 1.0.2q  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.9.0-8-amd64-x86_64-with-debian-9.8, 64bit
Linux distribution: Debian GNU/Linux 9 (stretch) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/dennis/.cache/qutebrowser
config: /home/dennis/.config/qutebrowser
data: /home/dennis/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:06
-------
