### ISSUE TITLE
AttributeError for self._reply.isOpen in _on_read_timer_timeout

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2367]
On v0.9.1 on Windows:

```
22:43:03 DEBUG    downloads  qtnetworkdownloads:fetch:464 fetch: PyQt5.QtCore.QUrl('http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov') -> hist210_01_083111.mov
22:43:03 DEBUG    downloads  downloads:_on_begin_insert_row:837 _on_begin_insert_row with idx 1, webengine False
22:43:03 DEBUG    prompt     prompt:ask_question:151 Asking question <qutebrowser.utils.usertypes.Question default='C:\\Users\\philip\\Downloads\\lectures\\history\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov</b>' title='Save file to:'>, blocking False, loops [], queue deque([])
# [...]
22:43:24 DEBUG    commands   command:run:509 command called: leave-mode
22:43:24 DEBUG    commands   command:run:524 Calling qutebrowser.keyinput.modeman.ModeManager.leave_current_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.prompt: 5>>)
22:43:24 DEBUG    modes      modeman:leave:289 Leaving mode KeyMode.prompt (reason: leave current)
22:43:24 DEBUG    statusbar  text:set_text:55 Setting normal text to ''.
22:43:24 DEBUG    statusbar  bar:set_mode_active:239 Setting prompt_active to False
22:43:24 DEBUG    prompt     prompt:_on_mode_left:212 Left mode KeyMode.prompt, hiding <qutebrowser.utils.usertypes.Question default='C:\\Users\\philip\\Downloads\\lectures\\history\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov</b>' title='Save file to:'>
22:43:24 DEBUG    prompt     prompt:_on_show_prompts:291 Deleting old prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='C:\\Users\\philip\\Downloads\\lectures\\history\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov</b>' title='Save file to:'>)
22:43:24 DEBUG    prompt     prompt:_on_show_prompts:296 No prompts left, hiding prompt container.
22:43:24 DEBUG    prompt     prompt:_on_show_prompts:291 Deleting old prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='C:\\Users\\philip\\Downloads\\lectures\\history\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov</b>' title='Save file to:'>)
22:43:24 DEBUG    prompt     prompt:_on_show_prompts:296 No prompts left, hiding prompt container.
22:43:24 DEBUG    prompt     prompt:_on_mode_left:216 Cancelling <qutebrowser.utils.usertypes.Question default='C:\\Users\\philip\\Downloads\\lectures\\history\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov</b>' title='Save file to:'> because KeyMode.prompt was left
22:43:24 DEBUG    downloads  downloads:_on_begin_remove_row:849 _on_begin_remove_row with idx 1, webengine False
22:43:24 DEBUG    downloads  downloads:_remove_item:773 Removed download 2: hist210_01_083111.mov [   0.00B/s| 0:00|100%|16.05MB/16.05MB]
22:43:24 DEBUG    modes      modeman:leave:289 Leaving mode KeyMode.prompt (reason: aborted)
22:43:24 DEBUG    statusbar  text:set_text:55 Setting normal text to ''.
22:43:24 DEBUG    statusbar  bar:set_mode_active:239 Setting prompt_active to False
22:43:24 DEBUG    prompt     prompt:_on_mode_left:212 Left mode KeyMode.prompt, hiding <qutebrowser.utils.usertypes.Question default='C:\\Users\\philip\\Downloads\\lectures\\history\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://openmedia.yale.edu/cgi-bin/open_yale/media_downloader.cgi?file=/courses/fall11/hist210/mov/chapters/hist210_01_083111.mov</b>' title='Save file to:'>
22:43:24 DEBUG    prompt     prompt:_on_show_prompts:296 No prompts left, hiding prompt container.
22:43:24 DEBUG    prompt     prompt:_on_show_prompts:296 No prompts left, hiding prompt container.
22:43:24 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.prompt (reason left in other window) as we're in mode KeyMode.normal
22:43:24 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.prompt (reason left in other window) as we're in mode KeyMode.normal
22:43:24 DEBUG    modes      tabbedbrowser:on_mode_left:570 Left status-input mode, focusing <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=4 url='http://razorcheatsheet.com/'>
22:43:24 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.prompt was left.
22:43:24 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.prompt was left.
22:43:24 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.prompt (reason aborted) as we're in mode KeyMode.normal
22:43:24 DEBUG    downloads  downloads:cancel:473 cancelled
22:43:24 DEBUG    downloads  downloads:delete:492 Not deleting None
22:43:24 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.prompt (reason left in other window) as we're in mode KeyMode.normal
22:43:24 DEBUG    modes      modeman:leave:283 Ignoring leave request for KeyMode.prompt (reason left in other window) as we're in mode KeyMode.normal
22:43:24 DEBUG    modes      tabbedbrowser:on_mode_left:570 Left status-input mode, focusing <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=5 url='http://oyc.yale.edu/history/hist-210/lecture-1#ch1'>
22:43:24 DEBUG    misc       app:on_focus_object_changed:768 Focus object changed: <qutebrowser.browser.webkit.webview.WebView tab_id=5 url='http://oyc.yale.edu/history/hist-210/lecture-1#ch1'>
22:43:24 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.prompt was left.
22:43:24 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.prompt was left.
22:43:24 DEBUG    webview    webview:on_mode_left:181 Restoring focus policy because mode KeyMode.prompt was left.
22:43:24 DEBUG    modes      modeman:_eventFilter_keypress:191 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=5 url='http://oyc.yale.edu/history/hist-210/lecture-1#ch1'>)
22:43:24 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "scripts/dev\..\..\scripts\..\qutebrowser\browser\qtnetworkdownloads.py", line 293, in _on_read_timer_timeout
AttributeError: 'NoneType' object has no attribute 'isOpen'
```

This might or might not be related to #2304.

**Comment by The-Compiler** [comment]
http://crashes.qutebrowser.org/view/60d367ea - on Windows, "Tried to download Firefox for Android!", v0.10.1

**Comment by The-Compiler** [comment]
http://crashes.qutebrowser.org/view/0978b24a - on Windows too, "I pressed "Esc" trying to cancel a Download prompt"

```
17:32:56 DEBUG    downloads  qtnetworkdownloads:fetch:489 fetch: PyQt5.QtCore.QUrl('http://www.vitoria-gasteiz.org/wb021/http/contenidosEstaticos/adjuntos/es/36/24/63624.pdf') -> 63624.pdf
17:32:56 DEBUG    downloads  downloads:_on_begin_insert_row:825 _on_begin_insert_row with idx 0, webengine False
17:32:56 DEBUG    misc       standarddir:_writable_location:143 writable location for DownloadLocation: C:/Users/Android garapena/Downloads
17:32:56 DEBUG    prompt     prompt:ask_question:151 Asking question <qutebrowser.utils.usertypes.Question default='C:\\Users\\Android garapena\\Downloads\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.vitoria-gasteiz.org/wb021/http/contenidosEstaticos/adjuntos/es/36/24/63624.pdf</b>' title='Save file to:'>, blocking False, loops [], queue deque([])
17:32:56 DEBUG    prompt     prompt:_on_show_prompts:311 Displaying prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='C:\\Users\\Android garapena\\Downloads\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.vitoria-gasteiz.org/wb021/http/contenidosEstaticos/adjuntos/es/36/24/63624.pdf</b>' title='Save file to:'>)
17:32:56 DEBUG    modes      modeman:enter:238 Entering mode KeyMode.prompt (reason: question asked)
17:32:56 DEBUG    statusbar  text:set_text:55 Setting normal text to '-- PROMPT MODE --'.
17:32:56 DEBUG    statusbar  bar:set_mode_active:242 Setting prompt_active to True
17:32:56 DEBUG    webview    webview:on_mode_entered:164 Ignoring focus because mode KeyMode.prompt was entered.
17:32:56 DEBUG    webview    webview:on_mode_entered:164 Ignoring focus because mode KeyMode.prompt was entered.
17:32:56 DEBUG    webview    webview:on_mode_entered:164 Ignoring focus because mode KeyMode.prompt was entered.
17:32:56 DEBUG    webview    webview:on_mode_entered:164 Ignoring focus because mode KeyMode.prompt was entered.
17:32:56 DEBUG    misc       app:on_focus_object_changed:779 Focus object changed: <qutebrowser.mainwindow.prompt.LineEdit>
17:32:56 DEBUG    misc       mainwindow:_update_overlay_geometry:267 new geometry for <qutebrowser.mainwindow.prompt.PromptContainer win_id=0>: PyQt5.QtCore.QRect(10, 314, 1347, 377)
17:32:56 DEBUG    sessions   sessions:save:280 Saving session _autosave to C:\Users\Android garapena\AppData\Local\qutebrowser\data\sessions\_autosave.yml...
17:32:56 DEBUG    webview    browsertab:_set_load_status:627 load status for <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=9 url=''>: LoadStatus.success
17:32:56 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_status_changed('success') (tab 3)
17:32:56 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_finished(True) (tab 3)
17:32:56 DEBUG    webview    tabbedbrowser:on_title_changed:515 Ignoring title change to ''.
17:32:58 DEBUG    modes      modeman:_eventFilter_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='prompt' warn=False>
17:32:58 DEBUG    commands   command:run:509 command called: leave-mode
17:32:58 DEBUG    commands   command:run:524 Calling qutebrowser.keyinput.modeman.ModeManager.leave_current_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.prompt: 5>>)
17:32:58 DEBUG    modes      modeman:leave:300 Leaving mode KeyMode.prompt (reason: leave current)
17:32:58 DEBUG    statusbar  text:set_text:55 Setting normal text to ''.
17:32:58 DEBUG    statusbar  bar:set_mode_active:242 Setting prompt_active to False
17:32:58 DEBUG    prompt     prompt:_on_mode_left:212 Left mode KeyMode.prompt, hiding <qutebrowser.utils.usertypes.Question default='C:\\Users\\Android garapena\\Downloads\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.vitoria-gasteiz.org/wb021/http/contenidosEstaticos/adjuntos/es/36/24/63624.pdf</b>' title='Save file to:'>
17:32:58 DEBUG    prompt     prompt:_on_show_prompts:291 Deleting old prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='C:\\Users\\Android garapena\\Downloads\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.vitoria-gasteiz.org/wb021/http/contenidosEstaticos/adjuntos/es/36/24/63624.pdf</b>' title='Save file to:'>)
17:32:58 DEBUG    misc       app:on_focus_object_changed:779 Focus object changed: <qutebrowser.mainwindow.tabwidget.TabBar count=4>
17:32:58 DEBUG    prompt     prompt:_on_show_prompts:296 No prompts left, hiding prompt container.
17:32:58 DEBUG    prompt     prompt:_on_mode_left:216 Cancelling <qutebrowser.utils.usertypes.Question default='C:\\Users\\Android garapena\\Downloads\\' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://www.vitoria-gasteiz.org/wb021/http/contenidosEstaticos/adjuntos/es/36/24/63624.pdf</b>' title='Save file to:'> because KeyMode.prompt was left
17:32:58 DEBUG    downloads  downloads:_on_begin_remove_row:837 _on_begin_remove_row with idx 0, webengine False
17:32:58 DEBUG    downloads  downloads:_remove_item:762 Removed download 1: 63624.pdf [1003.75kB/s| 0:05|32%|2.47MB/7.61MB]
17:32:58 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.prompt (reason aborted) as we're in mode KeyMode.normal
17:32:58 DEBUG    downloads  downloads:cancel:482 cancelled
17:32:58 DEBUG    downloads  downloads:delete:501 Not deleting None
17:32:58 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.prompt (reason left in other window) as we're in mode KeyMode.normal
17:32:58 DEBUG    modes      tabbedbrowser:on_mode_left:573 Left status-input mode, focusing <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=8 url='http://www.vitoria-gasteiz.org/we001/was/we001Action.do?idioma=eu&claveTema=9&claveArea=1&accion=cu…'>
17:32:58 DEBUG    misc       app:on_focus_object_changed:779 Focus object changed: <qutebrowser.browser.webkit.webview.WebView tab_id=8 url='http://www.vitoria-gasteiz.org/we001/was/we001Action.do?idioma=eu&claveTema=9&claveArea=1&accion=cu…'>
17:32:58 DEBUG    webview    webview:on_mode_left:177 Restoring focus policy because mode KeyMode.prompt was left.
17:32:58 DEBUG    webview    webview:on_mode_left:177 Restoring focus policy because mode KeyMode.prompt was left.
17:32:58 DEBUG    webview    webview:on_mode_left:177 Restoring focus policy because mode KeyMode.prompt was left.
17:32:58 DEBUG    webview    webview:on_mode_left:177 Restoring focus policy because mode KeyMode.prompt was left.
17:32:58 DEBUG    modes      modeman:_eventFilter_keypress:192 handled: True, forward-unbound-keys: auto, passthrough: True, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=8 url='http://www.vitoria-gasteiz.org/we001/was/we001Action.do?idioma=eu&claveTema=9&claveArea=1&accion=cu…'>)
17:32:58 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "scripts/dev\..\..\scripts\..\qutebrowser\browser\qtnetworkdownloads.py", line 293, in _on_read_timer_timeout
AttributeError: 'NoneType' object has no attribute 'isOpen'
```
