### ISSUE TITLE
Segfaults in QAbstractSocketPrivate::canReadNotification

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2396]
See https://bugreports.qt.io/browse/QTBUG-59288 and https://github.com/qutebrowser/qutebrowser/issues/2321#issuecomment-284024213

😟

**Comment by The-Compiler** [comment]
stack:

```
#0  0x00007f97d21aff5f in raise () at /usr/lib/libpthread.so.0
#1  0x00007f97d21b0080 in <signal handler called> () at /usr/lib/libpthread.so.0
#2  0x00007f97cfd827b1 in QMetaObject::activate(QObject*, int, int, void**) (sender=0x253df08, signalOffset=3, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffe75715600) at kernel/qobject.cpp:3612
#3  0x00007f97cfd836d7 in QMetaObject::activate(QObject*, QMetaObject const*, int, void**) (sender=<optimized out>, m=m@entry=0x7f97d01a2ec0 <QIODevice::staticMetaObject>, local_signal_index=local_signal_index@entry=1, argv=argv@entry=0x7ffe75715600) at kernel/qobject.cpp:3602
#4  0x00007f97cfdf9201 in QIODevice::channelReadyRead(int) (this=<optimized out>, _t1=<optimized out>) at .moc/moc_qiodevice.cpp:193
#5  0x00007f97c1ff1b7c in QAbstractSocketPrivate::canReadNotification() (this=0x24f25a0) at socket/qabstractsocket.cpp:733
#6  0x00007f97c1ffd131 in QReadNotifier::event(QEvent*) (this=<optimized out>, e=<optimized out>) at socket/qnativesocketengine.cpp:1241
#7  0x00007f97ba5753dc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x33b7780, e=0x7ffe757158d0) at kernel/qapplication.cpp:3745
#8  0x00007f97ba57cbf1 in QApplication::notify(QObject*, QEvent*) (this=0x2177180, receiver=0x33b7780, e=0x7ffe757158d0) at kernel/qapplication.cpp:3502
#9  0x00007f97badf42ce in sipQApplication::notify(QObject*, QEvent*) (this=0x2177180, a0=0x33b7780, a1=0x7ffe757158d0) at sipQtWidgetsQApplication.cpp:232
#10 0x00007f97cfd574b0 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x33b7780, event=event@entry=0x7ffe757158d0) at kernel/qcoreapplication.cpp:988
#11 0x00007f97cfdac56d in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7ffe757158d0, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:231
#12 0x00007f97cfdac56d in socketNotifierSourceDispatch(GSource*, GSourceFunc, gpointer) (source=0x21ac420) at kernel/qeventdispatcher_glib.cpp:106
#13 0x00007f97cc62c5a7 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#14 0x00007f97cc62c810 in  () at /usr/lib/libglib-2.0.so.0
#15 0x00007f97cc62c8bc in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#16 0x00007f97cfdac0bf in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x21ac2a0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#17 0x00007f97cfd5590a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7ffe75715af0, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#18 0x00007f97cfd5de54 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1261
```

I can reproduce it even without QtWebEngine in these 3 tests:

```gherkin
Feature: Downloading things from a website.

    Background:
        Given I set up a temporary download dir
        And I clean old downloads
        And I set ui -> remove-finished-downloads to -1

    Scenario: Downloading with error in closed tab (issue 889)
        When I set tabs -> last-close to blank
        And I open data/downloads/issue889.html
        And I hint with args "links download" and follow s
        And I run :tab-close
        And I wait for the error "Download error: * - server replied: NOT FOUND"
        And I run :download-retry
        And I wait for the error "Download error: * - server replied: NOT FOUND"
        Then no crash should happen

    Scenario: Closing window with remove-finished-downloads timeout (issue 1242)
        When I set ui -> remove-finished-downloads to 500
        And I open data/downloads/download.bin in a new window without waiting
        And I wait until the download is finished
        And I run :close
        And I wait 0.5s
        Then no crash should happen

    # https://github.com/qutebrowser/qutebrowser/issues/2134
    @qtwebengine_skip
    Scenario: Downloading, then closing a tab
        When I set storage -> prompt-download-directory to false
        And I open about:blank
        And I open data/downloads/issue2134.html in a new tab
        # This needs to be a download connected to the tabs QNAM
        And I hint with args "links normal" and follow a
        And I wait for "fetch: * -> drip" in the log
        And I run :tab-close
        And I wait for "Download drip finished" in the log
        Then the downloaded file drip should be 128 bytes big
```

**Comment by The-Compiler** [comment]
I tried ripping out [lots of download code](http://paste.the-compiler.org/view/ca7a8768) but it still happened. That seems to be a red herring.

It looks like it's related to IPC somehow - this seems to help reliably:

```diff
diff --git a/qutebrowser/misc/ipc.py b/qutebrowser/misc/ipc.py
index 2e918ed07..a9ae2d3a0 100644
--- a/qutebrowser/misc/ipc.py
+++ b/qutebrowser/misc/ipc.py
@@ -281,7 +281,7 @@ class IPCServer(QObject):
         if self._socket is None:
             log.ipc.debug("In on_disconnected with None socket!")
         else:
-            self._socket.deleteLater()
+            # self._socket.deleteLater()
             self._socket = None
         # Maybe another connection is waiting.
         self.handle_connection()
```

**Comment by The-Compiler** [comment]
I opened https://bugreports.qt.io/browse/QTBUG-59297 now - keeping the socket around for 500ms with a QTimer seems to help... Not so happy with it, but if that's what it takes, well...
