### ISSUE TITLE
git version crashes if cmdline contains a command

### ISSUE THREAD

**Issue by bitraid** [qutebrowser/qutebrowser#2408]
Latest git version, both backends.
Tested on multiple systems running Arch Linux x64, both X and Wayland
example:
`qutebrowser :adblock-update`
Crash screen is presented but execution continues.

**Comment by The-Compiler** [comment]
Reproduced:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 169, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 112, in run
    init(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 145, in init
    _process_args(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 203, in _process_args
    process_pos_args(args.command)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 268, in process_pos_args
    commandrunner.run_safely_init(cmd[1:])
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 307, in run_safely_init
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 287, in run
    macro_recorder = objreg.get('macro-recorder')
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 233, in get
    return reg[name]
  File "/usr/lib/python3.6/collections/__init__.py", line 990, in __getitem__
    raise KeyError(key)
KeyError: 'macro-recorder'
```

Looks like c422897abbd56ae4a70977397de2e1adcf1a1e0e introduced this.
