### ISSUE TITLE
--help fails with windows exe

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2421]
When running the built qutebrowser.exe with `--help` we get:

```
Traceback (most recent call last):
  File "C:\Users\florian\proj\qutebrowser\.tox\cxfreeze-windows\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27, in <module>
    exec(code, m.__dict__)
  File "qutebrowser/__main__.py", line 29, in <module>
  File "scripts/dev\..\..\scripts\..\qutebrowser\qutebrowser.py", line 157, in main
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 1721, in parse_args
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 1753, in parse_known_args
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 1959, in _parse_known_args
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 1899, in consume_optional
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 1827, in take_action
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 1016, in __call__
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 2352, in print_help
  File "c:\Python\64-bit\3.4\lib\argparse.py", line 2358, in _print_message
AttributeError: 'NoneType' object has no attribute 'write'
```

**Comment by The-Compiler** [comment]
Superseded by #5244.
