### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'history'

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2426]
Report on v0.10.0 when saving the autosave session:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webkit/webkittab.py", line 705, in _on_frame_load_finished
    self._on_load_finished(not self._widget.page().error_occurred)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/browsertab.py", line 688, in _on_load_finished
    sess_manager.save_autosave()
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 305, in save_autosave
    self.save('_autosave')
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 287, in save
    data = self._save_all(only_window=only_window)
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 242, in _save_all
    win_data['tabs'].append(self._save_tab(tab, active))
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sessions.py", line 210, in _save_tab
    for idx, item in enumerate(tab.history):
AttributeError: 'NoneType' object has no attribute 'history'
```

```
23:22:20 DEBUG    destroy    mainwindow:_do_close:519 Closing window 0
23:22:20 DEBUG    destroy    webview:shutdown:124 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=0 url='http://unix.stackexchange.com/questions/37313/how-do-i-grep-for-multiple-patterns'>.
23:22:20 DEBUG    destroy    webview:shutdown:124 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=1 url='https://appdb.winehq.org/objectManager.php?sClass=version&iId=32828'>.
23:22:20 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://www.qwant.com/?q=roger moore')) (tab 0)
23:22:20 DEBUG    webview    tabbedbrowser:on_title_changed:515 Ignoring title change to ''.
23:22:20 DEBUG    sessions   sessions:save:280 Saving session _autosave to /home/arnaud/.local/share/qutebrowser/sessions/_autosave.yml...
23:22:20 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
```

cc @cosminadrianpopescu

**Comment by cosminadrianpopescu** [comment]
I will have a look at it.

**Comment by cosminadrianpopescu** [comment]
Do you have a scenario? I could not reproduce it on 0.10. I've tried with both backends. Opened a clean session or a loaded session. On manjaro Linux qt 5.8, PyQt 5.8 qt5-webengine 5.8.0-3.

**Comment by The-Compiler** [comment]
Unfortunately not - I just have that crash report without contact info.

From the log it looks like it happened when closing a window and then (immediately afterwards) saving the session. It might not even be related to autosave sessions.

From a quick look, we basically do `for win_id in objreg.window_registry:` there, but when a window is still in the process of being cleaned up, it can be in `window_registry` but not "alive" anymore.  Maybe something like that happened there?

**Comment by The-Compiler** [comment]
bcee6d295c6bf3661a222e556b5d7a9dc75085ca fixes this I think.
