### ISSUE TITLE
OSError: Refusing to double-open AppendLineParser with :history-clear

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2443]
When doing `:history-clear` right after starting, when qutebrowser is still loading the history from disk:

```
07:35:10 DEBUG    init       app:_init_late_modules:456 Reading web history...
# [...]
07:35:12 DEBUG    commands   command:run:509 command called: history-clear
# [...]
07:35:12 DEBUG    commands   command:run:524 Calling qutebrowser.mainwindow.prompt.PromptContainer.prompt_accept(<qutebrowser.mainwindow.prompt.PromptContainer win_id=0>, 'yes')
# [...]
07:35:13 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/history.py", line 250, in _do_clear
    self._lineparser.clear()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/lineparser.py", line 197, in clear
    with self._open('w'):
  File "/usr/lib64/python3.6/contextlib.py", line 82, in __enter__
    return next(self.gen)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/lineparser.py", line 99, in _open
    raise IOError("Refusing to double-open AppendLineParser.")
OSError: Refusing to double-open AppendLineParser.
```

cc @EliteTK

**Comment by EliteTK** [comment]
Well, I can't think of a nice way to solve this.

We could, if the history is being loaded, prevent it from being cleared, but this doesn't solve the underlying problem of being able to call BaseLineParser.clear() while the lineparser is open.

We could set a _clearpending flag in the lineparser if self._opened is set instead of doing the clear there and then, and then when self._opened is set to false at the end of _open, do a call to clear and that's possibly the nicest way I can think of doing this.

In fact, the only way to fully solve the problem would be to do both.

I can write a patch if that sounds like a good idea (feel free to criticise anything you like, I am not an OOP python programmer). I'm betting you'll want me to write tests but in all honesty I'm not sure where to start with that. If you can point me in the direction of something which tests the result of performing an action WHILE another is happening, that would be great.

Actually this could probably be tested with:

```
with lp._open('r') as f:
    lp.clear()
```

or something like that.

Still not sure how testing preventing history-clear would work.

**Comment by The-Compiler** [comment]
I think the most important thing would be to show an error rather than crashing.

However, #2295 is hopefully in soon - with that, there's no phase where we're still reading the history. So with that, it'll probably fix itself :wink:

With that in mind, I guess it's fine to live with this crash (as it doesn't happen often) until the completion refactor is in.
