### ISSUE TITLE
Deleted C++ object: WebView in _on_frame_load_finished

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2444]
Report with qutebrowser 0.10.0, Qt/PyQt 5.5.1, QtWebKit:

```
21:06:50 DEBUG    webelem    webelem:is_editable:257 Checking if element is editable: <qutebrowser.browser.webkit.webkitelem.WebKitElement html='<em class="_4qba" data-intl-translation="Get Access Token" data-intl-trid=""><!-- react-text: 391 -->Get Access Token<!-- /react-text --></em>'>
# ...
21:06:50 DEBUG    webview    webview:createWindow:200 createWindow with type WebBrowserWindow
# ...
21:06:51 DEBUG    destroy    webview:shutdown:124 Shutting down <qutebrowser.browser.webkit.webview.WebView tab_id=2 url='https://developers.facebook.com/tools/explorer/callback?#'>.
21:06:51 DEBUG    modes      tabbedbrowser:on_current_changed:590 Current tab changed, focusing <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=1 url='https://www.facebook.com/events/upcoming'>
21:06:51 DEBUG    save       savemanager:mark_dirty:72 Marking cookies as dirty.
21:06:51 DEBUG    misc       app:on_focus_object_changed:779 Focus object changed: <qutebrowser.browser.webkit.webview.WebView tab_id=1 url='https://www.facebook.com/events/upcoming'>
21:06:51 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
21:06:51 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
21:06:51 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
21:06:51 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
21:06:51 DEBUG    webview    webpage:acceptNavigationRequest:478 navigation request: url https://developers.facebook.com/tools/explorer/145634995501895/, type NavigationTypeOther, target ClickTarget.normal override None
21:06:51 DEBUG    webview    browsertab:_set_load_status:627 load status for <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=2 url='https://developers.facebook.com/tools/explorer/callback?#'>: LoadStatus.loading
21:06:51 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_status_changed('loading') (tab -1)
21:06:51 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_started() (tab -1)
21:06:51 DEBUG    webview    tabbedbrowser:_tab_index:139 Got invalid tab (index is -1)!
21:06:51 DEBUG    webview    tabbedbrowser:_tab_index:139 Got invalid tab (index is -1)!
21:06:51 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/browser/webkit/webkittab.py", line 705, in _on_frame_load_finished
    self._on_load_finished(not self._widget.page().error_occurred)
RuntimeError: wrapped C/C++ object of type WebView has been deleted
```

**Comment by The-Compiler** [comment]
Another one: https://crashes.qutebrowser.org/view/46e162e8

> In Facebook Graph API page, removing permissions for access token

**Comment by The-Compiler** [comment]
Seeing some similar reports with QtWebEngine recently:

```
15:56:39 DEBUG    webview    tabbedbrowser:_tab_index:157 Got invalid tab (index is -1)!
15:56:39 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/browsertab.py", line 761, in _on_load_finished
    if not self.title():
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 622, in title
    return self._widget.title()
RuntimeError: wrapped C/C++ object of type WebEngineView has been deleted
```

> qutebrowser crashed after I started a download and closed a tab shortly after that. Before closing, there were two tabs open, so closing the tab didn't quit qutebrowser.
