### ISSUE TITLE
AttributeError for target in DownloadManager.fetch

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2445]
Report with QtWebKit on v0.10.0, Qt 5.8:

```
20:45:36 DEBUG    downloads  qtnetworkdownloads:fetch:489 fetch: PyQt5.QtCore.QUrl('http://fileshare1190.dfiles.ru/auth-1488563002f18ee0debda0eb2671a1dc-91.240.209.90-123429004-166350587-guest/FS119-3/Win7.SP1.x86-x64.Rus-Eng.18in1.IE11%2B.Activated.v4.part1.rar') -> Win7.SP1.x86-x64.Rus-Eng.18in1.IE11+.Activated.v4.part1.rar
# ...
20:46:24 DEBUG    downloads  downloads:_set_filename:603 Setting filename to /mnt/kino
20:46:25 DEBUG    downloads  qtnetworkdownloads:_set_fileobj:211 buffer: 98304 bytes
# ...
20:47:04 DEBUG    downloads  downloads:_on_begin_remove_row:833 _on_begin_remove_row with idx 0, webengine False
20:47:04 DEBUG    downloads  downloads:_remove_item:758 Removed download 1: Win7.SP1.x86-x64.Rus-Eng.18in1.IE11+.Activated.v4.part1.rar [441.19kB/s|1:51:24| 1%|16.99MB/1.46GB]
20:47:04 DEBUG    downloads  downloads:cancel:482 cancelled
20:47:04 DEBUG    downloads  downloads:delete:499 Deleted /mnt/kino/Win7.SP1.x86-x64.Rus-Eng.18in1.IE11+.Activated.v4.part1.rar
# ...
20:48:58 DEBUG    downloads  qtnetworkdownloads:fetch:489 fetch: PyQt5.QtCore.QUrl('http://fileshare1190.dfiles.ru/auth-1488563002f18ee0debda0eb2671a1dc-91.240.209.90-123429004-166350587-guest/FS119-3/Win7.SP1.x86-x64.Rus-Eng.18in1.IE11%2B.Activated.v4.part1.rar') -> Win7.SP1.x86-x64.Rus-Eng.18in1.IE11+.Activated.v4.part1.rar
# ...
20:49:59 DEBUG    downloads  downloads:_set_filename:603 Setting filename to /mnt/kino/shares/files/win7
# ...
20:49:59 ERROR    message    message:error:63 Download error: Нет такого файла или каталога
# ...
20:50:24 DEBUG    downloads  qtnetworkdownloads:fetch:489 fetch: PyQt5.QtCore.QUrl('http://fileshare1190.dfiles.ru/auth-1488563002f18ee0debda0eb2671a1dc-91.240.209.90-123429004-166350587-guest/FS119-3/Win7.SP1.x86-x64.Rus-Eng.18in1.IE11%2B.Activated.v4.part1.rar') -> win7
## ...
20:50:24 DEBUG    downloads  downloads:_remove_item:758 Removed download 1: win7 [100%|1.46GB] - Нет такого файла или каталога
20:50:24 DEBUG    downloads  downloads:cancel:482 cancelled
20:50:24 DEBUG    downloads  downloads:delete:501 Not deleting /mnt/kino/shares/files/win7
# ...
20:50:38 DEBUG    downloads  downloads:_set_filename:603 Setting filename to /mnt/kino/shares/files/win/
# ...
20:50:38 ERROR    message    message:error:63 Download error: Нет такого файла или каталога
# ...
20:50:46 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 172, in retry
    suggested_filename=self.basename)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 485, in fetch
    suggested_filename = target.suggested_filename()
AttributeError: 'NoneType' object has no attribute 'suggested_filename'
```

**Comment by The-Compiler** [comment]
Just got another one, but can't reproduce it based on that description:

- 1) Attempted to download a file to a directory that didn't exist,
- 2) Used the command ":download-retry",
- 3) Manually created the directory,
- 4) Used the command ":download-retry" [crashed]

```
11:16:23 DEBUG    downloads  qtnetworkdownloads:fetch:464 fetch: PyQt5.QtCore.QUrl('http://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data') -> zoo.data
# [...]
11:16:27 DEBUG    downloads  downloads:_set_filename:618 Setting filename to /home/sean/downloads/zoo/data
# [...]
11:16:27 ERROR    message    message:error:62 Download error: No such file or directory
# [...]
11:16:33 DEBUG    commands   command:run:524 Calling qutebrowser.browser.downloads.DownloadModel.download_retry(<qutebrowser.browser.downloads.DownloadModel object at 0x7f251afd1048>, 0)
11:16:34 DEBUG    downloads  qtnetworkdownloads:fetch:464 fetch: PyQt5.QtCore.QUrl('http://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data') -> data
11:16:34 DEBUG    downloads  downloads:_on_begin_insert_row:837 _on_begin_insert_row with idx 1, webengine False
11:16:34 DEBUG    prompt     prompt:ask_question:151 Asking question <qutebrowser.utils.usertypes.Question default='/home/sean/downloads/zoo/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://archive.ics.uci.edu/ml/machine-learning-databases/zoo/zoo.data</b>' title='Save file to:'>, blocking False, loops [], queue deque([])
# [...]
11:16:34 DEBUG    downloads  downloads:_remove_item:773 Removed download 1: data [100%|4.03kB] - No such file or directory
11:16:34 DEBUG    downloads  downloads:cancel:473 cancelled
11:16:34 DEBUG    downloads  downloads:delete:492 Not deleting /home/sean/downloads/zoo/data
# [...]
11:16:34 DEBUG    downloads  qtnetworkdownloads:_on_reply_finished:261 Reply finished, fileobj None
11:16:35 DEBUG    modes      modeman:_eventFilter_keypress:166 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.keyparser.PassthroughKeyParser mode='prompt' warn=False>
11:16:35 DEBUG    commands   command:run:509 command called: prompt-accept
11:16:35 DEBUG    commands   command:run:524 Calling qutebrowser.mainwindow.prompt.PromptContainer.prompt_accept(<qutebrowser.mainwindow.prompt.PromptContainer win_id=0>, None)
# [...]
11:16:35 DEBUG    downloads  downloads:_set_filename:618 Setting filename to /home/sean/downloads/zoo/
# [...]
11:16:35 ERROR    message    message:error:62 Download error: Is a directory
# [...]
11:16:54 DEBUG    commands   command:run:509 command called: download-retry
11:16:54 DEBUG    commands   command:run:524 Calling qutebrowser.browser.downloads.DownloadModel.download_retry(<qutebrowser.browser.downloads.DownloadModel object at 0x7f251afd1048>, 0)
11:16:54 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 295, in run_safely
    self.run(text, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 274, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/downloads.py", line 983, in download_retry
    download.retry()
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 172, in retry
    suggested_filename=self.basename)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 460, in fetch
    suggested_filename = target.suggested_filename()
AttributeError: 'NoneType' object has no attribute 'suggested_filename'
```

**Comment by The-Compiler** [comment]
Ah, I can reproduce it by entering a path which is a directory (`/foo/bar/`), then creating it, then retrying the download.

**Comment by Carpetsmoker** [comment]
The fix is easy, but I tried writing a (failing) test for this. I have now officially promoted pytext-bdd to the worst test framework I have ever had the displease of being exposed to. What should be a simple 6-line test has escalated to 2+ hours of dealing with all sorts of nonsense.

Anyway, this is what I have so far:

```
diff --git i/tests/end2end/features/downloads.feature w/tests/end2end/features/downloads.feature
index fe312944f..9441b6726 100644
--- i/tests/end2end/features/downloads.feature
+++ w/tests/end2end/features/downloads.feature
@@ -212,6 +212,14 @@ Feature: Downloading things from a website.
         And I run :download-retry
         Then the error "No failed downloads!" should be shown
 
+    Scenario: Retrying a failed download when the directory didn't exist (issue 2445)
+		Given A random test directory
+		When I download http://localhost:(port)/data/downloads/download.bin to the random directory
+		And I wait for the error "Download error: No such file or directory"
+		And I make the test directory
+		And I run :download-retry
+        # Then the downloaded file download.bin should exist
+
     ## Wrong invocations
 
     Scenario: :download with deprecated dest-old argument
diff --git i/tests/end2end/features/test_downloads_bdd.py w/tests/end2end/features/test_downloads_bdd.py
index cb0388ea4..9ab261523 100644
--- i/tests/end2end/features/test_downloads_bdd.py
+++ w/tests/end2end/features/test_downloads_bdd.py
@@ -18,8 +18,9 @@
 # along with qutebrowser.  If not, see <http://www.gnu.org/licenses/>.
 
 import os
-import sys
 import shlex
+import sys
+import tempfile
 
 import pytest_bdd as bdd
 bdd.scenarios('downloads.feature')
@@ -147,3 +148,26 @@ def fifo_should_be_fifo(tmpdir):
     download_dir = tmpdir / 'downloads'
     assert download_dir.exists()
     assert not os.path.isfile(str(download_dir / 'fifo'))
+
+
+@bdd.scenario("downloads.feature", "Retrying a failed download when the directory didn't exist (issue 2445)")
+def test_arguments():
+    pass
+
+
+@bdd.given("A random test directory")
+def random_dir():
+    with tempfile.TemporaryDirectory(prefix='qutetest_') as tmp:
+        random_dir = tmp
+    return random_dir
+
+
+@bdd.when(bdd.parsers.parse("I download {url} to the random directory"))
+def download_dest(quteproc, httpbin, random_dir, url):
+    url = url.replace('(port)', str(httpbin.port))
+    quteproc.send_cmd(':download --dest {}/download.bin {}'.format(random_dir, url))
+
+
+@bdd.when(bdd.parsers.parse("I make the test directory"))
+def mkdir_test(random_dir):
+    os.makedirs(random_dir)
```

**Comment by The-Compiler** [comment]
Abandoned PR from #2497:

```patch
From 1cda172c22c82610ff38bc9f02165087e49446b7 Mon Sep 17 00:00:00 2001
From: Martin Tournoij <martin@arp242.net>
Date: Fri, 31 Mar 2017 05:09:25 +0100
Subject: [PATCH] Fix :download-retry for directories that didn't exist

Also:

- Adds the filename when showing errors. Makes for clearer error
  messages.
- Fix downloading files that end with a trailing /.
- The `retry()` method added with `self.cancel()`, but that would remove
  the file after it was downloaded(?!). I don't see any reason that
  should be there, so I think this fixes another bug?

Fixes #2445
---
 qutebrowser/browser/downloads.py             | 18 +++++++++----
 qutebrowser/browser/qtnetworkdownloads.py    |  4 +--
 tests/end2end/features/downloads.feature     | 17 ++++++++++--
 tests/end2end/features/test_downloads_bdd.py | 39 ++++++++++++++++++++++++++--
 4 files changed, 67 insertions(+), 11 deletions(-)

diff --git a/qutebrowser/browser/downloads.py b/qutebrowser/browser/downloads.py
index f9b246d3a1..7da0dd16ff 100644
--- a/qutebrowser/browser/downloads.py
+++ b/qutebrowser/browser/downloads.py
@@ -131,7 +131,12 @@ def create_full_filename(basename, filename):
     encoding = sys.getfilesystemencoding()
     filename = utils.force_encoding(filename, encoding)
     basename = utils.force_encoding(basename, encoding)
-    if os.path.isabs(filename) and os.path.isdir(filename):
+
+    if filename.endswith('/'):
+        # The path is a directory we want to store the file in (rather than the
+        # path *to* the file).
+        return os.path.join(filename, basename)
+    elif os.path.isabs(filename) and os.path.isdir(filename):
         # We got an absolute directory from the user, so we save it under
         # the default filename in that directory.
         return os.path.join(filename, basename)
@@ -359,6 +364,8 @@ class AbstractDownloadItem(QObject):
         error_msg: The current error message, or None
         fileobj: The file object to download the file to.
         raw_headers: The headers sent by the server.
+        basename: The basename to use if filename is a directory.
+        target: The DownloadTarget for this download.
         _filename: The filename of the download.
         _dead: Whether the Download has _die()'d.
 
@@ -383,12 +390,12 @@ def __init__(self, parent=None):
         self.done = False
         self.stats = DownloadItemStats(self)
         self.index = 0
-        self.error_msg = None
-        self.basename = '???'
         self.successful = False
-
+        self.error_msg = None
         self.fileobj = UnsupportedAttribute()
         self.raw_headers = UnsupportedAttribute()
+        self.basename = '???'
+        self.target = None
 
         self._filename = None
         self._dead = False
@@ -669,6 +676,7 @@ def set_target(self, target):
         Args:
             target: The DownloadTarget for this download.
         """
+        self.target = target
         if isinstance(target, FileObjDownloadTarget):
             self._set_fileobj(target.fileobj, autoclose=False)
         elif isinstance(target, FileDownloadTarget):
@@ -927,7 +935,7 @@ def download_cancel(self, all_=False, count=0):
                 if not count:
                     count = len(self)
                 raise cmdexc.CommandError("Download {} is already done!"
-                                        .format(count))
+                                          .format(count))
             download.cancel()
 
     @cmdutils.register(instance='download-model', scope='window')
diff --git a/qutebrowser/browser/qtnetworkdownloads.py b/qutebrowser/browser/qtnetworkdownloads.py
index 920673d4b2..7a9f5f191e 100644
--- a/qutebrowser/browser/qtnetworkdownloads.py
+++ b/qutebrowser/browser/qtnetworkdownloads.py
@@ -103,7 +103,7 @@ def _create_fileobj(self):
         try:
             fileobj = open(self._filename, 'wb')
         except OSError as e:
-            self._die(e.strerror)
+            self._die('{}: {}'.format(e.strerror, self._filename))
         else:
             self._set_fileobj(fileobj)
 
@@ -172,9 +172,9 @@ def retry(self):
         assert not self.successful
         new_reply = self._retry_info.manager.get(self._retry_info.request)
         new_download = self._manager.fetch(new_reply,
+                                           target=self.target,
                                            suggested_filename=self.basename)
         self.adopt_download.emit(new_download)
-        self.cancel()
 
     def _get_open_filename(self):
         filename = self._filename
diff --git a/tests/end2end/features/downloads.feature b/tests/end2end/features/downloads.feature
index 51cb6a0907..208a70db98 100644
--- a/tests/end2end/features/downloads.feature
+++ b/tests/end2end/features/downloads.feature
@@ -213,6 +213,19 @@ Feature: Downloading things from a website.
         And I run :download-retry
         Then the error "No failed downloads!" should be shown
 
+    Scenario: Retrying a failed download when the directory didn't exist (issue 2445)
+        When I download http://localhost:(port)/data/downloads/download.bin to <path>
+        And I wait for the error "Download error: No such file or directory: *"
+        And I make the directory <mkdir>
+        And I run :download-retry
+        And I wait until the download is finished
+        Then the downloaded file <expected> should exist
+
+        Examples:
+        | path                 | mkdir   | expected             |
+        | asd/zxc/             | asd/zxc | asd/zxc/download.bin |
+        | qwe/rty              | qwe     | qwe/rty              |
+
     ## Wrong invocations
 
     Scenario: :download with deprecated dest-old argument
@@ -230,7 +243,7 @@ Feature: Downloading things from a website.
 
     Scenario: :download with a directory which doesn't exist
         When I run :download --dest (tmpdir)/downloads/somedir/filename http://localhost:(port)/
-        Then the error "Download error: No such file or directory" should be shown
+        Then the error "Download error: No such file or directory: *" should be shown
 
     ## mhtml downloads
 
@@ -573,7 +586,7 @@ Feature: Downloading things from a website.
     Scenario: Downloading to unwritable destination
         When I set storage -> prompt-download-directory to false
         And I run :download http://localhost:(port)/data/downloads/download.bin --dest (tmpdir)/downloads/unwritable
-        Then the error "Download error: Permission denied" should be shown
+        Then the error "Download error: Permission denied: *" should be shown
 
     Scenario: Downloading 20MB file
         When I set storage -> prompt-download-directory to false
diff --git a/tests/end2end/features/test_downloads_bdd.py b/tests/end2end/features/test_downloads_bdd.py
index 616c3cb149..0b65677765 100644
--- a/tests/end2end/features/test_downloads_bdd.py
+++ b/tests/end2end/features/test_downloads_bdd.py
@@ -18,8 +18,8 @@
 # along with qutebrowser.  If not, see <http://www.gnu.org/licenses/>.
 
 import os
-import sys
 import shlex
+import sys
 
 import pytest_bdd as bdd
 bdd.scenarios('downloads.feature')
@@ -86,7 +86,12 @@ def download_should_not_exist(filename, tmpdir):
 
 @bdd.then(bdd.parsers.parse("The downloaded file {filename} should exist"))
 def download_should_exist(filename, tmpdir):
-    path = tmpdir / 'downloads' / filename
+    path = tmpdir / 'downloads'
+    if '/' in filename:
+        for f in filename.split('/'):
+            path /= f
+    else:
+        path = tmpdir / 'downloads' / filename
     assert path.check()
 
 
@@ -149,3 +154,33 @@ def fifo_should_be_fifo(tmpdir):
     download_dir = tmpdir / 'downloads'
     assert download_dir.exists()
     assert not os.path.isfile(str(download_dir / 'fifo'))
+
+
+@bdd.when(bdd.parsers.parse("I download {url} to <path>"))
+def download_dest(quteproc, httpbin, tmpdir, url, path):
+    dest = '{}/downloads/{}'.format(tmpdir, path)
+    assert not os.path.exists(dest)
+
+    url = url.replace('(port)', str(httpbin.port))
+    quteproc.send_cmd(':download --dest {} {}'.format(dest, url))
+
+
+@bdd.when(bdd.parsers.parse("I make the directory <mkdir>"))
+def mkdir_test(tmpdir, mkdir):
+    dest = tmpdir / 'downloads'
+    for p in mkdir.split('/'):
+        dest /= p
+    assert not dest.exists()
+    dest.ensure(dir=True)
+    assert dest.exists()
+
+
+@bdd.then(bdd.parsers.parse("The downloaded file <expected> should exist"))
+def download_should_exist_table(tmpdir, expected):
+    path = tmpdir / 'downloads'
+    if '/' in expected:
+        for f in expected.split('/'):
+            path /= f
+    else:
+        path = tmpdir / 'downloads' / expected
+    assert path.check()
```
