### ISSUE TITLE
Crash with invalid PAC file

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2476]
With this PAC file:

```js
function FindProxyForURL(url, host) {
  return 'SOCKS5 172.26.133.85:1080';
}
```

we get:

```
13:29:34 ERROR: Error in PAC resolution: Unknown proxy type: SOCKS5.
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/network/pac.py", line 306, in resolve
    return self._pac.resolve(query, from_file=from_file)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/network/pac.py", line 225, in resolve
    return self._parse_proxy_string(result_str)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/network/pac.py", line 170, in _parse_proxy_string
    return [PACResolver._parse_proxy_entry(x) for x in proxies]
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/network/pac.py", line 170, in <listcomp>
    return [PACResolver._parse_proxy_entry(x) for x in proxies]
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/network/pac.py", line 165, in _parse_proxy_entry
    raise ParseProxyError(err.format(config[0]))
qutebrowser.browser.network.pac.ParseProxyError: Unknown proxy type: SOCKS5
```

```
13:29:34 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/network/proxy.py", line 69, in queryProxy
    for p in proxies:
TypeError: 'QNetworkProxy' object is not iterable
```

Also, maybe that file should be parsable? I'm told it works in other browsers.

cc @abbradar @amosbird

**Comment by The-Compiler** [comment]
The crash is still there, so I'm reopening this.

**Comment by amosbird** [comment]
Huh? It works fine here. What did you try?

**Comment by The-Compiler** [comment]
Still crashes with something like:

```js
function FindProxyForURL(url, host) {
  return 'FOO 172.26.133.85:1080';
}
```

**Comment by amosbird** [comment]
ah, right :smile: . I thought the crash may be a wanted behavior.

**Comment by abbradar** [comment]
I'll be able to look at it in the weekend if noone beats me -- I suppose we don't handle evaluation exceptions that I throw gracefully.

**Comment by The-Compiler** [comment]
From a quick look, `PACFetcher.resolve` should return `[QNetworkProxy(QNetworkProxy.HttpProxy, error_host, 9)]` instead of that proxy without a list. This really needs a test though.

**Comment by abbradar** [comment]
Sorry, I _still_ haven't found time to tackle the bug. I'll try this week!

**Comment by amosbird** [comment]
@abbradar when you do, please take a look of the ftp related issue. It seems the proxy doesn't work for ftp sites.

**Comment by amosbird** [comment]
Ah, right. Sorry for the noise :smile:
