### ISSUE TITLE
qute:help issues after qute: redirection

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2513]
Before 4ec5700cbf9ced71c24d57de3ddcae102c9116c0, opening `qute:help` gave us a 404 with:

```
12:17:24 ERROR: OSError while handling qute:* URL
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/qutescheme.py", line 139, in data_for_url
    mimetype, data = handler(url)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/qutescheme.py", line 104, in wrapper
    return self._function(*args, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/qutescheme.py", line 417, in qute_help
    data = utils.read_file(path)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/utils.py", line 146, in read_file
    data = pkg_resources.resource_string(qutebrowser.__name__, filename)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1215, in resource_string
    self, resource_name
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1457, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1577, in _get
    with open(path, 'rb') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/florian/proj/qutebrowser/git/qutebrowser/html/doc/help'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginequtescheme.py", line 54, in requestStarted
    mimetype, data = qutescheme.data_for_url(url)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/qutescheme.py", line 142, in data_for_url
    raise QuteSchemeOSError(e)
qutebrowser.browser.qutescheme.QuteSchemeOSError: [Errno 2] No such file or directory: '/home/florian/proj/qutebrowser/git/qutebrowser/html/doc/help'
```

After that commit, opening it *seems* to work. However, clicking a link just opens `about:blank`, and following a link with hints crashes the rendering process with:

```
Received signal 11 SEGV_MAPERR 000000000011
#0 0x7fa2b27b630e base::debug::StackTrace::StackTrace()
#1 0x7fa2b27b66e9 base::debug::(anonymous namespace)::StackDumpSignalHandler()
#2 0x7fa2adecefe0 <unknown>
#3 0x7fa2b1f0780a blink::SuspendableScriptExecutor::executeAndDestroySelf()
#4 0x7fa2b1f07c15 blink::SuspendableScriptExecutor::run()
#5 0x7fa2b1ea516e blink::WebLocalFrameImpl::requestExecuteScriptInIsolatedWorld()
#6 0x7fa2b25b946f content::RenderFrameImpl::OnJavaScriptExecuteRequestInIsolatedWorld()
#7 0x7fa2b25bcbe5 content::RenderFrameImpl::OnJavaScriptExecuteRequestInIsolatedWorld()
#8 0x7fa2b25c6e96 _ZN3IPC8MessageTI53FrameMsg_JavaScriptExecuteRequestInIsolatedWorld_MetaSt5tupleIJNSt7__cxx1112basic_stringItN4base20string16_char_traitsESaItEEEibiEEvE8DispatchIN7content15RenderFrameImplESD_vMSD_FvRKS8_ibiEEEbPKNS_7MessageEPT_PT0_PT1_T2_
#9 0x7fa2b25d81a3 content::RenderFrameImpl::OnMessageReceived()
#10 0x7fa2b2501847 IPC::MessageRouter::RouteMessage()
#11 0x7fa2b10f28c1 content::ChildThreadImpl::OnMessageReceived()
#12 0x7fa2b24f4003 IPC::ChannelProxy::Context::OnDispatchMessage()
#13 0x7fa2b282d2bd base::debug::TaskAnnotator::RunTask()
#14 0x7fa2b3030054 scheduler::TaskQueueManager::ProcessTaskFromWorkQueue()
#15 0x7fa2b3030687 scheduler::TaskQueueManager::DoWork()
#16 0x7fa2b282d2bd base::debug::TaskAnnotator::RunTask()
#17 0x7fa2b27d3aed base::MessageLoop::RunTask()
#18 0x7fa2b27d46fd base::MessageLoop::DeferOrRunPendingTask()
#19 0x7fa2b27d49e8 base::MessageLoop::DoWork()
#20 0x7fa2b27d64a9 base::MessagePumpDefault::Run()
#21 0x7fa2b27ec6c4 base::RunLoop::Run()
#22 0x7fa2b27d28c5 base::MessageLoop::Run()
#23 0x7fa2b260f500 content::RendererMain()
#24 0x7fa2b134b32e content::RunZygote()
#25 0x7fa2b134b838 content::ContentMainRunnerImpl::Run()
#26 0x7fa2b1349ab9 content::ContentMain()
#27 0x7fa2b0c4a264 QtWebEngine::processMain()
#28 0x000000400963 main
```

**Comment by The-Compiler** [comment]
Opening them via `F` works fine - ctrl-click or middle-click also opens `about:blank`. Looks like Qt does something weird to the page when redirecting?!
