### ISSUE TITLE
Binding with !normal mode crashes

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2566]
When doing `:bind --mode !normal foo leave-mode`, we get:

```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 296, in run_safely
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 275, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 186, in bind
    modes = [usertypes.KeyMode[m] for m in modenames]
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/parsers/keyconf.py", line 186, in <listcomp>
    modes = [usertypes.KeyMode[m] for m in modenames]
  File "/home/florian/code/qt/59env/lib/python3.6/enum.py", line 327, in __getitem__
    return cls._member_map_[name]
KeyError: '!normal'
```

This probably will just be fixed with the new config, but it makes a nice test case.

**Comment by The-Compiler** [comment]
Something like `!normal` won't exist for the new config anymore.
