### ISSUE TITLE
Python 2 syntax error

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2567]
qutebrowser is supposed to show an error when run with python 2, but a syntax error breaks that:

```
Traceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 25, in <module>
    import qutebrowser.qutebrowser
  File "qutebrowser/qutebrowser.py", line 133
    def logfilter_error(logfilter: str):
                                 ^
SyntaxError: invalid syntax
```

**Comment by luizhsc** [comment]
same problem

**Comment by The-Compiler** [comment]
@luizhsc huh, what do you mean?
