### ISSUE TITLE
Add dependency for PyQt5.QtOpenGL

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2683]
We recently added Nouveau detection assuming that QtOpenGL will always be available with QtWebEngine.

However, on distributions with split PyQt packages (such as Void Linux), this isn't true:

```
Traceback (most recent call last):
  File "/home/noctua/.local/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==0.10.1', 'gui_scripts', 'qutebrowser')()
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 178, in main
    return app.run(args)
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/app.py", line 112, in run
    init(args, crash_handler)
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/app.py", line 138, in init
    _init_modules(args, crash_handler)
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/app.py", line 472, in _init_modules
    browsertab.init()
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/browser/browsertab.py", line 63, in init
    webenginetab.init()
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 54, in init
    if version.opengl_vendor() == 'nouveau' and not software_rendering:
  File "/home/noctua/.local/lib/python3.5/site-packages/qutebrowser/utils/version.py", line 413, in opengl_vendor
    vf = ctx.versionFunctions(vp)
ImportError: No module named 'PyQt5._QOpenGLFunctions_2_0'
```

So PyQt5.QtOpenGL should be added to `earlyinit.py` (with QtWebEngine) and `INSTALL.asciidoc` where needed. Maybe it's also time to make PyOpenGL a required dependency to fix the "black screen" issue with some setups, looks like it's available for all distributions.

cc @NoctuaNivalis

**Comment by NoctuaNivalis** [comment]
This patch gives the correct dependency error window:

```patch
diff --git a/qutebrowser/misc/earlyinit.py b/qutebrowser/misc/earlyinit.py
index 1a0c361fc..d4a572962 100644
--- a/qutebrowser/misc/earlyinit.py
+++ b/qutebrowser/misc/earlyinit.py
@@ -322,6 +322,7 @@ def check_libraries(backend):
     if backend == 'webengine':
         modules['PyQt5.QtWebEngineWidgets'] = _missing_str("QtWebEngine",
                                                            webengine=True)
+        modules['PyQt5.QtOpenGL'] = _missing_str("QtOpenGL", webengine=True)
     else:
         assert backend == 'webkit'
         modules['PyQt5.QtWebKit'] = _missing_str("PyQt5.QtWebKit")

```
