### ISSUE TITLE
Crash on startup in opengl_vendor

### ISSUE THREAD

**Issue by teto** [qutebrowser/qutebrowser#2694]
With
```
qutebrowser v0.10.1
Git commit: v0.10.0-753-g71117f6de (2017-06-04 15:12:11 +0200)
Backend: QtWebEngine (Chromium 53.0.2785.148)

CPython: 3.5.3
Qt: 5.8.0
PyQt: 5.8.2

sip: 4.19.2
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.1 $Id$
typing: yes
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
SSL: OpenSSL 1.0.2g  1 Mar 2016

Style: QFusionStyle
Platform: Linux-4.10.0-21-generic-x86_64-with-Ubuntu-17.04-zesty, 64bit
Linux distribution: Ubuntu 17.04 (ubuntu)
Frozen: False
Imported from /home/teto/qutebrowser/qutebrowser
Qt library executable path: /home/teto/.local/lib/python3.5/site-packages/PyQt5/Qt/libexec, data path: /home/teto/.local/lib/python3.5/site-packages/PyQt5/Qt

Paths:
download: /home/teto
data: /home/teto/.local/share/qutebrowser
system_data: /home/teto/.local/share/qutebrowser
config: /home/teto/.config/qutebrowser
cache: /home/teto/.cache/qutebrowser
runtime: /run/user/1000/qutebrowser
```
I now get on startup:
```
21:34:42 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/teto/.local/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser', 'gui_scripts', 'qutebrowser')()
  File "/home/teto/qutebrowser/qutebrowser/qutebrowser.py", line 178, in main
    return app.run(args)
  File "/home/teto/qutebrowser/qutebrowser/app.py", line 112, in run
    init(args, crash_handler)
  File "/home/teto/qutebrowser/qutebrowser/app.py", line 138, in init
    _init_modules(args, crash_handler)
  File "/home/teto/qutebrowser/qutebrowser/app.py", line 472, in _init_modules
    browsertab.init()
  File "/home/teto/qutebrowser/qutebrowser/browser/browsertab.py", line 63, in init
    webenginetab.init()
  File "/home/teto/qutebrowser/qutebrowser/browser/webengine/webenginetab.py", line 54, in init
    if version.opengl_vendor() == 'nouveau' and not software_rendering:
  File "/home/teto/qutebrowser/qutebrowser/utils/version.py", line 401, in opengl_vendor
    assert ok
AssertionError
```
While at some point I had nouveau installed, my system should now use Nvidia drivers.

**Comment by The-Compiler** [comment]
I have no idea why that would fail for you and can't find a way to debug it either - so I just made the errors non-fatal for now.

**Comment by teto** [comment]
Could it be because of a driver update ? I rebooted and without upgrading qutebrowser, it's fixed.

**Comment by lahwaacz** [comment]
When I upgrade the nvidia driver in Arch Linux, using vdpau in mpv or any CUDA program is not possible until I reboot. I wouldn't be surprised if it was the same with OpenGL, though I never checked it.
