### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'data' (tab.data.pinned)

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2759]
Report on 4d64bcc85 with QtWebEngine, with no pinned tabs.

Relevant part of [the log](https://crashes.qutebrowser.org/view/4238577b):

```
15:45:32 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://duckduckgo.com/?q=opus+store+video&ia=web')) (tab 1)
15:45:32 DEBUG    webview    tabbedbrowser:on_title_changed:539 Changing title for idx 1 to 'opus store video at DuckDuckGo'
[...]
15:45:34 DEBUG    webview    browsertab:_set_load_status:653 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=92 url='https://duckduckgo.com/?q=opus+store+video&ia=web'>: LoadStatus.success_https
[...]
15:45:41 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.tab_close(<qutebrowser.browser.commands.CommandDispatcher>, False, False, False, False, None)
15:45:41 DEBUG    modes      tabbedbrowser:on_current_changed:606 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=91 url='file:///home/user/.config/qutebrowser/start.html'>
[...]
15:45:41 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: 92
15:45:41 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: tab
15:45:41 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: hintmanager
15:45:41 DEBUG    destroy    objreg:_on_destroyed:130 removed: 92
15:45:41 DEBUG    destroy    objreg:_on_destroyed:130 removed: tab
15:45:41 DEBUG    destroy    objreg:_on_destroyed:130 removed: hintmanager
[...]
15:46:25 DEBUG    commands   command:run:509 command called: undo
15:46:25 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.undo(<qutebrowser.browser.commands.CommandDispatcher>)
15:46:25 DEBUG    webview    tabbedbrowser:on_title_changed:539 Changing title for idx 0 to 'https://duckduckgo.com/?q=opus+store+video&ia=web'
[...]
15:46:25 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/home/user/.git_repos/qutebrowser/qutebrowser/app.py", line 899, in eventFilter
    return handler(event)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/app.py", line 859, in _handle_key_event
    return man.eventFilter(event)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/keyinput/modeman.py", line 337, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/keyinput/modeman.py", line 168, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/keyinput/basekeyparser.py", line 311, in handle
    match = self._handle_single_key(e)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/keyinput/modeparsers.py", line 75, in _handle_single_key
    match = super()._handle_single_key(e)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/keyinput/basekeyparser.py", line 200, in _handle_single_key
    self.execute(binding, self.Type.chain, count)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/keyinput/keyparser.py", line 44, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/commands/runners.py", line 275, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/browser/commands.py", line 928, in undo
    self._tabbed_browser.undo()
  File "/home/user/.git_repos/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 343, in undo
    self.set_tab_pinned(idx, pinned)
  File "/home/user/.git_repos/qutebrowser/qutebrowser/mainwindow/tabwidget.py", line 111, in set_tab_pinned
    if tab.data.pinned != pinned or loading:
AttributeError: 'NoneType' object has no attribute 'data'
```

From a quick look at the code, this can only happen when `self.widget(idx)` returned `None` - which makes some sense because the index was apparently `0`?

@jgkamat do you have any idea what happened here?

**Comment by jgkamat** [comment]
Hmm, I never expected `self.widget(*)` to return None, but I would still like to figure out why this happened... Currently I can't seem to reproduce, but I'll work on trying to figure it out. The closest I can get (getting idx to == `0`) is `:set tabs last-close-blank` and then closing, and undoing.

```
12:25:07 DEBUG    webview    tabbedbrowser:on_title_changed:551 Changing title for idx 0 to 'about:blank'
12:25:07 DEBUG    webview    webpage:acceptNavigationRequest:478 navigation request: url https://github.com/, type NavigationTypeBackOrForward, target ClickTarget.normal override None
12:25:07 DEBUG    webview    browsertab:_set_load_status:653 load status for <qutebrowser.browser.webkit.webkittab.WebKitTab tab_id=6 url='about:blank'>: LoadStatus.loading
12:25:07 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_status_changed('loading') (tab 0)
12:25:07 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_load_started() (tab 0)
12:25:07 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
12:25:07 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
12:25:07 DEBUG    modes      modeman:_eventFilter_keypress:192 handled: True, forward-unbound-keys: auto, passthrough: False, is_non_alnum: False --> filter: True (focused: <qutebrowser.browser.webkit.webview.WebView tab_id=6 url='about:blank'>)
12:25:07 DEBUG    qt         Unknown module:none:0 QNetworkReplyHttpImplPrivate::_q_startOperation was called more than once QUrl("https://github.com/")
  File "/usr/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/local/lib/python3.5/dist-packages/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/usr/local/lib/python3.5/dist-packages/qutebrowser/qutebrowser.py", line 178, in main
    return app.run(args)
  File "/usr/local/lib/python3.5/dist-packages/qutebrowser/app.py", line 113, in run
    ret = qt_mainloop()
  File "/usr/local/lib/python3.5/dist-packages/qutebrowser/app.py", line 123, in qt_mainloop
    return qApp.exec_()
  File "/usr/local/lib/python3.5/dist-packages/qutebrowser/utils/log.py", line 442, in qt_message_handler
    stack = ''.join(traceback.format_stack())

12:25:07 DEBUG    modes      modeman:_eventFilter_keyrelease:212 filter: True
12:25:08 DEBUG    save       savemanager:mark_dirty:72 Marking cookies as dirty.
12:25:08 DEBUG    webview    tabbedbrowser:on_title_changed:551 Changing title for idx 0 to 'https://github.com/'
12:25:08 DEBUG    signals    signalfilter:_filter_signals:86 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://github.com/')) (tab 0)
12:25:08 DEBUG    webview    tabbedbrowser:on_title_changed:543 Ignoring title change to ''.
12:25:08 DEBUG    webview    tabbedbrowser:on_title_changed:551 Changing title for idx 0 to 'The world's leading software development platform · GitHub'
12:25:08 DEBUG    save       savemanager:mark_dirty:72 Marking history as dirty.
```

(that stack trace above seems unrelated and dosen't crash the browser (but we might want to look into it)). I can't use webengine right now, but I'll try and take a closer look at this tonight.

If we are unable to figure this out, we might just want to log it and skip like [in the other places](https://github.com/qutebrowser/qutebrowser/blob/master/qutebrowser/mainwindow/tabbedbrowser.py#L364-L365). Really would like a way to repo this though :P

**Comment by jgkamat** [comment]
@The-Compiler nope, still unable to reproduce, and have a very similar log to the one before. If you want, I can submit a PR that replaces this crash with a warning log message (and assumes that the tab is unpinned), but if this statement can be `None` a bunch of other things might be broken as well (so I would really like to see how this happened....)

**Comment by The-Compiler** [comment]
So in general, `self.widget(...)` will give you `None` when there's no widget with the given index - so if you pass an index which is either negative, or bigger than `self.count() - 1`.

I just got another report, where it looks like the saved index was higher than what the restored tab actually got?

```python
18:30:15 DEBUG    commands   command:run:509 command called: undo
18:30:15 DEBUG    commands   command:run:524 Calling qutebrowser.browser.commands.CommandDispatcher.undo(<qutebrowser.browser.commands.CommandDispatcher>)
18:30:15 DEBUG    webview    tabbedbrowser:tabopen:408 Creating new tab with URL PyQt5.QtCore.QUrl('http://rulesoftheinternet.com/'), background False, explicit False, idx 8
18:30:15 DEBUG    webview    tabbedbrowser:on_title_changed:551 Changing title for idx 7 to 'http://rulesoftheinternet.com/'
18:30:15 DEBUG    misc       app:on_focus_object_changed:803 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f5827424a68>
18:30:15 DEBUG    modes      tabbedbrowser:on_current_changed:618 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=27 url=''>
18:30:15 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
18:30:15 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
18:30:15 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
18:30:15 DEBUG    modes      modeman:leave:294 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
18:30:15 DEBUG    mouse      mouse:eventFilter:56 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f58611e4948> got new child <PyQt5.QtWidgets.QWidget object at 0x7f5827411f78>, installing filter
18:30:15 DEBUG    misc       app:on_focus_object_changed:803 Focus object changed: <qutebrowser.mainwindow.mainwindow.MainWindow>
18:30:15 ERROR    misc       crashsignal:exception_hook:205 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 899, in eventFilter
    return handler(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 859, in _handle_key_event
    return man.eventFilter(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 337, in eventFilter
    return self._eventFilter_keypress(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 168, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/basekeyparser.py", line 311, in handle
    match = self._handle_single_key(e)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeparsers.py", line 75, in _handle_single_key
    match = super()._handle_single_key(e)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/basekeyparser.py", line 200, in _handle_single_key
    self.execute(binding, self.Type.chain, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/keyparser.py", line 44, in execute
    self._commandrunner.run(cmdstr, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 275, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 525, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/commands.py", line 930, in undo
    self._tabbed_browser.undo()
  File "/usr/lib/python3.6/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 343, in undo
    self.set_tab_pinned(idx, pinned)
  File "/usr/lib/python3.6/site-packages/qutebrowser/mainwindow/tabwidget.py", line 111, in set_tab_pinned
    if tab.data.pinned != pinned or loading:
AttributeError: 'NoneType' object has no attribute 'data'
```

**Comment by The-Compiler** [comment]
So the main issue here seems to be that the index we get from the undo stack doesn't match the index the tab gets when re-inserted.

When would that happen? If we *open* more tabs in the meantime, we should still always be able to insert at the earlier index. If we *close* more tabs, they should land on the top of the undo stack, so I think we can never have less tabs open than we had when it was closed, right? Also cc @Enzime who originally implemented index saving/restoring in #1826.

Perhaps a better solution for now would be to get the correct index via `self.index(newtab)` again, or (what I'd probably prefer), make `set_tab_pinned` take a tab widget instead of an index, which would simplify some other callers as well.

**Comment by lahwaacz** [comment]
The [documentation](qute://help/commands.html#undo) of the undo command says:

> Re-open a closed tab (optionally skipping [count] closed tabs).

I still have no idea how it works, but it seems possible to undo even from the middle of the stack. So if you have 5 tabs, close 4 of them (from the right) and then restore the one that was closed first, there new index will be 2 instead of 5.

**Comment by jgkamat** [comment]
@lahwaacz I noticed that, but I couldn't get `:undo` to work as documented (via `:run-with-count`). We probably need to open a seperate issue for that though. 

I think that via @The-Compiler's comment above and a little IRC discussion we had, I'll be able to figure out a way to fix this (although, I would still like the method to repro, so I can actually test it).

**Comment by The-Compiler** [comment]
Looks like that documentation was originally added long ago in b22b19d881db8a156837cd66031cbc85733d4c69 but it was never implemented that way - `:undo` never handled `count`... I'll fix that up in `master`.

**Comment by The-Compiler** [comment]
Let's hope #2765 helps.
