### ISSUE TITLE
KeyError when completing search engine

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2893]
```
:set searchengines j https://jisho.org/{}
:set searchengines j␣
```

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/completion/completer.py", line 236, in _update_completion
    model = func(*args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/completion/models/configmodel.py", line 79, in value
    default = configdata.DATA[sectname][optname].default() or '""'
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/sections.py", line 53, in __getitem__
    return self.values[key]
  File "/usr/lib/python3.6/collections/__init__.py", line 885, in __getitem__
    return self.__missing__(key)            # support subclasses that define __missing__
  File "/usr/lib/python3.6/collections/__init__.py", line 877, in __missing__
    raise KeyError(key)
KeyError: 'j'
```

Maybe best to delay this after the new config is in though. Probably already fixed then :wink:

cc @rcorre

**Comment by rcorre** [comment]
> Maybe best to delay this after the new config is in though

Agreed. I'm in the process of merging now.

**Comment by The-Compiler** [comment]
Fixed with the new config.

**Comment by Phantop** [comment]
I'm afraid I have no way, at all, of setting extra search engines. Trying to do this the way initially shown gives an unrecognized arguments error and there is no way to set this in qute://settings. What's up with that?
