### ISSUE TITLE
KeyError when deleting URL with space

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#2963]
When opening an [URL with a space](https://github.com/qutebrowser/qutebrowser/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20test) and then deleting that entry with `Ctrl-d` in the URL completion, this happens:

```
13:15:01 DEBUG    commands   command:run:515 Calling qutebrowser.completion.completionwidget.CompletionView.completion_item_del(<qutebrowser.completion.completionwidget.CompletionView>)
13:15:01 DEBUG    completion urlmodel:_delete_history:33 Deleting history entry https://github.com/qutebrowser/qutebrowser/issues?utf8=✓&q=is%3Aissue is%3Aopen test
13:15:01 DEBUG    sql        sql:__init__:80 Preparing SQL query: "DELETE FROM History where url = :val"
13:15:01 DEBUG    sql        sql:run:99 Running SQL query: "DELETE FROM History where url = :val"
13:15:01 DEBUG    sql        sql:run:102 query bindings: {':val': 'https://github.com/qutebrowser/qutebrowser/issues?utf8=✓&q=is%3Aissue is%3Aopen test'}
13:15:01 ERROR    misc       crashsignal:exception_hook:210 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 882, in eventFilter
    return handler(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 842, in _handle_key_event
    return man.eventFilter(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 330, in eventFilter
    return self._eventFilter_keypress(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 165, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 258, in handle
    handled = self._handle_special_key(e)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 137, in _handle_special_key
    self.execute(cmdstr, self.Type.special, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyparser.py", line 44, in execute
    self._commandrunner.run(cmdstr, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 292, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 516, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/completionwidget.py", line 379, in completion_item_del
    self.model().delete_cur_item(index)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/models/completionmodel.py", line 228, in delete_cur_item
    cat.delete_func(data)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/models/urlmodel.py", line 35, in _delete_history
    hist.delete_url(urlstr)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/history.py", line 147, in delete_url
    self.delete('url', url)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/sql.py", line 196, in delete
    raise KeyError('No row with {} = "{}"'.format(field, value))
KeyError: 'No row with url = "https://github.com/qutebrowser/qutebrowser/issues?utf8=✓&q=is%3Aissue is%3Aopen test"'
```

cc @rcorre @forkbong

**Comment by lahwaacz** [comment]
This still happens for some URLs, probably because the URLs imported from the text file were originally not percent-encoded and now they are (or vice versa, I don't really remember) - see #2903.

See this commit: https://github.com/qutebrowser/qutebrowser/pull/2965/files

Originally, `self.delete('url', url)` was a problem and now `self.delete('url', self._format_url(qurl))`, because neither format corresponds a priori to _all_ database entries. But I don't see why it's necessary to use one specific format - the completion asks the database to show a URL, so it already knows what URL is stored in the database and it should use the exact value returned by the database when asking it to delete the row.

Furthermore, these database queries should not crash the browser.

**Comment by The-Compiler** [comment]
Reopening this for now so this doesn't get lost, but a way to reproduce this would be great.

> But I don't see why it's necessary to use one specific format - the completion asks the database to show a URL, so it already knows what URL is stored in the database and it should use the exact value returned by the database when asking it to delete the row.

Because `:completion-item-del` operates on strings internally (in a human-readable format) - it operates on completion items, and those can come from other sources than the database.

**Comment by lahwaacz** [comment]
That's the problem with not doing data migrations in databases - new code easily loses track of what can or cannot be stored in the database and it's impossible to reproduce the old data with the new code.

**Comment by The-Compiler** [comment]
Related report from @lahwaacz: https://crashes.qutebrowser.org/view/fe2d9ad3

> This report reproduces the problem with deleting an old URL from the SQL database, which happens because the old URLs were not migrated to the format expected by the new code. The issue is the same as https://github.com/qutebrowser/qutebrowser/issues/2963 but with unicode characters instead of spaces.
>
> I can provide more URLs but it's kinda exhausting to let the browser crash to see if it's stored in the old or new format.

```

 17:25:49 DEBUG    commands   command:run:500 Calling qutebrowser.completion.completionwidget.CompletionView.completion_item_del(<qutebrowser.completion.completionwidget.CompletionView>)
17:25:49 DEBUG    completion urlmodel:_delete_history:33 Deleting history entry https://uloz.to/hledej?q=Ernelláék+Farkaséknál
17:25:49 DEBUG    sql        sql:__init__:150 Preparing SQL query: "DELETE FROM History where url = :val"
17:25:49 DEBUG    sql        sql:run:168 Running SQL query: "DELETE FROM History where url = :val"
17:25:49 DEBUG    sql        sql:run:171 query bindings: {':val': 'https://uloz.to/hledej?q=Ernell%C3%A1%C3%A9k+Farkas%C3%A9kn%C3%A1l'}
17:25:49 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 921, in eventFilter
    return handler(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 894, in _handle_key_event
    return man.eventFilter(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 331, in eventFilter
    return handler(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 162, in _eventFilter_keypress
    handled = parser.handle(event)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/basekeyparser.py", line 267, in handle
    handled = self._handle_special_key(e)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/basekeyparser.py", line 139, in _handle_special_key
    self.execute(cmdstr, self.Type.special, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/keyinput/keyparser.py", line 44, in execute
    self._commandrunner.run(cmdstr, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 300, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 501, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/completion/completionwidget.py", line 398, in completion_item_del
    self.model().delete_cur_item(index)
  File "/usr/lib/python3.6/site-packages/qutebrowser/completion/models/completionmodel.py", line 231, in delete_cur_item
    cat.delete_func(data)
  File "/usr/lib/python3.6/site-packages/qutebrowser/completion/models/urlmodel.py", line 35, in _delete_history
    hist.delete_url(urlstr)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/history.py", line 169, in delete_url
    self.delete('url', self._format_url(qurl))
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/sql.py", line 265, in delete
    raise KeyError('No row with {} = "{}"'.format(field, value))
KeyError: 'No row with url = "https://uloz.to/hledej?q=Ernell%C3%A1%C3%A9k+Farkas%C3%A9kn%C3%A1l"'
```
