### ISSUE TITLE
"Invalid cross-device link" on v0.11.0 with --temp-basedir

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3014]
This is fixed on `master` (because the migration code got removed), but on v0.11.0 I get:

```
$ python3 -m qutebrowser  --temp-basedir
22:38:44 ERROR: Failed to move old QtWebEngine data/cache: [Errno 2] No such file or directory: '/home/florian/.local/share/qutebrowser/qutebrowser/QtWebEngine/Default'
Traceback (most recent call last):
  File "/usr/lib/python3.6/shutil.py", line 544, in move
    os.rename(src, real_dst)
OSError: [Errno 18] Invalid cross-device link: '/home/florian/.local/share/qutebrowser/qutebrowser/QtWebEngine/Default' -> '/tmp/qutebrowser-basedir-whxniira/data/webengine'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/standarddir.py", line 258, in _move_webengine_data
    new_data_dir)
  File "/usr/lib/python3.6/shutil.py", line 558, in move
    copy_function(src, real_dst)
  File "/usr/lib/python3.6/shutil.py", line 257, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.6/shutil.py", line 120, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/home/florian/.local/share/qutebrowser/qutebrowser/QtWebEngine/Default'
```

**Comment by The-Compiler** [comment]
Meh, it's not like anyone cares about v0.11.0 anymore.
