### ISSUE TITLE
List type settings errors 

### ISSUE THREAD

**Issue by swalladge** [qutebrowser/qutebrowser#3104]
Noticed some strange behaviour with list settings from config.py. For example, with a temporary base directory and the following in `config.py`:

```
c.content.user_stylesheets.append('style.css')
```

I get this error:

```           
18:45:55 ERROR: Error while loading config.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 59, in early_init
    configfiles.read_config_py(config_file)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 417, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  Unhandled exception: 'NoneType' object has no attribute 'append'
```

Another example - config.py (from the configuring help page):

```
c.url.start_pages.append("https://www.python.org/")
```

error:

```
18:54:02 ERROR: Error while loading config.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 59, in early_init
    configfiles.read_config_py(config_file)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 417, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  Unhandled exception: 'str' object has no attribute 'append'
```

It seems that some settings variables aren't being initialized correctly... (default `c.content.user_stylesheets` is `None`, and `c.url.start_pages` is a `str` ('https://start.duckduckgo.com')).

Version info:

```
qutebrowser v1.0.1
Git commit: v1.0.1 (2017-10-13 09:21:56 +0200)
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.2
Qt: 5.9.1
PyQt: 5.9

sip: 4.19.3
colorama: no
pypeg2: 2.15
jinja2: 2.9.6
pygments: 2.2.0
yaml: 3.12
cssutils: 1.0.2 $Id$
attr: 17.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: 1.9.426 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.20.1
QtNetwork SSL: OpenSSL 1.0.2l  25 May 2017

Style: Qt5CTProxyStyle
Platform: Linux-4.12.13-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/samuel/qut_temp/cache
config: /home/samuel/qut_temp/config
data: /home/samuel/qut_temp/data
runtime: /home/samuel/qut_temp/runtime
system data: /usr/share/qutebrowser
```

**Comment by The-Compiler** [comment]
Thanks for the detailed report! Made it very easy to see what was going wrong 👍
