### ISSUE TITLE
Config validation exception for Dict of Key

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3105]
From https://crashes.qutebrowser.org/view/c77a6f3a

```
Traceback (most recent call last):
  File "qutebrowser\__main__.py", line 29, in <module>
  File "qutebrowser\qutebrowser.py", line 186, in main
  File "qutebrowser\app.py", line 137, in run
  File "qutebrowser\app.py", line 177, in init
  File "qutebrowser\app.py", line 210, in _process_args
  File "qutebrowser\app.py", line 245, in _load_session
  File "qutebrowser\misc\sessions.py", line 385, in load
  File "qutebrowser\mainwindow\mainwindow.py", line 204, in __init__
  File "qutebrowser\keyinput\modeman.py", line 69, in init
  File "qutebrowser\keyinput\modeparsers.py", line 51, in __init__
  File "qutebrowser\keyinput\basekeyparser.py", line 298, in _read_config
  File "qutebrowser\config\config.py", line 142, in get_bindings_for
  File "qutebrowser\config\config.py", line 448, in __getattr__
  File "qutebrowser\config\config.py", line 285, in get
  File "qutebrowser\config\configtypes.py", line 1223, in to_py
  File "qutebrowser\config\configtypes.py", line 1223, in <dictcomp>
  File "qutebrowser\config\configtypes.py", line 1223, in to_py
  File "qutebrowser\config\configtypes.py", line 1223, in <dictcomp>
  File "qutebrowser\config\configtypes.py", line 1648, in to_py
  File "qutebrowser\config\configtypes.py", line 166, in _basic_py_validation
qutebrowser.config.configexc.ValidationError: Invalid value '2' - expected a value of type str but got int.
```

Not sure yet how to reproduce, can't see the actual setting value in the log.

**Comment by The-Compiler** [comment]
Looking at the stacktrace: `Dict.to_py` -> `Dict.to_py` (for the nested bindings dict) -> `Key.to_py` (for the key in the bindings dict) -> `_basic_py_validation` -> got an int.

So this is probably something like `{normal: {a: 1}}` for `bindings.default`, but how did it get there?

**Comment by The-Compiler** [comment]
The only way I can reproduce this is to edit `configdata.yml`. I assume that's what the reporter did...
