### ISSUE TITLE
Crash on :version or :open qute:version

### ISSUE THREAD

**Issue by Justinzobel** [qutebrowser/qutebrowser#3126]
Version 1.0.1
OS: Solus

Terminal output:
```
19:46:35 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/webengine/webenginequtescheme.py", line 52, in requestStarted
    mimetype, data = qutescheme.data_for_url(url)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/qutescheme.py", line 157, in data_for_url
    mimetype, data = handler(url)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/qutescheme.py", line 117, in wrapper
    return self._function(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/qutebrowser/browser/qutescheme.py", line 261, in qute_version
    version=version.version(),
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/version.py", line 340, in version
    lines += _module_versions()
  File "/usr/lib/python3.5/site-packages/qutebrowser/utils/version.py", line 207, in _module_versions
    module = importlib.import_module(modname)
  File "/usr/lib/python3.5/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 985, in _gcd_import
  File "<frozen importlib._bootstrap>", line 968, in _find_and_load
  File "<frozen importlib._bootstrap>", line 957, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 693, in exec_module
  File "<frozen importlib._bootstrap_external>", line 799, in get_code
  File "<frozen importlib._bootstrap_external>", line 759, in source_to_code
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "/usr/lib/python3.5/site-packages/cssutils/__init__.py", line 321
    except xml.dom.HierarchyRequestErr, e:
                                      ^
SyntaxError: invalid syntax
```

**Comment by The-Compiler** [comment]
This is a SolusOS packaging bug; please report it there. They package a Python 2 version of cssutils in `/usr/lib/python3.5` - you should get the same when you do `python3 -c "import cssutils"`.

**Comment by Justinzobel** [comment]
Many thanks I've fixed it by splitting the python cssutils package into 2, it didn't like compiling and installing both like most other python packages in the repository.
