### ISSUE TITLE
Deleted C++ object: QLocalServer on :restart

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3220]
I've seen this happen once myself, and got some more reports lately, the oldest being db8fa5fdb. This was probably introduced in b906c862bb56da81304d8afdff34feb49f254c3b.

```
19:20:58 DEBUG    commands   command:run:489 command called: restart
19:20:58 DEBUG    commands   command:run:504 Calling qutebrowser.app.Quitter.restart_cmd(<qutebrowser.app.Quitter object at 0x7f6acc128128>)
19:20:58 DEBUG    destroy    app:restart:646 sys.executable: /usr/bin/python
19:20:58 DEBUG    destroy    app:restart:647 sys.path: ['/usr/bin', '/usr/lib/python36.zip', '/usr/lib/python3.6', '/usr/lib/python3.6/lib-dynload', '/usr/lib/python3.6/site-packages']
19:20:58 DEBUG    destroy    app:restart:648 sys.argv: ['/usr/bin/qutebrowser']
19:20:58 DEBUG    destroy    app:restart:649 frozen: False
19:20:58 DEBUG    sessions   sessions:save:281 Saving session _restart to /home/mokou/.local/share/qutebrowser/sessions/_restart.yml...
19:20:59 DEBUG    ipc        ipc:shutdown:402 Shutting down IPC (socket 0x7f6ad82bea80)
19:20:59 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 322, in run_safely
    self.run(text, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 301, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 505, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 616, in restart_cmd
    ok = self.restart(session='_restart')
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 658, in restart
    ipc.server.shutdown()
  File "/usr/lib/python3.6/site-packages/qutebrowser/misc/ipc.py", line 413, in shutdown
    self._server.close()
RuntimeError: wrapped C/C++ object of type QLocalServer has been deleted
```

Reports:

- https://crashes.qutebrowser.org/view/89f5bb40
- https://crashes.qutebrowser.org/view/4ba54b8d
- https://crashes.qutebrowser.org/view/67b5d034
- https://crashes.qutebrowser.org/view/93743137

**Comment by user202729** [comment]
This can trigged by a failed restart, because if `subprocess.Popen` raises `OSError` then the server is deleted, however the old process still runs, which will crash if it tries to use the server for any reason (such as trying to restart again)

Possible fixes:

* Restart the server if the restart fails.
* Exit the old process anyway, even if the new process fail to start.
