### ISSUE TITLE
Segfault in reset_setting after clicking hint

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3399]
There's a [rather big amount](https://crashes.qutebrowser.org/lists?search=reset_setting) of crash reports (~30 currently in total) segfaulting [on this line](https://github.com/qutebrowser/qutebrowser/blob/v1.0.4/qutebrowser/browser/webengine/webengineelem.py#L218-L219).

Not sure what's going on there, and I'm not sure if I ever got a C++ stacktrace of it...

**Comment by The-Compiler** [comment]
Stack without symbols:

```
#0  0x00007f48d6d90c40 raise (libpthread.so.0)
#1  0x00007f48d6d90da0 __restore_rt (libpthread.so.0)
#2  0x00007f48b541808e QtWebEngineCore::WebEngineSettings::setAttribute(QtWebEngineCore::WebEngineSettings::Attribute, bool) (libQt5WebEngineCore.so.5)
#3  0x00007f48bb4fcc34 n/a (QtWebEngineWidgets.so)
#4  0x00007f48d65ddaf0 _PyCFunction_FastCallDict (libpython3.6m.so.1.0)
#5  0x00007f48d658d08b n/a (libpython3.6m.so.1.0)
#6  0x00007f48d6572b9a _PyEval_EvalFrameDefault (libpython3.6m.so.1.0)
#7  0x00007f48d6571889 PyEval_EvalCodeEx (libpython3.6m.so.1.0)
#8  0x00007f48d661cb74 n/a (libpython3.6m.so.1.0)
#9  0x00007f48d65ccdbb PyObject_Call (libpython3.6m.so.1.0)
#10 0x00007f48ca958ede n/a (sip.so)
#11 0x00007f48ca9590e9 n/a (sip.so)
#12 0x00007f48bb4f35ce n/a (QtWebEngineWidgets.so)
#13 0x00007f48bb2c1ffa n/a (libQt5WebEngineWidgets.so.5)
#14 0x00007f48bb2bf126 n/a (libQt5WebEngineWidgets.so.5)
#15 0x00007f48bb2bf209 n/a (libQt5WebEngineWidgets.so.5)
#16 0x00007f48bb2b9795 QWebEnginePage::~QWebEnginePage() (libQt5WebEngineWidgets.so.5)
#17 0x00007f48bb4f224a n/a (QtWebEngineWidgets.so)
#18 0x00007f48ce812c6d QObjectPrivate::deleteChildren() (libQt5Core.so.5)
#19 0x00007f48c6b6e5c5 QWidget::~QWidget() (libQt5Widgets.so.5)
#20 0x00007f48bb4fd37a n/a (QtWebEngineWidgets.so)
#21 0x00007f48ce815b91 QObject::event(QEvent*) (libQt5Core.so.5)
#22 0x00007f48c6b731cc QWidget::event(QEvent*) (libQt5Widgets.so.5)
#23 0x00007f48bb4ff594 n/a (QtWebEngineWidgets.so)
#24 0x00007f48c6b32f5c QApplicationPrivate::notify_helper(QObject*, QEvent*) (libQt5Widgets.so.5)
#25 0x00007f48c6b3aa36 QApplication::notify(QObject*, QEvent*) (libQt5Widgets.so.5)
#26 0x00007f48c4d3f50f n/a (QtWidgets.so)
#27 0x00007f48ce7e5570 QCoreApplication::notifyInternal2(QObject*, QEvent*) (libQt5Core.so.5)
#28 0x00007f48ce7e7dc6 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (libQt5Core.so.5)
#29 0x00007f48ce840bf4 n/a (libQt5Core.so.5)
#30 0x00007f48cf6df270 g_main_context_dispatch (libglib-2.0.so.0)
#31 0x00007f48cf6e0f69 n/a (libglib-2.0.so.0)
#32 0x00007f48cf6e0fae g_main_context_iteration (libglib-2.0.so.0)
#33 0x00007f48ce8401e1 QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (libQt5Core.so.5)
#34 0x00007f48ce7e399b QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (libQt5Core.so.5)
```

**Comment by The-Compiler** [comment]
Reproduced with this on golem.de:

```
:hint ;; later 20 follow-hint ka ;; later 80 tab-close ;; later 200 undo
```

Stack:

```
#0  0x00007fffd625af9e in QtWebEngineCore::WebEngineSettings::setAttribute(QtWebEngineCore::WebEngineSettings::Attribute, bool) (this=0x55555c396f10, attr=QtWebEngineCore::WebEngineSettings::JavascriptCanOpenWindows, on=false)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/core/web_engine_settings.cpp:141
#1  0x00007fffdc8a4645 in meth_QWebEngineSettings_setAttribute(PyObject*, PyObject*) (sipSelf=0x7fff6484d668, sipArgs=0x7fff648419c8) at sipQtWebEngineWidgetsQWebEngineSettings.cpp:267
#2  0x00007ffff7418af0 in _PyCFunction_FastCallDict () at /usr/lib/libpython3.6m.so.1.0
#3  0x00007ffff73c808b in  () at /usr/lib/libpython3.6m.so.1.0
#4  0x00007ffff73adb9a in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.6m.so.1.0
#5  0x00007ffff73ac889 in PyEval_EvalCodeEx () at /usr/lib/libpython3.6m.so.1.0
#6  0x00007ffff7457b74 in  () at /usr/lib/libpython3.6m.so.1.0
#7  0x00007ffff7407dbb in PyObject_Call () at /usr/lib/libpython3.6m.so.1.0
#8  0x00007fffee016ede in  () at /usr/lib/python3.6/site-packages/sip.so
#9  0x00007fffee0170e9 in  () at /usr/lib/python3.6/site-packages/sip.so
#10 0x00007fffdc89945e in <lambda(const QVariant&)>::operator()(const QVariant &) const (__closure=0x5555565a5f50, arg=...) at /tmp/makepkg/pyqt5-debug/src/PyQt5_gpl-5.9.2/sip/QtWebEngineWidgets/qwebenginepage.sip:289
#11 0x00007fffdc89cdad in QtWebEnginePrivate::QWebEngineCallbackPrivate<const QVariant&, meth_QWebEnginePage_runJavaScript(PyObject*, PyObject*)::<lambda(const QVariant&)> >::operator()(const QVariant &) (this=0x5555565a5f40, value=...) at /usr/include/qt/QtWebEngineCore/qwebenginecallback.h:71
#12 0x00007fffdc61ac6a in QtWebEngineCore::CallbackDirectory::invokeEmptyInternal<QVariant const&>(QtWebEnginePrivate::QWebEngineCallbackPrivateBase<QVariant const&>*) (this=<optimized out>, callback=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/core/api/qwebenginecallback_p.h:185
#13 0x00007fffdc61ac6a in QtWebEngineCore::CallbackDirectory::CallbackSharedDataPointer<QVariant const&>::invokeEmpty() (this=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/core/api/qwebenginecallback_p.h:242
#14 0x00007fffdc617c96 in QtWebEngineCore::CallbackDirectory::~CallbackDirectory() (this=0x5555567381a8, __in_chrg=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/core/api/qwebenginecallback_p.h:87
#15 0x00007fffdc617c96 in QWebEnginePagePrivate::~QWebEnginePagePrivate() (this=0x555556738110, __in_chrg=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/webenginewidgets/api/qwebenginepage.cpp:238
#16 0x00007fffdc617d79 in QWebEnginePagePrivate::~QWebEnginePagePrivate() (this=0x555556738110, __in_chrg=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/webenginewidgets/api/qwebenginepage.cpp:242
#17 0x00007fffdc6114e5 in QScopedPointerDeleter<QWebEnginePagePrivate>::cleanup(QWebEnginePagePrivate*) (pointer=<optimized out>) at /usr/include/qt/QtCore/qscopedpointer.h:60
#18 0x00007fffdc6114e5 in QScopedPointer<QWebEnginePagePrivate, QScopedPointerDeleter<QWebEnginePagePrivate> >::~QScopedPointer() (this=0x555556765480, __in_chrg=<optimized out>) at /usr/include/qt/QtCore/qscopedpointer.h:107
#19 0x00007fffdc6114e5 in QWebEnginePage::~QWebEnginePage() (this=0x555556765470, __in_chrg=<optimized out>) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.10.0/src/webenginewidgets/api/qwebenginepage.cpp:813
#20 0x00007fffdc89652a in sipQWebEnginePage::~sipQWebEnginePage() (this=0x555556765470, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEnginePage.cpp:205
#21 0x00007fffdc896546 in sipQWebEnginePage::~sipQWebEnginePage() (this=0x555556765470, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEnginePage.cpp:208
#22 0x00007ffff23075bd in QObjectPrivate::deleteChildren() (this=this@entry=0x555556765250) at kernel/qobject.cpp:1992
#23 0x00007fffe69e1615 in QWidget::~QWidget() (this=0x5555567651d0, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1711
#24 0x00007fffdc8a4c1c in sipQWebEngineView::~sipQWebEngineView() (this=0x5555567651d0, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEngineView.cpp:329
#25 0x00007fffdc8a4c3e in sipQWebEngineView::~sipQWebEngineView() (this=0x5555567651d0, __in_chrg=<optimized out>) at sipQtWebEngineWidgetsQWebEngineView.cpp:332
#26 0x00007ffff230a4e1 in QObject::event(QEvent*) (this=this@entry=0x5555567651d0, e=e@entry=0x555556559b60) at kernel/qobject.cpp:1237
#27 0x00007fffe69e65fc in QWidget::event(QEvent*) (this=0x5555567651d0, event=0x555556559b60) at kernel/qwidget.cpp:9263
#28 0x00007fffdc8a5349 in sipQWebEngineView::event(QEvent*) (this=0x5555567651d0, a0=0x555556559b60) at sipQtWebEngineWidgetsQWebEngineView.cpp:487
#29 0x00007fffe69a5ecc in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555b351c0, receiver=receiver@entry=0x5555567651d0, e=e@entry=0x555556559b60) at kernel/qapplication.cpp:3732
#30 0x00007fffe69ad8a6 in QApplication::notify(QObject*, QEvent*) (this=0x555555fc44d0, receiver=0x5555567651d0, e=0x555556559b60) at kernel/qapplication.cpp:3491
#31 0x00007fffe59fbd2d in sipQApplication::notify(QObject*, QEvent*) (this=0x555555fc44d0, a0=0x5555567651d0, a1=0x555556559b60) at sipQtWidgetsQApplication.cpp:232
#32 0x00007ffff22d9250 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5555567651d0, event=event@entry=0x555556559b60) at kernel/qcoreapplication.cpp:1044
#33 0x00007ffff22dbeb6 in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x555556559b60, receiver=<optimized out>) at ../../include/QtCore/../../src/corelib/kernel/qcoreapplication.h:234
#34 0x00007ffff22dbeb6 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=receiver@entry=0x0, event_type=event_type@entry=0, data=0x555555948520) at kernel/qcoreapplication.cpp:1719
#35 0x00007ffff22dc44a in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=receiver@entry=0x0, event_type=event_type@entry=0) at kernel/qcoreapplication.cpp:1573
#36 0x00007ffff2336114 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x5555560742c0) at kernel/qeventdispatcher_glib.cpp:276
#37 0x00007ffff3519270 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#38 0x00007ffff351af69 in  () at /usr/lib/libglib-2.0.so.0
#39 0x00007ffff351afae in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#40 0x00007ffff2335701 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x55555606dce0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#41 0x00007fffc8021922 in QPAEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x55555606dce0, flags=...) at qeventdispatcher_glib.cpp:69
#42 0x00007ffff22d789b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffcd10, flags=..., flags@entry=...) at kernel/qeventloop.cpp:212
#43 0x00007ffff22e0b88 in QCoreApplication::exec() () at kernel/qcoreapplication.cpp:1332
```
