### ISSUE TITLE
AttributeError for prompt.prompt_queue.shutdown

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3557]
Seen this in four crash reports with v1.1.x:

```
1:42:15 DEBUG    init       app:__init__:818 Initializing application...
01:42:18 DEBUG    ipc        ipc:send_to_running_instance:435 Connecting to /run/user/1000/qutebrowser/ipc-534b44a19bf18d20b71ecc4eb77c572f
01:42:18 DEBUG    ipc        ipc:send_to_running_instance:468 No existing instance present (error 2)
01:42:18 DEBUG    init       ipc:send_or_listen:497 Starting IPC server...
01:42:18 DEBUG    ipc        ipc:__init__:193 Not calling setSocketOptions
01:42:18 DEBUG    ipc        ipc:listen:204 Listening as /run/user/1000/qutebrowser/ipc-534b44a19bf18d20b71ecc4eb77c572f
01:42:18 WARNING  qt         Unknown module:none:0 Icon theme "ubuntu-mono-dark" not found.
01:42:21 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: <PyQt5.QtWidgets.QPushButton object at 0x7fb320694f78>
01:42:21 DEBUG    misc       app:on_focus_object_changed:833 Focus object changed: None
01:42:24 DEBUG    destroy    crashsignal:handle_signal_wakeup:355 Handling signal wakeup!
01:42:24 INFO     destroy    error:handle_fatal_exc:69 SIGINT/SIGTERM received, shutting down!
01:42:24 INFO     destroy    error:handle_fatal_exc:69 Do the same again to forcefully quit.
01:42:24 DEBUG    destroy    app:shutdown:709 Shutting down with status 143, session None...
01:42:24 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/ipc.py", line 224, in listen
    os.chmod(self._server.fullServerName(), 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/qutebrowser/ipc-534b44a19bf18d20b71ecc4eb77c572f'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/ipc.py", line 499, in send_or_listen
    server.listen()
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/ipc.py", line 229, in listen
    raise ListenError(self._server)
qutebrowser.misc.ipc.ListenError: Error while listening to IPC server:  (error -1)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/app.py", line 719, in shutdown
    if prompt.prompt_queue.shutdown():
AttributeError: 'NoneType' object has no attribute 'shutdown'
01:42:24 ERROR    destroy    crashsignal:_get_exception_info:192 Error while getting history: 'command-history'
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/ipc.py", line 224, in listen
    os.chmod(self._server.fullServerName(), 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/qutebrowser/ipc-534b44a19bf18d20b71ecc4eb77c572f'
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/ipc.py", line 499, in send_or_listen
    server.listen()
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/ipc.py", line 229, in listen
    raise ListenError(self._server)
qutebrowser.misc.ipc.ListenError: Error while listening to IPC server:  (error -1)
 
During handling of the above exception, another exception occurred:
 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qutebrowser/misc/crashsignal.py", line 190, in _get_exception_info
    cmd_history = objreg.get('command-history')[-5:]
  File "/usr/lib/python3/dist-packages/qutebrowser/utils/objreg.py", line 229, in get
    return reg[name]
  File "/usr/lib/python3.6/collections/__init__.py", line 991, in __getitem__
    raise KeyError(key)
KeyError: 'command-history'
```

One report said "Opening the browser, it did not visually open but was running in the process list." and it seems to happen after getting killed (SIGTERM) when it hangs after init?

Reports:

- https://crashes.qutebrowser.org/view/5a0299a4
- https://crashes.qutebrowser.org/view/14a57dcd
- https://crashes.qutebrowser.org/view/ffe6173b
- https://crashes.qutebrowser.org/view/9327e645

**Comment by The-Compiler** [comment]
I can reproduce this on 1d43c15db37c70f487315bd60569d37ee3051424 when pressing ctrl-c in the console while a `config.py` error window is shown.
