### ISSUE TITLE
Uncaught configexc.ValidationError with invalid value for url.searchengines

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3580]
With `c.url.searchengines['maps'] = 'https://www.google.com/maps?q=%s'` in `config.py`, `:config-source` crashes and qutebrowser doesn't start anymore:

```
10:30:52 DEBUG    config     config:update_mutables:390 url.searchengines was mutated, updating
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 188, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 100, in run
    configinit.early_init(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configinit.py", line 59, in early_init
    configfiles.read_config_py(config_file)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configfiles.py", line 429, in read_config_py
    api.finalize()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configfiles.py", line 243, in finalize
    self._config.update_mutables()
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 391, in update_mutables
    self.set_obj(name, new_value, save_yaml=save_yaml)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 335, in set_obj
    self._set_value(self.get_opt(name), value)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 269, in _set_value
    opt.typ.to_py(value)  # for validation
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1223, in to_py
    for key, val in value.items()}
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1223, in <dictcomp>
    for key, val in value.items()}
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1405, in to_py
    raise configexc.ValidationError(value, "must contain \"{}\"")
qutebrowser.config.configexc.ValidationError: Invalid value 'https://www.google.com/maps?q=%s' - must contain "{}"
```

**Comment by The-Compiler** [comment]
Something similar happens when having a binding with a newline in it:

```
Traceback (most recent call last):
  File "/home/viktor/git/qutebrowser/qutebrowser/commands/runners.py", line 325, in run_safely
    self.run(text, count)
  File "/home/viktor/git/qutebrowser/qutebrowser/commands/runners.py", line 304, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/viktor/git/qutebrowser/qutebrowser/commands/command.py", line 507, in run
    self.handler(*posargs, **kwargs)
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configcommands.py", line 384, in config_source
    configfiles.read_config_py(filename)
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configfiles.py", line 586, in read_config_py
    api.finalize()
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configfiles.py", line 377, in finalize
    self._config.update_mutables()
  File "/home/viktor/git/qutebrowser/qutebrowser/config/config.py", line 455, in update_mutables
    self.set_obj(name, new_value, save_yaml=save_yaml)
  File "/home/viktor/git/qutebrowser/qutebrowser/config/config.py", line 399, in set_obj
    self._set_value(opt, value, pattern=pattern)
  File "/home/viktor/git/qutebrowser/qutebrowser/config/config.py", line 283, in _set_value
    opt.typ.to_py(value)  # for validation
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 1291, in to_py
    for key, val in value.items()}
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 1291, in <dictcomp>
    for key, val in value.items()}
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 1291, in to_py
    for key, val in value.items()}
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 1291, in <dictcomp>
    for key, val in value.items()}
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 888, in to_py
    self._basic_py_validation(value, str)
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 173, in _basic_py_validation
    self._basic_str_validation(value)
  File "/home/viktor/git/qutebrowser/qutebrowser/config/configtypes.py", line 189, in _basic_str_validation
    value, "may not contain unprintable chars!")
qutebrowser.config.configexc.ValidationError: Invalid value 'jseval --quiet function elementInViewport2(el) { var top = el.offsetTop; var left = el.offsetLeft; var width = el.offsetWidth; var height = el.offsetHeight; while(el.offsetParent) { el = el.offsetParent; top += el.offsetTop; left += el.offsetLeft; } return ( top < (window.pageYOffset + window.innerHeight) && left < (window.pageXOffset + window.innerWidth) && (top + height) > window.pageYOffset && (left + width) > window.pageXOffset); } var pres = document.getElementsByTagName('pre'); var focusedAny=false; for(var i=0; i<pres.length; i++) { if( pres[i].focused ){ focusedAny =true; var focusedPrev =i; } } var focusedNext = 0; if (focusedAny){ focusedNext = focusedPrev+1; if (focusedNext >= (pres.length-1)){ focusedNext=0; } } else{ var focusedPrev = pres.length-1; focusedNext = 0; } var foundAnyVisible=false; for(var j=0; j<pres.length; j++){ if (focusedNext==focusedPrev){ break; } if (elementInViewport2(pres[focusedNext])){ foundAnyVisible =true; break; } focusedNext=focusedNext+1; if (focusedNext >= (pres.length-1)){ focusedNext=0; } } if (foundAnyVisible){ pres[focusedPrev].focused=false; pres[focusedPrev].style="border:1px solid White;"; pres[focusedPrev].id=""; pres[focusedNext].focused=true; pres[focusedNext].id="clickhere"; pres[focusedNext].style="border:2px solid Tomato;"; } 
;; click-element id clickhere' - may not contain unprintable chars!
```
