### ISSUE TITLE
Look into Qt for Python / PySide2

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3625]
The [Qt roadmap 2018](http://blog.qt.io/blog/2018/02/22/qt-roadmap-2018/) says:

> A big new thing we aim to release during 2018 is Qt for Python, i.e. bindings to Python programming language. Initially started as PySide, the work has continued for quite some time already. After a lot of work, we are reaching the point of being able to offer a technology preview to be used on top of Qt 5.11.

Maybe we should look into whether we want to support it (as alternative to PyQt) if it's easy to do so. There are plans to decouple QtWebEngine from Qt:

> For Qt 5.12 LTS we are looking into possibilities for decoupling Qt WebEngine from Qt release schedules to allow more frequent updates of Qt WebEngine. This is still under research, but there seem to be quite tangible benefits from carving out Qt WebEngine to a separate item. Current thinking it that as a separate item we should be able to release Qt WebEngine every three months, following nicely the schedule of Chromium releases every six weeks. For Qt 5.12 LTS users this would mean the possibility to get not only the security updates, but a full new Chromium version supported on top of the long-term-supported release of Qt.

So I'm not sure what'll happen to QtWebEngine support in PyQt...

**Comment by gebulmer** [comment]
It'll probably be a long time before it's in a reasonable state, and possibly even longer before there's any compelling reason to switch I'd imagine. I guess we'll just have to wait and see

**Comment by The-Compiler** [comment]
It's been in development [since May 2015](http://lists.qt-project.org/pipermail/pyside/2015-July/002313.html) and was developed by the Qt company [since April 2016](http://lists.qt-project.org/pipermail/pyside/2016-April/002401.html) so I'd hope some 3 years later it'll finally be usable enough - but we'll see :wink:

I wouldn't want to switch, but with a `qutebrowser.qt` module which simply redirects to either PyQt5 or PySide2 (or just a `s/PyQt5/PySide2/g` for a first try) I don't think it'd be too much effort to at least try it out. I'm kind of scared of PyQt5 dropping QtWebEngine support once it's separate from Qt... I'd hope they continue to support it, but you never know.

**Comment by The-Compiler** [comment]
First official preview should be released after 5.11: http://blog.qt.io/blog/2018/04/13/qt-for-python-is-coming-to-a-computer-near-you/

**Comment by The-Compiler** [comment]
I've tried this in https://github.com/qutebrowser/experiments/compare/pyside but as long as some QtWebEngine functionality [isn't supported](https://wiki.qt.io/Qt_for_Python_Missing_Bindings#QtWebEngineWidgets) (such as... settings) I'm not going to look into this any further.

**Comment by The-Compiler** [comment]
Looks like https://wiki.qt.io/Qt_for_Python_Missing_Bindings#QtWebEngineWidgets was updated - `QWebEngineHistory` is still missing, but the rest looks a bit better.

**Comment by UnicodeAlt255** [comment]
How about QtPy? In my experience PySide2 is not as stable as PyQt5, but it is the one that's officially supported so perhaps in the future it would be good to support both at the same time?

**Comment by The-Compiler** [comment]
Yup, I don't plan to drop PyQt5 support. If that's done via our own wrapper (which we'd need with Qt 6 anyways at some point when keeping Qt5 support) or QtPy or something else remains to be seen, the first step would be to get it running at all.

**Comment by The-Compiler** [comment]
https://bugreports.qt.io/browse/PYSIDE-239 has been fixed, so it'd probably be possible to try this again. However, given that PyQt5 works quite well in general, this probably isn't worth the effort right now.

**Comment by The-Compiler** [comment]
FWIW #995 (which will probably be needed for PyQt6) will also make it much easier to try PySide2 (or whatever the Qt 6 equivalent is) at that point.

**Comment by The-Compiler** [comment]
Given that I'm working on proper (switchable) Qt 6 support, I decided to give this another try. Unfortunately, PySide6 (and even more PySide2) still is way behind PyQt in various subtle ways... Here is what I found so far:

- `exec` -> `exec_` again
- `QDesktopServices.setUrlHandler` doesn't just take a Python function reference, so I suppose we would need to pass a class and a name as a string or something? If it works at all...
- `QVariant` and `QMetaType` don't seem to be available at all, which is mostly relevant for DBus notifications
- Qt DBus isn't available for PySide2 at all
- `Qt.KeyboardModifiers`, `QKeySequence` and I suppose a lot more isn't hashable from Python, despite being hashable in Qt
- Connecting a `functools.partial` to a slot messes up its signature somehow (I think PySide tries to call the slot with the signature of the underlying function or something?). Thus, we would need to use lambdas instead for `self.status.backforward.on_tab_cur_url_changed` and `self._on_load_status_changed` in `mainwindow.py` and `tabbedbrowser.py`
- `TabBarStyle` doesn't work properly at all, apparently the style option object is just missing all attributes?
- No way to get `debug.signal_name` to work from what I can see
- `setCookieFilter` for QtWebEngine is missing
- `setNotificationPresenter` as well
- An empty `QByteArray` seems to be truthy
- `QFileSystemModel` is still in `QtWidgets` for PySide6 despite being moved to `QtGui` in Qt 6
- Different return value signature for `QVersionNumber.fromString` (just dropping the suffix apparently?)
- No equivalent to `sip.assign` seems to exist, making it impossible to abort an authentication attempt
- `qurl.toDisplayString(QUrl.UrlFormattingOption.RemoveScheme)` fails with a `TypeError` despite being valid in C++ and PyQt
- Same apparently for a similar `QUrl::matches` call with `QUrl.UrlFormattingOption(0)`
- probably more, giving up at this point, as this is getting way too hacky to do it before we get PyQt6 support.... Posted what I have so far to `qt6-v2-pyside` in the `experiments` repository.

**Comment by cmaureir** [comment]
(my very personal take on this attempt)
Efforts on PySide2 in 2022 made little sense, mainly because the development stopped a very long time ago.
Most of the new bug-fix releases are commercial only due to the LTS changes, so I'd not encourage any project to be PySide2-compatible. The jump needs to be towards PySide6 and I guess  as long as you are supporting Qt5, don't bother to do a comparison or attempt with PySide2, because many things were not fixed in favor of PySide6, mainly to avoid breaking people's code, to not add new features/modules in bug-fix releases, and not leaving OSS users behind by adding features in 5.15.4+.

A few comments in case in a couple of years you drop support for 5.15 (PySide2/PyQt5):

> * `exec` -> `exec_` again

`exec()` was adopted in 6.1, and PySide2 never moved away from `exec_()` mainly for not breaking people's code. Not sure how that's "being behind"
https://www.qt.io/blog/qt-for-python-6.1
 
> * `QDesktopServices.setUrlHandler` doesn't just take a Python function reference, so I suppose we would need to pass a class and a name as a string or something? If it works at all...

QDesktopServices hasn't been touched for a really long time, so the behavior you are encountering has always been like that probably since the beginning, so it might be worth file a bug report in case something is not working as expected.

> * `QVariant` and `QMetaType` don't seem to be available at all, which is mostly relevant for DBus notifications

`QVariant` doesn't make sense in Python, hopefully it will never been exposed to end-users.
`QMetaType` was included in 6.0 IIRC mainly to enable functionality of `QSqlField`

> * Qt DBus isn't available for PySide2 at all

It was added in PySide 6.2
https://www.qt.io/blog/qt-for-python-release-6.2

> * `Qt.KeyboardModifiers`, `QKeySequence` and I suppose a lot more isn't hashable from Python, despite being hashable in Qt

With shiboken we do have a special `hash-function` parameter to make some types hashable, like QSize, QTime, QUrl, etc... if you think those types should be as well, I think we could enable it :O

> * Connecting a `functools.partial` to a slot messes up its signature somehow (I think PySide tries to call the slot with the signature of the underlying function or something?). Thus, we would need to use lambdas instead for `self.status.backforward.on_tab_cur_url_changed` and `self._on_load_status_changed` in `mainwindow.py` and `tabbedbrowser.py`

we have an example in pyside6 using `functools.partial` on a signal connection. It might be an issue with PySide2
https://code.qt.io/cgit/pyside/pyside-setup.git/tree/examples/networkauth/redditclient/redditmodel.py#n106

> * `TabBarStyle` doesn't work properly at all, apparently the style option object is just missing all attributes?

Not sure about this type, from which module?
 
> * No way to get `debug.signal_name` to work from what I can see

I think this might be a bug. Most of the debugging we do is from gdb and for the underlying C++ wrapper code. Rarely we debug from Python.

> * `setCookieFilter` for QtWebEngine is missing

most of the methods that contain a std::function as argument need some special code to be injected into the wrapper, we do have some cases already, so I think the bug report will be a good start to look into this method (and other similar)

> * `setNotificationPresenter` as well

same as the previous statement, and here there is also a std::unique_ptr :S which might make things harder.
 
> * An empty `QByteArray` seems to be truthy

yeah, here at least I don't know what's the proper 'fix' at a Python level, because we kind of follow the Qt-methods to check the content of some types. Using `isEmpty()` and `isNull()` is what we have been encouraging.
Ideas are welcomed :)
 
> * `QFileSystemModel` is still in `QtWidgets` for PySide6 despite being moved to `QtGui` in Qt 6

We noticed many missing classes, and they were added for 6.2, with a pick-to: 6.1.
There is a note of moving it on PySide7 to avoid breaking existing code using it.
https://codereview.qt-project.org/c/pyside/pyside-setup/+/352218

> * Different return value signature for `QVersionNumber.fromString` (just dropping the suffix apparently?)

This hasn't been touched since 2017, so if something broke in pyside2->pyside6 might be a bug.

> * No equivalent to `sip.assign` seems to exist, making it impossible to abort an authentication attempt

Not sure if one could get the C++ pointer, and try to assign it. But it looks like a good feature request :dancers: 

> * `qurl.toDisplayString(QUrl.UrlFormattingOption.RemoveScheme)` fails with a `TypeError` despite being valid in C++ and PyQt

this sounds like a bug, the wrapper is checking for `QFlags<QUrl::ComponentFormattingOption>` but it might be related to how we threat the flags internally.

> * Same apparently for a similar `QUrl::matches` call with `QUrl.UrlFormattingOption(0)`

Might be related as well.

> * probably more, giving up at this point, as this is getting way too hacky to do it before we get PyQt6 support.... Posted what I have so far to `qt6-v2-pyside` in the `experiments` repository.

Sounds like a good strategy. Will be happy to jump into any discussion in the future if you consider PySide6 :tada:
thanks for the write up, and hopefully you can file  a couple of bugs.

**Comment by The-Compiler** [comment]
As a note to myself, I opened a couple of bug reports upstream:

- [[PYSIDE-1904] Missing QVariant/QMetaType API to specify type of QDBusArgument](https://bugreports.qt.io/browse/PYSIDE-1904)
- [[PYSIDE-1905] QDBusAbstractInterface::call only accepts 6 arguments](https://bugreports.qt.io/browse/PYSIDE-1905)
- [[PYSIDE-1906] All qHash functions should be exposed to Python](https://bugreports.qt.io/browse/PYSIDE-1906)
- [[PYSIDE-1907] Flag types are unhashable](https://bugreports.qt.io/browse/PYSIDE-1907)
- [[PYSIDE-1908] Signal connections to functools.partial use wrong signature](https://bugreports.qt.io/browse/PYSIDE-1908)
- [[PYSIDE-1909] Unable to use QStyleOption due to missing casts](https://bugreports.qt.io/browse/PYSIDE-1909)
- [[PYSIDE-1910] shiboken6.wrapInstance raises NameError about upper-case Shiboken](https://bugreports.qt.io/browse/PYSIDE-1910)
- [[PYSIDE-1911] Provide a way to get the name of a Signal(Instance)](https://bugreports.qt.io/browse/PYSIDE-1911)
- [[PYSIDE-1912] QtWebEngine: Missing setCookieFilter and setNotificationPresenter](https://bugreports.qt.io/browse/PYSIDE-1912)
- [[PYSIDE-1913] QByteArray bool() result is wrong for empty string](https://bugreports.qt.io/browse/PYSIDE-1913)
- [[PYSIDE-1914] QFileSystemModel still is in QtWidgets instead of QtGui](https://bugreports.qt.io/browse/PYSIDE-1914)
- [[PYSIDE-1915] suffixIndex gets dropped for QVersionNumber - Qt Bug Tracker](https://bugreports.qt.io/browse/PYSIDE-1915)
- [[PYSIDE-1916] Add a way to assign something to a pointer](https://bugreports.qt.io/browse/PYSIDE-1916)
- [[PYSIDE-1917] Weird repr output if repr contains dots](https://bugreports.qt.io/browse/PYSIDE-1917) -> [[QTBUG-103085] QVersionNumber doesn't indicate its type in QDebug output](https://bugreports.qt.io/browse/QTBUG-103085)
- [[PYSIDE-1918] QUrl.toString() doesn't take QUrl.UrlFormattingOption](https://bugreports.qt.io/browse/PYSIDE-1918)

Next up, I seem to be getting a segfault:

```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff1ff310d in QStyleSheetStyle::sizeFromContents (this=0x555556ed8380, ct=QStyle::CT_ItemViewItem, opt=0x555556a88c10, csz=..., w=0x7fffffff9f70) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/styles/qstylesheetstyle.cpp:5484
Downloading 0.25 MB source file /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/styles/qstylesheetstyle.cpp
5484	       sz = baseStyle()->sizeFromContents(ct, opt, csz, w);                 
```

unfortunately, neither Python's faulthandler nor gdb (despite supposedly downloading debug symbols) tells me more about where it gets called from exactly:

```
#0  0x00007ffff1ff310d in QStyleSheetStyle::sizeFromContents(QStyle::ContentsType, QStyleOption const*, QSize const&, QWidget const*) const (this=0x555556ed8380, ct=QStyle::CT_ItemViewItem, opt=0x555556a88c10, csz=..., w=0x7fffffff9f70) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/styles/qstylesheetstyle.cpp:5484
#1  0x00007ffff26e7cde in  () at /usr/lib/python3.10/site-packages/PySide6/QtWidgets.cpython-310-x86_64-linux-gnu.so
#2  0x00007ffff7d11462 in  () at /usr/lib/libpython3.10.so.1.0
#3  0x00007ffff7d0addb in _PyObject_MakeTpCall () at /usr/lib/libpython3.10.so.1.0
#4  0x00007ffff7d061c5 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.10.so.1.0
#5  0x00007ffff7cff752 in  () at /usr/lib/libpython3.10.so.1.0
#6  0x00007ffff7d1cf35 in  () at /usr/lib/libpython3.10.so.1.0
#7  0x00007ffff2a43a3b in  () at /usr/lib/python3.10/site-packages/PySide6/QtWidgets.cpython-310-x86_64-linux-gnu.so
#8  0x00007ffff225d6b4 in QTreeView::indexRowSizeHint(QModelIndex const&) const (this=this@entry=0x555556ec9b10, index=...) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qtreeview.cpp:3029
#9  0x00007ffff225e1ad in QTreeViewPrivate::layout(int, bool, bool) (this=0x555556f54870, i=<optimized out>, recursiveExpanding=false, afterIsUninitialized=false) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qtreeview.cpp:3376
#10 0x00007ffff2257e12 in QTreeView::doItemsLayout() (this=0x555556ec9b10) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qtreeview.cpp:2139
#11 0x00007ffff2265771 in QAbstractItemViewPrivate::executePostedLayout() const (this=0x555556f54870) at /usr/src/debug/build/include/QtWidgets/6.3.0/QtWidgets/private/../../../../../../qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qabstractitemview_p.h:94
#12 QAbstractItemViewPrivate::executePostedLayout() const (this=0x555556f54870) at /usr/src/debug/build/include/QtWidgets/6.3.0/QtWidgets/private/../../../../../../qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qabstractitemview_p.h:229
#13 QTreeViewPrivate::updateScrollBars() (this=0x555556f54870) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qtreeview.cpp:3732
#14 0x00007ffff225d29b in QTreeView::updateGeometries() (this=0x555556ec9b10) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/itemviews/qtreeview.cpp:2866
#15 0x00007ffff266139d in  () at /usr/lib/python3.10/site-packages/PySide6/QtWidgets.cpython-310-x86_64-linux-gnu.so
#16 0x00007ffff7d10eb7 in  () at /usr/lib/libpython3.10.so.1.0
#17 0x00007ffff7d0595b in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.10.so.1.0
#18 0x00007ffff7cff752 in  () at /usr/lib/libpython3.10.so.1.0
#19 0x00007ffff7d1cf35 in  () at /usr/lib/libpython3.10.so.1.0
#20 0x00007ffff2b11e1e in  () at /usr/lib/python3.10/site-packages/PySide6/QtWidgets.cpython-310-x86_64-linux-gnu.so
#21 0x00007ffff1f953c0 in QWidget::event(QEvent*) (this=0x555556ec9b10, event=0x7fffffffadd0) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:8983
#22 0x00007ffff201f7e7 in QFrame::event(QEvent*) (this=0x555556ec9b10, e=0x7fffffffadd0) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/widgets/qframe.cpp:550
#23 0x00007ffff5751470 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (event=<optimized out>, receiver=<optimized out>) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qcoreapplication.cpp:1200
#24 QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) (receiver=receiver@entry=0x5555568317c0, event=event@entry=0x7fffffffadd0) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qcoreapplication.cpp:1189
#25 0x00007ffff1f50b4c in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x5555568317c0, e=0x7fffffffadd0) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qapplication.cpp:3331
#26 0x00007ffff575243a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5555568317c0, event=0x7fffffffadd0) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qcoreapplication.cpp:1068
#27 0x00007ffff1f88a48 in QWidgetPrivate::sendPendingMoveAndResizeEvents(bool, bool) (this=this@entry=0x555556e61da0, recursive=recursive@entry=false, disableUpdates=<optimized out>, disableUpdates@entry=false) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:7867
#28 0x00007ffff1f8b3e8 in QWidgetPrivate::show_helper() (this=this@entry=0x555556e61da0) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:7918
#29 0x00007ffff1f8cdb5 in QWidgetPrivate::setVisible(bool) (this=0x555556e61da0, visible=<optimized out>) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:8267
#30 0x00007ffff1f91349 in QWidgetPrivate::showChildren(bool) (this=<optimized out>, spontaneous=false) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:8339
#31 0x00007ffff1f8b406 in QWidgetPrivate::show_helper() (this=this@entry=0x555556f54870) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:7924
#32 0x00007ffff1f8cdb5 in QWidgetPrivate::setVisible(bool) (this=0x555556f54870, visible=<optimized out>) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qwidget.cpp:8267
#33 0x00007ffff2b14c8a in  () at /usr/lib/python3.10/site-packages/PySide6/QtWidgets.cpython-310-x86_64-linux-gnu.so
#34 0x00007ffff2b64f51 in  () at /usr/lib/python3.10/site-packages/PySide6/QtWidgets.cpython-310-x86_64-linux-gnu.so
#35 0x00007ffff7d0f309 in  () at /usr/lib/libpython3.10.so.1.0
#36 0x00007ffff7d0595b in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.10.so.1.0
#37 0x00007ffff7d1ce04 in  () at /usr/lib/libpython3.10.so.1.0
#38 0x00007ffff7d0595b in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.10.so.1.0
#39 0x00007ffff7d1ce04 in  () at /usr/lib/libpython3.10.so.1.0
#40 0x00007ffff7d0595b in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.10.so.1.0
#41 0x00007ffff7d1d00d in  () at /usr/lib/libpython3.10.so.1.0
#42 0x00007ffff5bb939f in PySide::SignalManager::callPythonMetaMethod(QMetaMethod const&, void**, _object*, bool) () at /usr/lib/libpyside6.cpython-310-x86_64-linux-gnu.so.6.3
#43 0x00007ffff5bbc172 in PySide::SignalManager::SignalManagerPrivate::qtMethodMetacall(QObject*, int, void**) () at /usr/lib/libpyside6.cpython-310-x86_64-linux-gnu.so.6.3
#44 0x00007ffff57a5f97 in doActivate<false>(QObject*, int, void**) (sender=0x555556ed1dc0, signal_index=3, argv=0x7fffffffb910) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qobject.cpp:3945
#45 0x00007ffff57af7ef in QTimer::timeout(QTimer::QPrivateSignal) (this=<optimized out>, _t1=...) at /usr/src/debug/build/src/corelib/Core_autogen/include/moc_qtimer.cpp:210
#46 0x00007ffff5f304e1 in  () at /usr/lib/python3.10/site-packages/PySide6/QtCore.cpython-310-x86_64-linux-gnu.so
#47 0x00007ffff57986e6 in QObject::event(QEvent*) (this=0x555556ed1dc0, e=0x7fffffffbb30) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qobject.cpp:1333
#48 0x00007ffff5f2b121 in  () at /usr/lib/python3.10/site-packages/PySide6/QtCore.cpython-310-x86_64-linux-gnu.so
#49 0x00007ffff1f50b5d in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=<optimized out>, receiver=0x555556ed1dc0, e=0x7fffffffbb30) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/widgets/kernel/qapplication.cpp:3337
#50 0x00007ffff575243a in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555556ed1dc0, event=0x7fffffffbb30) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qcoreapplication.cpp:1068
#51 0x00007ffff58a239d in QTimerInfoList::activateTimers() (this=0x55555636ed20) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qtimerinfo_unix.cpp:646
#52 0x00007ffff596d6fa in timerSourceDispatch(GSource*, GSourceFunc, gpointer) (source=<optimized out>) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qeventdispatcher_glib.cpp:185
#53 0x00007ffff699e163 in g_main_dispatch (context=0x7fffc4005080) at ../glib/glib/gmain.c:3417
#54 g_main_context_dispatch (context=0x7fffc4005080) at ../glib/glib/gmain.c:4135
#55 0x00007ffff69f49e9 in g_main_context_iterate.constprop.0 (context=context@entry=0x7fffc4005080, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4211
#56 0x00007ffff699b6c5 in g_main_context_iteration (context=0x7fffc4005080, may_block=1) at ../glib/glib/gmain.c:4276
#57 0x00007ffff596b8d0 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555556366660, flags=...) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/kernel/qeventdispatcher_glib.cpp:429
#58 0x00007ffff575a94b in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffffffbde0, flags=...) at /usr/src/debug/qtbase-everywhere-src-6.3.0/src/corelib/global/qflags.h:70
[...]
```
