### ISSUE TITLE
Crash with invalid dictionary filenames

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3634]
Looks like this doesn't get caught properly on init:

```
16:39:44 DEBUG    init       app:_init_modules:468 Initializing websettings...
16:39:45 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==1.1.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 188, in main
    return app.run(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 137, in run
    init(args, crash_handler)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 163, in init
    _init_modules(args, crash_handler)
  File "/usr/lib/python3.6/site-packages/qutebrowser/app.py", line 469, in _init_modules
    websettings.init(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/websettings.py", line 215, in init
    webenginesettings.init(args)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 297, in init
    websettings.init_mappings(MAPPINGS)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/websettings.py", line 198, in init_mappings
    mapping.set(value)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/websettings.py", line 72, in set
    self._set(value, settings=settings)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 154, in _set
    filenames = [self._find_installed(code) for code in value]
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 154, in <listcomp>
    filenames = [self._find_installed(code) for code in value]
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 143, in _find_installed
    local_filename = spell.local_filename(code)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 64, in local_filename
    all_installed = local_files(code)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 51, in local_files
    for matching_dict in sorted(matching_dicts, key=version, reverse=True):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/spell.py", line 36, in version
    .format(filename))
ValueError: the given dictionary file name is malformed: /usr/share/qt/qtwebengine_dictionaries/en-US.bdic
```

https://crashes.qutebrowser.org/view/63cd0d83

cc @elshize

**Comment by elshize** [comment]
I'll look into this after I return from my vacation ;)

**Comment by The-Compiler** [comment]
Sure - enjoy the vacation! :+1:

**Comment by elshize** [comment]
When exactly do you get this error? I can't reproduce it. What are the spell settings that are set?

**Comment by elshize** [comment]
Okay, got it. I'll make sure to catch that. But should we still treat dictionaries without a version as invalid? (If not, then there's a problem of selecting the latest one if one has and one does not have a version.)

**Comment by The-Compiler** [comment]
I do think they should be treated as invalid, but qutebrowser should show some error instead of crashing.
