### ISSUE TITLE
Numbers are reserved for counts!

### ISSUE THREAD

**Issue by yellowhat** [qutebrowser/qutebrowser#3684]
Hi,
I am using the live version of qutebrowser on Arch.
Unfortunately now it returns this error on opening:
```
Traceback (most recent call last):                                                                                                                                                                                                 
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 59, in early_init                                                                                                                                 
    configfiles.read_config_py(config_file)                                                                                                                                                                                        
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 560, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  While setting 'bindings.commands': Invalid value '<1>' - Numbers are reserved for counts!
```
I have the following `config.py` file:
```
c.bindings.commands = {'normal' : {'<1>' : 'tab-prev', '<2>' : 'tab-next'}, }
```

I found very useful to be able to change tab using the key "1" and "2". is there an option to override this error?

Thanks

```
qutebrowser v1.1.2
Git commit: 34815f5cf (2018-03-07 18:30:44 +0100)
Backend: QtWebEngine (Chromium 61.0.3163.140)

CPython: 3.6.4
Qt: 5.10.1
PyQt: 5.10.1

sip: 4.19.8
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.0g  2 Nov 2017

Style: Breeze::Style
Platform: Linux-4.15.7-1-ARCH-x86_64-with-arch-Arch-Linux, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt
```

**Comment by The-Compiler** [comment]
Huh, I wasn't aware this was actually possible! :laughing: So you never use those numbers to enter a count? I'll look into making this possible again.

**Comment by yellowhat** [comment]
I will go in insert mode and write a number, but I really like to simply change tab with 1 and 2 keys.

Thanks

**Comment by The-Compiler** [comment]
You can type a number before a keybinding to change the "amount" (or sometimes tab/etc.) it uses, i.e. `5j` to scroll more, or `2gt` to move a tab two positions to the left. See `/count` on `qute://help/commands.html`. I suppose you were unaware of that feature then? :smile:

**Comment by yellowhat** [comment]
I was not aware of this feature. But I prefer to change tab instead.

Thanks
