### ISSUE TITLE
Can't bind Alt-Less

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3736]
On v1.2.1, `:bind <Alt+Less> scroll-to-perc 0` leads to:

```
22:49:25 DEBUG    commands   command:run:486 command called: bind ['<Alt+Less>', 'scroll-to-perc 0']
22:49:25 DEBUG    commands   command:run:501 Calling qutebrowser.config.configcommands.ConfigCommands.bind(<qutebrowser.config.configcommands.ConfigCommands object at 0x7fe66ed1b828>, 0, '<Alt+Less>', 'scroll-to-perc 0', mode='normal', default=False)
22:49:25 DEBUG    config     config:update_mutables:448 bindings.commands was mutated, updating
22:49:25 DEBUG    message    message:_log_stack:46 Stack for error (from exception) message:
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1663, in to_py
    return keyutils.KeySequence.parse(value)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyutils.py", line 557, in parse
    new._validate(keystr)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/keyutils.py", line 432, in _validate
    raise KeyParseError(keystr, "Got invalid key!")
qutebrowser.keyinput.keyutils.KeyParseError: Could not parse '<Alt+<>': Got invalid key!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configcommands.py", line 47, in _handle_config_error
    yield
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configcommands.py", line 175, in bind
    self._keyconfig.bind(seq, command, mode=mode, save_yaml=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 195, in bind
    self._config.update_mutables(save_yaml=save_yaml)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 449, in update_mutables
    self.set_obj(name, new_value, save_yaml=save_yaml)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 393, in set_obj
    self._set_value(opt, value, pattern=pattern)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/config.py", line 281, in _set_value
    opt.typ.to_py(value)  # for validation
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1226, in to_py
    for key, val in value.items()}
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1226, in <dictcomp>
    for key, val in value.items()}
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1226, in to_py
    for key, val in value.items()}
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1226, in <dictcomp>
    for key, val in value.items()}
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1665, in to_py
    raise configexc.ValidationError(value, str(e))
qutebrowser.config.configexc.ValidationError: Invalid value '<Alt+<>' - Could not parse '<Alt+<>': Got invalid key!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 325, in run_safely
    self.run(text, count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 304, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 502, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configcommands.py", line 175, in bind
    self._keyconfig.bind(seq, command, mode=mode, save_yaml=True)
  File "/usr/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configcommands.py", line 49, in _handle_config_error
    raise cmdexc.CommandError(str(e))
qutebrowser.commands.cmdexc.CommandError: Invalid value '<Alt+<>' - Could not parse '<Alt+<>': Got invalid key!
22:49:25 ERROR    message    message:error:63 Invalid value '<Alt+<>' - Could not parse '<Alt+<>': Got invalid key!
```

**Comment by The-Compiler** [comment]
I think this is happening because of the normalization added in 994181212734cacdfa6e4d7cb35402881282bf4f for #3699 - it gets normalized to `<Alt+<>` which then can't be bound. Probably suffices if `_key_to_string` handles `Qt.Key_Greater` and `Qt.Key_Less`.

**Comment by toofar** [comment]
I'm not familiar with that part of the codebase but there is [a test](https://github.com/qutebrowser/qutebrowser/blob/master/tests/unit/keyinput/test_keyutils.py#L193) that has some expected output.

**Comment by The-Compiler** [comment]
From #5965:

> * `<<<`: still, a single `<` moves the tab left
> * `<<><<>`: crashes qutebrowser because the key sequence cannot be parsed

**Comment by The-Compiler** [comment]
In a similar vein, `<Less><Less>` also gets translated to a single (rather than double) `<`.

**Comment by genomorro** [comment]
Hi. I just installed QB 2.0.2 with an Emacs-like config. I've tried keybindings such as:
```
config.bind('<Alt-<>','scroll-to-perc 0')
config.bind('<Alt->>','scroll-to-perc')
```
It doesn't work. I also tried:
```
config.bind('<Alt-Less>','scroll-to-perc 0')
config.bind('<Alt-Greater>','scroll-to-perc')
```
With those bindings QB just stop working:
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1972, in to_py
    return keyutils.KeySequence.parse(value)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/keyutils.py", line 655, in parse
    new._validate(keystr)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/keyutils.py", line 537, in _validate
    raise KeyParseError(keystr, "Got invalid key!")
qutebrowser.keyinput.keyutils.KeyParseError: Could not parse '<Alt+<>': Got invalid key!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.0.2', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 208, in main
    return app.run(args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 92, in run
    configinit.early_init(args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configinit.py", line 65, in early_init
    configfiles.read_config_py(config_file, warn_autoconfig=True)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configfiles.py", line 890, in read_config_py
    api.finalize()
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configfiles.py", line 641, in finalize
    self._config.update_mutables()
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 514, in update_mutables
    self.set_obj(name, new_value, save_yaml=save_yaml)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 452, in set_obj
    self._set_value(opt, value, pattern=pattern,
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 312, in _set_value
    opt.typ.to_py(value)  # for validation
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in to_py
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in <dictcomp>
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in toTraceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1972, in to_py
    return keyutils.KeySequence.parse(value)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/keyutils.py", line 655, in parse
    new._validate(keystr)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/keyutils.py", line 537, in _validate
    raise KeyParseError(keystr, "Got invalid key!")
qutebrowser.keyinput.keyutils.KeyParseError: Could not parse '<Alt+<>': Got invalid key!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python-exec/python3.8/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.0.2', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 208, in main
    return app.run(args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 92, in run
    configinit.early_init(args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configinit.py", line 65, in early_init
    configfiles.read_config_py(config_file, warn_autoconfig=True)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configfiles.py", line 890, in read_config_py
    api.finalize()
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configfiles.py", line 641, in finalize
    self._config.update_mutables()
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 514, in update_mutables
    self.set_obj(name, new_value, save_yaml=save_yaml)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 452, in set_obj
    self._set_value(opt, value, pattern=pattern,
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 312, in _set_value
    opt.typ.to_py(value)  # for validation
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in to_py
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in <dictcomp>
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in to_py
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in <dictcomp>
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1974, in to_py
    raise configexc.ValidationError(value, str(e))
qutebrowser.config.configexc.ValidationError: Invalid value '<Alt+<>' - Could not parse '<Alt+<>': Got invalid key!
_py
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1446, in <dictcomp>
    d = {self.keytype.to_py(key): self.valtype.to_py(val)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1974, in to_py
    raise configexc.ValidationError(value, str(e))
qutebrowser.config.configexc.ValidationError: Invalid value '<Alt+<>' - Could not parse '<Alt+<>': Got invalid key!
```

**Comment by ryazh3nka** [comment]
as of qutebrowser v3.5.1 the issue still persists

**Comment by qisc123** [comment]
still not work and give me that:
Errors occurred while reading config.py: 
While binding '<Alt-Less>': Invalid value '<Alt+<>' - Could not parse '<Alt+<>': Got invalid key!
