### ISSUE TITLE
ValueError with number keys and AZERTY layout

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3743]
With an [AZERTY keyboard layout](https://en.wikipedia.org/wiki/AZERTY), number keys are shifted while symbols are unshifted - leading to this:

```
15:47:41 DEBUG    keyboard   basekeyparser:_debug_log:89 Got key: 0xb2 / modifiers: 0x0 / text: '²' / dry_run True
15:47:41 DEBUG    modes      modeman:_handle_keypress:194 match: 2, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False, dry_run: True --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7fd8c03af438>)
15:47:41 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
15:47:41 DEBUG    keyboard   basekeyparser:_debug_log:89 Got key: 0xb2 / modifiers: 0x0 / text: '²' / dry_run False
15:47:41 DEBUG    modes      modeman:_handle_keypress:194 match: 2, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False, dry_run: False --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7fd8c03af438>)
15:47:41 DEBUG    modes      modeman:_handle_keyrelease:214 filter: True
15:47:41 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
15:47:41 DEBUG    keyboard   basekeyparser:_debug_log:89 Got key: 0x4f / modifiers: 0x0 / text: 'o' / dry_run True
15:47:41 DEBUG    modes      modeman:_handle_keypress:194 match: 2, forward_unbound_keys: auto, passthrough: False, is_non_alnum: False, dry_run: True --> filter: True (focused: <PyQt5.QtWidgets.QWidget object at 0x7fd8c03af438>)
15:47:41 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
15:47:41 DEBUG    keyboard   basekeyparser:_debug_log:89 Got key: 0x4f / modifiers: 0x0 / text: 'o' / dry_run False
15:47:41 DEBUG    keyboard   basekeyparser:_debug_log:89 Definitive match for 'o'.
15:47:41 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib64/python3.6/site-packages/qutebrowser/app.py", line 933, in eventFilter
    return handler(event)
  File "/usr/lib64/python3.6/site-packages/qutebrowser/app.py", line 906, in _handle_key_event
    return man.handle_event(event)
  File "/usr/lib64/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 335, in handle_event
    return handler(event)
  File "/usr/lib64/python3.6/site-packages/qutebrowser/keyinput/modeman.py", line 168, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
  File "/usr/lib64/python3.6/site-packages/qutebrowser/keyinput/modeparsers.py", line 98, in handle
    match = super().handle(e, dry_run=dry_run)
  File "/usr/lib64/python3.6/site-packages/qutebrowser/keyinput/basekeyparser.py", line 180, in handle
    count = int(self._count) if self._count else None
ValueError: invalid literal for int() with base 10: '²'
```

**Comment by The-Compiler** [comment]
Crash reports:

- https://crashes.qutebrowser.org/view/a65e06de
- https://crashes.qutebrowser.org/view/9fda7321
- https://crashes.qutebrowser.org/view/141be359
- https://crashes.qutebrowser.org/view/aa9cfc9e
- https://crashes.qutebrowser.org/view/d8802694
- https://crashes.qutebrowser.org/view/69fa9f25
- https://crashes.qutebrowser.org/view/28caa672
- https://crashes.qutebrowser.org/view/73d599b8
- https://crashes.qutebrowser.org/view/942e1a4b
- https://crashes.qutebrowser.org/view/a201b8ae
- https://crashes.qutebrowser.org/view/d187c1b1
- https://crashes.qutebrowser.org/view/5350d7bf
- https://crashes.qutebrowser.org/view/e37816b7
- https://crashes.qutebrowser.org/view/833289fa
- https://crashes.qutebrowser.org/view/20929f83
- https://crashes.qutebrowser.org/view/67e51f1c

> Yeah definitivly reproductible : open a tab, type '²' then '<Esc>' -> boom.

**Comment by The-Compiler** [comment]
Main issue here:

```
>>> '²'.isdigit()
True
>>> int('²')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: invalid literal for int() with base 10: '²'
```

so we should probably check `txt in string.digits` instead.
