### ISSUE TITLE
Crash when retrying downloads in DownloadInProgress state

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3847]
I can't reproduce this right now, but there are some crash reports:

- https://crashes.qutebrowser.org/view/6388c0c5
- https://crashes.qutebrowser.org/view/1841d5da
- https://crashes.qutebrowser.org/view/66c0ac7a
- https://crashes.qutebrowser.org/view/a9f3c446

Logs:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 325, in run_safely
    self.run(text, count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/runners.py", line 304, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.6/site-packages/qutebrowser/commands/command.py", line 502, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/downloads.py", line 1070, in download_retry
    download.try_retry()
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/downloads.py", line 570, in try_retry
    self.retry()
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginedownloads.py", line 104, in retry
    assert state == QWebEngineDownloadItem.DownloadInterrupted, state
AssertionError: 1
```

One report says:

> - opened gen.lib.rus.ec/
> - Initiated a download
> - Download didn't process aftersometime.
> - Retried the download. Nothing happened.
> - Cancelled the download.
> - Retried the download again.
> - Browser crashed.

**Comment by The-Compiler** [comment]
Not sure yet why this happens, but I made it a warning instead of an assertion for now.
