### ISSUE TITLE
RegistryUnavailableError when closing download prompt after closing window

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3852]
When doing this:

- Open two windows
- Start a download in window 1
- Close window 2
- Close the download prompt in window 1

We get:

```
15:49:30 DEBUG    downloads  downloads:_on_begin_insert_row:924 _on_begin_insert_row with idx 0, webengine True
15:49:30 DEBUG    prompt     prompt:ask_question:159 Asking question <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'>, blocking True, loops [], queue deque([])
15:49:30 DEBUG    prompt     prompt:ask_question:180 New question is blocking, saving None
15:49:30 DEBUG    prompt     prompt:_on_show_prompts:329 Displaying prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'>)
15:49:30 DEBUG    modes      modeman:enter:240 Entering mode KeyMode.prompt (reason: question asked)
15:49:30 DEBUG    statusbar  text:set_text:57 Setting normal text to '-- PROMPT MODE --'.
15:49:30 DEBUG    statusbar  bar:set_mode_active:289 Setting prompt flag to True
15:49:30 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.prompt.PromptContainer win_id=0>: PyQt5.QtCore.QRect(10, 281, 1255, 410)
15:49:30 DEBUG    prompt     prompt:_on_show_prompts:329 Displaying prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'>)
15:49:30 DEBUG    modes      modeman:enter:240 Entering mode KeyMode.prompt (reason: question asked)
15:49:30 DEBUG    statusbar  text:set_text:57 Setting normal text to '-- PROMPT MODE --'.
15:49:30 DEBUG    statusbar  bar:set_mode_active:289 Setting prompt flag to True
15:49:30 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <qutebrowser.mainwindow.prompt.LineEdit>
15:49:30 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.prompt.PromptContainer win_id=1>: PyQt5.QtCore.QRect(10, 281, 2535, 410)
15:49:30 DEBUG    prompt     prompt:ask_question:194 Starting loop.exec_() for <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'>
15:49:30 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.modeparsers.PassthroughKeyParser mode='prompt'>
15:49:30 DEBUG    modes      modeman:_handle_keypress:194 match: 0, forward_unbound_keys: auto, passthrough: True, is_non_alnum: True, dry_run: True --> filter: False (focused: <qutebrowser.mainwindow.prompt.LineEdit>)
15:49:30 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.modeparsers.PassthroughKeyParser mode='prompt'>
15:49:30 DEBUG    modes      modeman:_handle_keypress:194 match: 0, forward_unbound_keys: auto, passthrough: True, is_non_alnum: True, dry_run: False --> filter: False (focused: <qutebrowser.mainwindow.prompt.LineEdit>)
15:49:31 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
15:49:31 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <qutebrowser.mainwindow.prompt.LineEdit>
15:49:31 DEBUG    modes      modeman:_handle_keyrelease:214 filter: True
15:49:32 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.modeparsers.PassthroughKeyParser mode='prompt'>
15:49:32 DEBUG    modes      modeman:_handle_keypress:194 match: 0, forward_unbound_keys: auto, passthrough: True, is_non_alnum: True, dry_run: True --> filter: False (focused: <qutebrowser.mainwindow.prompt.LineEdit>)
15:49:32 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.modeparsers.PassthroughKeyParser mode='prompt'>
15:49:32 DEBUG    modes      modeman:_handle_keypress:194 match: 0, forward_unbound_keys: auto, passthrough: True, is_non_alnum: True, dry_run: False --> filter: False (focused: <qutebrowser.mainwindow.prompt.LineEdit>)
15:49:32 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
15:49:32 DEBUG    destroy    mainwindow:_do_close:559 Closing window 0
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: 0
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: tab
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: hintmanager
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: 0
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: main-window
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: last-focused-main-window
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: message-bridge
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: tabbed-browser
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: statusbar
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: status-command
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: completion
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: mode-manager
15:49:32 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: prompt-container
15:49:32 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.prompt.PromptContainer win_id=1>: PyQt5.QtCore.QRect(10, 993, 1255, 410)
15:49:32 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7fdc1c598678>: PyQt5.QtCore.QRect(0, 1402, 1275, 1)
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: 0
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: tab
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: hintmanager
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: 0
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: main-window
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: last-focused-main-window
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: message-bridge
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: tabbed-browser
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: statusbar
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: status-command
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: completion
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: mode-manager
15:49:32 DEBUG    destroy    objreg:_on_destroyed:126 removed: prompt-container
15:49:33 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <qutebrowser.mainwindow.prompt.LineEdit>
15:49:33 DEBUG    modes      modeman:_handle_keyrelease:214 filter: False
15:49:33 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.modeparsers.PassthroughKeyParser mode='prompt'>
15:49:33 DEBUG    modes      modeman:_handle_keypress:194 match: 2, forward_unbound_keys: auto, passthrough: True, is_non_alnum: False, dry_run: True --> filter: True (focused: <qutebrowser.mainwindow.prompt.LineEdit>)
15:49:33 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.prompt - delegating to <qutebrowser.keyinput.modeparsers.PassthroughKeyParser mode='prompt'>
15:49:33 DEBUG    commands   command:run:486 command called: leave-mode
15:49:33 DEBUG    commands   command:run:501 Calling qutebrowser.keyinput.modeman.ModeManager.leave_current_mode(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.prompt: 5>>)
15:49:33 DEBUG    modes      modeman:leave:298 Leaving mode KeyMode.prompt (reason: leave current)
15:49:33 DEBUG    statusbar  text:set_text:57 Setting normal text to ''.
15:49:33 DEBUG    statusbar  bar:set_mode_active:289 Setting prompt flag to False
15:49:33 DEBUG    prompt     prompt:_on_mode_left:221 Left mode KeyMode.prompt, hiding <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'>
15:49:33 DEBUG    prompt     prompt:_on_show_prompts:309 Deleting old prompt qutebrowser.mainwindow.prompt.DownloadFilenamePrompt(question=<qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'>)
15:49:33 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <qutebrowser.mainwindow.tabwidget.TabBar count=1>
15:49:33 DEBUG    prompt     prompt:_on_show_prompts:314 No prompts left, hiding prompt container.
15:49:33 DEBUG    prompt     prompt:_on_mode_left:225 Cancelling <qutebrowser.utils.usertypes.Question default='/tmp/qutebrowser-basedir-z9h34rlj/download/' mode=<PromptMode.download: 5> text='Please enter a location for <b>http://cmpl.cc/downloads/100mb.bin</b>' title='Save file to:'> because KeyMode.prompt was left
15:49:33 DEBUG    downloads  webenginedownloads:_on_state_changed:61 State for <qutebrowser.browser.webengine.webenginedownloads.DownloadItem basename='100mb.bin'> changed to DownloadCancelled
15:49:33 DEBUG    downloads  downloads:_on_begin_remove_row:936 _on_begin_remove_row with idx 0, webengine True
15:49:33 DEBUG    downloads  downloads:_on_begin_remove_row:936 _on_begin_remove_row with idx 0, webengine True
15:49:33 DEBUG    downloads  downloads:_remove_item:861 Removed download 1: 100mb.bin [   0.00B/s|0.00B]
15:49:33 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 200, in _get_window_registry
    return win.registry
AttributeError: 'NoneType' object has no attribute 'registry'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/prompt.py", line 336, in <lambda>
    maybe=True))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 114, in leave
    instance(win_id).leave(mode, reason, maybe=maybe)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 104, in instance
    return objreg.get('mode-manager', scope='window', window=win_id)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 227, in get
    reg = _get_registry(scope, window, tab)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 216, in _get_registry
    return _get_window_registry(window)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 202, in _get_window_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```

**Comment by The-Compiler** [comment]
Logs:

- https://crashes.qutebrowser.org/view/b1f8a17e (me)
- https://crashes.qutebrowser.org/view/577b2c90 (@rcorre)
- https://crashes.qutebrowser.org/view/66929051
- https://crashes.qutebrowser.org/view/af386c91
- https://crashes.qutebrowser.org/view/300d55f7
- https://crashes.qutebrowser.org/view/72c3d964
