### ISSUE TITLE
Deleted C++ object: WebEngineTab in _openurl_prepare

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3896]
- https://crashes.qutebrowser.org/view/67cc3df8
- https://crashes.qutebrowser.org/view/835d1239 ("Closed a tab closely after opening the browser, while all the tabs were still loading.")
- https://crashes.qutebrowser.org/view/ed9cb545

```
22:53:52 DEBUG    signals    signalfilter:_filter_signals:91 ignoring: cur_load_finished(True) (tab -1)
22:53:52 DEBUG    webview    tabbedbrowser:_tab_index:158 Got invalid tab (index is -1)!
22:53:52 DEBUG    config     webenginetab:_on_load_finished:918 Reloading https://github.com/wallix/awless because of config change
22:53:52 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7f3d4009b318>
22:53:52 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: 1
22:53:52 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: tab
22:53:52 DEBUG    destroy    objreg:on_destroyed:121 schedule removal: hintmanager
22:53:52 DEBUG    destroy    objreg:_on_destroyed:126 removed: 1
22:53:52 DEBUG    destroy    objreg:_on_destroyed:126 removed: tab
22:53:52 DEBUG    destroy    objreg:_on_destroyed:126 removed: hintmanager
22:53:52 DEBUG    modes      modeman:_handle_keyrelease:214 filter: True
22:53:52 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 920, in <lambda>
    self.openurl(url))
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 674, in openurl
    self._openurl_prepare(url)
  File "/usr/lib/python3.6/site-packages/qutebrowser/browser/browsertab.py", line 820, in _openurl_prepare
    self.predicted_navigation.emit(url)
RuntimeError: wrapped C/C++ object of type WebEngineTab has been deleted
```

**Comment by The-Compiler** [comment]
I think this is somewhat similar to #3498 (fixed in 748de85ba2cc7bd8557a87fce88aab0ac3f3ad27).

We [trigger that load via a QTimer](https://github.com/qutebrowser/qutebrowser/blob/v1.3.0/qutebrowser/browser/webengine/webenginetab.py#L1031-L1032) with a lambda, and I'm not sure at what point/how the `self` there gets bound.
