### ISSUE TITLE
Deleted C++ object: TabWidget in _on_config_changed -> _update_favicons

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3897]
```
13:15:16 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/home/ord/bin/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 142, in _on_config_changed
    self._update_favicons()
  File "/home/ord/bin/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 531, in _update_favicons
    for i, tab in enumerate(self.widgets()):
  File "/home/ord/bin/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 170, in widgets
    for i in range(self.widget.count()):
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
13:15:16 ERROR    destroy    crashsignal:_get_exception_info:198 Error while getting objects
Traceback (most recent call last):
  File "/home/ord/bin/qutebrowser/qutebrowser/misc/crashsignal.py", line 196, in _get_exception_info
    objects = debug.get_all_objects()
  File "/home/ord/bin/qutebrowser/qutebrowser/utils/debug.py", line 293, in get_all_objects
    widget_lines = _get_widgets()
  File "/home/ord/bin/qutebrowser/qutebrowser/utils/debug.py", line 279, in _get_widgets
    widgets.sort(key=repr)
  File "/home/ord/bin/qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 137, in __repr__
    return utils.get_repr(self, count=self.widget.count())
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
```

- https://crashes.qutebrowser.org/view/b41df622
- https://crashes.qutebrowser.org/view/8dbada9c
- https://crashes.qutebrowser.org/view/e5e3b481

**Comment by The-Compiler** [comment]
Almost the same in `update_tab_titles`:

```
14:43:28 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/home/marcosrdac/.qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 147, in _on_config_changed
    self.widget.update_tab_titles()
  File "/home/marcosrdac/.qutebrowser/qutebrowser/mainwindow/tabwidget.py", line 202, in update_tab_titles
    for idx in range(self.count()):
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
14:43:28 ERROR    destroy    crashsignal:_get_exception_info:198 Error while getting objects
Traceback (most recent call last):
  File "/home/marcosrdac/.qutebrowser/qutebrowser/misc/crashsignal.py", line 196, in _get_exception_info
    objects = debug.get_all_objects()
  File "/home/marcosrdac/.qutebrowser/qutebrowser/utils/debug.py", line 294, in get_all_objects
    widget_lines = _get_widgets()
  File "/home/marcosrdac/.qutebrowser/qutebrowser/utils/debug.py", line 280, in _get_widgets
    widgets.sort(key=repr)
  File "/home/marcosrdac/.qutebrowser/qutebrowser/mainwindow/tabbedbrowser.py", line 138, in __repr__
    return utils.get_repr(self, count=self.widget.count())
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
```

- https://crashes.qutebrowser.org/view/25a681a2
- https://crashes.qutebrowser.org/view/88d94427
- https://crashes.qutebrowser.org/view/f8ec8d12
- https://crashes.qutebrowser.org/view/4a79d29d
- https://crashes.qutebrowser.org/view/d420df2b
- https://crashes.qutebrowser.org/view/4828f3d9
