### ISSUE TITLE
Qt 5.11 keyboard focus issues

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#3939]
Trying to clean up all the confusion in my head about that one :wink:

- [Change 226416](https://codereview.qt-project.org/#/c/226416/) made it into QtWebEngine as fix for [QTBUG-65595](https://bugreports.qt.io/browse/QTBUG-65595)
- That broke some stuff: [QTBUG-68224](https://bugreports.qt.io/browse/QTBUG-68224) (only half of the screen height is used, #3920) and [QTBUG-68076](https://bugreports.qt.io/browse/QTBUG-68076) (what this issue is about)
- The first fix (setting `FocusOnNavigationEnabled`) in fa41af63b67b007a67cbac1b119729d030b9e533 (then tracked in #3661) broke things and caused #3872, so it was reverted in 68794cc2e27b8d7028481a8128a7738271071dc9
- ae295a7f652ed851ac8b258aa10500d72e6a52b6 tried to call `setFocus()` at the right places, which didn't affect #3872, but still isn't the full story
- Together with [Qt change 229367](https://codereview.qt-project.org/#/c/229367/4) it hopefully fixes everything, but we still need to find a workaround for that
- @jgkamat submitted #3921 which calls `setFocus()` when entering insert mode - that works, but I'd still like to find a better solution before falling back to that.

**Comment by The-Compiler** [comment]
`QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget::setKeyboardFocus` is called like this:

```
#0  0x00007fffdc4da230 in QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget::setKeyboardFocus() (this=0x55555691a110)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.11.0-rc/src/webenginewidgets/render_widget_host_view_qt_delegate_widget.cpp:249
#1  0x00007fffd65e6740 in QtWebEngineCore::RenderWidgetHostViewQt::Focus() (this=0x55555c60a110)
    at /usr/include/c++/8.1.0/bits/unique_ptr.h:342
#2  0x00007fffd6e229a7 in content::RenderFrameHostManager::CommitPending() ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_manager.cc:2073
#3  0x00007fffd6e22eb5 in content::RenderFrameHostManager::CommitPendingIfNecessary(content::RenderFrameHostImpl*, bool) ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_manager.cc:254
#4  0x00007fffd6e22f04 in content::RenderFrameHostManager::DidNavigateFrame(content::RenderFrameHostImpl*, bool) ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_manager.cc:223
#5  0x00007fffd6dfcdf2 in content::NavigatorImpl::DidNavigate(content::RenderFrameHostImpl*, FrameHostMsg_DidCommitProvisionalLoad_Params const&, std::unique_ptr<content::NavigationHandleImpl, std::default_delete<content::NavigationHandleImpl> >) ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/content/browser/frame_host/navigator_impl.cc:486
#6  0x00007fffd6e0b723 in content::RenderFrameHostImpl::DidCommitProvisionalLoad(std::unique_ptr<FrameHostMsg_DidCommitProvisionalLoad_Params, std::default_delete<FrameHostMsg_DidCommitProvisionalLoad_Params> >, mojo::InterfaceRequest<service_manager::mojom::InterfaceProvider>) ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_impl.cc:1731
#7  0x00007fffd677f443 in content::mojom::FrameHostStubDispatch::Accept(content::mojom::FrameHost*, mojo::Message*) ()
    at ./gen/content/common/frame.mojom.cc:2243
#8  0x00007fffd83f0afd in mojo::InterfaceEndpointClient::HandleValidatedMessage(mojo::Message*) ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/mojo/public/cpp/bindings/lib/interface_endpoint_client.cc:419
#9  0x00007fffd84298e9 in AcceptOnProxyThread() ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/ipc/ipc_mojo_bootstrap.cc:789
#10 0x00007fffd84293ce in Invoke<scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController> const&, mojo::Message> ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/bind_internal.h:211
#11 0x00007fffd84293ce in MakeItSo<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::* const&)(mojo::Message), scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController> const&, mojo::Message> ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/bind_internal.h:294
#12 0x00007fffd84293ce in RunImpl<void (IPC::(anonymous namespace)::ChannelAssociatedGroupController::* const&)(mojo::Message), std::tuple<scoped_refptr<IPC::(anonymous namespace)::ChannelAssociatedGroupController>, base::internal::PassedWrapper<mojo::Message> > const&, 0, 1>() ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/bind_internal.h:368
#13 0x00007fffd7b6f778 in base::OnceCallback<void ()>::Run() && ()
    at ../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/callback.h:65
#14 0x00007fffd7b6f778 in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) ()
    at ./../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/debug/task_annotator.cc:55
#15 0x00007fffd7b8ffea in base::internal::IncomingTaskQueue::RunTask(base::PendingTask*) ()
    at ./../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/message_loop/incoming_task_queue.cc:124
#16 0x00007fffd7b8ffea in base::MessageLoop::RunTask(base::PendingTask*) ()
    at ./../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/message_loop/message_loop.cc:399
#17 0x00007fffd7b90aaf in base::MessageLoop::DeferOrRunPendingTask(base::PendingTask) ()
    at ./../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/message_loop/message_loop.cc:411
#18 0x00007fffd7b90c2a in base::MessageLoop::DoWork() ()
    at ./../../../../qtwebengine-everywhere-src-5.11.0-rc/src/3rdparty/chromium/base/message_loop/message_loop.cc:455
#19 0x00007fffd65a856d in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::handleScheduledWork (this=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.11.0-rc/src/core/content_browser_client_qt.cpp:227
#20 0x00007fffd65a856d in QtWebEngineCore::(anonymous namespace)::MessagePumpForUIQt::customEvent(QEvent*) (this=0x555556580c40, ev=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.11.0-rc/src/core/content_browser_client_qt.cpp:209
#21 0x00007ffff20c730b in QObject::event(QEvent*) (this=0x555556580c40, e=<optimized out>) at kernel/qobject.cpp:1232
[...]
```
