### ISSUE TITLE
Crash and emptied session with bdb.BdbQuit exception

### ISSUE THREAD

**Issue by blueyed** [qutebrowser/qutebrowser#3993]
I've used `pdb.set_trace` to see if `_pinned_statistics` gets called, and then exited Pdb using `quit`.

This caused qutebrowser to crash, and also left the (default) session in a broken state:

When opening qutebrowser afterwards I see a single tab 0 only, with no contents
- although there should have been duckduckgo probably at least (as with
`--temp-basedir`, i.e. no session).

While this case is constructed, it is pretty bad, since the session contained a
lot of tabs that I would rather have closed manually instead.
(I have a backup, but still)

I have copied the broken basedir (I am using `--basedir $HOME/.local/share/qutebrowser-foo`), in case you want something from there.

It is probably easy to reproduce though, and might be caused due to the following:

> 00:07:15 DEBUG    destroy    app:shutdown:714 Shutting down with status 0, session None...
> 00:07:15 DEBUG    sessions   sessions:save:289 Saving session default to /home/daniel/.local/share/qutebrowser-noa/data/sessions/default.yml...

Maybe things should not get stored in case of a crash like this altogether, including:

> 00:07:15 DEBUG    save       savemanager:save:96 Save of state-config requested - dirty False, save_on_exit True, is_exit True, force False -> True

"Crash" here means bdb.BdbQuit really, which seems to be handled like a normal exit.
Therefore the main issue probably is that the session should not be stored if it wasn't fully loaded yet ("session None").

```
00:07:00 DEBUG    init       app:_init_modules:435 Initializing proxy...
00:07:00 DEBUG    init       app:_init_modules:438 Initializing readline-bridge...
00:07:00 DEBUG    init       app:_init_modules:443 Initializing sql...
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "PRAGMA journal_mode=WAL"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "PRAGMA journal_mode=WAL"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "PRAGMA synchronous=NORMAL"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "PRAGMA synchronous=NORMAL"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    init       app:_init_modules:446 Initializing web history...
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "CREATE TABLE IF NOT EXISTS History (url NOT NULL, title NOT NULL, atime NOT NULL, redirect NOT NULL)"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "CREATE TABLE IF NOT EXISTS History (url NOT NULL, title NOT NULL, atime NOT NULL, redirect NOT NULL)"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "CREATE TABLE IF NOT EXISTS CompletionHistory (url PRIMARY KEY, title NOT NULL, last_atime NOT NULL)"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "CREATE TABLE IF NOT EXISTS CompletionHistory (url PRIMARY KEY, title NOT NULL, last_atime NOT NULL)"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "CREATE INDEX IF NOT EXISTS CompletionHistoryAtimeIndex ON CompletionHistory (last_atime)"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "CREATE INDEX IF NOT EXISTS CompletionHistoryAtimeIndex ON CompletionHistory (last_atime)"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "pragma user_version"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "pragma user_version"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "SELECT count(*) FROM CompletionHistory"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "SELECT count(*) FROM CompletionHistory"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "CREATE INDEX IF NOT EXISTS HistoryIndex ON History (url)"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "CREATE INDEX IF NOT EXISTS HistoryIndex ON History (url)"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "CREATE INDEX IF NOT EXISTS HistoryAtimeIndex ON History (atime)"
00:07:00 DEBUG    sql        sql:run:173 Running SQL query: "CREATE INDEX IF NOT EXISTS HistoryAtimeIndex ON History (atime)"
00:07:00 DEBUG    sql        sql:run:176 query bindings: {}
00:07:00 DEBUG    sql        sql:__init__:155 Preparing SQL query: "SELECT EXISTS(SELECT * FROM History WHERE url = :val)"
> /home/daniel/Vcs/qutebrowser/qutebrowser/mainwindow/tabwidget.py(578)

 574         @functools.lru_cache(maxsize=1)                                                                                                                                                  
 575         def _pinned_statistics(self) -> (int, int):                                                                                                                                      
 576             __import__('pdb').set_trace()                                                                                                                                                
 577             """Get the number of pinned tabs and the total width of pinned tabs."""                                                                                                      
 578  ->         pinned_list = [idx for idx in range(self.count())                                                                                                                            
 579                            if self._tab_pinned(idx)]                                                                                                                                     
 580             pinned_count = len(pinned_list)                                                                                                                                              
 581             pinned_width = sum(self.minimumTabSizeHint(idx, ellipsis=False).width()                                                                                                      
 582                                for idx in pinned_list)                                                                                                                                   
 583             return (pinned_count, pinned_width)                                                                                                                                          
(Pdb++) q
00:07:15 ERROR    misc       crashsignal:exception_hook:216 Uncaught exception
Traceback (most recent call last):
  File "/home/daniel/Vcs/qutebrowser/qutebrowser/mainwindow/tabwidget.py", line 624, in tabSizeHint
    pinned_count, pinned_width = self._pinned_statistics()
  File "/home/daniel/Vcs/qutebrowser/qutebrowser/mainwindow/tabwidget.py", line 578, in _pinned_statistics
    pinned_list = [idx for idx in range(self.count())
  File "/home/daniel/Vcs/qutebrowser/qutebrowser/mainwindow/tabwidget.py", line 578, in _pinned_statistics
    pinned_list = [idx for idx in range(self.count())
  File "/usr/lib/python3.6/bdb.py", line 51, in trace_dispatch
    return self.dispatch_line(frame)
  File "/usr/lib/python3.6/bdb.py", line 70, in dispatch_line
    if self.quitting: raise BdbQuit
bdb.BdbQuit
00:07:15 DEBUG    destroy    app:shutdown:714 Shutting down with status 0, session None...
00:07:15 DEBUG    sessions   sessions:save:289 Saving session default to /home/daniel/.local/share/qutebrowser-noa/data/sessions/default.yml...
00:07:15 DEBUG    prompt     prompt:shutdown:135 Shutting down with loops []
00:07:15 DEBUG    destroy    app:_shutdown:741 Stage 2 of shutting down...
00:07:15 DEBUG    destroy    app:_shutdown:747 Removing eventfilter...
00:07:15 DEBUG    destroy    mainwindow:_do_close:559 Closing window 0
00:07:15 DEBUG    mouse      mouse:eventFilter:54 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7f9c19d9fa68> got new child <PyQt5.QtWidgets.QWidget object at 0x7f9c19e370d8>, installing filter
00:07:15 DEBUG    ipc        ipc:shutdown:402 Shutting down IPC (socket 0x7f9cacf5fa60)
00:07:15 DEBUG    save       savemanager:save:96 Save of yaml-config requested - dirty False, save_on_exit False, is_exit True, force False -> False
00:07:15 DEBUG    save       savemanager:save:96 Save of state-config requested - dirty False, save_on_exit True, is_exit True, force False -> True
00:07:15 DEBUG    save       savemanager:save:96 Save of command-history requested - dirty False, save_on_exit False, is_exit True, force False -> False
00:07:15 DEBUG    save       savemanager:save:96 Save of quickmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
00:07:15 DEBUG    save       savemanager:save:96 Save of bookmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
00:07:15 DEBUG    save       savemanager:save:96 Save of cookies requested - dirty False, save_on_exit False, is_exit True, force False -> False
00:07:15 DEBUG    destroy    app:_shutdown:779 Deactivating crash log...
00:07:15 DEBUG    destroy    app:_shutdown:789 Deactivating message handler...
00:07:15 DEBUG    destroy    app:_shutdown:792 Deferring QApplication::exit...
Received signal 11 <unknown> 000000000000
#0 0x7f9c8ce03abe <unknown>
#1 0x7f9c8ce03bd0 <unknown>
#2 0x7f9c8ce04207 <unknown>
#3 0x7f9cad361a80 <unknown>
#4 0x7f9c9cbcd12d QTabBarPrivate::layoutTabs()
#5 0x7f9c9cbd29b9 QTabBarPrivate::refresh()
#6 0x7f9c9cbd2ab7 QTabBar::setTabText()
#7 0x7f9c9adc2f34 <unknown>
#8 0x7f9cacbb6343 _PyCFunction_FastCallDict
#9 0x7f9cacb7f84e <unknown>
#10 0x7f9cacb430fa _PyEval_EvalFrameDefault
#11 0x7f9cacb7da99 <unknown>
#12 0x7f9cacb7f4e0 <unknown>
#13 0x7f9cacb7f952 <unknown>
#14 0x7f9cacb430fa _PyEval_EvalFrameDefault
#15 0x7f9cacb7f31b <unknown>
#16 0x7f9cacb7f952 <unknown>
#17 0x7f9cacb430fa _PyEval_EvalFrameDefault
#18 0x7f9cacb7eb2b _PyFunction_FastCallDict
#19 0x7f9cacbb128f _PyObject_FastCallDict
#20 0x7f9cacbb1c12 _PyObject_Call_Prepend
#21 0x7f9cacbb1cf3 PyObject_Call
#22 0x7f9cacc4d312 <unknown>
#23 0x7f9cacbb1cf3 PyObject_Call
#24 0x7f9ca51d29d1 <unknown>
#25 0x7f9ca51d2ef1 <unknown>
#26 0x7f9ca51d31e3 <unknown>
#27 0x7f9ca51d3bb0 <unknown>
#28 0x7f9ca4b78add QMetaObject::activate()
#29 0x7f9ca51cf4a0 <unknown>
#30 0x7f9cacbb6343 _PyCFunction_FastCallDict
#31 0x7f9cacb7f84e <unknown>
#32 0x7f9cacb430fa _PyEval_EvalFrameDefault
#33 0x7f9cacb7f31b <unknown>
#34 0x7f9cacb7f952 <unknown>
#35 0x7f9cacb430fa _PyEval_EvalFrameDefault
#36 0x7f9cacb7da99 <unknown>
#37 0x7f9cacb7ed48 _PyFunction_FastCallDict
#38 0x7f9cacbb128f _PyObject_FastCallDict
#39 0x7f9cacbb1c12 _PyObject_Call_Prepend
#40 0x7f9cacbb1cf3 PyObject_Call
#41 0x7f9ca51d29d1 <unknown>
#42 0x7f9ca51d2ef1 <unknown>
#43 0x7f9ca51d309d <unknown>
#44 0x7f9ca51d59a5 <unknown>
#45 0x7f9ca51d5ab3 <unknown>
#46 0x7f9ca4b78add QMetaObject::activate()
#47 0x7f9ca51cf4a0 <unknown>
#48 0x7f9cacbb6343 _PyCFunction_FastCallDict
#49 0x7f9cacb7f84e <unknown>
#50 0x7f9cacb430fa _PyEval_EvalFrameDefault
#51 0x7f9cacb7da99 <unknown>
#52 0x7f9cacb7f4e0 <unknown>
#53 0x7f9cacb7f952 <unknown>
#54 0x7f9cacb430fa _PyEval_EvalFrameDefault
#55 0x7f9cacb7da99 <unknown>
#56 0x7f9cacb7f4e0 <unknown>
#57 0x7f9cacb7f952 <unknown>
#58 0x7f9cacb430fa _PyEval_EvalFrameDefault
#59 0x7f9cacb7da99 <unknown>
#60 0x7f9cacb7f4e0 <unknown>
#61 0x7f9cacb7f952 <unknown>
  r8: 00007f9c19e45f78  r9: 00000000fffffffe r10: 0000000000000013 r11: 0000000000000001
 r12: 000055a29727c540 r13: 0000000000000000 r14: 0000000000000000 r15: 0000000000000000
  di: 00000000ffffffff  si: 0000000000000000  bp: 0000000000000000  bx: 000055a2971e7d90
  dx: ffffffffffffffff  ax: 0064006900570051  cx: 00000000fffffffe  sp: 00007ffde5dadc00
  ip: 00007f9c9cbcd12d efl: 0000000000010202 cgf: 002b000000000033 erf: 0000000000000000
 trp: 000000000000000d msk: 0000000000000000 cr2: 0000000000000000
[end of stack trace]
Calling _exit(1). Core file will not be generated.
[7453:7453:0100/000000.926590:ERROR:broker_posix.cc(43)] Invalid node channel message
```

**Comment by The-Compiler** [comment]
I can't reproduce this. Here's what I do:

- `qutebrowser --basedir /tmp/qute`
- open two tabs
- quit with `:wq`
- add the breakpoint in `pinned_statistics`
- start qutebrowser again
- `q` at the pdb prompt
- remove the breakpoint
- start qutebrowser a third time, the pages are there like I'd expect.

The `session None` just means there was no session name given with `:quit`.

**Comment by blueyed** [comment]
Thanks for looking into this.

1. Have you used `--debug` also?
2. Does it happen at the same point, i.e. after the `sql:__init__:155 Preparing SQL query: "SELECT EXISTS(SELECT * FROM History WHERE url = :val)"` line?  (I'm asking since I might have used `c` a few times before `q`).
3. Do you see the exception? (crashsignal:exception_hook:216 Uncaught exception)
4. Do you see the "signal 11"?

**Comment by The-Compiler** [comment]
Hm, yeah, I was able to reproduce it now. I'll push a fix to just quit hard when using `q` in pdb - that's realistically the best we can do in that situation.

**Comment by blueyed** [comment]
Thank you!

**Comment by The-Compiler** [comment]
As for the crash: That's still likely to happen I'm afraid - there's just no clean way to exit cleanly when you want to exit at an arbitrary point (somewhere deep into a C++/Python stack) and have two languages involved...
