### ISSUE TITLE
Crash on moving window to another Display

### ISSUE THREAD

**Issue by benedikt-bartscher** [qutebrowser/qutebrowser#3995]
I'm running Arch Linux with i3wm. While moving qutebrowser to another Monitor, it crashes with the following error message:

```
19:20:08 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
19:20:09 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: <PyQt5.QtQuickWidgets.QQuickWidget object at 0x7feb18343828>
19:20:09 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
19:20:10 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7feb18335ca8>: PyQt5.QtCore.QRect(0, 1129, 957, 1)
Received signal 11 SEGV_MAPERR 0000000009c0
#0 0x7feb746ffabe <unknown>
#1 0x7feb746ffbd0 <unknown>
#2 0x7feb74700207 <unknown>
#3 0x7feb8d1f7a80 <unknown>
#4 0x7feb7d20c5a1 <unknown>
#5 0x7feb7d1efeac <unknown>
#6 0x7feb7ef0c580 <unknown>
  r8: 0000000000000000  r9: 0000000000000014 r10: 0000000000000000 r11: 0000000000000008
 r12: 0000000040ebc000 r13: 0000000000000000 r14: 0000000000000000 r15: 0000000000000000
  di: 0000000040ebc000  si: 0000000000000000  bp: 00005617e0b7a550  bx: 0000000000000000
  dx: 0000000000000000  ax: 0000000000000000  cx: 0000000000000000  sp: 00007ffd219afda0
  ip: 00007feb7d20c5a1 efl: 0000000000010206 cgf: 002b000000000033 erf: 0000000000000004
 trp: 000000000000000e msk: 0000000000000000 cr2: 00000000000009c0
[end of stack trace]
Calling _exit(1). Core file will not be generated.
```

qutebrowser --version
```
qutebrowser v1.3.2
Git commit: 1541088e7 (2018-06-12 17:01:34 +0200)
Backend: QtWebEngine (Chromium 65.0.3325.151)

CPython: 3.6.5
Qt: 5.11.0
PyQt: 5.10.1

sip: 4.19.8
colorama: 0.3.9
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 18.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.24.0
QtNetwork SSL: OpenSSL 1.1.0h  27 Mar 2018

Style: QFusionStyle
Platform: Linux-4.16.13-2-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.6/site-packages/qutebrowser
Using Python from /usr/bin/python
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/benedikt/.cache/qutebrowser
config: /home/benedikt/.config/qutebrowser
data: /home/benedikt/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:00:00
[1]    14388 segmentation fault (core dumped)  qutebrowser --version
```

**Comment by The-Compiler** [comment]
That's odd. Can you please install my debug packages and get a stacktrace via gdb? See https://github.com/qutebrowser/qutebrowser/blob/master/doc/stacktrace.asciidoc

**Comment by benedikt-bartscher** [comment]
qutebrowser does not open if i execute
gdb $(readlink -f $(which python3)) -ex 'run -m qutebrowser --debug'
```
GNU gdb (GDB) 8.1
Copyright (C) 2018 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-pc-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from /usr/bin/python3.6...(no debugging symbols found)...done.
Starting program: /usr/bin/python3.6 -m qutebrowser --debug
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".
19:41:31 DEBUG    init       earlyinit:init_log:265 Log initialized.

```

**Comment by benedikt-bartscher** [comment]
Okay sorry, i didn't wait long enough!

```
19:52:28 DEBUG    modes      modeman:_handle_keypress:167 got keypress in mode KeyMode.normal - delegating to <qutebrowser.keyinput.modeparsers.NormalKeyParser>
19:52:28 DEBUG    keyboard   basekeyparser:_debug_log:91 Got key: 0x1000020 / modifiers: 0x12000000 / text: '<Meta+Shift>' / dry_run False
19:52:28 DEBUG    keyboard   basekeyparser:_debug_log:91 Ignoring, only modifier
19:52:28 DEBUG    modes      modeman:_handle_keypress:194 match: 0, forward_unbound_keys: auto, passthrough: False, is_non_alnum: True, dry_run: False --> filter: False (focused: <PyQt5.QtQuickWidgets.QQuickWidget object at 0x7fff43074318>)
19:52:28 DEBUG    misc       app:on_focus_object_changed:840 Focus object changed: None
19:52:29 DEBUG    misc       mainwindow:_update_overlay_geometry:297 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7fff43075798>: PyQt5.QtCore.QRect(0, 1129, 1917, 1)
```

[gdb.txt](https://github.com/qutebrowser/qutebrowser/files/2095266/gdb.txt)

**Comment by The-Compiler** [comment]
Looking at that stacktrace, the crash is inside the nvidia driver:

```
#0  0x00007fffe895a5a1 in  () at /usr/lib/nvidia/libnvidia-glcore.so.340.106
#1  0x00007fffe893deac in  () at /usr/lib/nvidia/libnvidia-glcore.so.340.106
#2  0x00007fffea65a580 in  () at /usr/lib/nvidia/libGL.so.1
#3  0x00007fffea65a72c in  () at /usr/lib/nvidia/libGL.so.1
#4  0x00007fffea68d949 in  () at /usr/lib/nvidia/libGL.so.1
#5  0x00007fffc3514300 in QGLXContext::makeCurrent(QPlatformSurface*) (this=0x5555574536f0, surface=0x555556c9db00) at qglxintegration.cpp:548
...
```

Nothing qutebrowser can do there I'm afraid. Maybe things work better with the `qt.force_software_rendering` option, but that'll decrease performance.
