### ISSUE TITLE
Unexpected behaviour of config object in config.py

### ISSUE THREAD

**Issue by Holzhaus** [qutebrowser/qutebrowser#4042]
The config object behaves odd in some situations, e.g. with this `config.py`:

```python
# ~/.config/qutebrowser/config.py
for d in ({'foo': 'quit'}, {'bar': 'quit'}):
    d.update(config.get('aliases'))
    print(d)
    config.set('aliases', d)
print(config.get('aliases'))
assert 'foo' in config.get('aliases')
assert 'bar' in config.get('aliases')
```

I'd expect that `aliases` is set to this value:

```
{'foo': 'quit', 'bar': 'quit', 'w': 'session-save', 'q': 'quit', 'wq': 'quit --save'}
```

However, this is not the case:

```
$ qutebrowser
{'foo': 'quit', 'w': 'session-save', 'q': 'quit', 'wq': 'quit --save'}
{'bar': 'quit', 'w': 'session-save', 'q': 'quit', 'wq': 'quit --save'}
{'w': 'session-save', 'q': 'quit', 'wq': 'quit --save'}
18:39:35 ERROR: Error while loading config.py
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configinit.py", line 60, in early_init
    configfiles.read_config_py(config_file)
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 572, in read_config_py
    raise configexc.ConfigFileErrors('config.py', api.errors)
qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py:
  Unhandled exception - AssertionError:
```

```
Errors occurred while reading config.py: 
Unhandled exception: 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/qutebrowser/config/configfiles.py", line 561, in read_config_py
    exec(code, module.__dict__)
  File "/home/jan/.config/qutebrowser/config.py", line 7, in <module>
    assert 'foo' in config.get('aliases')
AssertionError
```

Using commit d2254ca48 (http://paste.the-compiler.org/view/4824fe5d)

**Comment by The-Compiler** [comment]
The config has some quite tricky code to handle mutable objects correctly (so you can do `c.aliases['foo'] = 'bar'` and the right thing actually happens). It looks like it doesn't catch this case properly, not sure why.

**Comment by toofar** [comment]
I had a quick look at this while procrastinating. `config.get()` calls `get_mutable_obj()` which caches a copy of the value for later calls but `config.set()` calls `set_obj()` which calls `self._set_value()` which just updates `self._values` directly without updating or invalidating the cached mutable object. Then the next loop gets the cached mutable object again and overwrites the value.
