### ISSUE TITLE
PyYAML parsing bug found by hypothesis

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4607]
```python
>>> from qutebrowser.config import configdata, configtypes
>>> d = configtypes.Dict(keytype=configtypes.String(), valtype=configtypes.Bool(), none_ok=True)
>>> val = {'\xa0\xa0ƠƠƠƠ\xa0ƠƠƠƠ\xa0ƠƠƠƠƠƠƠƠƠ\xa0\xa0\xa0ƠƠƠ佒佒\xa0佒\xa0佒佒佒佒佒½佒佒佒佒佒佒佒佒佒佒佒\xa0\xa0佒佒佒佒佒佒佒佒佒\xa0佒佒ŒŒŒŒ\xa0ŒŒŒŒŒ\xa0\xa0ŒŒ\xa0ŒŒŒ\xa0ŒŒŒ\xa0ŒŒ0ŒŒŒŒ\xa0ŒŒŒ\xa0\xa0Œ\xa0ŒŒŒŒ0佒\xa0\xa0佒佒佒ŒŒŒ\xa0\xa0ŒŒ\xa0ŒŒŒŒŒŒ\xa0Œ0\xa0\xa0佒佒佒佒佒佒佒佒佒佒佒佒\xa0佒佒\xa0佒佒佒\xa0佒\xa0佒\xa0佒佒\xa0佒佒佒佒佒佒佒佒佒\xa0佒Œ佒\xa0佒': False}
>>> d.from_str(d.to_str(d.to_py(val)))
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1343, in from_str
    yaml_val = utils.yaml_load(value)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/utils.py", line 669, in yaml_load
    data = yaml.load(f, Loader=YamlLoader)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 1
did not find expected ',' or '}'
  in "<unicode string>", line 1, column 1027

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 1345, in from_str
    raise configexc.ValidationError(value, str(e))
qutebrowser.config.configexc.ValidationError: Invalid value '{"\u00a0\u00a0\u01a0\u01a0\u01a0\u01a0\u00a0\u01a0\u01a0\u01a0\u01a0\u00a0\u01a0\u01a0\u01a0\u01a0\u01a0\u01a0\u01a0\u01a0\u01a0\u00a0\u00a0\u00a0\u01a0\u01a0\u01a0\u4f52\u4f52\u00a0\u4f52\u00a0\u4f52\u4f52\u4f52\u4f52\u4f52\u00bd\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u00a0\u00a0\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u00a0\u4f52\u4f52\u0152\u0152\u0152\u0152\u00a0\u0152\u0152\u0152\u0152\u0152\u00a0\u00a0\u0152\u0152\u00a0\u0152\u0152\u0152\u00a0\u0152\u0152\u0152\u00a0\u0152\u01520\u0152\u0152\u0152\u0152\u00a0\u0152\u0152\u0152\u00a0\u00a0\u0152\u00a0\u0152\u0152\u0152\u01520\u4f52\u00a0\u00a0\u4f52\u4f52\u4f52\u0152\u0152\u0152\u00a0\u00a0\u0152\u0152\u00a0\u0152\u0152\u0152\u0152\u0152\u0152\u00a0\u01520\u00a0\u00a0\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u00a0\u4f52\u4f52\u00a0\u4f52\u4f52\u4f52\u00a0\u4f52\u00a0\u4f52\u00a0\u4f52\u4f52\u00a0\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u4f52\u00a0\u4f52\u0152\u4f52\u00a0\u4f52": false}' - while parsing a flow mapping
  in "<unicode string>", line 1, column 1
did not find expected ',' or '}'
  in "<unicode string>", line 1, column 1027
```

```python
>>> utils.yaml_load('{"\\u00a0\\u00a0\\u01a0\\u01a0\\u01a0\\u01a0\\u00a0\\u01a0\\u01a0\\u01a0\\u01a0\\u00a0\\u01a0\\u01a0\\u01a0\\u01a0\\u01a0\\u01a0\\u01a0\\u01a0\\u01a0\\u00a0\\u00a0\\u00a0\\u01a0\\u01a0\\u01a0\\u4f52\\u4f52\\u00a0\\u4f52\\u00a0\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u00bd\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u00a0\\u00a0\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u00a0\\u4f52\\u4f52\\u0152\\u0152\\u0152\\u0152\\u00a0\\u0152\\u0152\\u0152\\u0152\\u0152\\u00a0\\u00a0\\u0152\\u0152\\u00a0\\u0152\\u0152\\u0152\\u00a0\\u0152\\u0152\\u0152\\u00a0\\u0152\\u01520\\u0152\\u0152\\u0152\\u0152\\u00a0\\u0152\\u0152\\u0152\\u00a0\\u00a0\\u0152\\u00a0\\u0152\\u0152\\u0152\\u01520\\u4f52\\u00a0\\u00a0\\u4f52\\u4f52\\u4f52\\u0152\\u0152\\u0152\\u00a0\\u00a0\\u0152\\u0152\\u00a0\\u0152\\u0152\\u0152\\u0152\\u0152\\u0152\\u00a0\\u01520\\u00a0\\u00a0\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u00a0\\u4f52\\u4f52\\u00a0\\u4f52\\u4f52\\u4f52\\u00a0\\u4f52\\u00a0\\u4f52\\u00a0\\u4f52\\u4f52\\u00a0\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u4f52\\u00a0\\u4f52\\u0152\\u4f52\\u00a0\\u4f52": false}')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/utils.py", line 669, in yaml_load
    data = yaml.load(f, Loader=YamlLoader)
  File "/usr/lib/python3.7/site-packages/yaml/__init__.py", line 72, in load
    return loader.get_single_data()
  File "/usr/lib/python3.7/site-packages/yaml/constructor.py", line 35, in get_single_data
    node = self.get_single_node()
  File "ext/_yaml.pyx", line 707, in _yaml.CParser.get_single_node
  File "ext/_yaml.pyx", line 725, in _yaml.CParser._compose_document
  File "ext/_yaml.pyx", line 776, in _yaml.CParser._compose_node
  File "ext/_yaml.pyx", line 892, in _yaml.CParser._compose_mapping_node
  File "ext/_yaml.pyx", line 905, in _yaml.CParser._parse_next_event
yaml.parser.ParserError: while parsing a flow mapping
  in "<unicode string>", line 1, column 1
did not find expected ',' or '}'
  in "<unicode string>", line 1, column 1027
```

Can be reproduced with:

```python
    @hypothesis.reproduce_failure('4.6.0', b'AXiclZFtCgAgCEO3E3qR7v87IoIcs49gpKJPM5KIKYpeY04Iz10mIt8qtKc2iVexXO6y9cAFN36Vd/CBe5sdb0YYiOqVP1OaEQb6Z3nVIrVeP/iUe+Mz+QA64eUpBw==')
```

in `test_configdata.py` (`TestDict.test_hypothesis`)

**Comment by The-Compiler** [comment]
Another one:

```

___________________________ TestDict.test_hypothesis ___________________________
self = <qutebrowser.config.configtypes.Dict fixed_keys=None keytype=<qutebrowser.config.configtypes.String completions=None e...k=False valid_values=None> none_ok=True required_keys=None valtype=<qutebrowser.config.configtypes.Bool none_ok=False>>
value = '{"\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u...00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0": false}'
    def from_str(self, value: str) -> typing.Optional[typing.Dict]:
        self._basic_str_validation(value)
        if not value:
            return None
    
        try:
>           yaml_val = utils.yaml_load(value)
qutebrowser/config/configtypes.py:1397: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
f = '{"\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u...00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0": false}'
    def yaml_load(f):
        """Wrapper over yaml.load using the C loader if possible."""
        start = datetime.datetime.now()
    
        # WORKAROUND for https://github.com/yaml/pyyaml/pull/181
        with log.ignore_py_warnings(
                category=DeprecationWarning,
                message=r"Using or importing the ABCs from 'collections' instead "
                r"of from 'collections\.abc' is deprecated, and in 3\.8 it will "
                r"stop working"):
>           data = yaml.load(f, Loader=YamlLoader)
qutebrowser/utils/utils.py:669: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
stream = '{"\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u...00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0": false}'
Loader = <class 'yaml.cyaml.CSafeLoader'>
    def load(stream, Loader=None):
        """
        Parse the first YAML document in a stream
        and produce the corresponding Python object.
        """
        if Loader is None:
            load_warning('load')
            Loader = FullLoader
    
        loader = Loader(stream)
        try:
>           return loader.get_single_data()
.tox/py37-pyqt512/lib/python3.7/site-packages/yaml/__init__.py:114: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <yaml.cyaml.CSafeLoader object at 0x72d4168>
    def get_single_data(self):
        # Ensure that the stream contains a single document and construct it.
>       node = self.get_single_node()
.tox/py37-pyqt512/lib/python3.7/site-packages/yaml/constructor.py:41: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
ext/_yaml.pyx:707: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
ext/_yaml.pyx:725: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
ext/_yaml.pyx:776: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
ext/_yaml.pyx:892: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
>   ???
E   yaml.parser.ParserError: while parsing a flow mapping
E     in "<unicode string>", line 1, column 1
E   did not find expected ',' or '}'
E     in "<unicode string>", line 1, column 1030
ext/_yaml.pyx:905: ParserError
During handling of the above exception, another exception occurred:
self = <test_configtypes.TestDict object at 0x7f03034197f0>
klass = <class 'qutebrowser.config.configtypes.Dict'>
    @hypothesis.given(val=strategies.dictionaries(
>       strategies.text(min_size=1, alphabet=strategies.characters(
            # No control characters, surrogates, or codepoints encoded as
            # surrogate
            blacklist_categories=['Cc', 'Cs'], max_codepoint=0xFFFF)),
        strategies.booleans()))
    def test_hypothesis(self, klass, val):
tests/unit/config/test_configtypes.py:1656: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
tests/unit/config/test_configtypes.py:1667: in test_hypothesis
    assert d.from_str(d.to_str(converted)) == expected
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
self = <qutebrowser.config.configtypes.Dict fixed_keys=None keytype=<qutebrowser.config.configtypes.String completions=None e...k=False valid_values=None> none_ok=True required_keys=None valtype=<qutebrowser.config.configtypes.Bool none_ok=False>>
value = '{"\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u...00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0\\u00a0": false}'
    def from_str(self, value: str) -> typing.Optional[typing.Dict]:
        self._basic_str_validation(value)
        if not value:
            return None
    
        try:
            yaml_val = utils.yaml_load(value)
        except yaml.YAMLError as e:
>           raise configexc.ValidationError(value, str(e))
E           qutebrowser.config.configexc.ValidationError: Invalid value '{"\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0\u00a0": false}' - while parsing a flow mapping
E             in "<unicode string>", line 1, column 1
E           did not find expected ',' or '}'
E             in "<unicode string>", line 1, column 1030
qutebrowser/config/configtypes.py:1399: ValidationError
---------------------------------- Hypothesis ----------------------------------
Falsifying example: test_hypothesis(self=<test_configtypes.TestDict at 0x7f03034197f0>, klass=Dict, val={'\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0': False})
You can reproduce this example by temporarily adding @reproduce_failure('4.24.6', b'AXicY2RkZPAfxaN4KGAGBgYAwTc2HQ==') as a decorator on your test case
```
