### ISSUE TITLE
Spawning qute-keepass causes AttributeError

### ISSUE THREAD

**Issue by Knowledge-soda** [qutebrowser/qutebrowser#4613]
**Version info (see `:version`)**:
```
qutebrowser v1.5.2
Git commit: 
Backend: QtWebEngine (Chromium 69.0.3497.128)

CPython: 3.7.2
Qt: 5.12.1
PyQt: 5.12

sip: 4.19.14
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.0.943 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.27.1
QtNetwork SSL: OpenSSL 1.1.1a  20 Nov 2018

Style: QFusionStyle
Platform: Linux-4.20.12-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: /home/jakov/.cache/qutebrowser
config: /home/jakov/.config/qutebrowser
data: /home/jakov/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

Uptime: 0:22:55
```

**Does the bug happen if you start with `--temp-basedir`?** (if applicable): Yes.

**Description**
When I use `:spawn --userscript qute-keepass -p /home/jakov/main.kdb` I get `Userscript exited with status 1, see :messages for details.`.
Error in messages is:
```
Process stderr:
Traceback (most recent call last):
  File "/usr/share/qutebrowser/userscripts/qute-keepass", line 261, in <module>
    sys.exit(run(arguments))
  File "/usr/share/qutebrowser/userscripts/qute-keepass", line 212, in run
    candidates = find_candidates(args, url_host)
  File "/usr/share/qutebrowser/userscripts/qute-keepass", line 182, in find_candidates
    return kp.find_entries(url="{}{}{}".format(".*", host, ".*"), regex=True)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 311, in find_entries
    res = self._find(prefix, entry_xp, path=path, tree=group, **kwargs)
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 216, in _find
    **kwargs
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 141, in _xpath
    tree = self.tree
  File "/usr/lib/python3.7/site-packages/pykeepass/pykeepass.py", line 108, in tree
    return self.kdbx.body.payload.xml
AttributeError: 'NoneType' object has no attribute 'payload'
```

**How to reproduce**
Try to run qute-keepass with KeePassX 0.4.4 database on Arch linux.

**Comment by The-Compiler** [comment]
That seems like an issue with pykeepass (or maybe an incompatibility in file formats since it works for other people, pykeepass says it supports  KDBX3 and KDBX4). Nothing qutebrowser can do here.
