### ISSUE TITLE
RegistryUnavailableError when running :hint as startup command

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#4776]
With `qutebrowser --temp-basedir :hint`:

```
13:57:28 DEBUG    init       app:process_pos_args:287 Startup cmd ':hint'
13:57:28 DEBUG    commands   command:run:535 command called: hint
13:57:28 ERROR    misc       crashsignal:exception_hook:214 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 194, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 143, in run
    init(args, crash_handler)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 185, in init
    _process_args(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 225, in _process_args
    process_pos_args(args.command)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 289, in process_pos_args
    commandrunner.run_safely(cmd[1:])
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 380, in run_safely
    self.run(text, count, safely=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 360, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 548, in run
    posargs, kwargs = self._get_call_args(win_id)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 500, in _get_call_args
    kwargs=kwargs):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 451, in _handle_special_call_arg
    scope=self._scope)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 362, in _get_objreg
    return objreg.get(name, scope=scope, window=win_id, tab=tab_id)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 225, in get
    reg = _get_registry(scope, window, tab)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 212, in _get_registry
    return _get_tab_registry(window, tab)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 174, in _get_tab_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```

**Comment by user202729** [comment]
1. Not sure why someone would want to run this anyway, as the command wouldn't wait for the page to finished loading.
2. Otherwise, how should this issue be fixed? We can wait for the window to be available before running startup commonned, but that would introduce a performance penalty for commands that doesn't require the window. (`:something ;; quit` - if that's useful in any situation)

**Comment by The-Compiler** [comment]
There's `raise cmdutils.CommandError("No WebView available yet!")` in `commands.py` and `hints.py` - I'd expect one of those to be triggered.

**Comment by The-Compiler** [comment]
The same issue also happens when doing something like `:close ;; later 500 message-info foo` and the window is gone by the time the second command is executed.

**Comment by The-Compiler** [comment]
Probably the same as mentioned above:

```
qutebrowser --temp-basedir about:blank ':open -w about:blank' ':later 1000 close' ':later 2000 open -w about:blank'
13:10:22 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/commands/runners.py", line 318, in run_safely
    self.run(text, count, safely=True)
  File "/usr/lib/python3.8/site-packages/qutebrowser/commands/runners.py", line 356, in run
    mode_manager = modeman.instance(self._win_id)
  File "/usr/lib/python3.8/site-packages/qutebrowser/keyinput/modeman.py", line 200, in instance
    mode_manager = objreg.get('mode-manager', scope='window', window=win_id,
  File "/usr/lib/python3.8/site-packages/qutebrowser/utils/objreg.py", line 241, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.8/site-packages/qutebrowser/utils/objreg.py", line 225, in _get_registry
    return _get_window_registry(window)
  File "/usr/lib/python3.8/site-packages/qutebrowser/utils/objreg.py", line 204, in _get_window_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```

**Comment by The-Compiler** [comment]
And another one: `qutebrowser --temp-basedir ":zoom 200"`
