### ISSUE TITLE
Browser window is always started on first work space

### ISSUE THREAD

**Issue by reschl** [qutebrowser/qutebrowser#4829]
**Version info (see `:version`)**:
% qutebrowser --version
qutebrowser v1.6.1
Git commit: 
Backend: QtWebEngine (Chromium 65.0.3325.230)

CPython: 3.7.3
Qt: 5.11.3
PyQt: 5.11.3

sip: 4.19.14
colorama: 0.3.7
pypeg2: 2.15
jinja2: 2.10
pygments: 2.3.1
yaml: 3.13
cssutils: no
attr: 18.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.27.2
QtNetwork SSL: OpenSSL 1.1.1b  26 Feb 2019

Style: QFusionStyle
Platform: Linux-4.19.0-5-amd64-x86_64-with-debian-10.0, 64bit
Linux distribution: Debian GNU/Linux 10 (buster) (debian)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /home/resch/.cache/qutebrowser
config: /home/resch/.config/qutebrowser
data: /home/resch/.local/share/qutebrowser
runtime: /run/user/1000/qutebrowser
system data: /usr/share/qutebrowser

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
When I try to start different browser windows on different workspaces the all end up in workspace 1.

I am not able to reproduce the same behaviour on Ubuntu 18.04 LTS with v1.1.1. Both systems use X11 and i3wm.

**How to reproduce**
From the shell run
```
exec i3-msg "workspace 1; exec qutebrowser --target window --temp-basedir ':fullscreen' ':set statusbar.hide true' ':set window.hide_decoration true' ':set tabs.show multiple' example.com"&
exec i3-msg "workspace 2; exec qutebrowser --target window --temp-basedir ':fullscreen' ':set statusbar.hide true' ':set window.hide_decoration true' ':set tabs.show multiple' example.com"&
exec i3-msg "workspace 3; exec qutebrowser --target window --temp-basedir ':fullscreen' ':set statusbar.hide true' ':set window.hide_decoration true' ':set tabs.show multiple' example.com"&
exec i3-msg "workspace 4; exec qutebrowser --target window --temp-basedir ':fullscreen' ':set statusbar.hide true' ':set window.hide_decoration true' ':set tabs.show multiple' example.com"&
```
Or just try to run qutebrowser from different workspaces.

**Comment by The-Compiler** [comment]
This seems like an issue with your i3 configuration - qutebrowser doesn't know anything about workspaces.

**Comment by reschl** [comment]
My i3 configuration is as is from the debian package. Can you provide any hint on what to look for in the i3 configuration?

**Comment by The-Compiler** [comment]
I haven't used i3 in years, but I'd make sure you don't have any [workspace assignments](https://i3wm.org/docs/userguide.html#assign_workspace) configured which would match on qutebrowser (you wouldn't be the first person where this was the problem :wink:).

**Comment by reschl** [comment]
Unfortunately I don't even have a single `assign` in my i3 configuration or anything about qutebrowser. I will have to check for the differences in the configuration shipped by Ubuntu.

**Comment by The-Compiler** [comment]
No clue then - maybe someone else using i3 has an idea. FWIW there are many qutebrowser users who use i3, and this is the first time I hear about such an issue.

**Comment by reschl** [comment]
After copying config back and forth I just can't reproduce the same behavior outside of Debian testing, but I am also unable to reproduce the same behavior with any other program than qutebrowser in Debian testing.

So, without any hints from more experienced i3 users I think I won't be able to pin this down unfortunately.

**Comment by o-jasper** [comment]
Under files in the man page i looks in this order? `~/.config/i3/config` `~/.i3/config``/etc/xdg/i3/config` (or `$XDG_CONFIG_DIRS/i3/config` if set) or `/etc/i3/config`.

If you haven't customized it, there is the odd chance it's a different config file is taking precedence.

If there are scripts doing i3 ipc, they could move the window.

**Comment by reschl** [comment]
I only have `/etc/i3/config` and `~/.config/i3/config` on my system. Both look the same: [i3.conf.txt](https://github.com/qutebrowser/qutebrowser/files/3358921/i3.conf.txt)

But with the current version of Debian testing I get 2 windows on 2 workspaces with 2 tabs each running the same commands as above and having the same i3 config as before. Slightly different behavior, but still not running as intended.

**Comment by reschl** [comment]
I see that starting on a dedicated workspace is working as expected with the package provided by Ubuntu 18.04 LTS (1.1.1-1ubuntu0.1). Using the version I get from pip3 qutebrowser always starts on the first workspace (v1.6.3). Both with the same i3 config in place.

I see the mouse cursor moving from one workspace to the next. Only the browser windows always appear on the first workspace.

There are 4 basedirs being created in /tmp with both versions. So, there are still 4 independent instances.

System config is the same, including login session. The only difference from `qutebrowser --version` is the version of qutebrowser (full output underneath). To me that looks like the behavior was caused by some change from 1.1.1 to 1.6.3.

Is there a faster way to triage that without giving every version in between a try?

i3 version 4.14.1-1 (Ubuntu package)

pip3 qutebrowser:
```
/usr/local/bin/qutebrowser --basedir=$(pwd) --version
qutebrowser v1.6.3
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.8
Qt: 5.9.5
PyQt: 5.10.1

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.2 LTS (ubuntu)
Frozen: False
Imported from /usr/local/lib/python3.6/dist-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-fs6_3bwl/cache
config: /tmp/qutebrowser-basedir-fs6_3bwl/config
data: /tmp/qutebrowser-basedir-fs6_3bwl/data
runtime: /tmp/qutebrowser-basedir-fs6_3bwl/runtime
system data: /usr/share/qutebrowser
```

Ubuntu qutebrowser:
```
/usr/bin/qutebrowser --basedir=$(pwd) --version
qutebrowser v1.1.1
Git commit: 
Backend: QtWebEngine (Chromium 56.0.2924.122)

CPython: 3.6.8
Qt: 5.9.5
PyQt: 5.10.1

sip: 4.19.7
colorama: no
pypeg2: 2.15
jinja2: 2.10
pygments: 2.2.0
yaml: 3.12
cssutils: no
attr: 17.4.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: no
sqlite: 3.22.0
QtNetwork SSL: OpenSSL 1.1.1  11 Sep 2018

Style: QFusionStyle
Platform: Linux-4.18.0-25-generic-x86_64-with-Ubuntu-18.04-bionic, 64bit
Linux distribution: Ubuntu 18.04.2 LTS (ubuntu)
Frozen: False
Imported from /usr/lib/python3/dist-packages/qutebrowser
Qt library executable path: /usr/lib/x86_64-linux-gnu/qt5/libexec, data path: /usr/share/qt5

Paths:
cache: /tmp/qutebrowser-basedir-7x8p3ec9/cache
config: /tmp/qutebrowser-basedir-7x8p3ec9/config
data: /tmp/qutebrowser-basedir-7x8p3ec9/data
runtime: /tmp/qutebrowser-basedir-7x8p3ec9/runtime
system data: /usr/share/qutebrowser
```

**Comment by toofar** [comment]
> Is there a faster way to triage that without giving every version in between a try?

I can't think of any change in particular that might have changed that, except for maybe https://github.com/qutebrowser/qutebrowser/pull/4072

It shouldn't be too bad with git bisect. You can use a script like:

```shell
#!/bin/sh
rm -r .venv || true
tox -e mkvenv
.venv/bin/python3 -m qutebrowser --temp-basedir
```
Then just close qute and tell git if it was bad or good.

**Comment by reschl** [comment]
Thanks for the hint @toofar 

After about an hour of bisecting git pointed me to https://github.com/qutebrowser/qutebrowser/commit/2d2bdad2ca1e08ee16f16862a3ce11556bc46181 as the first bad commit. Not sure if that really introduced this bug, but it just gave me stack trace:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/qutebrowser.py", line 188, in main
    return app.run(args)
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/app.py", line 101, in run
    configinit.early_init(args)
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/config/configinit.py", line 81, in early_init
    _init_envvars()
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/config/configinit.py", line 93, in _init_envvars
    if config.val.window.hide_wayland_decoration:
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/config/config.py", line 525, in __getattr__
    return self._config.get(name)
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/config/config.py", line 315, in get
    opt = self.get_opt(name)
  File "/home/ngworx/qtbrowser/qutebrowser/qutebrowser/config/config.py", line 311, in get_opt
    raise exception from None
qutebrowser.config.configexc.NoOptionError: No option 'window.hide_wayland_decoration'
```

If that commit does not provide anything useful I can go through bisect again and consider it a good commit.

**Comment by reschl** [comment]
I also tried it without the changes introduced in #4072, but that did not change the behavior.

**Comment by The-Compiler** [comment]
> It shouldn't be too bad with git bisect. You can use a script like: [...]

You won't need to rebuild the virtualenv, it uses the files from the repository. Just do `git bisect good` or `git bisect bad` and test the next version.

> After about an hour of bisecting

That strikes me as odd - you should find the offending commit with 10-20 runs, no?

> Not sure if that really introduced this bug, but it just gave me stack trace:

That seems unrelated. I'd recommend doing `git bisect skip` whenever you have a commit you can't run for unrelated reasons (usually it being broken in some way).

**Comment by reschl** [comment]
> That strikes me as odd - you should find the offending commit with 10-20 runs, no?

Rebuilding the virtualenv was probably the longest time on the machine.

With `git bisect skip` it ends up with the same changes:

There are only 'skip'ped commits left to test.
The first bad commit could be any of:
2d2bdad2ca1e08ee16f16862a3ce11556bc46181
ff299c87a84723864ddea4c11e766a47b0cc671e
We cannot bisect more!

Removing the `':set window.hide_decoration true'` fixes the behavior also in the 1.6.3 release. So, I guess it is related to those changes. Should have tried that earlier m(
