### ISSUE TITLE
Insert mode accepts no typing often.

### ISSUE THREAD

**Issue by mhertz** [qutebrowser/qutebrowser#5005]
To reproduce, press 'o' and enter 'google.com' and it doesn't matter how you enter insert mode i.e. pressing 'i', 'gi' or clicking mouse in messagebox. The result is that there is listed you're in insert mode in the statusbar and the cursor blinks, but no input from typed keys gets populated/shown. The fix I found, was to change to another tab and back again and now insert mode will work as it should, and if not having other tabs open, then I need to make a new tab and delete it for it to work. I have had this issue in very many pages, maybe 50% of the messageboxes roughly. I've only used qutebrowser for two days and love it, thanks alot for "bringing dwb back" and in even improved format. Much respect and thank-you's here from! (Btw, also qutebrowser crashed(exited) on me a few times when going to a youtube page, but haven't happened lately, possibly because of an update which fixed it of one of the backend components.) 

Version/component info follows:

Version info
qutebrowser v1.7.0
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)

CPython: 3.7.4
Qt: 5.13.1 (compiled 5.13.0)
PyQt: 5.13.0

sip: 4.19.18
colorama: no
pypeg2: 2.15
jinja2: 2.10.1
pygments: 2.4.2
yaml: 5.1.2
cssutils: no
attr: 19.1.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebKitWidgets: no
pdf.js: 2.2.228 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.29.0
QtNetwork SSL: OpenSSL 1.1.1c  28 May 2019

Style: QFusionStyle
Platform: Linux-5.2.13-arch1-1-ARCH-x86_64-with-arch, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.7/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Comment by The-Compiler** [comment]
Can you please reproduce this (ideally with `--temp-basedir`) and then do `:report` so I can take a look at the logs?

**Comment by The-Compiler** [comment]
Looks like this is a bug in Qt 5.13.1: [[QTBUG-78126] Keyboard randomly doesn't work in input fields - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-78126)

I'm currently building a debug build so I can find out what's going on... Let's hope there's a workaround in some way!

**Comment by The-Compiler** [comment]
There's a fix in Qt now: [QWidget::setFocusProxy: adjust focus widget properly (I218acf7a) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/273365) - still looking for a workaround...

**Comment by The-Compiler** [comment]
First attempt at a workaround, recycling an earlier one:

```python
diff --git a/qutebrowser/browser/eventfilter.py b/qutebrowser/browser/eventfilter.py
index 0d5d2f887..8c355be78 100644
--- a/qutebrowser/browser/eventfilter.py
+++ b/qutebrowser/browser/eventfilter.py
@@ -57,7 +57,8 @@ class ChildEventFilter(QObject):
             assert obj is self._widget
             child.installEventFilter(self._filter)
 
-            if qtutils.version_check('5.11', compiled=False, exact=True):
+            #if qtutils.version_check('5.11', compiled=False, exact=True):
+            if True:
                 # WORKAROUND for https://bugreports.qt.io/browse/QTBUG-68076
                 pass_modes = [usertypes.KeyMode.command,
                               usertypes.KeyMode.prompt,
@@ -73,7 +74,7 @@ class ChildEventFilter(QObject):
                     except RuntimeError:
                         widget_index = -1
                     if current_index == widget_index:
-                        QTimer.singleShot(0, self._widget.setFocus)
+                        QTimer.singleShot(500, self._focus_workaround)
 
         elif event.type() == QEvent.ChildRemoved:
             child = event.child()
@@ -81,6 +82,10 @@ class ChildEventFilter(QObject):
 
         return False
 
+    def _focus_workaround(self):
+        self._widget.clearFocus()
+        self._widget.setFocus()
+
 
 class TabEventFilter(QObject):
 
```

however, the 500ms wait being needed (100ms isn't enough) tells me this isn't the right place yet...

**Comment by mhertz** [comment]
Thanks alot for your support, i'm much impressed btw! :) The QT fix you stated was added to the qt5-base package in testing-repo of arch-linux(v0.13.2), and upgrading to this fixes the issue completely(haven't updated qutebrowser, i'm just using stable release from the repo's). Thanks again.

I must admit I don't really understand what the above post is about(since my issue is fixed), so i'm not gonna close this issue, and please do it yourself when appropriate, thanks :)

**Comment by The-Compiler** [comment]
Great to hear! I'd like to find a workaround for distributions shipping Qt 5.13.1 without that fix (and so I can ship Windows/macOS builds with Qt 5.13 finally) - I often use issues as a place for notes while working on them, so feel free to disregard the rest! :wink:

**Comment by marrowsuck** [comment]
Thanks for the bug report. I ended up recompiling qt-5.13.1 with the mentioned patch. Everything is working so far.

**Comment by The-Compiler** [comment]
`QWidget::setFocusProxy(QWidget*)` gets called twice on DuckDuckGo. Once here:

```
#0  0x00007ffff2ae41e0 in QWidget::setFocusProxy(QWidget*) (this=this@entry=0x555556483c60, w=w@entry=0x55555aa59b00)
    at kernel/qwidget.cpp:6427
#1  0x00007ffff1aa457b in QWebEngineViewPrivate::widgetChanged(QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget*, QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget*) (this=<optimized out>, oldWidget=<optimized out>, newWidget=0x55555aa59b00)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.13.1/src/webenginewidgets/api/qwebengineview.cpp:112
#2  0x00007fffe4699cb0 in QtWebEngineCore::WebContentsAdapter::initialize(content::SiteInstance*)
    (this=this@entry=0x55555aa4fec0, site=<optimized out>) at /usr/include/c++/9.1.0/bits/unique_ptr.h:357
#3  0x00007fffe469bc0d in QtWebEngineCore::WebContentsAdapter::load(QWebEngineHttpRequest const&)
    (this=this@entry=0x55555aa4fec0, request=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.13.1/src/core/web_contents_adapter.cpp:602
#4  0x00007fffe469ca03 in QtWebEngineCore::WebContentsAdapter::load(QUrl const&) (this=0x55555aa4fec0, url=...)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.13.1/src/core/web_contents_adapter.cpp:593
```

via `qutebrowser/mainwindow/tabbedbrowser.py (510): tabopen` then again here:

```
#0  0x00007ffff2ae41e0 in QWidget::setFocusProxy(QWidget*) (this=this@entry=0x555556483c60, w=w@entry=0x55555bcad2f0) at kernel/qwidget.cpp:6427
#1  0x00007ffff1aa457b in QWebEngineViewPrivate::widgetChanged(QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget*, QtWebEngineCore::RenderWidgetHostViewQtDelegateWidget*) (this=<optimized out>, oldWidget=<optimized out>, newWidget=0x55555bcad2f0)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.13.1/src/webenginewidgets/api/qwebengineview.cpp:112
#2  0x00007fffe6387743 in content::WebContentsImpl::NotifyViewSwapped(content::RenderViewHost*, content::RenderViewHost*) () at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/content/browser/web_contents/web_contents_impl.cc:5083
#3  0x00007fffe6387aa5 in content::WebContentsImpl::NotifySwappedFromRenderManager(content::RenderFrameHost*, content::RenderFrameHost*, bool) ()
    at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/content/browser/web_contents/web_contents_impl.cc:6253
#4  0x00007fffe609ea1b in content::RenderFrameHostManager::CommitPending(std::unique_ptr<content::RenderFrameHostImpl, std::default_delete<content::RenderFrameHostImpl> >) ()
    at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_manager.cc:2283
#5  0x00007fffe60a17a8 in content::RenderFrameHostManager::GetFrameHostForNavigation(content::NavigationRequest const&) () at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/content/browser/frame_host/render_frame_host_manager.cc:646
#6  0x00007fffe60673d0 in content::NavigationRequest::OnResponseStarted(scoped_refptr<network::ResourceResponse> const&, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, content::NavigationDownloadPolicy, bool, base::Optional<content::SubresourceLoaderParams>) ()
    at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/content/browser/frame_host/navigation_request.cc:1152
#7  0x00007fffe614110f in content::NavigationURLLoaderImpl::OnReceiveResponse(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool) () at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/content/browser/loader/navigation_url_loader_impl.cc:1786
#8  0x00007fffe61417cd in base::internal::FunctorTraits<void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), void>::Invoke<void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), base::WeakPtr<content::NavigationURLLoaderImpl>, scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID, bool, bool>(void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), base::WeakPtr<content::NavigationURLLoaderImpl>&&, scoped_refptr<network::ResourceResponse>&&, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>&&, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >&&, content::GlobalRequestID&&, bool&&, bool&&) ()
    at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/bind_internal.h:516
#9  0x00007fffe61417cd in base::internal::InvokeHelper<true, void>::MakeItSo<void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), base::WeakPtr<content::NavigationURLLoaderImpl>, scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID, bool, bool>(void (content::NavigationURLLoaderImpl::*&&)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), base::WeakPtr<content::NavigationURLLoaderImpl>&&, scoped_refptr<network::ResourceResponse>&&, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>&&, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >&&, content::GlobalRequestID&&, bool&&, bool&&) ()
    at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/bind_internal.h:636
#10 0x00007fffe61417cd in base::internal::Invoker<base::internal::BindState<void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), base::WeakPtr<content::NavigationURLLoaderImpl>, scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID, bool, bool>, void ()>::RunImpl<void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), std::tuple<base::WeakPtr<content::NavigationURLLoaderImpl>, scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID, bool, bool>, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>(void (content::NavigationURLLoaderImpl::*&&)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), std::tuple<base::WeakPtr<content::NavigationURLLoaderImpl>, scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID, bool, bool>&&, std::integer_sequence<unsigned long, 0ul, 1ul, 2ul, 3ul, 4ul, 5ul, 6ul>) () at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/bind_internal.h:690
#11 0x00007fffe61417cd in base::internal::Invoker<base::internal::BindState<void (content::NavigationURLLoaderImpl::*)(scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID const&, bool, bool), base::WeakPtr<content::NavigationURLLoaderImpl>, scoped_refptr<network::ResourceResponse>, mojo::StructPtr<network::mojom::URLLoaderClientEndpoints>, std::unique_ptr<content::NavigationData, std::default_delete<content::NavigationData> >, content::GlobalRequestID, bool, bool>, void ()>::RunOnce(base::internal::BindStateBase*) ()
    at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/bind_internal.h:658
#12 0x00007fffe69ee73b in base::OnceCallback<void ()>::Run() && () at ../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/callback.h:99
#13 0x00007fffe69ee73b in base::debug::TaskAnnotator::RunTask(char const*, base::PendingTask*) () at ./../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/debug/task_annotator.cc:105
#14 0x00007fffe6954c27 in base::MessageLoopImpl::RunTask(base::PendingTask*) () at ./../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/message_loop/message_loop_impl.cc:355
#15 0x00007fffe695590e in base::MessageLoopImpl::DeferOrRunPendingTask(base::PendingTask) () at ./../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/message_loop/message_loop_impl.cc:366
#16 0x00007fffe6955e6c in base::MessageLoopImpl::DoWork() () at ./../../../../qtwebengine-everywhere-src-5.13.1/src/3rdparty/chromium/base/message_loop/message_loop_impl.cc:458
#17 0x00007fffe460d273 in QtWebEngineCore::MessagePumpForUIQt::handleScheduledWork() (this=0x5555564c3eb0) at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.13.1/src/core/browser_main_parts_qt.cpp:197
#18 0x00007fffe460d273 in QtWebEngineCore::MessagePumpForUIQt::MessagePumpForUIQt()::{lambda()#1}::operator()() const (__closure=<optimized out>)
    at /tmp/makepkg/qt5-webengine-debug/src/qtwebengine-everywhere-src-5.13.1/src/core/browser_main_parts_qt.cpp:114
#19 0x00007fffe460d273 in std::_Function_handler<void (), QtWebEngineCore::MessagePumpForUIQt::MessagePumpForUIQt()::{lambda()#1}>::_M_invoke(std::_Any_data const&) (__functor=...) at /usr/include/c++/9.1.0/bits/std_function.h:300
#20 0x00007ffff5fb33e5 in QObject::event(QEvent*) (this=0x5555564c3ec0, e=<optimized out>) at kernel/qobject.cpp:1282
#21 0x00007ffff2ab84f5 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555c53bb0, receiver=receiver@entry=0x5555564c3ec0, e=e@entry=0x7fffa4157bf0) at kernel/qapplication.cpp:3703
#22 0x00007ffff2ac1e11 in QApplication::notify(QObject*, QEvent*) (this=0x555555e0e170, receiver=0x5555564c3ec0, e=0x7fffa4157bf0) at kernel/qapplication.cpp:3449
#23 0x00007ffff31be769 in sipQApplication::notify(QObject*, QEvent*) (this=0x555555e0e170, a0=0x5555564c3ec0, a1=0x7fffa4157bf0) at sipQtWidgetsQApplication.cpp:238
#24 0x00007ffff5f869c2 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5555564c3ec0, event=0x7fffa4157bf0) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:143
#25 0x00007ffff5f89739 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x5555556d8d40) at kernel/qcoreapplication.cpp:1840
#26 0x00007ffff5fdf404 in postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x555555f13060) at kernel/qeventdispatcher_glib.cpp:277
#27 0x00007ffff67e53ae in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff67e71c1 in  () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff67e7201 in g_main_context_iteration () at /usr/lib/libglib-2.0.so.0
#30 0x00007ffff5fdea03 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555555dd0fc0, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#31 0x00007ffff5f854ec in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=this@entry=0x7fffffffcce0, flags=..., flags@entry=...) at ../../include/QtCore/../../src/corelib/global/qflags.h:140
```

from the Qt mainloop. Apparently in response to a timer event?

```
(gdb) frame 21
#21 0x00007ffff2ab84f5 in QApplicationPrivate::notify_helper (this=this@entry=0x555555c53bb0, receiver=receiver@entry=0x5555564c3ec0, e=e@entry=0x7fffa4157bf0) at kernel/qapplication.cpp:3703
(gdb) print e->type()
$3 = QEvent::Timer
```

**Comment by The-Compiler** [comment]
Test script:

```python
import sys
import argparse
import logging

from PyQt5.QtCore import QUrl, QObject, QEvent
from PyQt5.QtWidgets import QApplication
from PyQt5.QtWebEngineWidgets import QWebEngineView, QWebEnginePage

from qutebrowser.utils import debug


class ShowEventFilter(QObject):

    def eventFilter(self, obj, event):
        typ = debug.qenum_key(QEvent, event.type())
        if event.type() != QEvent.Timer:
            print(f"sub {event.__class__.__name__} {typ} -> {obj}")
            #if isinstance(obj, QWebEngineView):
            #    obj.clearFocus()
            #    obj.setFocus()
        return False


class EventFilter(QObject):

    def __init__(self, parent=None):
        super().__init__(parent)
        self.ev2 = ShowEventFilter()

    def eventFilter(self, obj, event):
        typ = debug.qenum_key(QEvent, event.type())
        if event.type() == QEvent.ChildAdded:
            print(f"!!! {event.__class__.__name__} {typ} -> {obj}")
            obj.installEventFilter(self.ev2)
        elif event.type() == QEvent.Timer:
            print(f"{event.__class__.__name__} {typ} -> {obj}")
        return False


def parse_args():
    """Parse commandline arguments."""
    parser = argparse.ArgumentParser()
    parser.add_argument('url', help='The URL to open')
    return parser.parse_known_args()[0]


class Page(QWebEnginePage):

    def acceptNavigationRequest(self, url, typ, mainframe):
        print(f"{url} {typ}")
        return True


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)
    args = parse_args()

    app = QApplication(sys.argv)
    ev = EventFilter()
    #app.installEventFilter(ev)

    wv = QWebEngineView()
    wv.installEventFilter(ev)
    page = Page()
    wv.setPage(page)
    #debug.log_signals(wv)

    wv.loadStarted.connect(lambda: print("Loading started"))
    wv.loadProgress.connect(lambda p: print("Loading progress: {}%".format(p)))
    wv.loadFinished.connect(lambda: print("Loading finished"))

    breakpoint()

    wv.load(QUrl.fromUserInput(args.url))
    wv.show()

    app.exec_()
```

logged events:

```
!!! QChildEvent ChildAdded -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QChildEvent ChildPolished -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent LayoutRequest -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
Loading progress: 20%

Thread 1 "python3" hit Breakpoint 1, 0x00007ffff328af00 in QWidget::setFocusProxy(QWidget*) () from /home/florian/code/qt/bin/5.13.1/gcc_64/lib/libQt5Widgets.so.5
(gdb) c
Continuing.
sub QKeyEvent ShortcutOverride -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent LayoutRequest -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent UpdateLater -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent UpdateRequest -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent UpdateRequest -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
Loading progress: 70%
sub QInputMethodQueryEvent InputMethodQuery -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QChildEvent ChildRemoved -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent UpdateRequest -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent UpdateRequest -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
sub QEvent WindowDeactivate -> <PyQt5.QtWebEngineWidgets.QWebEngineView object at 0x7fffe701f690>
```

**Comment by The-Compiler** [comment]
I'm giving up with this - after some hours of trying, I can't find a reliable workaround for the bug. I can ship macOS/Windows with Qt 5.13.0 but QtWebEngine 5.13.1 (and that's what I'm going to do) and Archlinux has the bug patched already.

FWIW, it looks like Qt 5.13.2 should be released mid October (week 42 or so).

**Comment by andys8** [comment]
I'm experiencing this issue with 1.8.1 and  QtWebEngine (Chromium 73.0.3683.105). E.g. with Microsoft Teams. Is it meant to be fixed?

**Comment by The-Compiler** [comment]
@andys8 this issue was fixed in Qt 5.13.2, it can't be fixed in qutebrowser.

**Comment by andys8** [comment]
That's the version I'm currently using.

```
CPython: 3.6.9
Qt: 5.13.2
PyQt: 5.13.2
```

**Comment by The-Compiler** [comment]
@andys8 Then you probably aren't seeing this issue. Can you open a new issue with some more information about what you're doing exactly and what happens?

**Comment by andys8** [comment]
I'll try to find a reproducible case. Thanks
