### ISSUE TITLE
Refactor debug-flags handling

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5016]
Currently debug flags are just strings, which means handling them is quite error prone.

I started something:

```diff
commit 668871f9e652e3c408d7569b6e695f5dd42e970c
Author: Florian Bruhin <me@the-compiler.org>
Date:   Fri Sep 13 15:24:18 2019 +0200

    Use an enum type for debug flags

diff --git a/qutebrowser/app.py b/qutebrowser/app.py
index cf35f918f..234110f10 100644
--- a/qutebrowser/app.py
+++ b/qutebrowser/app.py
@@ -863,7 +863,7 @@ class Application(QApplication):
     def exit(self, status):
         """Extend QApplication::exit to log the event."""
         log.destroy.debug("Now calling QApplication::exit.")
-        if 'debug-exit' in objects.debug_flags:
+        if usertypes.DebugFlag.debug_exit in objects.debug_flags:
             if hunter is None:
                 print("Not logging late shutdown because hunter could not be "
                       "imported!", file=sys.stderr)
diff --git a/qutebrowser/browser/browsertab.py b/qutebrowser/browser/browsertab.py
index 10f430e34..4f9977d6e 100644
--- a/qutebrowser/browser/browsertab.py
+++ b/qutebrowser/browser/browsertab.py
@@ -528,7 +528,7 @@ class AbstractScroller(QObject):
         super().__init__(parent)
         self._tab = tab
         self._widget = None  # type: typing.Optional[QWidget]
-        if 'log-scroll-pos' in objects.debug_flags:
+        if usertypes.DebugFlag.log_scroll_pos in objects.debug_flags:
             self.perc_changed.connect(self._log_scroll_pos_change)
 
     @pyqtSlot()
diff --git a/qutebrowser/browser/webengine/interceptor.py b/qutebrowser/browser/webengine/interceptor.py
index 47edabda8..fe1aa2b27 100644
--- a/qutebrowser/browser/webengine/interceptor.py
+++ b/qutebrowser/browser/webengine/interceptor.py
@@ -27,7 +27,7 @@ from PyQt5.QtWebEngineCore import (QWebEngineUrlRequestInterceptor,
 
 from qutebrowser.config import config
 from qutebrowser.browser import shared
-from qutebrowser.utils import utils, log, debug, qtutils
+from qutebrowser.utils import utils, log, debug, qtutils, usertypes
 from qutebrowser.extensions import interceptors
 from qutebrowser.misc import objects
 
@@ -133,7 +133,7 @@ class RequestInterceptor(QWebEngineUrlRequestInterceptor):
         Args:
             info: QWebEngineUrlRequestInfo &info
         """
-        if 'log-requests' in objects.debug_flags:
+        if usertypes.DebugFlag.log_requests in objects.debug_flags:
             resource_type = debug.qenum_key(QWebEngineUrlRequestInfo,
                                             info.resourceType())
             navigation_type = debug.qenum_key(QWebEngineUrlRequestInfo,
diff --git a/qutebrowser/browser/webengine/webenginetab.py b/qutebrowser/browser/webengine/webenginetab.py
index fc11b75a5..50fcdb9e5 100644
--- a/qutebrowser/browser/webengine/webenginetab.py
+++ b/qutebrowser/browser/webengine/webenginetab.py
@@ -475,7 +475,8 @@ class WebEngineScroller(browsertab.AbstractScroller):
         self._at_bottom = math.ceil(pos.y()) >= scrollable_y
 
         if (self._pos_perc != (perc_x, perc_y) or
-                'no-scroll-filtering' in objects.debug_flags):
+                usertypes.DebugFlag.no_scroll_filtering in
+                objects.debug_flags):
             self._pos_perc = perc_x, perc_y
             self.perc_changed.emit(*self._pos_perc)
 
diff --git a/qutebrowser/browser/webengine/webview.py b/qutebrowser/browser/webengine/webview.py
index faa26cdf9..6c3357ac4 100644
--- a/qutebrowser/browser/webengine/webview.py
+++ b/qutebrowser/browser/webengine/webview.py
@@ -68,7 +68,7 @@ class WebEngineView(QWebEngineView):
 
         This got introduced in Qt 5.11.0 and fixed in 5.12.0.
         """
-        if 'lost-focusproxy' not in objects.debug_flags:
+        if usertypes.DebugFlag.lost_focusproxy not in objects.debug_flags:
             proxy = self.focusProxy()
             if proxy is not None:
                 return proxy
diff --git a/qutebrowser/browser/webkit/network/networkmanager.py b/qutebrowser/browser/webkit/network/networkmanager.py
index 46abd5cf2..43475e184 100644
--- a/qutebrowser/browser/webkit/network/networkmanager.py
+++ b/qutebrowser/browser/webkit/network/networkmanager.py
@@ -412,7 +412,7 @@ class NetworkManager(QNetworkAccessManager):
                 req, HOSTBLOCK_ERROR_STRING, QNetworkReply.ContentAccessDenied,
                 self)
 
-        if 'log-requests' in objects.debug_flags:
+        if usertypes.DebugFlag.log_requests in objects.debug_flags:
             operation = debug.qenum_key(QNetworkAccessManager, op)
             operation = operation.replace('Operation', '').upper()
             log.webview.debug("{} {}, first-party {}".format(
diff --git a/qutebrowser/config/configinit.py b/qutebrowser/config/configinit.py
index 74c07e3ab..67e467846 100644
--- a/qutebrowser/config/configinit.py
+++ b/qutebrowser/config/configinit.py
@@ -194,15 +194,15 @@ def _qtwebengine_args(namespace: argparse.Namespace) -> typing.Iterator[str]:
     # also see:
     # https://codereview.qt-project.org/c/qt/qtwebengine-chromium/+/265753
     if qtutils.version_check('5.12.3', compiled=False):
-        if 'stack' in namespace.debug_flags:
+        if usertypes.DebugFlag.stack in namespace.debug_flags:
             # Only actually available in Qt 5.12.5, but let's save another
             # check, as passing the option won't hurt.
             yield '--enable-in-process-stack-traces'
     else:
-        if 'stack' not in namespace.debug_flags:
+        if usertypes.DebugFlag.stack not in namespace.debug_flags:
             yield '--disable-in-process-stack-traces'
 
-    if 'chromium' in namespace.debug_flags:
+    if usertypes.DebugFlag.chromium in namespace.debug_flags:
         yield '--enable-logging'
         yield '--v=1'
 
diff --git a/qutebrowser/misc/crashsignal.py b/qutebrowser/misc/crashsignal.py
index 9d98d2a34..c2726c571 100644
--- a/qutebrowser/misc/crashsignal.py
+++ b/qutebrowser/misc/crashsignal.py
@@ -221,11 +221,13 @@ class CrashHandler(QObject):
 
         is_ignored_exception = (exctype is bdb.BdbQuit or
                                 not issubclass(exctype, Exception))
+        pdb_post_mortem = (usertypes.DebugFlag.pdb_postmortem in
+                           objects.debug_flags)
 
-        if 'pdb-postmortem' in objects.debug_flags:
+        if pdb_post_mortem:
             pdb.post_mortem(tb)
 
-        if is_ignored_exception or 'pdb-postmortem' in objects.debug_flags:
+        if is_ignored_exception or pdb_post_mortem:
             # pdb exit, KeyboardInterrupt, ...
             sys.exit(usertypes.Exit.exception)
 
diff --git a/qutebrowser/misc/objects.py b/qutebrowser/misc/objects.py
index e2885ca22..d90909fd7 100644
--- a/qutebrowser/misc/objects.py
+++ b/qutebrowser/misc/objects.py
@@ -39,4 +39,4 @@ class NoBackend:
 
 backend = NoBackend()  # type: typing.Union[usertypes.Backend, NoBackend]
 commands = {}  # type: typing.Dict[str, command.Command]
-debug_flags = set()  # type: typing.Set[str]
+debug_flags = set()  # type: typing.Set[usertypes.DebugFlag]
diff --git a/qutebrowser/qutebrowser.py b/qutebrowser/qutebrowser.py
index 05fdd8878..7961c682c 100644
--- a/qutebrowser/qutebrowser.py
+++ b/qutebrowser/qutebrowser.py
@@ -53,9 +53,25 @@ except ImportError:
 check_python_version()
 
 import argparse  # pylint: disable=wrong-import-order
+import enum
 from qutebrowser.misc import earlyinit
 
 
+class DebugFlag(enum.Enum):
+
+    """A possible --debug-flag argument."""
+
+    debug_exit = 1  #: Turn on debugging of late exit.
+    pdb_postmortem = 2  #: Drop into pdb on exceptions.
+    no_sql_history = 3  #: Don't store history items.
+    no_scroll_filtering = 4  #: Process all scrolling updates.
+    log_requests = 5  #: Log all network requests.
+    log_scroll_pos = 6  #: Log all scrolling changes.
+    lost_focusproxy = 7  #: Simulate a lost focusProxy
+    stack = 8  #: Enable Chromium stack logging.
+    chromium = 9  #: Enable Chromium logging.
+
+
 def get_argparser():
     """Get the argparse parser."""
     parser = argparse.ArgumentParser(prog='qutebrowser',
@@ -127,7 +143,7 @@ def get_argparser():
                        action='append')
     debug.add_argument('--qt-flag', help="Pass an argument to Qt as flag.",
                        nargs=1, action='append')
-    debug.add_argument('-D', '--debug-flag', type=debug_flag_error,
+    debug.add_argument('-D', '--debug-flag', type=get_debug_flag,
                        default=[], help="Pass name of debugging feature to be"
                        " turned on.", action='append', dest='debug_flags')
     parser.add_argument('command', nargs='*', help="Commands to execute on "
@@ -158,26 +174,12 @@ def logfilter_error(logfilter):
                 logfilter, ', '.join(log.LOGGER_NAMES)))
 
 
-def debug_flag_error(flag):
-    """Validate flags passed to --debug-flag.
-
-    Available flags:
-        debug-exit: Turn on debugging of late exit.
-        pdb-postmortem: Drop into pdb on exceptions.
-        no-sql-history: Don't store history items.
-        no-scroll-filtering: Process all scrolling updates.
-        log-requests: Log all network requests.
-        log-scroll-pos: Log all scrolling changes.
-        stack: Enable Chromium stack logging.
-        chromium: Enable Chromium logging.
-    """
-    valid_flags = ['debug-exit', 'pdb-postmortem', 'no-sql-history',
-                   'no-scroll-filtering', 'log-requests', 'lost-focusproxy',
-                   'log-scroll-pos', 'stack', 'chromium']
-
-    if flag in valid_flags:
-        return flag
-    else:
+def get_debug_flag(flag):
+    """Validate/convert flags passed to --debug-flag."""
+    try:
+        return DebugFlag[flag.replace('-', '_')]
+    except KeyError:
+        valid_flags = [flag.name.replace('_', '-') for flag in DebugFlag]
         raise argparse.ArgumentTypeError("Invalid debug flag - valid flags: {}"
                                          .format(', '.join(valid_flags)))
 
diff --git a/qutebrowser/utils/usertypes.py b/qutebrowser/utils/usertypes.py
index 0bb7badc8..91472ee01 100644
--- a/qutebrowser/utils/usertypes.py
+++ b/qutebrowser/utils/usertypes.py
@@ -31,6 +31,7 @@ import attr
 from PyQt5.QtCore import pyqtSignal, pyqtSlot, QObject, QTimer
 
 from qutebrowser.utils import log, qtutils, utils
+from qutebrowser.qutebrowser import DebugFlag  # pylint: disable=unused-import
 
 
 _UNSET = object()
diff --git a/tests/end2end/features/test_history_bdd.py b/tests/end2end/features/test_history_bdd.py
index 44f64991e..aaaaf4ce4 100644
--- a/tests/end2end/features/test_history_bdd.py
+++ b/tests/end2end/features/test_history_bdd.py
@@ -30,7 +30,8 @@ bdd.scenarios('history.feature')
 @pytest.fixture(autouse=True)
 def turn_on_sql_history(quteproc):
     """Make sure SQL writing is enabled for tests in this module."""
-    cmd = ":debug-pyeval objects.debug_flags.remove('no-sql-history')"
+    cmd = (":debug-pyeval objects.debug_flags.remove("
+           "usertypes.DebugFlag.no_sql_history)")
     quteproc.send_cmd(cmd)
     quteproc.wait_for_load_finished_url('qute://pyeval')
 
diff --git a/tests/end2end/fixtures/quteprocess.py b/tests/end2end/fixtures/quteprocess.py
index c0a00624a..07474910d 100644
--- a/tests/end2end/fixtures/quteprocess.py
+++ b/tests/end2end/fixtures/quteprocess.py
@@ -874,10 +874,11 @@ class QuteProc(testprocess.Process):
 
     def turn_on_scroll_logging(self, no_scroll_filtering=False):
         """Make sure all scrolling changes are logged."""
-        cmd = ":debug-pyeval -q objects.debug_flags.add('{}')"
+        cmd = (":debug-pyeval -q objects.debug_flags.add("
+               "usertypes.DebugFlag.{})")
         if no_scroll_filtering:
-            self.send_cmd(cmd.format('no-scroll-filtering'))
-        self.send_cmd(cmd.format('log-scroll-pos'))
+            self.send_cmd(cmd.format('no_scroll_filtering'))
+        self.send_cmd(cmd.format('log_scroll_pos'))
 
 
 class YamlLoader(yaml.SafeLoader):
diff --git a/tests/unit/browser/test_history.py b/tests/unit/browser/test_history.py
index 87984f1a5..68f2ab445 100644
--- a/tests/unit/browser/test_history.py
+++ b/tests/unit/browser/test_history.py
@@ -171,7 +171,8 @@ class TestAdd:
             assert list(web_history.completion) == expected
 
     def test_no_sql_web_history(self, web_history, monkeypatch):
-        monkeypatch.setattr(objects, 'debug_flags', {'no-sql-history'})
+        monkeypatch.setattr(objects, 'debug_flags',
+                            {usertypes.DebugFlag.no_sql_history})
         web_history.add_url(QUrl('https://www.example.com/'), atime=12346,
                             title='Hello World', redirect=False)
         assert not list(web_history)
```

but it leads to circular imports:

```
INVALID: Traceback (most recent call last):
INVALID:   File "/usr/lib64/python3.7/runpy.py", line 193, in _run_module_as_main
INVALID:     "__main__", mod_spec)
INVALID:   File "/usr/lib64/python3.7/runpy.py", line 85, in _run_code
INVALID:     exec(code, run_globals)
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
INVALID:     sys.exit(qutebrowser.qutebrowser.main())
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 199, in main
INVALID:     # We do this imports late as earlyinit needs to be run first (because of
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 62, in <module>
INVALID:     from qutebrowser.completion.models import miscmodels
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/completion/models/miscmodels.py", line 24, in <module>
INVALID:     from qutebrowser.config import configdata
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configdata.py", line 32, in <module>
INVALID:     from qutebrowser.config import configtypes
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configtypes.py", line 64, in <module>
INVALID:     from qutebrowser.config import configexc, configutils
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configexc.py", line 25, in <module>
INVALID:     from qutebrowser.utils import jinja, usertypes, log
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/jinja.py", line 33, in <module>
INVALID:     from qutebrowser.utils import utils, urlutils, log, qtutils, javascript
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/utils.py", line 54, in <module>
INVALID:     from qutebrowser.utils import qtutils, log
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/qtutils.py", line 48, in <module>
INVALID:     from qutebrowser.utils import usertypes
INVALID:   File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/usertypes.py", line 34, in <module>
INVALID:     from qutebrowser.qutebrowser import DebugFlag  # pylint: disable=unused-import
INVALID: ImportError: cannot import name 'DebugFlag' from 'qutebrowser.qutebrowser' (/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py)
```

also, it's not really nice syntactically. Ideally, we'd have an object where we could just do e.g. `if objects.debug_flags.no_sql_history:` instead.

**Comment by user202729** [comment]
Perhaps you can do something like this?

```
class DebugFlags:
  __slots__ = 'no_sql_history', 'etc'
  def __init__(self):
    for x in DebugFlags.__slots__: setattr(self, x, False)

debug_flags = DebugFlags()

# set property
debug_flags.no_sql_history = True
```

Which will
