### ISSUE TITLE
Test new PyQt5 exit scheme

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5017]
PyQt5 5.13.1 adds support for a new exit/cleanup logic via `QtCore.pyqt5_enable_new_onexit_scheme(True)`.

At my request, it was disabled by default because it caused various new exit issues with qutebrowser. I should investigate what's going on exactly and fix/report issues.

**Comment by The-Compiler** [comment]
FWIW this is needed on Windows with Qt 5.13 to avoid segfaults on exit.

**Comment by The-Compiler** [comment]
We still get an abort on exit when enabling it for tests, but at least we get a stacktrace now!

```
================================== 8168 passed, 258 skipped, 71 xfailed in 937.44s (0:15:37) ==================================
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 297, in delete
    reg = _get_registry(scope, window, tab)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 227, in _get_registry
    return _get_window_registry(window)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/objreg.py", line 206, in _get_window_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
Fatal Python error: Aborted

Current thread 0x00007f6f84967740 (most recent call first):
<no Python frame>
ERROR: InvocationError for command /home/florian/proj/qutebrowser/git/.tox/py38/bin/python -bb -m pytest --qute-bdd-webengine (exited with code -6 (SIGABRT)) (exited with code -6)
```

**Comment by The-Compiler** [comment]
Looks like *something* calls `objreg.delete('keyparsers', scope='window', window=0)` but `window_registry` is empty already.

Probably this in `modeman.init()`:

```python
    modeman.destroyed.connect(  # type: ignore
        functools.partial(objreg.delete, 'keyparsers', scope='window',
                          window=win_id))
```

added in e6fe358d73f397711d3a4c81e5dd764e877f385c.
