### ISSUE TITLE
dictcli.py - TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'

### ISSUE THREAD

**Issue by Eluminae** [qutebrowser/qutebrowser#5029]
**Version info (see `:version`)**:

https://paste.the-compiler.org/view/5ecbb88e

**Description**

I got a problem with the dictcli.py userscript on voidlinux 

**How to reproduce**

:spawn --userscript dictcli.py install something

```
Process stderr:
Found a dictionary with a malformed name: sh-3-0
Found a dictionary with a malformed name: sh-4-0
Traceback (most recent call last):
  File "/home/reed/.local/share/qutebrowser/userscripts/dictcli.py", line 284, in <module>
    main()
  File "/home/reed/.local/share/qutebrowser/userscripts/dictcli.py", line 267, in main
    languages = available_languages()
  File "/home/reed/.local/share/qutebrowser/userscripts/dictcli.py", line 181, in available_languages
    if latest_yet(code2file, code, filename):
  File "/home/reed/.local/share/qutebrowser/userscripts/dictcli.py", line 172, in latest_yet
    return spell.version(code2file[code]) < spell.version(filename)
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

**Comment by The-Compiler** [comment]
This is already fixed, see #4987.
