### ISSUE TITLE
FileNotFoundError with :print --pdf {url}.pdf

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5160]
```
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 318, in run_safely
    self.run(text, count, safely=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/runners.py", line 373, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/commands/command.py", line 557, in run
    self.handler(*posargs, **kwargs)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/components/misccommands.py", line 112, in printpage
    _print_pdf(tab, pdf)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/components/misccommands.py", line 87, in _print_pdf
    os.mkdir(directory)
FileNotFoundError: [Errno 2] No such file or directory: 'https://www.reddit.com/r/qutebrowser/comments/e3mcwy/automatically_print_to_pdf'
```

**Comment by user202729** [comment]
```diff
--- a/qutebrowser/components/misccommands.py
+++ b/qutebrowser/components/misccommands.py
@@ -83,8 +83,11 @@ def _print_pdf(tab: apitypes.Tab, filename: str) -> None:
     tab.printing.check_pdf_support()
     filename = os.path.expanduser(filename)
     directory = os.path.dirname(filename)
-    if directory and not os.path.exists(directory):
-        os.mkdir(directory)
+    if directory:
+        try:
+            os.makedirs(os.path.normpath(directory), exist_ok=True)
+        except FileExistsError:
+            return # what to do here?
     tab.printing.to_pdf(filename)
     logging.getLogger('misc').debug("Print to file: {}".format(filename))
 ```

It's still possible that there's a file with the name being the same as the directory.

**Comment by The-Compiler** [comment]
We should handle other `OSError` exceptions there too, and show an error in the UI. Another one, with `:print --pdf /foo`:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qutebrowser/commands/runners.py", line 130, in run_safely
    self.run(text, count, safely=True)
  File "/usr/lib/python3.10/site-packages/qutebrowser/commands/runners.py", line 188, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.10/site-packages/qutebrowser/commands/command.py", line 551, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.10/site-packages/qutebrowser/components/misccommands.py", line 125, in printpage
    _print_pdf(tab, pdf)
  File "/usr/lib/python3.10/site-packages/qutebrowser/components/misccommands.py", line 100, in _print_pdf
    os.mkdir(directory)
PermissionError: [Errno 13] Permission denied: '/foo'
```
