### ISSUE TITLE
Qt 5.14: Segfault in QStyleSheetStyle on exit with smoke test

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5187]
On both Linux and Windows, this segfaults: `python3 -m qutebrowser --temp-basedir --nowindow --debug about:blank ':later 500 quit'`

```
11:01:27 DEBUG    init       app:process_pos_args:299 Startup cmd ':later 500 quit'
11:01:27 DEBUG    commands   command:run:541 command called: later ['500', 'quit']
11:01:27 DEBUG    commands   command:run:555 Calling qutebrowser.misc.utilcmds.later(500, 'quit', 0)
11:01:27 DEBUG    init       app:_process_args:243 Init finished after 1.2268s
11:01:27 DEBUG    init       app:init:199 Init done!
11:01:27 DEBUG    webview    browsertab:_set_load_status:927 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='about:blank'>: LoadStatus.loading
11:01:27 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 0)
11:01:27 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 0)
11:01:27 DEBUG    webview    tabbedbrowser:_on_title_changed:748 Changing title for idx 0 to 'about:blank'
11:01:28 DEBUG    webview    browsertab:_set_load_status:927 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='about:blank'>: LoadStatus.success
11:01:28 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.success: 2>) (tab 0)
11:01:28 DEBUG    sql        sql:__init__:183 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
11:01:28 DEBUG    sql        sql:run:215 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
11:01:28 DEBUG    sql        sql:run:219 query bindings: {':atime': 1578823288, ':redirect': False, ':title': 'about:blank', ':url': 'about:blank'}
11:01:28 DEBUG    sql        sql:__init__:183 Preparing SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
11:01:28 DEBUG    sql        sql:run:215 Running SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
11:01:28 DEBUG    sql        sql:run:219 query bindings: {':last_atime': 1578823288, ':title': 'about:blank', ':url': 'about:blank'}
11:01:28 DEBUG    sessions   sessions:save:305 Saving session _autosave to /tmp/qutebrowser-basedir-lvm9amcz/data/sessions/_autosave.yml...
11:01:28 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab 0)
11:01:28 DEBUG    modes      modeman:leave:377 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
11:01:28 DEBUG    modes      modeman:leave:377 Ignoring leave request for KeyMode.hint (reason load started) as we're in mode KeyMode.normal
11:01:28 DEBUG    commands   command:run:541 command called: quit
11:01:28 DEBUG    commands   argparser:multitype_conv:158 Trying to parse None as <class 'qutebrowser.misc.sessions.Sentinel'>
11:01:28 DEBUG    commands   command:run:555 Calling qutebrowser.app.Quitter.quit(<qutebrowser.app.Quitter object at 0x7fb6b93cc5e0>, False, None)
11:01:28 DEBUG    destroy    app:shutdown:720 Shutting down with status 0, session None...
11:01:28 DEBUG    prompt     prompt:shutdown:139 Shutting down with loops []
11:01:28 DEBUG    destroy    app:_shutdown:749 Stage 2 of shutting down...
11:01:28 DEBUG    ipc        ipc:shutdown:403 Shutting down IPC (socket 0x7fb6bf27ba00)
11:01:28 DEBUG    save       savemanager:save:94 Save of yaml-config requested - dirty False, save_on_exit False, is_exit True, force False -> False
11:01:28 DEBUG    save       savemanager:save:94 Save of state-config requested - dirty False, save_on_exit True, is_exit True, force False -> True
11:01:28 DEBUG    save       savemanager:save:94 Save of command-history requested - dirty False, save_on_exit False, is_exit True, force False -> False
11:01:28 DEBUG    save       savemanager:save:94 Save of quickmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
11:01:28 DEBUG    save       savemanager:save:94 Save of bookmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
11:01:28 DEBUG    save       savemanager:save:94 Save of cookies requested - dirty False, save_on_exit False, is_exit True, force False -> False
11:01:28 DEBUG    destroy    app:_shutdown:764 Deferring QApplication::exit...
11:01:28 DEBUG    destroy    app:exit:828 Now calling QApplication::exit.
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: download-model
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: quitter
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: command-history
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: 0
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: main-window
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: last-focused-main-window
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: last-visible-main-window
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: message-bridge
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: tabbed-browser
11:01:28 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: status-command
Fatal Python error: Segmentation fault

Current thread 0x00007fb6bedb5740 (most recent call first):
<no Python frame>
[1]    303975 segmentation fault (core dumped)  python3 -m qutebrowser --temp-basedir --nowindow --debug about:blank 
```

```
10:46:58 DEBUG    init       app:process_pos_args:299 Startup cmd ':later 500 quit'
10:46:58 DEBUG    commands   command:run:541 command called: later ['500', 'quit']
10:46:58 DEBUG    commands   command:run:556 Calling qutebrowser.misc.utilcmds.later(500, 'quit', 0)
10:46:58 DEBUG    init       app:_process_args:243 Init finished after 11.500216s
10:46:58 DEBUG    init       app:init:199 Init done!
10:46:58 DEBUG    webview    browsertab:_set_load_status:927 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='about:blank'>: LoadStatus.loading
10:46:58 DEBUG    signals    signalfilter:_filter_signals:88 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 0)
10:46:58 DEBUG    signals    signalfilter:_filter_signals:88 emitting: cur_load_started() (tab 0)
10:46:58 DEBUG    commands   command:run:541 command called: quit
10:46:58 DEBUG    commands   argparser:multitype_conv:158 Trying to parse None as <class 'NoneType'>
10:46:58 DEBUG    commands   command:run:556 Calling qutebrowser.app.Quitter.quit(<qutebrowser.app.Quitter object at 0x0000021F46BED9D8>, False, None)
10:46:58 DEBUG    destroy    app:shutdown:721 Shutting down with status 0, session None...
10:46:58 DEBUG    prompt     prompt:shutdown:139 Shutting down with loops []
10:46:58 DEBUG    destroy    app:_shutdown:749 Stage 2 of shutting down...
10:46:58 DEBUG    ipc        ipc:shutdown:404 Shutting down IPC (socket 0x7ff9d7453ce0)
10:46:58 DEBUG    save       savemanager:save:97 Save of yaml-config requested - dirty False, save_on_exit False, is_exit True, force False -> False
10:46:58 DEBUG    save       savemanager:save:97 Save of state-config requested - dirty False, save_on_exit True, is_exit True, force False -> True
10:46:58 DEBUG    save       savemanager:save:97 Save of command-history requested - dirty False, save_on_exit False, is_exit True, force False -> False
10:46:59 DEBUG    save       savemanager:save:97 Save of quickmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
10:46:59 DEBUG    save       savemanager:save:97 Save of bookmark-manager requested - dirty False, save_on_exit False, is_exit True, force False -> False
10:46:59 DEBUG    save       savemanager:save:97 Save of cookies requested - dirty False, save_on_exit False, is_exit True, force False -> False
10:46:59 DEBUG    destroy    app:_shutdown:764 Deferring QApplication::exit...
10:46:59 DEBUG    destroy    app:exit:828 Now calling QApplication::exit.
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: download-model
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: quitter
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: command-history
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: 0
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: main-window
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: last-focused-main-window
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: last-visible-main-window
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: message-bridge
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: tabbed-browser
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: status-command
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: 0
10:46:59 DEBUG    destroy    objreg:on_destroyed:125 schedule removal: tab
10:46:59 DEBUG    misc       eventfilter:eventFilter:80 <PyQt5.QtWidgets.QWidget object at 0x0000021F4CAD3A68>: removed child <PyQt5.QtCore.QObject object at 0x0000021F4C9C8A68>
10:46:59 DEBUG    misc       eventfilter:eventFilter:80 <PyQt5.QtWidgets.QWidget object at 0x0000021F4CAD3A68>: removed child <PyQt5.QtWidgets.QWidget object at 0x0000021F4C8C1288>
Windows fatal exception: access violation

Current thread 0x00001ef0 (most recent call first):
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37-x64\lib\subprocess.py", line 512, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['py', '-3', '-m', 'qutebrowser', '--temp-basedir', '--nowindow', '--debug', 'about:blank', ':later 500 quit']' returned non-zero exit status 3221225477.
```

Interestingly, this goes away when removing `--nowindow`...

**Comment by The-Compiler** [comment]
Stacktrace:

```
#0  0x00007fb6bf2dff25 in raise () at /usr/lib/libc.so.6
#1  0x00007fb6bf2dffb0 in <signal handler called> () at /usr/lib/libc.so.6
#2  0x0000000000000030 in  ()
#3  0x00007fb6ba23c18f in QStyleSheetStyle::event(QEvent*) (this=0x5640dfe08940, e=0x7ffe8b8f5eb0) at styles/qstylesheetstyle.cpp:6040
#4  0x00007fb6ba19c472 in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x5640df4525d0, receiver=receiver@entry=0x5640dfe08940, e=e@entry=0x7ffe8b8f5eb0) at kernel/qapplication.cpp:3693
#5  0x00007fb6ba1a5c89 in QApplication::notify(QObject*, QEvent*) (this=0x5640df761b80, receiver=0x5640dfe08940, e=0x7ffe8b8f5eb0) at kernel/qapplication.cpp:3439
#6  0x00007fb6bab35441 in sipQApplication::notify(QObject*, QEvent*) (this=0x5640df761b80, a0=0x5640dfe08940, a1=0x7ffe8b8f5eb0) at sipQtWidgetsQApplication.cpp:243
#7  0x00007fb6bd576832 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x5640dfe08940, event=0x7ffe8b8f5eb0) at ../../include/QtCore/../../src/corelib/kernel/qobject.h:153
#8  0x00007fb6ba1a34fd in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) (reason=Qt::OtherFocusReason, focus=<optimized out>) at /usr/include/c++/9.2.0/bits/atomic_base.h:413
#9  0x00007fb6ba1a34fd in QApplicationPrivate::setFocusWidget(QWidget*, Qt::FocusReason) (focus=focus@entry=0x0, reason=reason@entry=Qt::OtherFocusReason) at kernel/qapplication.cpp:1691
#10 0x00007fb6ba1dae58 in QWidget::clearFocus() (this=this@entry=0x5640dff74640) at kernel/qwidget.cpp:6514
#11 0x00007fb6ba1dbec9 in QWidget::~QWidget() (this=0x5640dff74640, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1467
#12 0x00007fb6bab6d102 in sipQWidget::~sipQWidget() (this=0x5640dff74640, __in_chrg=<optimized out>) at sipQtWidgetsQWidget.cpp:355
#13 0x00007fb6bab6d124 in sipQWidget::~sipQWidget() (this=0x5640dff74640, __in_chrg=<optimized out>) at sipQtWidgetsQWidget.cpp:358
#14 0x00007fb6bd5a0c0e in QObjectPrivate::deleteChildren() (this=this@entry=0x5640dfee2ed0) at kernel/qobject.cpp:2123
#15 0x00007fb6ba1dbfee in QWidget::~QWidget() (this=0x5640dff57f10, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1530
#16 0x00007fb6ba3584ea in QStackedWidget::~QStackedWidget() (this=0x5640dff57f10, __in_chrg=<optimized out>) at widgets/qstackedwidget.cpp:145
#17 0x00007fb6bd5a0c0e in QObjectPrivate::deleteChildren() (this=this@entry=0x5640e006f7d0) at kernel/qobject.cpp:2123
#18 0x00007fb6ba1dbfee in QWidget::~QWidget() (this=0x7fb6a0005b50, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1530
#19 0x00007fb6ba8f2a94 in sipQTabWidget::~sipQTabWidget() (this=0x7fb6a0005b50, __in_chrg=<optimized out>) at sipQtWidgetsQTabWidget.cpp:326
#20 0x00007fb6ba8f2ab6 in sipQTabWidget::~sipQTabWidget() (this=0x7fb6a0005b50, __in_chrg=<optimized out>) at sipQtWidgetsQTabWidget.cpp:329
#21 0x00007fb6bd5a0c0e in QObjectPrivate::deleteChildren() (this=this@entry=0x5640df3d3030) at kernel/qobject.cpp:2123
#22 0x00007fb6ba1dbfee in QWidget::~QWidget() (this=0x5640df86e200, __in_chrg=<optimized out>) at kernel/qwidget.cpp:1530
#23 0x00007fb6bab6d102 in sipQWidget::~sipQWidget() (this=0x5640df86e200, __in_chrg=<optimized out>) at sipQtWidgetsQWidget.cpp:355
#24 0x00007fb6bab6d124 in sipQWidget::~sipQWidget() (this=0x5640df86e200, __in_chrg=<optimized out>) at sipQtWidgetsQWidget.cpp:358
#25 0x00007fb6bdae3525 in cleanup_qobject(sipSimpleWrapper*, void*) (sw=0x7fb694fb38b0, closure=0x5640df761b80) at ../../qpy/QtCore/qpycore_public_api.cpp:66
#26 0x00007fb6bd847ad8 in sip_api_visit_wrappers (visitor=0x7fb6bdae33ab <cleanup_qobject(sipSimpleWrapper*, void*)>, closure=0x5640df761b80) at siplib.c:13227
#27 0x00007fb6bdae3574 in pyqt5_cleanup_qobjects() () at ../../qpy/QtCore/qpycore_public_api.cpp:78
#28 0x00007fb6bdae2f51 in cleanup_on_exit(PyObject*, PyObject*) () at ../../qpy/QtCore/qpycore_init.cpp:37
#29 0x00007fb6bf05d6c9 in  () at /usr/lib/libpython3.8.so.1.0
#30 0x00007fb6bf06ddf1 in PyVectorcall_Call () at /usr/lib/libpython3.8.so.1.0
#31 0x00007fb6bf1547eb in  () at /usr/lib/libpython3.8.so.1.0
#32 0x00007fb6bf0364ee in  () at /usr/lib/libpython3.8.so.1.0
#33 0x00007fb6bf157e93 in Py_RunMain () at /usr/lib/libpython3.8.so.1.0
#34 0x00007fb6bf158339 in Py_BytesMain () at /usr/lib/libpython3.8.so.1.0
#35 0x00007fb6bf2cb153 in __libc_start_main () at /usr/lib/libc.so.6
#36 0x00005640de18705e in _start ()
```
