### ISSUE TITLE
AttributeError on reference to default_size

### ISSUE THREAD

**Issue by dgmulf** [qutebrowser/qutebrowser#5223]
**Version info (see `:version`)**:

Arch Linux build version 1.10.0-1

**Description**

The following error occurs when referencing `default_size` in `fonts.*` configuration value strings in config.py.
```
Traceback (most recent call last): File "/usr/lib/python3.8/site-packages/qutebrowser/config/configinit.py", line 67, in early_init configfiles.read_config_py(config_file) File "/usr/lib/python3.8/site-packages/qutebrowser/config/configfiles.py", line 743, in read_config_py raise configexc.ConfigFileErrors('config.py', api.errors) qutebrowser.config.configexc.ConfigFileErrors: Errors occurred while reading config.py: Unhandled exception - AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by The-Compiler** [comment]
Do you have an example `config.py` triggering this? Can you please also show the stacktrace displayed in the error window?

**Comment by dgmulf** [comment]
Sure. Here's a simple config.py that triggers the error:

```
c.fonts.debug_console = 'default_size default_family'
```

Here's the full stacktrace:

```
Errors occurred while reading config.py: 
Unhandled exception: 'NoneType' object has no attribute 'lower' 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configfiles.py", line 731, in read_config_py
    exec(code, module.__dict__)
  File "/home/dgmulf/.config/qutebrowser/config.py", line 52, in <module>
    c.fonts.debug_console = 'default_size default_family'
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 611, in __setattr__
    self._config.set_obj(name, value, pattern=self._pattern)
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 457, in set_obj
    self._set_value(opt, value, pattern=pattern,
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/config.py", line 317, in _set_value
    opt.typ.to_py(value)  # for validation
  File "/usr/lib/python3.8/site-packages/qutebrowser/config/configtypes.py", line 1336, in to_py
    if size.lower().endswith('pt'):
AttributeError: 'NoneType' object has no attribute 'lower'
```

**Comment by The-Compiler** [comment]
Thanks, reproduced now. It looks like it doesn't happen for e.g. `fonts.statusbar`.
