### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.QtQml'

### ISSUE THREAD

**Issue by karlh626** [qutebrowser/qutebrowser#5243]
**Version info (see `:version`)**:  1.10.1

**Does the bug happen if you start with `--temp-basedir`?**:  yes

**Description**
I am using ubuntu 18.04  and ran a system update and installed the latest version of qutebrowser using `pip3 install -U qutebrowser`

Afterwards qutebrowser is failing to start.

I ran qutebrowser --debug and get the following output:

```qutebrowser --debug
20:48:20 DEBUG    init       earlyinit:init_log:275 Log initialized.

Traceback (most recent call last):
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 224, in _check_modules
    importlib.import_module(name)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'PyQt5.QtQml'
20:48:21 WARNING  qt         Unknown module:none:0 Qt: Session management error: Could not open network socket
  File "/home/karl/.local/bin/qutebrowser", line 11, in <module>
    sys.exit(main())
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/qutebrowser.py", line 197, in main
    earlyinit.early_init(args)
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 305, in early_init
    check_libraries()
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 242, in check_libraries
    _check_modules(modules)
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 226, in _check_modules
    _die(text, e)
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/misc/earlyinit.py", line 87, in _die
    app = QApplication(sys.argv)
  File "/home/karl/.local/lib/python3.6/site-packages/qutebrowser/utils/log.py", line 505, in qt_message_handler
    stack = ''.join(traceback.format_stack())  # type: typing.Optional[str]
```

**Comment by The-Compiler** [comment]
It looks like your install is broken in some way - I don't think there's much qutebrowser can do here.

How did ou install PyQt? What do these commands say?

- `pip3 freeze`
- `python3 -c "import qutebrowser; print(qutebrowser.__file__)"`
- `python3 -c "import PyQt5; print(PyQt5.__file__)"`
- `python3 -c "import PyQt5.Qml; print(PyQt5.Qml.__file__)"`

**Comment by karlh626** [comment]
Thank you for repsonding.

I don't specifically remember installing PyQt.  I know the recently, I have done all of the qutebrowser updates in ubuntu using pip3.  In MacOS, I use the pre-compiled binary.
```
% python3 -c "import qutebrowser; print(qutebrowser.__file__)"
/home/karl/.local/lib/python3.6/site-packages/qutebrowser/__init__.py
```

```
python3 -c "import PyQt5; print(PyQt5.__file__)"
/usr/lib/python3/dist-packages/PyQt5/__init__.py
```

```
python3 -c "import PyQt5.Qml; print(PyQt5.Qml.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.Qml'
```

```
pip3 freeze
aiohttp==2.3.10
apturl==0.5.2
asciinema==2.0.1
asn1crypto==0.24.0
async-timeout==3.0.1
attrs==19.3.0
beautifulsoup4==4.8.0
Brlapi==0.6.6
buku==4.2.2
certifi==2019.9.11
cffi==1.12.3
chardet==3.0.4
click==6.7
colorama==0.3.7
command-not-found==0.3
cryptography==2.7
cupshelpers==1.0
defer==1.0.6
distro-info===0.18ubuntu0.18.04.1
dmenu==0.2.1
fido2==0.8.1
html5lib==1.0.1
httplib2==0.9.2
humanize==0.5.1
idna==2.8
idna-ssl==1.1.0
iotop==0.6
Jinja2==2.11.1
keyring==10.6.0
keyrings.alt==3.0
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
louis==3.5.0
lxml==4.2.1
macaroonbakery==1.1.3
Mako==1.0.7
MarkupSafe==1.1.1
meld==3.18.0
multidict==4.6.1
netifaces==0.10.4
oauth==1.0.1
olefile==0.45.1
pexpect==4.2.1
Pillow==5.1.0
pluggy==0.6.0
protobuf==3.0.0
psutil==5.4.2
py==1.5.2
pycairo==1.16.2
pycparser==2.19
pycrypto==2.6.1
pycups==1.9.73
Pygments==2.5.2
pygobject==3.26.1
pymacaroons==0.13.0
PyNaCl==1.1.2
pyOpenSSL==17.5.0
pyPEG2==2.15.2
pyRFC3339==1.0
pyscard==1.9.6
python-apt==1.6.5+ubuntu0.2
python-dateutil==2.8.1
python-debian==0.1.32
python-xapp==1.0.0
python-xlib==0.20
pytz==2018.7
pyusb==1.0.0
pyxattr==0.6.0
pyxdg==0.25
PyYAML==5.3
qutebrowser==1.10.1
reportlab==3.4.0
requests==2.18.4
requests-file==1.4.3
requests-unixsocket==0.1.5
SecretStorage==2.3.1
setproctitle==1.1.10
simplejson==3.13.2
six==1.13.0
soupsieve==1.9.3
speedtest-cli==2.1.2
ssh-import-id==5.7
system-service==0.3
systemd-python==234
tasklib==1.1.0
tldextract==2.2.0
tox==2.5.0
twtxt==1.2.3
tzlocal==1.5.1
ubuntu-drivers-common==0.0.0
ufw==0.36
unattended-upgrades==0.1
urllib3==1.25.3
usb-creator==0.3.3
vboxapi==1.0
virtualenv==15.1.0
wadllib==1.3.2
webencodings==0.5.1
xkit==0.0.0
yarl==1.4.1
youtube-dl==2018.3.14
yubikey-manager==3.1.1
zope.interface==4.3.2
```

**Comment by The-Compiler** [comment]
Do you have `python3-pyqt5.qtquick` installed?

**Comment by karlh626** [comment]
I tried the following:

```
% sudo apt-get install python3-pyqt5.qtquick
[sudo] password for karl: 
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following NEW packages will be installed:
  python3-pyqt5.qtquick
0 upgraded, 1 newly installed, 0 to remove and 0 not upgraded.
Need to get 293 kB of archives.
After this operation, 2,314 kB of additional disk space will be used.
Get:1 http://us.archive.ubuntu.com/ubuntu bionic/universe amd64 python3-pyqt5.qtquick amd64 5.10.1+dfsg-1ubuntu2 [293 kB]
Fetched 293 kB in 1s (554 kB/s)               
Selecting previously unselected package python3-pyqt5.qtquick.
(Reading database ... 267219 files and directories currently installed.)
Preparing to unpack .../python3-pyqt5.qtquick_5.10.1+dfsg-1ubuntu2_amd64.deb ...
Unpacking python3-pyqt5.qtquick (5.10.1+dfsg-1ubuntu2) ...
Setting up python3-pyqt5.qtquick (5.10.1+dfsg-1ubuntu2) ...
karl@kharris-MacBookPro ~ % qutebrowser 
09:16:27 WARNING: Qt: Session management error: Could not open network socket
```

**Comment by karlh626** [comment]
I also ran:

```
python3 -c "import PyQt5.Qml; print(PyQt5.Qml.__file__)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.Qml'
```

**Comment by karlh626** [comment]
hmmm... I noticed that when I tried to run qutebrowser, it now showed a different error.

This time about missing an QtSQL module so I installed:
`apt-get install python3-pyqt5.qtsql`

Then, I got an error about missing the module QtGL so I installed:
`apt-get install PyQt5.QtOpenGL`

...and *qutebrowser* starts again and I have my lovely browser back.

I am still not sure how it got to be in this state but I happy now.

Thanks for all your help!

**Comment by kesslermaximilian** [comment]
I encountered the same error when installing qutebrowser 2.4.0 on Ubuntu 21.04 after a system update from Ubuntu 20.04 LTS.
qutebrowser has been installed with pip, and installing the packages
`python3-pyqt5.qtquick`, ` python3-pyqt5.qtsql`, `PyQt5.QtOpenGL`
via `apt` and furthermore
`PyQt5.QtWebEngine`
fixed the problem.
I do not know why these packages were missing, but I just wanted to comment this in case anyone else encounters the same / similar issue again.
