### ISSUE TITLE
AssertionError: qWebKitVersion is not None

### ISSUE THREAD

**Issue by tallero** [qutebrowser/qutebrowser#5484]
Power went down and now I get this when trying to start qute:

```
07:31:02 INFO: Run :adblock-update to get adblock lists.
07:31:03 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==1.12.0', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 203, in main
    return app.run(args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 123, in run
    init(args=args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 151, in init
    _init_modules(args=args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/app.py", line 389, in _init_modules
    backendproblem.init(args=args, save_manager=save_manager)
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/backendproblem.py", line 553, in init
    checker.check()
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/backendproblem.py", line 534, in check
    self._check_backend_modules()
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/backendproblem.py", line 429, in _check_backend_modules
    imports = self._try_import_backends()
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/backendproblem.py", line 370, in _try_import_backends
    if qtutils.is_new_qtwebkit():
  File "/usr/lib/python3.8/site-packages/qutebrowser/utils/qtutils.py", line 118, in is_new_qtwebkit
    assert qWebKitVersion is not None
AssertionError
07:31:03 ERROR: Error while getting history: 'command-history'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/crashsignal.py", line 208, in _get_exception_info
    cmd_history = objreg.get('command-history')[-5:]
  File "/usr/lib/python3.8/site-packages/qutebrowser/utils/objreg.py", line 247, in get
    return reg[name]
  File "/usr/lib/python3.8/collections/__init__.py", line 1010, in __getitem__
    raise KeyError(key)
KeyError: 'command-history'
```

Ideas?

Qutebrowser 1.12.0 on arch.

**Comment by The-Compiler** [comment]
The relevant part of the output is this:

```
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/backendproblem.py", line 429, in _check_backend_modules
    imports = self._try_import_backends()
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/backendproblem.py", line 370, in _try_import_backends
    if qtutils.is_new_qtwebkit():
  File "/usr/lib/python3.8/site-packages/qutebrowser/utils/qtutils.py", line 118, in is_new_qtwebkit
    assert qWebKitVersion is not None
AssertionError
```

I got some crash reports with the same output as well, so I don't think this is because of a hard reboot - it's much more likely to be caused by a recent system update.

Are you using the Archlinux `[testing]` repository? Can you show the output of the following commands?

- `pacman -Q qt5-webkit qt5-webengine python-pyqt5`
- `python3 -c "from PyQt5 import QtWebKit"` (I'm guessing it works without any output)
- `python3 -c "from PyQt5.QtWebKit import qWebKitVersion; print(qWebKitVersion())"` (I'm guessing there will be some kind of `ImportError` here)

**Comment by tallero** [comment]
Apparently the problem was due to having given a pip upgrade command as user yesterday, so that I had various PyQt* installed in `~/.local/share`, (and in fact the import was not working).

So probably some PyQt* pip package is not working correctly.

**Comment by The-Compiler** [comment]
Taking the freedom to reopen this - it seems to happen to at least two other people, and I'd like to handle this gracefully in qutebrowser. Do you know how I could reproduce it?

**Comment by Glassinatorn** [comment]
I got the exact same error yesterday evening after I had updated to v.1.12 on arch, tried updating to the latest through the aur but still got the same problem. It worked on the second computer though (also arch) the only difference I could find between them were a few python packages. 
Installed manjaro on the computer that didn't work last night and it works now there as well, though the official manjaro repo have v.1.11 as the latest. Git-v.1.12 through the aur works now on manjaro though.
I'll try to spin up a vm to see if I can get the same issue on "pure" arch again.

**Comment by The-Compiler** [comment]
@Glassinatom the command-history error is irrelevant - what's the exception you got above that?

**Comment by Glassinatorn** [comment]
Oh, my bad, I don't have the log anymore after the reinstall but from what I remember, it looked almost exactly like the error tallero got. I'll try to see if I can get it again.

**Comment by tallero** [comment]
@The-Compiler on arch this should be enough:
```
$ pip freeze | %{$_.split('==')[0]} | %{pip install --upgrade $_ }
```
