### ISSUE TITLE
Renderer crash when redirecting certain links from Facebook (to strip fbclid parameter)

### ISSUE THREAD

**Issue by andrewcarlotti** [qutebrowser/qutebrowser#5737]
**Version info**:
```
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.5
PyQt: 5.15.1

sip: 5.4.0
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.1
yaml: 5.3.1
cssutils: no
attr: 20.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1g  21 Apr 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.1.8
Platform: Linux-5.8.1-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

Paths:
cache: ~/tmp/qutebrowser-crashes/workdir/cache
config: ~/tmp/qutebrowser-crashes/workdir/config
data: ~/tmp/qutebrowser-crashes/workdir/data
runtime: ~/tmp/qutebrowser-crashes/workdir/runtime
system data: /usr/share/qutebrowser

Autoconfig loaded: yes
Config.py: ~/tmp/qutebrowser-crashes/workdir/config/config.py has been loaded
Uptime: 0:03:31
```

**Does the bug happen if you start with `--temp-basedir`?**:
Not reliably, but I think I managed to get some crashes after editing the config via the config-edit command.

**Description**
I sometimes get renderer crashes when opening links from Facebook to other sites. These crashes only happen when I strip the `fbclid` parameter from links. My config.py is:
```
from qutebrowser.api import interceptor
from PyQt5.QtCore import QUrl, QUrlQuery

config.load_autoconfig()

# Remove and fbclid query items
def intercept(info: interceptor.Request) -> None:
    if info.request_url.hasQuery():
        query = QUrlQuery(info.request_url.query())
        if query.hasQueryItem("fbclid"):
            query.removeQueryItem("fbclid")
            new_url = QUrl(info.request_url)
            new_url.setQuery(query)
            print(new_url)
            info.redirect(new_url)

interceptor.register(intercept)
```

This only seems to happen on certain sites. Two sites where I have observed this behaviour are www.rugbyadvertiser.co.uk and www.theatlantic.com. I first observed a crash on or before August 1st, though I couldn't reliably reproduce it at the time. I've now managed to reproduce it fairly reliably for both of these sites (using a copy of my normal working files).

I think I also triggered it once or twice using a clean working directory with just config.py edited, but I'm not sure how - most of the crashes I could get were when I accidentally reloaded config.py and duplicated the interceptor.

The crash can also be triggered by loading the l.facebook url directly.

This is an extract of the debug output during a crash:
```17:32:44 DEBUG    sql        sql:__init__:183 Preparing SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
17:32:44 DEBUG    sql        sql:run:216 Running SQL query: "INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)"
17:32:44 DEBUG    sql        sql:run:220 query bindings: {':atime': 1600705964, ':redirect': False, ':title': 'https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.theatlantic.com%2Finternational%2Farchive%2F2020%2F08%2Fwhy-britain-failed-coronavirus-pandemic%2F615166%2F%3Futm_source%3Dfacebook%26utm_medium%3Dsocial%26utm_campaign%3Dshare%26fbclid%3DIwAR1-Y1jK1YKORycGy94TjwNgek_7a-PLL4ZynWD2JF6U6FXaesk2iOJId-M&h=AT19AthUvf-QwZ9co1Xcrji8eIGkWu9atA0XY2uRBAKcaEQIN0j7hB8mcfH7NOjn5N0LUfIjbOVV1vzTm-E62YoB-rGtiGtyC2cOTec-C3vfo6YODjHgpv2uSnD0thWMauAnJLptwjLH&__tn__=%2CmH-R&c[0]=AT0ELnq6na-XwHzEo81xOYKfUhGnBYQekrUAhDKS7OVYt7a2GVeQrvU_qBkjO4H7uNkWNZExKWCWlhiObvAzCvNGKIKIZZEokMCuDVeX9HHP-LCx-pFr81bPkM9efKzz1Wqf9mp--axz2sPzmwBPo31e', ':url': 'https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.theatlantic.com%2Finternational%2Farchive%2F2020%2F08%2Fwhy-britain-failed-coronavirus-pandemic%2F615166%2F%3Futm_source%3Dfacebook%26utm_medium%3Dsocial%26utm_campaign%3Dshare%26fbclid%3DIwAR1-Y1jK1YKORycGy94TjwNgek_7a-PLL4ZynWD2JF6U6FXaesk2iOJId-M&h=AT19AthUvf-QwZ9co1Xcrji8eIGkWu9atA0XY2uRBAKcaEQIN0j7hB8mcfH7NOjn5N0LUfIjbOVV1vzTm-E62YoB-rGtiGtyC2cOTec-C3vfo6YODjHgpv2uSnD0thWMauAnJLptwjLH&__tn__=%2CmH-R&c[0]=AT0ELnq6na-XwHzEo81xOYKfUhGnBYQekrUAhDKS7OVYt7a2GVeQrvU_qBkjO4H7uNkWNZExKWCWlhiObvAzCvNGKIKIZZEokMCuDVeX9HHP-LCx-pFr81bPkM9efKzz1Wqf9mp--axz2sPzmwBPo31e'}
17:32:44 DEBUG    sql        sql:__init__:183 Preparing SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
17:32:44 DEBUG    sql        sql:run:216 Running SQL query: "REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)"
17:32:44 DEBUG    sql        sql:run:220 query bindings: {':last_atime': 1600705964, ':title': 'https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.theatlantic.com%2Finternational%2Farchive%2F2020%2F08%2Fwhy-britain-failed-coronavirus-pandemic%2F615166%2F%3Futm_source%3Dfacebook%26utm_medium%3Dsocial%26utm_campaign%3Dshare%26fbclid%3DIwAR1-Y1jK1YKORycGy94TjwNgek_7a-PLL4ZynWD2JF6U6FXaesk2iOJId-M&h=AT19AthUvf-QwZ9co1Xcrji8eIGkWu9atA0XY2uRBAKcaEQIN0j7hB8mcfH7NOjn5N0LUfIjbOVV1vzTm-E62YoB-rGtiGtyC2cOTec-C3vfo6YODjHgpv2uSnD0thWMauAnJLptwjLH&__tn__=%2CmH-R&c[0]=AT0ELnq6na-XwHzEo81xOYKfUhGnBYQekrUAhDKS7OVYt7a2GVeQrvU_qBkjO4H7uNkWNZExKWCWlhiObvAzCvNGKIKIZZEokMCuDVeX9HHP-LCx-pFr81bPkM9efKzz1Wqf9mp--axz2sPzmwBPo31e', ':url': 'https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.theatlantic.com%2Finternational%2Farchive%2F2020%2F08%2Fwhy-britain-failed-coronavirus-pandemic%2F615166%2F%3Futm_source%3Dfacebook%26utm_medium%3Dsocial%26utm_campaign%3Dshare%26fbclid%3DIwAR1-Y1jK1YKORycGy94TjwNgek_7a-PLL4ZynWD2JF6U6FXaesk2iOJId-M&h=AT19AthUvf-QwZ9co1Xcrji8eIGkWu9atA0XY2uRBAKcaEQIN0j7hB8mcfH7NOjn5N0LUfIjbOVV1vzTm-E62YoB-rGtiGtyC2cOTec-C3vfo6YODjHgpv2uSnD0thWMauAnJLptwjLH&__tn__=%2CmH-R&c[0]=AT0ELnq6na-XwHzEo81xOYKfUhGnBYQekrUAhDKS7OVYt7a2GVeQrvU_qBkjO4H7uNkWNZExKWCWlhiObvAzCvNGKIKIZZEokMCuDVeX9HHP-LCx-pFr81bPkM9efKzz1Wqf9mp--axz2sPzmwBPo31e'}
17:32:44 DEBUG    sessions   sessions:save:317 Saving session _autosave to /home/andrew/tmp/qutebrowser-crashes/workdir/data/sessions/_autosave.yml...
17:32:44 DEBUG    signals    signalfilter:_filter_signals:92 ignoring: cur_load_finished(True) (tab 2)
17:32:44 DEBUG    modes      modeman:_handle_keyrelease:331 filter: False
17:32:46 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: None
17:32:56 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7fac58268c10>
17:32:56 DEBUG    misc       app:on_focus_object_changed:524 Focus object changed: None
PyQt5.QtCore.QUrl('https://www.theatlantic.com/international/archive/2020/08/why-britain-failed-coronavirus-pandemic/615166/?utm_source=facebook&utm_medium=social&utm_campaign=share')
[152958:152982:0921/173257.824422:ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field 3)
[152958:152982:0921/173257.824752:ERROR:render_process_host_impl.cc(4880)] Terminating render process for bad Mojo message: Received bad user message: Validation failed for blink.mojom.ServiceWorkerFetchResponseCallback [VALIDATION_ERROR_UNEXPECTED_NULL_POINTER (null field 3)
[152958:152982:0921/173257.824797:ERROR:bad_message.cc(27)] Terminating renderer for bad IPC message, reason 123
PyQt5.QtCore.QUrl('https://www.theatlantic.com/international/archive/2020/08/why-britain-failed-coronavirus-pandemic/615166/?utm_source=facebook&utm_medium=social&utm_campaign=share')
17:33:09 DEBUG    misc       eventfilter:eventFilter:95 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fabdd487af0>: removed child <PyQt5.QtCore.QObject object at 0x7fac383fe940>
17:33:09 DEBUG    misc       eventfilter:eventFilter:95 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fac58268ee0>: removed child <PyQt5.QtCore.QObject object at 0x7fac383fe550>
17:33:09 DEBUG    misc       eventfilter:eventFilter:84 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fabdd487af0> got new child <PyQt5.QtWidgets.QWidget object at 0x7fac383fec10>, installing filter
17:33:09 DEBUG    webview    browsertab:_on_navigation_request:1039 navigation request: url data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…, type Type.typed, is_main_frame True
17:33:09 ERROR    webview    tabbedbrowser:show_error_page:942 Renderer process was killed
17:33:09 DEBUG    webview    webenginetab:_store_match_data:214 Active search match: 0/0
17:33:09 DEBUG    webview    browsertab:_set_load_status:981 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='https://www.facebook.com/dylanhmorris/'>: LoadStatus.loading
17:33:09 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 1)
17:33:09 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 1)
17:33:09 DEBUG    misc       eventfilter:eventFilter:84 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7fac58268ee0> got new child <PyQt5.QtWidgets.QWidget object at 0x7fac383fe5e0>, installing filter
17:33:09 DEBUG    webview    browsertab:_on_navigation_request:1039 navigation request: url data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…, type Type.typed, is_main_frame True
17:33:09 ERROR    webview    tabbedbrowser:show_error_page:942 Renderer process was killed
```

This is the output from gdb attached to that process. I don't have debugging symbols so it's probably not very helpful:
```
Attaching to process 153036
[New LWP 153037]
[New LWP 153038]
[New LWP 153039]
[New LWP 153040]
[New LWP 153041]
[New LWP 153042]
[New LWP 153043]
[New LWP 153044]
[New LWP 153045]
[New LWP 153046]
[New LWP 153047]
[New LWP 153048]
[New LWP 153049]
[New LWP 153050]
[New LWP 153051]
[New LWP 153052]
[New LWP 153053]
[New LWP 153054]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/usr/lib/libthread_db.so.1".

warning: Loadable section "" outside of ELF segments
BFD: /usr/lib/chromium/libwidevinecdm.so: version count (402) does not match symbol count (401)

warning: Target and debugger are in different PID namespaces; thread lists and other data are likely unreliable.  Connect to gdbserver inside the container.
0x00007f0be11b39c8 in pthread_cond_timedwait@@GLIBC_2.3.2 () from /usr/lib/libpthread.so.0
(gdb) c
Continuing.
[New Thread 0x7f0ba2ffd640 (LWP 153088)]

Thread 20 "ServiceWorker t" received signal SIGSYS, Bad system call.
[Switching to Thread 0x7f0ba2ffd640 (LWP 153088)]
0x00007f0be124c174 in pthread_getaffinity_np@GLIBC_2.3.4 () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007f0be124c174 in pthread_getaffinity_np@GLIBC_2.3.4 () at /usr/lib/libc.so.6
#1  0x00007f0be124c2fc in pthread_getattr_np@GLIBC_2.2.5 () at /usr/lib/libc.so.6
#2  0x00007f0be4c4139d in  () at /usr/lib/libQt5WebEngineCore.so.5
#3  0x0000000000000000 in  ()
(gdb) c
Continuing.

Thread 1 "QtWebEngineProc" received signal SIGTERM, Terminated.
[Switching to Thread 0x7f0bd777fc80 (LWP 153036)]
0x00007f0be33cc925 in ?? () from /usr/lib/libQt5WebEngineCore.so.5
(gdb) bt
#0  0x00007f0be33cc925 in  () at /usr/lib/libQt5WebEngineCore.so.5
#1  0x0000279e0ac7f189 in  ()
#2  0x0000279e0ac7f1b1 in  ()
#3  0x0000279e084f6ef1 in  ()
#4  0x0000279e08abddd1 in  ()
#5  0x0000279e08abddd1 in  ()
#6  0x0000279e0b227cbd in  ()
#7  0x0000279e084f6f05 in  ()
#8  0x000000000000001a in  ()
#9  0x00007ffdaef0c798 in  ()
#10 0x00007f0be34749d0 in  () at /usr/lib/libQt5WebEngineCore.so.5
#11 0x00007ffdaef0c828 in  ()
#12 0x0000563a06c86f20 in  ()
#13 0x000000000000007f in  ()
#14 0x000000000000001a in  ()
#15 0x00007ffdaef0c828 in  ()
#16 0x00007f0be337996b in  () at /usr/lib/libQt5WebEngineCore.so.5
#17 0x0000279e084f6ef1 in  ()
#18 0x0000279e098bc841 in  ()
#19 0x000000000000002a in  ()
#20 0x0000279e00000044 in  ()
#21 0x0000279e098bc945 in  ()
#22 0x0000279e098bc945 in  ()
#23 0x0000279e0b227cbd in  ()
#24 0x0000279e098bc885 in  ()
#25 0x0000279e084f6ef1 in  ()
#26 0x0000279e00000000 in  ()
#27 0x0000279e084f6ef1 in  ()
#28 0x0000279e0b227cbd in  ()
#29 0x00000000000000f4 in  ()
#30 0x0000279e09214105 in  ()
#31 0x0000279e0b227b59 in  ()
#32 0x0000279e08abddd1 in  ()
#33 0x00007ffdaef0c888 in  ()
#34 0x00007f0be3372f3f in  () at /usr/lib/libQt5WebEngineCore.so.5
#35 0x0000279e080834e1 in  ()
#36 0x0000279e098bb749 in  ()
#37 0x0000279e08040169 in  ()
#38 0x0000279e085a1689 in  ()
#39 0x0000279e088f1bc1 in  ()
#40 0x0000279e098bc841 in  ()
#41 0x0000000000000000 in  ()
(gdb) c
Continuing.
Couldn't get registers: No such process.
Couldn't get registers: No such process.
(gdb) [Thread 0x7f0ba2ffd640 (LWP 153088) exited]
[Thread 0x7f0ba3fff640 (LWP 153054) exited]
[Thread 0x7f0ba8ffa640 (LWP 153053) exited]
[Thread 0x7f0ba97fb640 (LWP 153052) exited]
[Thread 0x7f0ba9ffc640 (LWP 153051) exited]
[Thread 0x7f0baa7fd640 (LWP 153050) exited]
[Thread 0x7f0baaffe640 (LWP 153049) exited]
[Thread 0x7f0babfff640 (LWP 153048) exited]
[Thread 0x7f0bc4ff9640 (LWP 153047) exited]
[Thread 0x7f0bc57fa640 (LWP 153046) exited]
[Thread 0x7f0bc5ffb640 (LWP 153045) exited]
[Thread 0x7f0bc67fc640 (LWP 153044) exited]
[Thread 0x7f0bc6ffd640 (LWP 153043) exited]
[Thread 0x7f0bc77fe640 (LWP 153042) exited]
[Thread 0x7f0bc7fff640 (LWP 153041) exited]
[Thread 0x7f0bd4b52640 (LWP 153040) exited]
[Thread 0x7f0bd5353640 (LWP 153039) exited]
[Thread 0x7f0bd5b54640 (LWP 153038) exited]
[Thread 0x7f0bd6355640 (LWP 153037) exited]
[Inferior 1 (process 153036) exited with code 0361]
```

**Comment by The-Compiler** [comment]
This might be a duplicate of #5721 or it might be a separate issue, I'm not sure - in any case, I can't reproduce it at the moment because all I'm running into is the renderer process crash from there.

**Comment by The-Compiler** [comment]
Can you please re-check with Archlinux' qt5-webengine >= 5.15.1-2?

**Comment by andrewcarlotti** [comment]
I've tested with Arch Linux's qt5-webengine 5.15.1-3 and it still crashes. I'm pretty sure this is not related to the crash that was fixed by 5.15.1-2
