### ISSUE TITLE
qute-pass userscript not working anymore

### ISSUE THREAD

**Issue by m-falconi** [qutebrowser/qutebrowser#5846]
**Version info**:

qutebrowser v1.14.0
Git commit: 
Backend: QtWebEngine (Chromium 80.0.3987.163)
Qt: 5.15.1

CPython: 3.8.6
PyQt: 5.15.1

sip: 5.4.0
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.7.1
yaml: 5.3.1
cssutils: no
attr: 20.2.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.15.1
PyQt5.QtWebKitWidgets: no
pdf.js: 2.6.347 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.33.0
QtNetwork SSL: OpenSSL 1.1.1h  22 Sep 2020

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 20.2.1
Platform: Linux-5.9.1-arch1-1-x86_64-with-glibc2.2.5, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt/libexec, data path: /usr/share/qt

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

Since the last update the userscript qute-pass is not working anymore. Whenever I try to invoke it I get a permission error from python. The error message log is the following:

ERROR | message | message:error:59                   | Userscript exited with status 1, see :messages for details. |
ERROR | procs       | guiprocess:_on_finished:122 | Process stderr:
                                 Traceback (most recent call last):
                                 File "/home/lobo/.local/share/qutebrowser/userscripts/qute-pass", line 255, in <module>
                                 sys.exit(main(arguments))
                                 File "/home/lobo/.local/share/qutebrowser/userscripts/qute-pass", line 181, in main
                                 extract_result = extractor(arguments.url)
                                 File "/usr/lib/python3.8/site-packages/tldextract/tldextract.py", line 222, in __call__
                                 suffix_index = self._get_tld_extractor().suffix_index(
                                 File "/usr/lib/python3.8/site-packages/tldextract/tldextract.py", line 264, in _get_tld_extractor
                                 public_tlds, private_tlds = get_suffix_lists(
                                 File "/usr/lib/python3.8/site-packages/tldextract/suffix_list.py", line 52, in get_suffix_lists
                                 return cache.run_and_cache(
                                 File "/usr/lib/python3.8/site-packages/tldextract/cache.py", line 104, in run_and_cache
                                 cache_filepath = self._key_to_cachefile_path(namespace, key_args)
                                 File "/usr/lib/python3.8/site-packages/tldextract/cache.py", line 95, in _key_to_cachefile_path
                                 _make_dir(cache_path)
                                 File "/usr/lib/python3.8/site-packages/tldextract/cache.py", line 155, in _make_dir
                                 os.makedirs(os.path.dirname(filename))
                                 File "/usr/lib/python3.8/os.py", line 213, in makedirs
                                 makedirs(head, exist_ok=exist_ok)
                                 File "/usr/lib/python3.8/os.py", line 223, in makedirs
                                 mkdir(name, mode)
                                 PermissionError: [Errno 13] Permission denied: '/usr/lib/python3.8/site-packages/tldextract/.suffix_cache'

**How to reproduce**

The error is reproduced each time I try to invoke the qute-pass userscript

**Comment by m-falconi** [comment]
Already discussed in [here](https://github.com/qutebrowser/qutebrowser/pull/5830)
