### ISSUE TITLE
Exceptions logged when shutting down with downloads running

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5865]
When downloading a couple of files and closing the window while the downloads are still running (on ebed435a0c0202e24c31cf0de7c76f4c05a5b607 with Qt 5.15.1), I get:

```
10:50:25 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 1057, in _on_begin_remove_row
    self.beginRemoveRows(QModelIndex(), idx, idx)
RuntimeError: wrapped C/C++ object of type DownloadModel has been deleted
10:50:25 ERROR: Error while recovering pages: wrapped C/C++ object of type TabWidget has been deleted
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 213, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 140, in _recover_pages
    for tab in tabbed_browser.widgets():
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 286, in widgets
    for i in range(self.widget.count()):
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
Error in sys.excepthook:
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 288, in exception_hook
    self._app.lastWindowClosed.disconnect(
RuntimeError: wrapped C/C++ object of type Application has been deleted

Original exception was:
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 1057, in _on_begin_remove_row
    self.beginRemoveRows(QModelIndex(), idx, idx)
RuntimeError: wrapped C/C++ object of type DownloadModel has been deleted
10:50:25 ERROR: ARGH, there was an exception while the crash dialog is already shown:
RuntimeError: wrapped C/C++ object of type DownloadModel has been deleted
10:50:25 ERROR: ARGH, there was an exception while the crash dialog is already shown:
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/downloads.py", line 1069, in _on_data_changed
    start_index = self.index(0, 0)
RuntimeError: wrapped C/C++ object of type DownloadModel has been deleted
```

**Comment by The-Compiler** [comment]
Sometimes also:

```
10:52:27 ERROR: Uncaught exception
RuntimeError: wrapped C/C++ object of type DownloadView has been deleted
10:52:27 ERROR: Error while recovering pages: wrapped C/C++ object of type TabWidget has been deleted
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 213, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/misc/crashsignal.py", line 140, in _recover_pages
    for tab in tabbed_browser.widgets():
  File "/home/florian/proj/qutebrowser/git/qutebrowser/mainwindow/tabbedbrowser.py", line 284, in widgets
    for i in range(self.widget.count()):
RuntimeError: wrapped C/C++ object of type TabWidget has been deleted
```

with a semi-broken crash dialog?!
