### ISSUE TITLE
python segfaults after :q

### ISSUE THREAD

**Issue by zeda-para-iba** [qutebrowser/qutebrowser#5870]
**Version info**:

```
qutebrowser v1.13.1
Git commit: 
Backend: QtWebEngine (Chromium 73.0.3683.105)
Qt: 5.13.2

CPython: 3.8.6
PyQt: 5.13.2

sip: 4.19.19
colorama: no
pypeg2: 2.15
jinja2: 2.11.2
pygments: 2.5.2
yaml: 5.3.1
cssutils: 1.0.2 $Id$
attr: 19.3.0
PyQt5.QtWebEngineWidgets: yes
PyQt5.QtWebEngine: 5.13.2
PyQt5.QtWebKitWidgets: yes
pdf.js: no
sqlite: 3.31.1
QtNetwork SSL: LibreSSL 3.2.2

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel Open Source Technology Center, 3.0 Mesa 20.0.8
Platform: OpenBSD-6.8-amd64-64bit-ELF, 64bit
Frozen: False
Imported from /usr/local/lib/python3.8/site-packages/qutebrowser
Using Python from /usr/local/bin/python3.8
Qt library executable path: /usr/local/lib/qt5/libexec, data path: /usr/local/lib/qt5
OS Version: OpenBSD thinkbsd.my.domain 6.8 GENERIC.MP#98 amd64 amd64

Paths:
cache: /home/lucas/.cache/qutebrowser
config: /home/lucas/.config/qutebrowser
data: /home/lucas/.data/qutebrowser
runtime: /tmp/runtime-lucas/qutebrowser

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:09
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**Description**

When closing qutebrowser with `:q`, python segfaults and generates a coredump.

Here's what qutebrowser outputs:

```
Fatal Python error: Segmentation fault

Current thread 0x000004e5c85cda00 (most recent call first):
<no Python frame>
Segmentation fault (core dumped) 
```

Here's the backtrace generated by gdb:

```
#0  thrkill () at /tmp/-:3
#1  <signal handler called>
#2  0x000004e60a180eb5 in QNetworkConfiguration::bearerTypeName () from /usr/local/lib/qt5/libQt5Network.so.3.0
#3  0x000004e60a17f79f in QNetworkConfiguration::~QNetworkConfiguration () from /usr/local/lib/qt5/libQt5Network.so.3.0
#4  0x000004e60a189595 in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#5  0x000004e60a1894f7 in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#6  0x000004e5b92964ad in QHashData::free_helper () from /usr/local/lib/qt5/libQt5Core.so.3.0
#7  0x000004e60a1894ad in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#8  0x000004e60a18945a in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#9  0x000004e60a1893ef in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#10 0x000004e60a1893a8 in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#11 0x000004e60a189353 in QBearerEnginePlugin::~QBearerEnginePlugin () from /usr/local/lib/qt5/libQt5Network.so.3.0
#12 0x000004e5b91d1c26 in QThreadStorageData::finish () from /usr/local/lib/qt5/libQt5Core.so.3.0
#13 0x000004e5b94d31cc in QCoreApplicationPrivate::cleanupThreadData () from /usr/local/lib/qt5/libQt5Core.so.3.0
#14 0x000004e6711626e6 in QGuiApplicationPrivate::~QGuiApplicationPrivate () from /usr/local/lib/qt5/libQt5Gui.so.3.0
#15 0x000004e66ad3c6f4 in QApplicationPrivate::~QApplicationPrivate () from /usr/local/lib/qt5/libQt5Widgets.so.3.0
#16 0x000004e66ad3c739 in QApplicationPrivate::~QApplicationPrivate () from /usr/local/lib/qt5/libQt5Widgets.so.3.0
#17 0x000004e5b954b95e in QObject::qt_metacall () from /usr/local/lib/qt5/libQt5Core.so.3.0
#18 0x000004e5b95472ed in QObject::qt_metacall () from /usr/local/lib/qt5/libQt5Core.so.3.0
#19 0x000004e5b953a2f1 in QObject::~QObject () from /usr/local/lib/qt5/libQt5Core.so.3.0
#20 0x000004e5b94d5073 in QCoreApplication::~QCoreApplication () from /usr/local/lib/qt5/libQt5Core.so.3.0
#21 0x000004e67115ec61 in QGuiApplication::~QGuiApplication () from /usr/local/lib/qt5/libQt5Gui.so.3.0
#22 0x000004e66ad3f5ce in QApplication::~QApplication () from /usr/local/lib/qt5/libQt5Widgets.so.3.0
#23 0x000004e6734a2580 in sipQApplication::~sipQApplication () from /usr/local/lib/python3.8/site-packages/PyQt5/QtWidgets.so
#24 0x000004e6734a25c9 in sipQApplication::~sipQApplication () from /usr/local/lib/python3.8/site-packages/PyQt5/QtWidgets.so
#25 0x000004e5867709d1 in _ZL15cleanup_on_exitP7_objectS0_ () from /usr/local/lib/python3.8/site-packages/PyQt5/QtCore.so
#26 0x000004e5a6254e34 in PyCFunction_NewEx () from /usr/local/lib/libpython3.8.so.0.0
#27 0x000004e5a620f52e in PyVectorcall_Call () from /usr/local/lib/libpython3.8.so.0.0
#28 0x000004e5a639354d in PyInit_atexit () from /usr/local/lib/libpython3.8.so.0.0
#29 0x000004e5a63346b2 in Py_FinalizeEx () from /usr/local/lib/libpython3.8.so.0.0
#30 0x000004e5a633544f in Py_Exit () from /usr/local/lib/libpython3.8.so.0.0
#31 0x000004e5a633a718 in _PyErr_Print () from /usr/local/lib/libpython3.8.so.0.0
#32 0x000004e5a6339661 in PyRun_SimpleFileExFlags () from /usr/local/lib/libpython3.8.so.0.0
#33 0x000004e5a635a2a9 in Py_RunMain () from /usr/local/lib/libpython3.8.so.0.0
#34 0x000004e5a635a74e in Py_Main () from /usr/local/lib/libpython3.8.so.0.0
#35 0x000004e5a635a7c8 in Py_BytesMain () from /usr/local/lib/libpython3.8.so.0.0
#36 0x000004e3752f2951 in _start () from /usr/local/bin/python3.8
#37 0x0000000000000000 in ?? ()

```

**How to reproduce**
`:q`

**Comment by The-Compiler** [comment]
That crash happens deep inside Qt and I doubt there's anything qutebrowser can do about it. FWIW it looks like something OpenBSD-specific: http://openbsd-archive.7691.n7.nabble.com/Update-and-unbreak-www-qutebrowser-td390502.html

The crash is inside Bearer Management code, which [has already been removed in Qt 6](https://bugreports.qt.io/browse/QTBUG-76502) because it's problematic in a variety of ways. Perhaps upgrading to the latest Qt 5.15 (or even just 5.14) will help as well.

I don't think qutebrowser *needs* the bearer management stuff, but there isn't [any way to disable it](https://bugreports.qt.io/browse/QTBUG-45834). #2543 might help as well.
