### ISSUE TITLE
test_set_pattern_no_model in test_completionwidget.py segfaults with --no-xvfb

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5932]
> Ah, interesting. I had started a draft and got a segfault there. It happens pretty reliably on my machine, but with a different stack trace:
>
> ```
> py38-pyqt515-cov installed: apipkg==1.5,attrs==20.3.0,beautifulsoup4==4.9.3,certifi==2020.11.8,chardet==3.0.4,cheroot==8.4.7,click==7.1.2,colorama==0.4.4,coverage==5.3,EasyProcess==0.3,execnet==1.7.1,filelock==3.0.12,Flask==1.1.2,glob2==0.7,hunter==3.3.1,hypothesis==5.41.3,icdiff==1.9.1,idna==2.10,iniconfig==1.1.1,itsdangerous==1.1.0,jaraco.functools==3.0.1,Jinja2==2.11.2,Mako==1.1.3,manhole==1.6.0,MarkupSafe==1.1.1,more-itertools==8.6.0,packaging==20.4,parse==1.18.0,parse-type==0.5.2,pluggy==0.13.1,pprintpp==0.4.0,py==1.9.0,py-cpuinfo==7.0.0,Pygments==2.7.2,pyparsing==2.4.7,pyPEG2==2.15.2,PyQt5==5.15.2,PyQt5-sip==12.8.1,PyQtWebEngine==5.15.2,pytest==6.1.2,pytest-bdd==4.0.1,pytest-benchmark==3.2.3,pytest-clarity==0.3.0a0,pytest-cov==2.10.1,pytest-forked==1.3.0,pytest-icdiff==0.5,pytest-instafail==0.4.2,pytest-mock==3.3.1,pytest-qt==3.3.0,pytest-repeat==0.9.1,pytest-rerunfailures==9.1.1,pytest-xdist==2.1.0,pytest-xvfb==2.0.0,PyVirtualDisplay==1.3.2,PyYAML==5.3.1,requests==2.25.0,requests-file==1.5.1,six==1.15.0,sortedcontainers==2.3.0,soupsieve==2.0.1,termcolor==1.1.0,tldextract==3.1.0,toml==0.10.2,urllib3==1.25.11,vulture==2.1,Werkzeug==1.0.1
> py38-pyqt515-cov run-test-pre: PYTHONHASHSEED='3782341814'
> py38-pyqt515-cov run-test: commands[0] | /home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/bin/python scripts/link_pyqt.py --tox /home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov
> LINK_PYQT_SKIP set, exiting...
> py38-pyqt515-cov run-test: commands[1] | /home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/bin/python -bb -m pytest tests/unit/completion/test_completionwidget.py
> pytest-xvfb could not find Xvfb. You can install it to prevent windows from being shown.
> ============================= test session starts ==============================
> platform linux -- Python 3.8.6, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
> cachedir: .tox/py38-pyqt515-cov/.pytest_cache
> PyQt5 5.15.2 -- Qt runtime 5.15.2 -- Qt compiled 5.15.2
> benchmark: 3.2.3 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
> rootdir: /home/rcorre/src/qutebrowser, configfile: pytest.ini
> plugins: xdist-2.1.0, qt-3.3.0, bdd-4.0.1, xvfb-2.0.0, forked-1.3.0, clarity-0.3.0a0, benchmark-3.2.3, instafail-0.4.2, repeat-0.9.1, icdiff-0.5, cov-2.10.1, mock-3.3.1, hypothesis-5.41.3, rerunfailures-9.1.1
> collected 81 items
>
> tests/unit/completion/test_completionwidget.py .....Fatal Python error: Segmentation fault
>
> Current thread 0x00007f7cb00de740 (most recent call first):
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pytestqt/plugin.py", line 197 in _process_events
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pytestqt/plugin.py", line 166 in pytest_runtest_call
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/callers.py", line 203 in _multicall
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/runner.py", line 256 in <lambda>
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/runner.py", line 310 in from_call
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/runner.py", line 255 in call_runtest_hook
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/runner.py", line 216 in call_and_report
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/runner.py", line 127 in runtestprotocol
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/runner.py", line 110 in pytest_runtest_protocol
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/main.py", line 338 in pytest_runtestloop
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/main.py", line 313 in _main
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/main.py", line 257 in wrap_session
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/main.py", line 306 in pytest_cmdline_main
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/callers.py", line 187 in _multicall
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 84 in <lambda>
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/manager.py", line 93 in _hookexec
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pluggy/hooks.py", line 286 in __call__
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/config/__init__.py", line 164 in main
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/_pytest/config/__init__.py", line 187 in console_main
>   File "/home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/lib/python3.8/site-packages/pytest/__main__.py", line 5 in <module>
>   File "/usr/lib/python3.8/runpy.py", line 87 in _run_code
>   File "/usr/lib/python3.8/runpy.py", line 194 in _run_module_as_main
> ERROR: InvocationError for command /home/rcorre/src/qutebrowser/.tox/py38-pyqt515-cov/bin/python -bb -m pytest tests/unit/completion/test_completionwidget.py (exited with code -11 (SIGSEGV)) (exited with code -11)
> ___________________________________ summary ____________________________________
> ERROR:   py38-pyqt515-cov: commands failed
> ```
>
> Its been so long since I worked on qutebrowser (:disappointed:) that I had to re-setup my dev env. It was basically:
>
> - Clone the repo
> - `python3 scripts/mkvenv.py`
> - `. .venv/bin/activate`
> - `tox -e tox -e py38-pyqt515-cov`
>
> That consistently produces the segfault above. I just noticed I didn't have xvfb. After installing that, the tests now pass, but I get an error after-the-fact:
>
> ```
> The X11 connection broke: I/O error (code 1)
> XIO:  fatal IO error 0 (Success) on X server ":1"
>       after 3168 requests (3163 known processed) with 0 events remaining.
> ```

_Originally posted by @rcorre in https://github.com/qutebrowser/qutebrowser/issues/5916#issuecomment-734925287_

I can reproduce with `tox -e py38-pyqt515 -- tests/unit/completion/test_completionwidget.py --no-xvfb -v`

**Comment by The-Compiler** [comment]
```
Thread 1 "python3" received signal SIGSEGV, Segmentation fault.
0x00007ffff01cd635 in QStyleSheetStyle::styleHint (this=0x5555566bc700, sh=QStyle::SH_ScrollBar_Transient, opt=0x0, 
    w=0x555556791f00, shret=0x0) at styles/qstylesheetstyle.cpp:5460
5460	   return baseStyle()->styleHint(sh, opt, w, shret);
(gdb) bt
#0  0x00007ffff01cd635 in QStyleSheetStyle::styleHint (this=0x5555566bc700, sh=QStyle::SH_ScrollBar_Transient, opt=0x0, w=0x555556791f00, shret=0x0) at styles/qstylesheetstyle.cpp:5460
#1  0x00007ffff0223d70 in QAbstractScrollAreaPrivate::layoutChildren_helper (this=0x5555567a1c30, needHorizontalScrollbar=0x7fffffff7fc6, needVerticalScrollbar=0x7fffffff7fc7) at widgets/qabstractscrollarea.cpp:332
#2  0x00007ffff0223ca4 in QAbstractScrollAreaPrivate::layoutChildren (this=0x5555567a1c30) at widgets/qabstractscrollarea.cpp:322
#3  0x00007ffff0225ec1 in QAbstractScrollArea::event (this=0x5555567927f0, e=0x7fffffff8b10) at widgets/qabstractscrollarea.cpp:936
#4  0x00007ffff0417f66 in QAbstractItemView::event (this=0x5555567927f0, event=0x7fffffff8b10) at itemviews/qabstractitemview.cpp:1675
#5  0x00007ffff0784ff3 in sipQTreeView::event(QEvent*) () from /home/florian/proj/qutebrowser/git/.venv-515/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#6  0x00007ffff00dd8fb in QApplicationPrivate::notify_helper (this=0x55555567c5c0, receiver=0x5555567927f0, e=0x7fffffff8b10) at kernel/qapplication.cpp:3632
#7  0x00007ffff00dd6ec in QApplication::notify (this=0x5555562286b0, receiver=0x5555567927f0, e=0x7fffffff8b10) at kernel/qapplication.cpp:3582
#8  0x00007ffff0991b5e in sipQApplication::notify(QObject*, QEvent*) () from /home/florian/proj/qutebrowser/git/.venv-515/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#9  0x00007ffff4b72d99 in QCoreApplication::notifyInternal2 (receiver=0x5555567927f0, event=0x7fffffff8b10) at kernel/qcoreapplication.cpp:1064
#10 0x00007ffff4b72e38 in QCoreApplication::forwardEvent (receiver=0x5555567927f0, event=0x7fffffff8b10, originatingEvent=0x0) at kernel/qcoreapplication.cpp:1079
#11 0x00007ffff015d1ca in QWidgetWindow::handleResizeEvent (this=0x5555567c7c10, event=0x7fffffff8b10) at kernel/qwidgetwindow.cpp:829
#12 0x00007ffff015ae53 in QWidgetWindow::event (this=0x5555567c7c10, event=0x7fffffff8b10) at kernel/qwidgetwindow.cpp:322
#13 0x00007ffff00dd8fb in QApplicationPrivate::notify_helper (this=0x55555567c5c0, receiver=0x5555567c7c10, e=0x7fffffff8b10) at kernel/qapplication.cpp:3632
#14 0x00007ffff00dac39 in QApplication::notify (this=0x5555562286b0, receiver=0x5555567c7c10, e=0x7fffffff8b10) at kernel/qapplication.cpp:2972
#15 0x00007ffff0991b5e in sipQApplication::notify(QObject*, QEvent*) () from /home/florian/proj/qutebrowser/git/.venv-515/lib/python3.8/site-packages/PyQt5/QtWidgets.abi3.so
#16 0x00007ffff4b72d99 in QCoreApplication::notifyInternal2 (receiver=0x5555567c7c10, event=0x7fffffff8b10) at kernel/qcoreapplication.cpp:1064
#17 0x00007ffff4b7382a in QCoreApplication::sendSpontaneousEvent (receiver=0x5555567c7c10, event=0x7fffffff8b10) at kernel/qcoreapplication.cpp:1471
#18 0x00007ffff1505aa4 in QGuiApplicationPrivate::processGeometryChangeEvent (e=0x5555567d1d30) at kernel/qguiapplication.cpp:2607
#19 0x00007ffff1503728 in QGuiApplicationPrivate::processWindowSystemEvent (e=0x5555567d1d30) at kernel/qguiapplication.cpp:2014
#20 0x00007ffff14e12ef in QWindowSystemInterface::sendWindowSystemEvents (flags=...) at kernel/qwindowsysteminterface.cpp:1169
#21 0x00007fffd149e9b6 in xcbSourceDispatch (source=0x5555563d4230) at qxcbeventdispatcher.cpp:105
#22 0x00007ffff2151914 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#23 0x00007ffff21a57d1 in ?? () from /usr/lib/libglib-2.0.so.0
#24 0x00007ffff2150121 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#25 0x00007ffff4c0c1bb in QEventDispatcherGlib::processEvents (this=0x5555563d1520, flags=...) at kernel/qeventdispatcher_glib.cpp:423
#26 0x00007fffd149ebe8 in QXcbGlibEventDispatcher::processEvents (this=0x5555563d1520, flags=...) at qxcbeventdispatcher.cpp:143
#27 0x00007ffff4b733b8 in QCoreApplication::processEvents (flags=...) at kernel/qcoreapplication.cpp:1285
```
