### ISSUE TITLE
AUR: importlib_resources was not found

### ISSUE THREAD

**Issue by andys8** [qutebrowser/qutebrowser#5968]
**Version info**: qutebrowser-git 1.14.1.r372.g2e65f731b-1

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**

The current release `1.14.1` seems to be broken on Arch/Manjaro. I don't know if this has to be solved in this repository or the [`PKGBUILD`](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=qutebrowser-git) (and where this would be tracked).

```
The 'importlib_resources>=1.1.0' distribution was not found and is required by qutebrowser
```

Maybe related:

https://github.com/qutebrowser/qutebrowser/pull/5946
https://github.com/qutebrowser/qutebrowser/commit/1649c6fe1990367c73b600c445fb266ac0a9c102

These recent changes seem to be added after the release, that might be broken on arch.

```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==1.14.1', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.8/site-packages/qutebrowser/qutebrowser.py", line 197, in main
    earlyinit.early_init(args)
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/earlyinit.py", line 297, in early_init
    check_libraries()
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/earlyinit.py", line 238, in check_libraries
    _check_modules(modules)
  File "/usr/lib/python3.8/site-packages/qutebrowser/misc/earlyinit.py", line 220, in _check_modules
    importlib.import_module(name)
  File "/usr/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3239, in <module>
    def _initialize_master_working_set():
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3222, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 3251, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 567, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 884, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 770, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'importlib_resources>=1.1.0' distribution was not found and is required by qutebrowser
```

**How to reproduce**

* Install https://aur.archlinux.org/packages/qutebrowser-git
* Run `qutebrowser` or `qutebrowser --version`

**System**

Python: 3.8.6
OS: Manjaro 20.2 Nibia
Kernel: x86_64 Linux 5.4.77-1-MANJARO

**Comment by The-Compiler** [comment]
The `importlib_resources` dependency is not needed with Python 3.9, which is what Archlinux ships with - given that the AUR is targeted at Archlinux (rather than Manjaro), you will need to install that dependency manually, if Manjaro didn't upgrade to Python 3.9 yet (something Archlinux did [almost 6 weeks ago](https://github.com/archlinux/svntogit-packages/commit/af120a8e7631cd55ee01e397316c30d29cc40f73#diff-3e341d2d9c67be01819b25b25d5e53ea3cdf3a38d28846cda85a195eb9b7203a)).

**Comment by andys8** [comment]
Okay, will do that for now. Installing `python-importlib_resources` manually does work.

```
yay -S python-importlib_resources
```
