### ISSUE TITLE
Improve error messages for changed dotted paths for settings

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#5991]
For trivial cases, we can already show that a setting was renamed/deleted. However, we don't do that nicely with e.g. the recent adblock rename.

With this `config.py`:

```python
config.load_autoconfig(False)
c.content.host_blocking.lists = ["/home/florian/.config/qutebrowser/blocked_hosts"]
```

The following error gets shown:

> - **While getting 'content.host_blocking':** No option 'content.host_blocking'
> - **Unhandled exception:** 'NoneType' object has no attribute 'lists'
>
> ````
> Traceback (most recent call last):
>   File "/home/florian/proj/qutebrowser/git/qutebrowser/config/configfiles.py", line 805, in read_config_py
>     exec(code, module.__dict__)
>   File "/tmp/block/config/config.py", line 2, in <module>
>     c.content.host_blocking.lists = ["/home/florian/.config/qutebrowser/blocked_hosts"]
> AttributeError: 'NoneType' object has no attribute 'lists'
> ````

**Comment by The-Compiler** [comment]
Definitely something to look at before v2.0 - two people were confused about the error already.

**Comment by The-Compiler** [comment]
There's actually some more room for improvement here. The commit message of 2c382a761de5c72071bfc952e11c608016139c1f explains the details - but we could actually look through all errors at the end, and remove NoOptionErrors which are "shadowed" by more specific ones.
