### ISSUE TITLE
AttributeError: partially initialized module 'yaml' has no attribute '__with_libyaml__' (most likely due to a circular import)

### ISSUE THREAD

**Issue by skuzzymiglet** [qutebrowser/qutebrowser#6055]
**Version info**:

Could not start qutebrowser, not available

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

Launching qutebrowser causes this error:

```
Traceback (most recent call last):
  File "/home/skuzzymiglet/.local/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==1.14.1', 'gui_scripts', 'qutebrowser')())
  File "/home/skuzzymiglet/.local/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 200, in main
    earlyinit.early_init(args)
  File "/home/skuzzymiglet/.local/lib/python3.9/site-packages/qutebrowser/misc/earlyinit.py", line 310, in early_init
    check_libraries()
  File "/home/skuzzymiglet/.local/lib/python3.9/site-packages/qutebrowser/misc/earlyinit.py", line 246, in check_libraries
    _check_modules(modules)
  File "/home/skuzzymiglet/.local/lib/python3.9/site-packages/qutebrowser/misc/earlyinit.py", line 228, in _check_modules
    importlib.import_module(name)
  File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/home/skuzzymiglet/.local/lib/python3.9/site-packages/yaml/__init__.py", line 13, in <module>
    from .cyaml import *
  File "/home/skuzzymiglet/.local/lib/python3.9/site-packages/yaml/cyaml.py", line 7, in <module>
    from _yaml import CParser, CEmitter
  File "/usr/lib/python3.9/site-packages/_yaml/__init__.py", line 8, in <module>
    if not yaml.__with_libyaml__:
AttributeError: partially initialized module 'yaml' has no attribute '__with_libyaml__'
(most likely due to a circular import)
```

**How to reproduce**

Install from pip or Void Linux repos.

**Comment by skuzzymiglet** [comment]
Seems to have dissappeared after updating all pip packages

**Comment by The-Compiler** [comment]
FWIW it looks like this was a PyYAML issue: https://github.com/yaml/pyyaml/issues/478
