### ISSUE TITLE
KeyError if changelog.html is not packaged

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6086]
```pytb
Traceback (most recent call last):
  File "/usr/local/bin/qutebrowser", line 11, in <module>
    load_entry_point('qutebrowser==2.0.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/local/lib/python3.8/dist-packages/qutebrowser-2.0.1-py3.8.egg/qutebrowser/qutebrowser.py", line 201, in main
    return app.run(args)
  File "/usr/local/lib/python3.8/dist-packages/qutebrowser-2.0.1-py3.8.egg/qutebrowser/app.py", line 128, in run
    init(args=args)
  File "/usr/local/lib/python3.8/dist-packages/qutebrowser-2.0.1-py3.8.egg/qutebrowser/app.py", line 170, in init
    _process_args(args)
  File "/usr/local/lib/python3.8/dist-packages/qutebrowser-2.0.1-py3.8.egg/qutebrowser/app.py", line 235, in _process_args
    _open_special_pages(args)
  File "/usr/local/lib/python3.8/dist-packages/qutebrowser-2.0.1-py3.8.egg/qutebrowser/app.py", line 398, in _open_special_pages
    changelog = utils.read_file('html/doc/changelog.html')
  File "/usr/local/lib/python3.8/dist-packages/qutebrowser-2.0.1-py3.8.egg/qutebrowser/utils/utils.py", line 243, in read_file
    return path.read_text(encoding='utf-8')
  File "/usr/lib/python3.8/zipfile.py", line 2329, in read_text
    with self.open() as strm:
  File "/usr/lib/python3.8/zipfile.py", line 1514, in open
    zinfo = self.getinfo(name)
  File "/usr/lib/python3.8/zipfile.py", line 1441, in getinfo
    raise KeyError(
KeyError: "There is no item named 'qutebrowser/html/doc/changelog.html' in the archive"
```

https://crashes.qutebrowser.org/view/376850fe

**Comment by The-Compiler** [comment]
Seems to affect pdf.js too: https://crashes.qutebrowser.org/view/2b6775c4

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/browser/webengine/webenginequtescheme.py", line 97, in requestStarted
    mimetype, data = qutescheme.data_for_url(url)
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/browser/qutescheme.py", line 165, in data_for_url
    mimetype, data = handler(url)
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/browser/qutescheme.py", line 118, in wrapper
    return self._function(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/browser/qutescheme.py", line 297, in qute_version
    version=version.version_info(),
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/utils/version.py", line 569, in version_info
    'pdf.js: {}'.format(_pdfjs_version()),
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/utils/version.py", line 440, in _pdfjs_version
    pdfjs_file, file_path = pdfjs.get_pdfjs_res_and_path('build/pdf.js')
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/browser/pdfjs.py", line 152, in get_pdfjs_res_and_path
    content = utils.read_file_binary(res_path)
  File "/usr/local/lib/python3.9/site-packages/qutebrowser-2.0.1-py3.9.egg/qutebrowser/utils/utils.py", line 256, in read_file_binary
    return path.read_bytes()
  File "/usr/lib64/python3.9/zipfile.py", line 2322, in read_bytes
    with self.open('rb') as strm:
  File "/usr/lib64/python3.9/zipfile.py", line 2306, in open
    stream = self.root.open(self.at, zip_mode, pwd=pwd)
  File "/usr/lib64/python3.9/zipfile.py", line 1502, in open
    zinfo = self.getinfo(name)
  File "/usr/lib64/python3.9/zipfile.py", line 1429, in getinfo
    raise KeyError(
KeyError: "There is no item named 'qutebrowser/3rdparty/pdfjs/build/pdf.js' in the archive"
```

**Comment by The-Compiler** [comment]
This looks like it's specific to Python 3.9 - older versions use the `zipp` backport which correctly raises `FileNotFoundError`; Python 3.10 also raises `FileNotFoundError` in this case.

I opened a Python bug: [Issue 43063: zipfile.Path / importlib.resources raises KeyError if a file wasn't found - Python tracker](https://bugs.python.org/issue43063)
