### ISSUE TITLE
AttributeError when right-clicking download bar

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6087]
```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/downloadview.py", line 159, in show_context_menu
    actions = self._get_menu_actions(item)
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/downloadview.py", line 144, in _get_menu_actions
    utils.set_clipboard, item.url().toDisplayString())))
AttributeError: 'NoneType' object has no attribute 'url'
```

https://crashes.qutebrowser.org/view/d3fdf35a
https://crashes.qutebrowser.org/view/130ae9f2

**Comment by The-Compiler** [comment]
Ouch, reproduced by right-clicking the downloads bar outside of a download item.
