### ISSUE TITLE
AttributeError when restarting into pre-v2.0.0

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6091]
```pytb
Traceback (most recent call last):
  File "/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==1.14.1', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 204, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 127, in run
    init(args=args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 156, in init
    _init_modules(args=args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 469, in _init_modules
    websettings.init(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/config/websettings.py", line 271, in init
    webenginesettings.init(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 482, in init
    if (args.enable_webengine_inspector and
AttributeError: 'Namespace' object has no attribute 'enable_webengine_inspector'
```

on v1.14.1 with:

```json
--json-args {"basedir": null, "config_py": null, "version": false, "temp_settings": [], "session": null, "override_restore": true, "target": null, "backend": null, "json_args": null, "temp_basedir_restarted": null, "desktop_file_name": "org.qutebrowser.qutebrowser", "loglevel": null, "logfilter": null, "loglines": 2000, "debug": false, "json_logging": false, "color": true, "force_color": false, "nowindow": false, "temp_basedir": false, "no_err_windows": false, "qt_arg": null, "qt_flag": null, "debug_flags": [], "command": [], "url": []}
```

https://crashes.qutebrowser.org/view/ce77b424

**Comment by The-Compiler** [comment]
I see two ways to fix this - probably *both* would make sense:

- Re-adding `--enable-webengine-inspector` as a hidden argument - so that it always get added to `--json-args` and no matter what the version being restarted into is, will always be accepted. Perhaps we could still error out if it's actually non-`None`.
- Future-proofing things by somehow first getting an `argparse.Namespace` with all-default arguments before we load the `--json-args` argument.
