### ISSUE TITLE
RegistryUnavailableError in _update_completion

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6122]
Noticed this popping up in the crash reports from time to time:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/completion/completer.py", line 260, in _update_completion
    cur_tab = objreg.get('tab', scope='tab', window=self._win_id,
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/objreg.py", line 241, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/objreg.py", line 223, in _get_registry
    return _get_tab_registry(window, tab)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/objreg.py", line 180, in _get_tab_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
```

https://crashes.qutebrowser.org/lists?search=RegistryUnavailableError

Already happens with v1.14.x though.

**Comment by The-Compiler** [comment]
Reproduced when calling `qutebrowser` a second time with an empty argument (i.e. `qutebrowser --basedir /tmp/x ""`):

```
22:05:31 DEBUG    ipc        ipc:_handle_data:320 Processing: {"args": [""], "target_arg": null, "version": "2.0.1", "protocol_version": 1, "cwd": "/home/florian/proj/qutebrowser/git"}

22:05:31 DEBUG    init       app:process_pos_args:277 Empty argument
```

We will then end up with a window without any tabs which will crash when pressing `:`.

**Comment by The-Compiler** [comment]
So the original idea in 6e61f4c58610a50310e90cd48eb4e059d3e03338 actually was to treat an empty argument as a window separator. This is still documented, but doesn't seem to work anymore either.

I suspect either efaa721ef72953786db05b305815e801d2dcd52a or efac9a092b1e33d88414bf11f33cc25c0b14888d broke this, though I haven't checked in detail yet.

The main issue here is that [open_url_in_instance.sh](https://github.com/qutebrowser/qutebrowser/blob/384527ce35aaef43c2db84e20fa9cfef8e96341f/scripts/open_url_in_instance.sh) sends a single empty argument if it's started without a commandline argument given to it...
