### ISSUE TITLE
Error on start of qutebrowser

### ISSUE THREAD

**Issue by alexandre1985** [qutebrowser/qutebrowser#6155]
**Version info**:
2.0.2-1

**Does the bug happen if you start with `--temp-basedir`?**:
It does not

**Description**
Cannot start qutebrowser

**How to reproduce**

$ qutebrowser 
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.0.2', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 208, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 88, in run
    standarddir.init(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/standarddir.py", line 340, in init
    _init_dirs(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/standarddir.py", line 327, in _init_dirs
    _init_config(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/standarddir.py", line 90, in _init_config
    _create(path)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/standarddir.py", line 319, in _create
    os.makedirs(path, 0o700, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '/home/daniel/.config/qutebrowser'

**Comment by alexandre1985** [comment]
My issue.
I had a symlink in $HOME/.config/qutebrowser that was not getting reached.
It is fixed now.
Sorry!
