### ISSUE TITLE
Move backend library checking to earlyinit

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6161]
Right now we check for QtWebEngine/QtWebKit being available in `backendproblem.py`. However, this is kinda late, and can lead to accidentally assuming that QtWebEngine is really available if it was selected as a backend. This happened with 94967ee979350271a0e8ff9dcbbad4cab50236e5:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/__main__.py", line 29, in <module>
    sys.exit(qutebrowser.qutebrowser.main())
  File "/home/florian/proj/qutebrowser/git/qutebrowser/qutebrowser.py", line 217, in main
    return app.run(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 95, in run
    app = Application(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/app.py", line 554, in __init__
    qt_args = qtargs.qt_args(args)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/qtargs.py", line 64, in qt_args
    argv += list(_qtwebengine_args(namespace, special_flags))
  File "/home/florian/proj/qutebrowser/git/qutebrowser/config/qtargs.py", line 151, in _qtwebengine_args
    versions = version.qtwebengine_versions(avoid_init=True)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/utils/version.py", line 609, in qtwebengine_versions
    assert webenginesettings is not None
AssertionError
```

**Comment by The-Compiler** [comment]
I've had to take a slightly different approach here because there are some benefits to having it in `backendproblem.py` (mainly nicer error dialogs). At least now there's a test for the error message.
