### ISSUE TITLE
FileNotFoundError with fileselect file

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6175]
https://crashes.qutebrowser.org/view/2b4a85eb

```
20:03:45 DEBUG    procs      guiprocess:_pre_start:154 Executing: kitty nnn -p /tmp/qutebrowser-fileselect-kqiigxcd
[...]
20:03:48 DEBUG    procs      guiprocess:_on_finished:91 Process finished with code 0, status 0.
20:03:48 ERROR    misc       utils:cleanup_file:891 Failed to delete tempfile /tmp/qutebrowser-fileselect-kqiigxcd ([Errno 2] No such file or directory: '/tmp/qutebrowser-fileselect-kqiigxcd')!
20:03:48 ERROR    misc       crashsignal:_handle_early_exits:240 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/webengine/webview.py", line 255, in chooseFiles
    return shared.choose_file(
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/shared.py", line 375, in choose_file
    with open(tmpfilename, mode='r', encoding=sys.getfilesystemencoding()) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qutebrowser-fileselect-kqiigxcd'
```

Not sure how they managed to (probably accidentally?) delete that file via `nnn`, but we should probably handle `OSError` in general there (which includes `FileNotFoundError`.

@AckslD Is this something you want to take a look at?

**Comment by The-Compiler** [comment]
Ah, no, we don't create the file at all - we just blindly assume it exists. Thus, if the terminal window with `nnn` gets closed (probably with `vifm` / `ranger` as well, but I didn't check), then the exception will happen.

**Comment by AckslD** [comment]
@The-Compiler Sure thing, I'll open a PR tomorrow :+1:
