### ISSUE TITLE
QCoreApplication.libraryPaths() is empty with non-ascii paths

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6224]
```
─[florian@aragog]──[~/proj/qutebrowser/git]──[21-03-01]──[21:48]──[git/master]────┄
$ .tox/py39-pyqt515-cov/bin/python3
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import QCoreApplication
>>> QCoreApplication.libraryPaths()
['/home/florian/proj/qutebrowser/git/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/PyQt5/Qt/plugins']
```

vs.

```
─[florian@aragog]──[~/tmp/Téléchargements/qutebrowser]──[21-03-01]──[21:48]──[git/master]────┄
$ .tox/py39-pyqt515-cov/bin/python3
Python 3.9.2 (default, Feb 20 2021, 18:40:11) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PyQt5.QtCore import QCoreApplication
>>> QCoreApplication.libraryPaths()
[]
```

which causes:

```
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 269, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 322, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 333, in pytest_collection
INTERNALERROR>     session.perform_collect()
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 637, in perform_collect
INTERNALERROR>     hook.pytest_collection_modifyitems(
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286, in __call__
INTERNALERROR>     return self._hookexec(self, self.get_hookimpls(), kwargs)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84, in <lambda>
INTERNALERROR>     self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 208, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 80, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/florian/tmp/Téléchargements/qutebrowser/tests/end2end/conftest.py", line 145, in pytest_collection_modifyitems
INTERNALERROR>     lib_path = pathlib.Path(QCoreApplication.libraryPaths()[0])
INTERNALERROR> IndexError: list index out of range
```

smells like a possible (Py)Qt bug, though?

cc @Lembrun

**Comment by The-Compiler** [comment]
After fixing that one:

```diff
diff --git i/tests/end2end/conftest.py w/tests/end2end/conftest.py
index 879ebc6de..132cac08a 100644
--- i/tests/end2end/conftest.py
+++ w/tests/end2end/conftest.py
@@ -142,8 +142,13 @@ def pytest_collection_modifyitems(config, items):
     # (note this isn't actually fixed properly before Qt 5.15)
     header_bug_fixed = qtutils.version_check('5.15', compiled=False)
 
-    lib_path = pathlib.Path(QCoreApplication.libraryPaths()[0])
-    qpdf_image_plugin = lib_path / 'imageformats' / 'libqpdf.so'
+    paths = QCoreApplication.libraryPaths()
+    if paths:
+        lib_path = pathlib.Path(paths[0])
+        qpdf_image_plugin = lib_path / 'imageformats' / 'libqpdf.so'
+        qpdf_image_plugin_exists = qpdf_image_plugin.exists()
+    else:
+        qpdf_image_plugin_exists = False
 
     markers = [
         ('qtwebengine_todo', 'QtWebEngine TODO', pytest.mark.xfail,
@@ -166,7 +171,7 @@ def pytest_collection_modifyitems(config, items):
         ('qtwebkit_pdf_imageformat_skip',
          'Skipped with QtWebKit if PDF image plugin is available',
          pytest.mark.skipif,
-         not config.webengine and qpdf_image_plugin.exists()),
+         not config.webengine and qpdf_image_plugin_exists),
         ('windows_skip',
          'Skipped on Windows',
          pytest.mark.skipif,

```

Qt itself then fails:

```
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Fatal Python error: Aborted

Current thread 0x00007fed6d1a1740 (most recent call first):
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pytestqt/plugin.py", line 57 in qapp
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 932 in call_fixture_func
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 1126 in pytest_fixture_setup
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 1072 in execute
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 687 in _compute_fixture_value
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 601 in _get_active_fixturedef
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 1048 in execute
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 687 in _compute_fixture_value
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 601 in _get_active_fixturedef
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 1048 in execute
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 687 in _compute_fixture_value
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 601 in _get_active_fixturedef
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 581 in getfixturevalue
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/fixtures.py", line 568 in _fillfixtures
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/python.py", line 1647 in setup
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 449 in prepare
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 150 in pytest_runtest_setup
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 255 in <lambda>
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 311 in from_call
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 254 in call_runtest_hook
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 215 in call_and_report
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 120 in runtestprotocol
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/runner.py", line 109 in pytest_runtest_protocol
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 348 in pytest_runtestloop
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 323 in _main
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 269 in wrap_session
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/main.py", line 316 in pytest_cmdline_main
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/callers.py", line 187 in _multicall
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 84 in <lambda>
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/manager.py", line 93 in _hookexec
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pluggy/hooks.py", line 286 in __call__
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/config/__init__.py", line 162 in main
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/_pytest/config/__init__.py", line 185 in console_main
  File "/home/florian/tmp/T\xe9l\xe9chargements/qutebrowser/.tox/py39-pyqt515-cov/lib/python3.9/site-packages/pytest/__main__.py", line 5 in <module>
  File "/usr/lib/python3.9/runpy.py", line 87 in _run_code
  File "/usr/lib/python3.9/runpy.py", line 197 in _run_module_as_main
```

This is weird. Is this really just not supported by Qt/PyQt?

**Comment by Lembrun** [comment]
After uninstalling some python packages with my system package manager,I get this  instead

```
amadeus $ tox
___________________________________________________________________________________________ summary ___________________________________________________________________________________________
ERROR:   py38-pyqt515-cov: undefined
ERROR:   mypy: undefined
ERROR:   misc: undefined
ERROR:   vulture: undefined
ERROR:   flake8: undefined
ERROR:   pylint: undefined
ERROR:   pyroma: undefined
ERROR:   check-manifest: undefined
ERROR:   eslint: undefined
ERROR:   yamllint: undefined
Traceback (most recent call last):
  File "/home/amadeus/.local/bin/tox", line 8, in <module>
    sys.exit(cmdline())
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/session/__init__.py", line 44, in cmdline
    main(args)
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/session/__init__.py", line 69, in main
    exit_code = session.runcommand()
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/session/__init__.py", line 197, in runcommand
    return self.subcommand_test()
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/session/__init__.py", line 225, in subcommand_test
    run_sequential(self.config, self.venv_dict)
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/session/commands/run/sequential.py", line 9, in run_sequential
    if venv.setupenv():
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/venv.py", line 623, in setupenv
    with self.new_action("getenv", self.envconfig.envdir) as action:
  File "/home/amadeus/.local/lib64/python2.7/site-packages/tox/action.py", line 58, in __enter__
    msg = "{} {}".format(self.msg, " ".join(map(str, self.args)))
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 15: ordinal not in range(128)
```

Trying to build venv same err as above

```
amadeus $ python3 scripts/mkvenv.py                                                                                                                                       

==================== Creating virtual environment ====================
$ rm -r .venv
$ python3 -m venv .venv

==================== Upgrading initial packages ====================
venv$ pip install -U pip
Collecting pip
  Using cached pip-21.0.1-py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.2.3
    Uninstalling pip-20.2.3:
      Successfully uninstalled pip-20.2.3
Successfully installed pip-21.0.1
venv$ pip install -U setuptools wheel
Requirement already satisfied: setuptools in ./.venv/lib/python3.9/site-packages (49.2.1)
Collecting setuptools
  Using cached setuptools-54.0.0-py3-none-any.whl (784 kB)
Collecting wheel
  Using cached wheel-0.36.2-py2.py3-none-any.whl (35 kB)
Installing collected packages: wheel, setuptools
  Attempting uninstall: setuptools
    Found existing installation: setuptools 49.2.1
    Uninstalling setuptools-49.2.1:
      Successfully uninstalled setuptools-49.2.1
Successfully installed setuptools-54.0.0 wheel-0.36.2

==================== Installing PyQt from binary ====================
No proprietary codec support will be available in qutebrowser.
venv$ pip install -r /home/amadeus/Téléchargements/qutebrowser/misc/requirements/requirements-pyqt.txt --only-binary PyQt5,PyQtWebEngine
Collecting PyQt5==5.15.2
  Using cached PyQt5-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (68.3 MB)
Collecting PyQt5-sip==12.8.1
  Using cached PyQt5_sip-12.8.1-cp39-cp39-manylinux1_x86_64.whl (286 kB)
Collecting PyQtWebEngine==5.15.2
  Using cached PyQtWebEngine-5.15.2-5.15.2-cp35.cp36.cp37.cp38.cp39-abi3-manylinux2014_x86_64.whl (67.7 MB)
Installing collected packages: PyQt5-sip, PyQt5, PyQtWebEngine
Successfully installed PyQt5-5.15.2 PyQt5-sip-12.8.1 PyQtWebEngine-5.15.2

==================== Running xcb-util workaround ====================
Failed to match ldconfig output: 4852 libs trouvé dans le cache « /etc/ld.so.cache »
Failed to match ldconfig output: Cache generated by: ldconfig (GNU libc) release release version 2.33
Workaround not needed: libxcb-util.so.1 found.

==================== Running Qt smoke test ====================
Python: 3.9.2 (default, Feb 19 2021, 13:07:40)
[GCC 10.2.0]
qVersion: 5.15.2
QT_VERSION_STR: 5.15.2
PYQT_VERSION_STR: 5.15.2
QFactoryLoader::QFactoryLoader() checking directory path "/home/amadeus/Téléchargements/qutebrowser/.venv/bin/platforms" ...
qt.qpa.plugin: Could not find the Qt platform plugin "xcb" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.


```

Note that I did manage to build the venv by manually exporting qt.qpa.plugin to libxcb and after that copying/symlinking everything that was required (resources,location...) to the .venv/bin

`export QT_PLUGIN_PATH=/home/amadeus/Téléchargements/qutebrowser/.venv/lib64/python3.9/site-packages/PyQt5/Qt/plugins/`

`QTWEBENGINEPROCESS_PATH=$PWD/.venv/lib/python3.8/site-packages/PyQt5/Qt/libexec/QtWebEngineProcess .venv/bin/python3 -m qutebrowser --temp-basedir`

**Comment by The-Compiler** [comment]
@Lembrun That's an unrelated issue, and most likely solved by not using Python 2 (which has been end-of-life since January 2020). Depending on your distribution, you might need to run `tox3` instead.

**Comment by Lembrun** [comment]
Yup ignore previous comment
