### ISSUE TITLE
TypeError during distribution version parsing on NixOS

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6354]
```
  File "/nix/store/v3hvsr689f5kn6sbzhigpgs4lk61hwyj-qutebrowser-2.1.0/lib/python3.8/site-packages/qutebrowser/browser/webengine/webengineinspector.py", line 62, in __init__
    self._check_devtools_resources()
  File "/nix/store/v3hvsr689f5kn6sbzhigpgs4lk61hwyj-qutebrowser-2.1.0/lib/python3.8/site-packages/qutebrowser/browser/webengine/webengineinspector.py", line 76, in _check_devtools_resources
    dist = version.distribution()
  File "/nix/store/v3hvsr689f5kn6sbzhigpgs4lk61hwyj-qutebrowser-2.1.0/lib/python3.8/site-packages/qutebrowser/utils/version.py", line 163, in distribution
    dist_version = utils.VersionNumber.parse(info[version_key])
  File "/nix/store/v3hvsr689f5kn6sbzhigpgs4lk61hwyj-qutebrowser-2.1.0/lib/python3.8/site-packages/qutebrowser/utils/utils.py", line 129, in parse
    return cls(*ver.normalized().segments())
  File "/nix/store/v3hvsr689f5kn6sbzhigpgs4lk61hwyj-qutebrowser-2.1.0/lib/python3.8/site-packages/qutebrowser/utils/utils.py", line 92, in __init__
    self._ver = QVersionNumber(*args)
TypeError: arguments did not match any overloaded call:
  QVersionNumber(): too many arguments
  QVersionNumber(Iterable[int]): argument 1 has unexpected type 'int'
  QVersionNumber(int): too many arguments
  QVersionNumber(int, int): too many arguments
  QVersionNumber(int, int, int): too many arguments
  QVersionNumber(QVersionNumber): argument 1 has unexpected type 'int'
```

https://crashes.qutebrowser.org/view/7045e3c6

**Comment by The-Compiler** [comment]
```
>>> from PyQt5.QtCore import QVersionNumber
>>> v = QVersionNumber.fromString('1.2.3.4.5')[0]
>>> v.segments()
[1, 2, 3, 4, 5]
>>> v2 = QVersionNumber(*v.segments())
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: arguments did not match any overloaded call:
  QVersionNumber(): too many arguments
  QVersionNumber(Iterable[int]): argument 1 has unexpected type 'int'
  QVersionNumber(int): too many arguments
  QVersionNumber(int, int): too many arguments
  QVersionNumber(int, int, int): too many arguments
  QVersionNumber(QVersionNumber): argument 1 has unexpected type 'int'
>>> v2 = QVersionNumber(v.segments())
>>> v2.segments()
[1, 2, 3, 4, 5]
```
