### ISSUE TITLE
QtValueError: QRegularExpression(...) is not valid: regular expression is too large (take 2)

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6355]
Even after the trimming fix from #5973, I get crash reports with that error: https://crashes.qutebrowser.org/view/7045e3c6

We should probably not even attempt the trimming, and just error out in some sane way.

**Comment by The-Compiler** [comment]
Another report in `170713137625.8881.5658762370275919602@crashes.qutebrowser.org`:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qutebrowser/completion/[completiondelegate.py](http://completiondelegate.py/)", line 308, in paint
    self._draw_text(index)
  File "/usr/lib/python3.11/site-packages/qutebrowser/completion/[completiondelegate.py](http://completiondelegate.py/)", line 158, in _draw_text
    self._get_textdoc(index)
  File "/usr/lib/python3.11/site-packages/qutebrowser/completion/[completiondelegate.py](http://completiondelegate.py/)", line 230, in _get_textdoc
    _Highlighter(self._doc, pattern, color)
  File "/usr/lib/python3.11/site-packages/qutebrowser/completion/[completiondelegate.py](http://completiondelegate.py/)", line 36, in __init__
    qtutils.ensure_valid(self._expression)
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/[qtutils.py](http://qtutils.py/)", line 183, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: PyQt6.QtCore.QRegularExpression('https://viewer\\.diagrams\\.net/\\?tags=%7B%7D\\&highlight=0000ff\\&edit=_blank\\&layers=1\\&nav=1\\&title=Documents\\#...', PyQt6.QtCore.QRegularExpression.PatternOptions(1)) is not valid: regular expression is too large
```

with the total URL being 32767 characters long (as printed)
