### ISSUE TITLE
notifications: Padding assertion hit

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6375]
```
01:58:38 ERROR    misc       crashsignal:_handle_early_exits:240 Uncaught exception
Traceback (most recent call last):
  File "/home/trysdyn/workspace/qutebrowser/qutebrowser/browser/webengine/notification.py", line 262, in present
    notification_id = self._adapter.present(
  File "/home/trysdyn/workspace/qutebrowser/qutebrowser/browser/webengine/notification.py", line 934, in present
    data = self._convert_image(icon)
  File "/home/trysdyn/workspace/qutebrowser/qutebrowser/browser/webengine/notification.py", line 1032, in _convert_image
    assert 0 <= padding < 3, padding
AssertionError: 3
```

**Comment by trysdyn** [comment]
Hello. I sent a follow-up report from commit 76ee6f3 (which includes 54b81cb) after replicating the issue. The additional debug data looks to be present.

```
Traceback (most recent call last):
  File "/home/trysdyn/workspace/qutebrowser/qutebrowser/browser/webengine/notification.py", line 262, in present
    notification_id = self._adapter.present(
  File "/home/trysdyn/workspace/qutebrowser/qutebrowser/browser/webengine/notification.py", line 934, in present
    data = self._convert_image(icon)
  File "/home/trysdyn/workspace/qutebrowser/qutebrowser/browser/webengine/notification.py", line 1032, in _convert_image
    assert 0 <= padding < 3, (padding, bytes_per_line, width, channel_count)
AssertionError: (3, 720, 239, 3)
```

For some history: this happens on my self-hosted instance of an open source federated Twitter alternative (Mastodon / Pleroma if you're aware of the software suites). One specific user on another federated server has a profile image/avatar that consistently triggers this. Their profile image is hosted at https://dragon.style/system/accounts/avatars/000/113/007/original/RJ9HC5RH2UDB.png . Any time that image appears in a notification, I hit the assert. The linked image size and your assert's report of the image width seem to match up so I think that's our culprit.

Oddly so far it's **only** been this user/avatar that's done it. I'm quite chatty on Mastodon/Pleroma and no one else has an avatar that's managed to crash me.

**Comment by The-Compiler** [comment]
Yep, it's due to the dimensions (239x239) leading to 3 bytes of padding (239 mod 4 = 3). Clearly that condition should be `<= 3` rather than `< 3`, not sure what I was thinking. Thanks for the report!
