### ISSUE TITLE
IndexError with rl-unix-word-rubout and emoji

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6383]
On 46bedd5f6 with Qt 5.15.2, press `:`, paste 🔈 and hit Ctrl-W:

```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/keyinput/eventfilter.py", line 104, in eventFilter
    return handler(cast(QKeyEvent, event))
  File "/usr/lib/python3.9/site-packages/qutebrowser/keyinput/eventfilter.py", line 74, in _handle_key_event
    return man.handle_event(event)
  File "/usr/lib/python3.9/site-packages/qutebrowser/keyinput/modeman.py", line 468, in handle_event
    return handler(cast(QKeyEvent, event))
  File "/usr/lib/python3.9/site-packages/qutebrowser/keyinput/modeman.py", line 289, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
  File "/usr/lib/python3.9/site-packages/qutebrowser/keyinput/basekeyparser.py", line 324, in handle
    self.execute(result.command, count)
  File "/usr/lib/python3.9/site-packages/qutebrowser/keyinput/modeparsers.py", line 76, in execute
    self._commandrunner.run(cmdstr, count)
  File "/usr/lib/python3.9/site-packages/qutebrowser/commands/runners.py", line 374, in run
    result.cmd.run(self._win_id, args, count=count)
  File "/usr/lib/python3.9/site-packages/qutebrowser/commands/command.py", line 553, in run
    self.handler(*posargs, **kwargs)
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/readlinecommands.py", line 228, in rl_unix_word_rubout
    bridge.unix_word_rubout()
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/readlinecommands.py", line 119, in unix_word_rubout
    self._rubout([' '])
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/readlinecommands.py", line 105, in _rubout
    is_boundary = text[target_position - 1] in delim
IndexError: string index out of range
```

**Comment by The-Compiler** [comment]
Looks like Qt has a rather wrong cursor position:

```
(Pdb) cursor_position
3
(Pdb) text
':🔈'
(Pdb) len(text)
2
```

**Comment by The-Compiler** [comment]
Still present with qutebrowser v3.4.0 and Qt 6.8.2. Reproducer:

```
qutebrowser --temp-basedir  ":cmd-later 500 cmd-set-text :open 🏠" ":cmd-later 1000 rl-rubout ' '"
```
