### ISSUE TITLE
Deleting a unicode character outside of the BMP sometimes crashes the browser

### ISSUE THREAD

**Issue by m42a** [qutebrowser/qutebrowser#6455]
Reproduction steps:
1. Run the following command: `qutebrowser --temp-basedir -s 'url.searchengines' '{"e":"{}","DEFAULT":"{}"}' https://graphemica.com/%F0%9F%90%B8`
2. Press "o&lt;Tab&gt;&lt;Tab&gt;" to put the current page's url (which ends with the character 🐸) on the command line.
3. Press backspace to delete the 🐸 character

Full error:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/completion/completer.py", line 262, in _update_completion
    completion.set_pattern(pattern)
  File "/usr/lib/python3.9/site-packages/qutebrowser/completion/completionwidget.py", line 385, in set_pattern
    self.model().set_pattern(pattern)
  File "/usr/lib/python3.9/site-packages/qutebrowser/completion/models/completionmodel.py", line 184, in set_pattern
    cat.set_pattern(pattern)
  File "/usr/lib/python3.9/site-packages/qutebrowser/completion/models/listcategory.py", line 70, in set_pattern
    qtutils.ensure_valid(rx)
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/qtutils.py", line 169, in ensure_valid
    raise QtValueError(obj)
qutebrowser.utils.qtutils.QtValueError: PyQt5.QtCore.QRegularExpression('https://graphemica\\.com/\udc38', PyQt5.QtCore.QRegularExpression.PatternOptions(1)) is not valid: UTF-16 error: isolated low surrogate
```

This does not happen unless you have a non-DEFAULT search engine.  It does not happen if you use "go" to place the URL on the command-line, or if you use the arrow keys to move the cursor before deleting the character.

I suspect the cursor is somehow being placed in between the code units of the character, so backspace only deletes the first code unit and not the second.

**Comment by The-Compiler** [comment]
I can't reproduce. Pressing `o` would just put `:open ` (with a trailing space) in the command line, so pressing backspace then results in `:open`.

Could you please also show your `:version` information? There's a reason the bug template asks for it :wink:

**Comment by The-Compiler** [comment]
Ah, that makes sense now! Yeah, Markdown supports a HTML subset inline, so e.g. `<b>foo</b>` gets rendered as <b>foo</b>, but that means `<Tab>` will be handled as invalid HTML tag and disappear...

Reproduced now with the updated reproduction steps. It looks indeed at some point (during completion?) the :frog: probably gets split into two or so, and we end up with an input resulting in an invalid regex pattern.

Ideally this wouldn't happen at all, but if it does, we should at least not crash due to the regex error but instead display it somehow (also see #6355).

**Comment by rcorre** [comment]
I'm surprised I'm not seeing an easy way to make [QLineEdit](https://doc.qt.io/qt-5/qlineedit.html#textChanged) unicode-aware. You can't override `backspace()`. We could add more [keyPressEvent overrides](https://github.com/qutebrowser/qutebrowser/blob/7a0118119ef92adf1f68c6990ae5cac84aed3fec/qutebrowser/misc/miscwidgets.py#L54) to catch backspace/del/ect. and handle those actions ourselves, but it feels like a bit of a hack.

**Comment by The-Compiler** [comment]
I don't think QLineEdit itself is the problem: Like mentioned, if you go to https://graphemica.com/%F0%9F%90%B8, press `go` and press backspace, the frog gets deleted correctly.

However, when the same data is coming in from the history completion, something different happens - I suspect the data is encoded differently somehow after making the round-trip through sqlite?

**Comment by rcorre** [comment]
Ah yes, if you bookmark that site, it shows in the completion as `https://graphemica.com/%F0%9F%90%B8`

**Comment by rcorre** [comment]
Aha, we fully encode URLs that are stored in the history table, but not the completion table: https://github.com/qutebrowser/qutebrowser/blob/7a0118119ef92adf1f68c6990ae5cac84aed3fec/qutebrowser/browser/history.py#L430-L434

So an easy fix would be to urlencode completion urls too. I'm not sure that's desired though (I'm not even sure that's ideal for quick/bookmarks?)

**Comment by The-Compiler** [comment]
Couldn't recreate this just now, but I got another error during shutdown:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/savemanager.py", line 212, in shutdown
    self.save(key, is_exit=True)
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/savemanager.py", line 166, in save
    self.saveables[name].save(is_exit=is_exit, explicit=explicit,
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/savemanager.py", line 100, in save
    self._save_handler()
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/lineparser.py", line 241, in save
    self._write(f, self.data[-limit:])
  File "/usr/lib/python3.9/site-packages/qutebrowser/misc/lineparser.py", line 123, in _write
    fp.write('\n'.join(data))
UnicodeEncodeError: 'utf-8' codec can't encode character '\ude2d' in position 100: surrogates not allowed
```

and someone reported going a similar error in the crash reporter too.

**Comment by The-Compiler** [comment]
Another report of this happening: https://crashes.qutebrowser.org/view/34a79087
