### ISSUE TITLE
DeserializationError from Brave adblock library

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6489]
[Crash report](https://crashes.qutebrowser.org/view/1c41bcd3):

```pytb
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.2.2', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 220, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 125, in run
    init(args=args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 158, in init
    loader.load_components()
  File "/usr/lib/python3.9/site-packages/qutebrowser/extensions/loader.py", line 86, in load_components
    _load_component(info, skip_hooks=skip_hooks)
  File "/usr/lib/python3.9/site-packages/qutebrowser/extensions/loader.py", line 161, in _load_component
    mod_info.init_hook(_get_init_context())
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/braveadblock.py", line 307, in init
    ad_blocker.read_cache()
  File "/usr/lib/python3.9/site-packages/qutebrowser/components/braveadblock.py", line 214, in read_cache
    self._engine.deserialize_from_file(str(self._cache_path))
ValueError: DeserializationError
```

with

```
qutebrowser v2.2.2
adblock: 0.4.4
```

Not sure how and why something apparently got corrupted, but we should probably handle this somehow and present an error to the user asking them to run `:adblock-update`.

cc @ArniDagur

**Comment by ArniDagur** [comment]
As you say, the simplest solution would probably be to ask the user to perform `:adblock-update`. That should delete the old cache file.

**Comment by ArniDagur** [comment]
I should probably make it so that not all exceptions become ValueError. I opened https://github.com/ArniDagur/python-adblock/issues/44

**Comment by The-Compiler** [comment]
Yeah - would be great if those were all different python exceptions, inheriting from an `adblock.Error` base class or so.
