### ISSUE TITLE
Invalid SSL certificate causes AssertionError on Qt 5.14

### ISSUE THREAD

**Issue by user202729** [qutebrowser/qutebrowser#6564]
**Version info**:

Latest upstream master.

(qt 5.14 only, cannot reproduce on 5.15)

**Does the bug happen if you start with `--temp-basedir`?**:

Yes.

**How to reproduce**

(note: the mentioned site might fix the SSL error soon.)

* start with temp base dir
* Type `:open -t https://codeforces.com`, press enter, wait for a while, get "server certificate is expired" error
* press escape
* Type `:open -t https://codeforces.com` (again), press enter, wait for a while
* Get   

	```
	File "qutebrowser/browser/webengine/webenginetab.py", line 1549, in _on_ssl_errors
		assert self.data.last_navigation is not None
	```

	as result.

It's not deterministic. Could be a race condition.

**Comment by The-Compiler** [comment]
Reproduced with `.tox/py39-pyqt514/bin/python3 -m qutebrowser --temp-basedir --debug 'https://codeforces.com' ':later 2000 prompt-accept no' ':later 4000 open -t https://codeforces.com'` - logs:

<details>

````
17:59:53 DEBUG    url        urlutils:get_path_if_valid:366 Checking if 'https://codeforces.com' is a path
17:59:53 DEBUG    url        urlutils:is_url:271 Checking if 'https://codeforces.com' is a URL (autosearch=naive).
17:59:53 DEBUG    url        urlutils:is_url:294 Contains explicit scheme
17:59:53 DEBUG    url        urlutils:is_url:318 url = True
17:59:53 DEBUG    url        urlutils:fuzzy_url:225 URL is a fuzzy address
17:59:53 DEBUG    url        urlutils:fuzzy_url:227 Converting fuzzy term 'https://codeforces.com' to URL -> https://codeforces.com
17:59:53 DEBUG    init       app:open_url:314 About to open URL: https://codeforces.com
17:59:53 DEBUG    webview    tabbedbrowser:tabopen:593 Creating new tab with URL PyQt5.QtCore.QUrl('https://codeforces.com'), background False, related False, idx None
17:59:53 DEBUG    webview    tabbedbrowser:_get_new_tab_idx:680 tabs.new_position last -> opening new tab at -1, next left: 0 / right: -1
17:59:53 DEBUG    modes      tabbedbrowser:_on_current_changed:832 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url=''>
17:59:53 DEBUG    modes      tabbedbrowser:_on_current_changed:839 Mode before tab change: normal (mode_on_change = normal)
17:59:53 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
17:59:53 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
17:59:53 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
17:59:53 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
17:59:53 DEBUG    modes      tabbedbrowser:_on_current_changed:850 Mode after tab change: normal (mode_on_change = normal)
17:59:53 DEBUG    webview    browsertab:_on_before_load_started:1041 Going to start loading: https://codeforces.com
17:59:53 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 0 to 'https://codeforces.com'
17:59:53 DEBUG    misc       eventfilter:eventFilter:53 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7ff38c389d30> got new child <PyQt5.QtWidgets.QWidget object at 0x7ff38c38c790>, installing filter
17:59:53 DEBUG    init       app:process_pos_args:273 Startup cmd ':later 2000 prompt-accept no'
17:59:53 DEBUG    commands   command:run:537 command called: later ['2000', 'prompt-accept no']
17:59:53 DEBUG    commands   command:run:551 Calling qutebrowser.misc.utilcmds.later('2000', 'prompt-accept no', 0)
17:59:53 DEBUG    init       app:process_pos_args:273 Startup cmd ':later 4000 open -t https://codeforces.com'
17:59:53 DEBUG    commands   command:run:537 command called: later ['4000', 'open -t https://codeforces.com']
17:59:53 DEBUG    commands   command:run:551 Calling qutebrowser.misc.utilcmds.later('4000', 'open -t https://codeforces.com', 0)
17:59:53 DEBUG    init       app:_process_args:238 Init finished after 1.364439s
17:59:53 DEBUG    init       app:init:176 Init done!
17:59:53 DEBUG    misc       mainwindow:_update_overlay_geometry:350 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7ff3ac043ca0>: PyQt5.QtCore.QRect(0, 581, 801, 1)
17:59:53 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 0 to 'https://codeforces.com/'
17:59:53 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://codeforces.com/')) (tab 0)
17:59:53 DEBUG    misc       mainwindow:_update_overlay_geometry:350 new geometry for <qutebrowser.mainwindow.messageview.MessageView object at 0x7ff3ac043ca0>: PyQt5.QtCore.QRect(0, 1017, 470, 1)
17:59:54 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7ff38c38c940>
17:59:54 DEBUG    webview    webenginetab:_store_match_data:151 Active search match: 0/0
17:59:54 DEBUG    webview    browsertab:_set_load_status:1007 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://codeforces.com/'>: LoadStatus.loading
17:59:54 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 0)
17:59:54 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 0)
17:59:54 DEBUG    webview    browsertab:_on_navigation_request:1065 navigation request: url https://codeforces.com/, type Type.typed, is_main_frame True
17:59:54 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 0 to 'https://codeforces.com'
17:59:54 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 0 to 'Codeforces'
[53922:53955:0620/175955.134409:ERROR:cert_verify_proc_nss.cc(969)] CERT_PKIXVerifyCert for st.codeforces.com failed err=-8181
[53922:53956:0620/175955.136371:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -201
17:59:55 DEBUG    network    webenginetab:_on_ssl_errors:1552 Certificate error: Server's certificate has expired.
17:59:55 DEBUG    network    webenginetab:_on_ssl_errors:1553 First party URL: PyQt5.QtCore.QUrl('https://codeforces.com/')
17:59:55 DEBUG    network    shared:ignore_certificate_error:178 Certificate error <qutebrowser.browser.webengine.certificateerror.CertificateErrorWrapper error='CertificateDateInvalid' string="Server's certificate has expired.">, config ask
17:59:55 DEBUG    prompt     prompt:ask_question:160 Asking question <qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>, blocking True, loops [], queue deque([])
17:59:55 DEBUG    prompt     prompt:ask_question:182 New question is blocking, saving None
17:59:55 DEBUG    prompt     prompt:_on_show_prompts:334 Displaying prompt qutebrowser.mainwindow.prompt.YesNoPrompt(question=<qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>)
17:59:55 DEBUG    modes      modeman:enter:363 Entering mode KeyMode.yesno (reason: question asked)
17:59:55 DEBUG    statusbar  bar:set_mode_active:330 Setting prompt flag to True
17:59:55 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: qutebrowser.mainwindow.prompt.YesNoPrompt(question=<qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>)
17:59:55 DEBUG    misc       mainwindow:_update_overlay_geometry:350 new geometry for <qutebrowser.mainwindow.prompt.PromptContainer win_id=0>: PyQt5.QtCore.QRect(31, 666, 408, 352)
17:59:55 DEBUG    prompt     prompt:ask_question:197 Starting loop.exec() for <qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>
17:59:55 DEBUG    commands   command:run:537 command called: prompt-accept ['no']
17:59:55 DEBUG    commands   command:run:551 Calling qutebrowser.mainwindow.prompt.PromptContainer.prompt_accept(<qutebrowser.mainwindow.prompt.PromptContainer win_id=0>, 'no', save=False)
17:59:55 DEBUG    modes      modeman:leave:432 Leaving mode KeyMode.yesno (reason: :prompt-accept)
17:59:55 DEBUG    statusbar  bar:set_mode_active:330 Setting prompt flag to False
17:59:55 DEBUG    prompt     prompt:_on_mode_left:225 Left mode KeyMode.yesno, hiding <qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>
17:59:55 DEBUG    prompt     prompt:_on_show_prompts:314 Deleting old prompt qutebrowser.mainwindow.prompt.YesNoPrompt(question=<qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>)
17:59:55 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: <qutebrowser.mainwindow.tabwidget.TabBar count=1>
17:59:55 DEBUG    prompt     prompt:_on_show_prompts:319 No prompts left, hiding prompt container.
17:59:55 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.yesno (reason left in other window) as we're in mode KeyMode.normal
17:59:55 DEBUG    modes      tabbedbrowser:on_mode_left:812 Left status-input mode, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://codeforces.com/'>
17:59:55 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7ff38c38cf70>
17:59:55 DEBUG    modes      modeman:leave:432 Leaving mode KeyMode.normal (reason: enter normal: restore mode before yesno)
17:59:55 DEBUG    prompt     prompt:ask_question:201 Ending loop.exec() for <qutebrowser.utils.usertypes.Question default=False mode=PromptMode.yesno option=None text='\n            <p>\n                Error while loading resource <b>https://st.codeforces.com/images/icons/cup.png</b><br/>\n                on page <b>https://codeforces.com/</b>:\n            </p>\n            \n\n            <p>Server&#x27;s certificate has expired.</p>\n\n            \n            <p><i>Consider reporting this to the website operator, or set\n            <tt>content.tls.certificate_errors</tt> to <tt>ask-block-thirdparty</tt> to\n            always block invalid resource loads.</i></p>\n            \n\n            Do you want to ignore these errors and continue loading the page <b>insecurely</b>?' title='Certificate error'>
17:59:55 DEBUG    prompt     prompt:ask_question:203 Restoring old question None
17:59:55 DEBUG    prompt     prompt:_on_show_prompts:319 No prompts left, hiding prompt container.
17:59:55 DEBUG    network    webenginetab:_on_ssl_errors:1566 ignore False, URL PyQt5.QtCore.QUrl('https://st.codeforces.com/images/icons/cup.png'), requested PyQt5.QtCore.QUrl('https://codeforces.com/')
17:59:55 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7ff38c38cc10>
17:59:57 DEBUG    webview    browsertab:_set_load_status:1007 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://codeforces.com/'>: LoadStatus.success_https
17:59:57 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.success_https: 3>) (tab 0)
17:59:57 DEBUG    js         shared:javascript_log_message:156 [https://codeforces.com/:2526] Service worker registered
17:59:57 DEBUG    webview    browsertab:_on_navigation_request:1065 navigation request: url https://www.facebook.com/v2.8/plugins/like.php?app_id=554666954583323&channel=https%3A%2F%2Fstaticx…, type Type.redirect, is_main_frame False
17:59:57 DEBUG    webview    browsertab:_set_load_status:1007 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=0 url='https://codeforces.com/'>: LoadStatus.success_https
17:59:57 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.success_https: 3>) (tab 0)
17:59:57 DEBUG    sql        sql:run:278 INSERT INTO History (url, title, atime, redirect) values(:url, :title, :atime, :redirect)
17:59:57 DEBUG    sql        sql:run:282     {':atime': 1624204797, ':redirect': False, ':title': 'Codeforces', ':url': 'https://codeforces.com/'}
17:59:57 DEBUG    sql        sql:run:278 REPLACE INTO CompletionHistory (url, title, last_atime) values(:url, :title, :last_atime)
17:59:57 DEBUG    sql        sql:run:282     {':last_atime': 1624204797, ':title': 'Codeforces', ':url': 'https://codeforces.com/'}
17:59:57 DEBUG    sessions   sessions:save:338 Saving session _autosave to /tmp/qutebrowser-basedir-v6qeebvz/data/sessions/_autosave.yml...
17:59:57 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_finished(True) (tab 0)
17:59:57 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.insert (reason load started) as we're in mode KeyMode.normal
17:59:57 DEBUG    modes      tabbedbrowser:_leave_modes_on_load:737 Ignoring leave_on_load request due to setting.
17:59:57 DEBUG    commands   command:run:537 command called: open ['-t', 'https://codeforces.com']
17:59:57 DEBUG    commands   command:run:551 Calling qutebrowser.browser.commands.CommandDispatcher.openurl(<qutebrowser.browser.commands.CommandDispatcher>, 'https://codeforces.com', False, False, True, False, None, False, False)
17:59:57 DEBUG    url        urlutils:get_path_if_valid:366 Checking if 'https://codeforces.com' is a path
17:59:57 DEBUG    url        urlutils:is_url:271 Checking if 'https://codeforces.com' is a URL (autosearch=naive).
17:59:57 DEBUG    url        urlutils:is_url:294 Contains explicit scheme
17:59:57 DEBUG    url        urlutils:is_url:318 url = True
17:59:57 DEBUG    url        urlutils:fuzzy_url:225 URL is a fuzzy address
17:59:57 DEBUG    url        urlutils:fuzzy_url:227 Converting fuzzy term 'https://codeforces.com' to URL -> https://codeforces.com
17:59:57 DEBUG    webview    tabbedbrowser:tabopen:593 Creating new tab with URL PyQt5.QtCore.QUrl('https://codeforces.com'), background False, related False, idx None
17:59:57 DEBUG    webview    tabbedbrowser:_get_new_tab_idx:680 tabs.new_position last -> opening new tab at -1, next left: 0 / right: 1
17:59:57 DEBUG    webview    browsertab:_on_before_load_started:1041 Going to start loading: https://codeforces.com
17:59:57 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 1 to 'https://codeforces.com'
17:59:57 DEBUG    misc       eventfilter:eventFilter:53 <qutebrowser.browser.webengine.webview.WebEngineView object at 0x7ff36c1b7160> got new child <PyQt5.QtWidgets.QWidget object at 0x7ff38c38ca60>, installing filter
17:59:57 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7ff38c38cd30>
17:59:57 DEBUG    misc       app:on_focus_object_changed:582 Focus object changed: <PyQt5.QtWidgets.QWidget object at 0x7ff38c38caf0>
17:59:57 DEBUG    modes      tabbedbrowser:_on_current_changed:832 Current tab changed, focusing <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url=''>
17:59:57 DEBUG    modes      tabbedbrowser:_on_current_changed:839 Mode before tab change: normal (mode_on_change = normal)
17:59:57 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.hint (reason tab changed) as we're in mode KeyMode.normal
17:59:57 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.caret (reason tab changed) as we're in mode KeyMode.normal
17:59:57 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.insert (reason tab changed) as we're in mode KeyMode.normal
17:59:57 DEBUG    modes      modeman:leave:425 Ignoring leave request for KeyMode.passthrough (reason tab changed) as we're in mode KeyMode.normal
17:59:57 DEBUG    modes      tabbedbrowser:_on_current_changed:850 Mode after tab change: normal (mode_on_change = normal)
17:59:57 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 1 to 'https://codeforces.com/'
17:59:57 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_url_changed(PyQt5.QtCore.QUrl('https://code
forces.com/')) (tab 1)
17:59:58 DEBUG    webview    webenginetab:_store_match_data:151 Active search match: 0/0
17:59:58 DEBUG    webview    browsertab:_set_load_status:1007 load status for <qutebrowser.browser.webengine.webenginetab.WebEngineTab tab_id=1 url='https://codeforces.com/'>: LoadStatus.loading
17:59:58 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_status_changed(<LoadStatus.loading: 6>) (tab 1)
17:59:58 DEBUG    signals    signalfilter:_filter_signals:87 emitting: cur_load_started() (tab 1)
17:59:58 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 1 to 'https://codeforces.com'
17:59:58 DEBUG    webview    tabbedbrowser:_on_title_changed:757 Changing title for idx 1 to 'Codeforces'
[53922:53956:0620/175958.512934:ERROR:ssl_client_socket_impl.cc(941)] handshake failed; returned -1, SSL error code 1, net_error -201
17:59:58 ERROR    misc       crashsignal:_handle_early_exits:240 Uncaught exception
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/browser/webengine/webenginetab.py", line 1549, in _on_ssl_errors
    assert self.data.last_navigation is not None
AssertionError
```

</details>

I tried reproducing with:

```html
<html>
    <body>
        <img src="https://expired.badssl.com/">
    </body>
</html>
```

but no luck.

**Comment by The-Compiler** [comment]
Related crash report, on Qt 5.14 too: https://crashes.qutebrowser.org/view/260a34d4

**Comment by The-Compiler** [comment]
Qt 5.14 support is dropped now.
