### ISSUE TITLE
Windows nightly builds started failing

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6669]
```pytb
==================== Verifying 64-bit exe ====================
Traceback (most recent call last):
  File "D:\a\qutebrowser\qutebrowser\scripts\dev\build_release.py", line 693, in <module>
    main()
  File "D:\a\qutebrowser\qutebrowser\scripts\dev\build_release.py", line 660, in main
    artifacts = build_windows(
  File "D:\a\qutebrowser\qutebrowser\scripts\dev\build_release.py", line 409, in build_windows
    artifacts += _build_windows_single(
  File "D:\a\qutebrowser\qutebrowser\scripts\dev\build_release.py", line 375, in _build_windows_single
    verify_windows_exe(exe_path)
  File "D:\a\qutebrowser\qutebrowser\scripts\dev\build_release.py", line 212, in verify_windows_exe
    pe = pefile.PE(exe_path)
  File "D:\a\qutebrowser\qutebrowser\.tox\build-release\lib\site-packages\pefile.py", line 2742, in __init__
    self.__parse__(name, data, fast_load)
  File "D:\a\qutebrowser\qutebrowser\.tox\build-release\lib\site-packages\pefile.py", line 3147, in __parse__
    self.full_load()
  File "D:\a\qutebrowser\qutebrowser\.tox\build-release\lib\site-packages\pefile.py", line 3258, in full_load
    self.parse_data_directories()
  File "D:\a\qutebrowser\qutebrowser\.tox\build-release\lib\site-packages\pefile.py", line 3553, in parse_data_directories
    value = entry[1](dir_entry.VirtualAddress, dir_entry.Size)
  File "D:\a\qutebrowser\qutebrowser\.tox\build-release\lib\site-packages\pefile.py", line 3646, in parse_exceptions_directory
    rf.unwindinfo.set_chained_function_entry(
  File "D:\a\qutebrowser\qutebrowser\.tox\build-release\lib\site-packages\pefile.py", line 1945, in set_chained_function_entry
    raise Exception("Chained function entry cannot be changed")
Exception: Chained function entry cannot be changed
```

Looks like this is a regression in pefile 2021.9.2, and apparently we accidentally didn't pin the dependency... Reported here: https://github.com/erocarrera/pefile/issues/334

**Comment by The-Compiler** [comment]
This has long been fixed upstream.
