### ISSUE TITLE
`gt` or `:tab-select` breaks userscript.

### ISSUE THREAD

**Issue by crocket** [qutebrowser/qutebrowser#6742]
**Version info**:

qutebrowser v2.3.1
Git commit: 
Backend: QtWebEngine 5.15.2, based on Chromium 87.0.4280.144
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

~/.config/qutebrowser/config.py

```
config.bind("<Return>", "spawn -u command-accept", mode="command")
```

~/.config/qutebrowser/userscripts/command-accept

```
#!/bin/sh

echo "command-accept" >> "${QUTE_FIFO}"
```

**How to reproduce**

If Enter key is mapped to `spawn -u command-accept` in config.py, pressing enter after pressing `gt` crashes qutescript because

```
12:04:22 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/qutebrowser/commands/userscripts.py", line 76, in read_line
    for line in self._fifo:
ValueError: I/O operation on closed file.
```

**Comment by crocket** [comment]
I just submitted the report through the UI.

**Comment by The-Compiler** [comment]
Reproduced now (on X11) - standalone reproducer:

```
echo -e '#!/bin/sh\necho command-accept > $QUTE_FIFO' > /tmp/u.sh && chmod +x /tmp/u.sh && python3 -m qutebrowser --temp-basedir --debug ":set-cmd-text -s :tab-select" ":later 500 completion-item-focus next" ":later 1000 spawn -u /tmp/u.sh"
```

**Comment by thjbdvlt** [comment]
hello! i have a similar issue while trying to use a userscript on `tab-select`, but the error only happens sometimes (~1/10, independant of the url or anything):

```
Traceback (most recent call last):
  File "/home/uut/softwares/qutebrowser/qutebrowser/commands/userscripts.py", line 60, in read_line
    for line in self._fifo:
ValueError: I/O operation on closed file.
```

output of qutebrowser version:

```
qutebrowser v3.0.2
Git commit: 044b1e38e-dirty on main (2023-10-31 09:28:32 +0100)
Backend: QtWebEngine 6.5.3, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.3

CPython: 3.9.2
PyQt: 6.5.3

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.16.1
yaml: 6.0.1
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.7.12
pdf.js: 2.6.0 (/usr/share/javascript/pdf/build/pdf.js)
sqlite: 3.43.1
QtNetwork SSL: no
...
```
