### ISSUE TITLE
[ libvpx ] QtWebEngine could not be imported

### ISSUE THREAD

**Issue by LamprosPitsillos** [qutebrowser/qutebrowser#6764]
**Version info**:
```
qutebrowser v2.4.0
Git commit: 
Backend: new QtWebKit (WebKit 602.1) # I think this was forced after first error..
Qt: 5.15.2

CPython: 3.9.7
PyQt: 5.15.5

sip: 6.1.0.dev2104271705
colorama: 0.4.4
jinja2: 3.0.2
pygments: 2.10.0
yaml: 5.4.1
adblock: 0.5.0
PyQt5.QtWebEngineWidgets: no
PyQt5.QtWebEngine: no
PyQt5.QtWebKitWidgets: yes
pdf.js: 2.11.338 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.36.0
QtNetwork SSL: OpenSSL 1.1.1l  24 Aug 2021
```

**Description**
![Window_QtWEBengine](https://user-images.githubusercontent.com/61395246/138425650-8f0a8fde-ff76-4452-b63e-12cea5ee0842.png)

```python
❯ qutebrowser --backend webengine -V
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.4.0', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.9/site-packages/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/usr/lib/python3.9/site-packages/qutebrowser/app.py", line 104, in run
    print(version.version_info())
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 810, in version_info
    lines.append('Backend: {}'.format(_backend()))
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 778, in _backend
    return str(qtwebengine_versions(
  File "/usr/lib/python3.9/site-packages/qutebrowser/utils/version.py", line 745, in qtwebengine_versions
    from qutebrowser.browser.webengine import webenginesettings
  File "/usr/lib/python3.9/site-packages/qutebrowser/browser/webengine/webenginesettings.py", line 33, in <module>
    from PyQt5.QtWebEngineWidgets import QWebEngineSettings, QWebEngineProfile
ImportError: libvpx.so.6: cannot open shared object file: No such file or directory
```

**How to reproduce**
I just upgraded libvpx (1.10.0-1 -> 1.11.0-1) and this just happend.
Is there a way to fix this?

**Comment by Darukutsu** [comment]
**Version info**:
qutebrowser v3.1.0
Git commit: 3494614fc on main (2024-01-22 10:53:22 +0100)
Backend: QtWebEngine 6.6.1, based on Chromium 112.0.5615.213 (from api)
Qt: 6.6.1

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
This shows when trying to open qutebrowser. Did I update at wrong time :D? Not sure if this should be reported. Arch btw. Any recommendation what to do in situatuions like this? Should ignore or report somewhere?

```
qutebrowser needs QtWebKit or QtWebEngine, but neither could be imported!

The errors encountered were:

- QtWebKit: Unavailable with PyQt6
- QtWebEngine: libvpx.so.8: cannot open shared object file: No such file or directory.

Qt wrapper info:
PyQt6: success
PyQt5: not imported
> selected: PyQt6 (via autoselect)
```

**How to reproduce**
```
 $  pacman -Q qt5-webengine 
qt5-webengine 5.15.16-3
 $  pacman -Q qt6-webengine 
qt6-webengine 6.6.1-2
```
```
[2024-01-25T14:12:30+0100] [ALPM] upgraded rav1e (0.6.6-3 -> 0.7.1-1)
[2024-01-25T14:12:30+0100] [ALPM] upgraded libavif (1.0.3-1 -> 1.0.3-2)
[2024-01-25T14:12:31+0100] [ALPM] upgraded libvpx (1.13.1-1 -> 1.14.0-1)
```



I had to downgrade these packages to be able to open qutebrowser again
```
 $  sudo pacman -U file:///var/cache/pacman/pkg/libvpx-1.13.1-1-x86_64.pkg.tar.zst file:///var/cache/pacman/pkg/libavif-1.0.3-1-x86_64.pkg.tar.zst file://var/cache/pacman/pkg/rav1e-0.6.6-3-x86_64.pkg.tar.zst 
```

**Comment by Darukutsu** [comment]
Ah thanks, I'm running `obs-studion-tytan652` which bundles `ffmpeg-obs`. It hasn't got update yet so the issue is there.

**Comment by The-Compiler** [comment]
It doesn't need to be, since AUR packages are source packages, and this is a binary-only change. You just need to rebuild it.
