### ISSUE TITLE
Deleted C++ object: WebEngineView in show_error_page

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6826]
Seeing various reports about this:

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 969, in <lambda>
    QTimer.singleShot(100, lambda: show_error_page(error_page))
  File "/usr/lib/python3.8/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 947, in show_error_page
    tab.set_html(html)
  File "/usr/lib/python3.8/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 1378, in set_html
    self._widget.setHtml(html, base_url)
RuntimeError: wrapped C/C++ object of type WebEngineView has been deleted
```

https://crashes.qutebrowser.org/lists?search=show_error_page

**Comment by NDagestad** [comment]
I am hitting this bug again but things have changed slightly on qutebrowser since.
```
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qutebrowser/browser/browsertab.py", line 911, in <lambda>
    65, lambda: self._tab.elements.find_focused(_auto_insert_mode_cb))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 789, in find_focused
    self._tab.run_js_async(js_code, js_cb)
  File "/usr/lib/python3.12/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 1378, in run_js_async
    self._widget.page().runJavaScript(code, world_id, callback)
    ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/browser/webengine/webview.py", line 137, in page
    maybe_page = super().page()
                 ^^^^^^^^^^^^^^
RuntimeError: wrapped C/C++ object of type WebEngineView has been deleted
```
It looks like I only hit the crash when opening and closing a tab too fast (or sometimes swithcing to a tab and closing it quickly - only for tabs opened in the background I think)

I have fixed™ it temporarly on my side by wrapping the if/else block in a try/except block, but that's probably to broad and could ignore other RuntimeExceptions which could be important.

It is very random, so difficult to reproduce but it happened at least once a week/every 2 weeks before I patched it out locally.
I am running the latest qutebrowser v3.3.1.

**Comment by NDagestad** [comment]
The last of the logs before the crash if it can be of any use: https://paste.sr.ht/~nicolai_dagestad/81749d002d46d18e515bd6342668eb8de31d7eda

**Comment by The-Compiler** [comment]
@NDagestad Entirely unrelated issue based on the stacktrace. I opened #8400 for it. Would be good if you could comment there with your QtWebEngine and Qt versions.

**Comment by NDagestad** [comment]
Yeah, I was a bit Quick because it happend to be the exact same line in webwnginetab.py and the same exception (but that's not the same function as before).
I will add the requested info when I get back to that computer tomorrow morning 👍
