### ISSUE TITLE
Handle invalid URLs in Greasemonkey requirements

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#6968]
From a [crash report](https://crashes.qutebrowser.org/view/0d60424b) on 2.4.0:

```
13:17:55 DEBUG    init       app:_init_modules:522 Initializing Greasemonkey...
13:17:55 DEBUG    greasemonkey greasemonkey:load_scripts:307 Reading scripts from: /home/redacted/.local/share/qutebrowser/greasemonkey
13:17:55 DEBUG    greasemonkey greasemonkey:load_scripts:307 Reading scripts from: /home/arya/.config/qutebrowser/greasemonkey
13:17:55 DEBUG    greasemonkey greasemonkey:add_script:331 Deferring script until requirements are fulfilled: Auto Close YouTube Ads
13:17:55 DEBUG    greasemonkey greasemonkey:_add_script_with_requires:388 Adding required script for Auto Close YouTube Ads to IIFE: https://cdn.jsdelivr.net/gh/kufii/My-UserScripts@23586fd0a72b587a1786f7bb9088e807a5b53e79/libs/gm_config.js
13:17:55 DEBUG    greasemonkey greasemonkey:_add_script_with_requires:388 Adding required script for Auto Close YouTube Ads to IIFE: https://cdn.jsdelivr.net/gh/fuzetsu/userscripts@ec863aa92cea78a20431f92e80ac0e93262136df/wait-for-elements/wait-for-elements.js
13:17:55 DEBUG    greasemonkey greasemonkey:_add_script:352 Loaded script: Auto Close YouTube Ads
13:17:55 DEBUG    greasemonkey greasemonkey:add_script:331 Deferring script until requirements are fulfilled: Whatsapp Incognito
13:17:55 DEBUG    message    message:_log_stack:42 Stack for error message:
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.4.0', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 123, in run
    init(args=args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 158, in init
    _init_modules(args=args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 523, in _init_modules
    greasemonkey.init()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 470, in init
    gm_manager = GreasemonkeyManager()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 285, in __init__
    self.load_scripts()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 317, in load_scripts
    self.add_script(script, force)
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 333, in add_script
    self._get_required_scripts(script, force)
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 414, in _get_required_scripts
    download = download_manager.get(QUrl(url), target=target,
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/qtnetworkdownloads.py", line 445, in get
    urlutils.invalid_url_error(url, "start download")
  File "/usr/lib/python3.10/site-packages/qutebrowser/utils/urlutils.py", line 338, in invalid_url_error
    message.error(errstring)
  File "/usr/lib/python3.10/site-packages/qutebrowser/utils/message.py", line 54, in error
    stack = ''.join(traceback.format_stack())
13:17:55 ERROR    message    message:error:59 Trying to start download with invalid URL - Relative URL's path component contains ':' before any '/'; source was "'https://cdn.jsdelivr.net/gh/tomer8007/whatsapp-web-incognito@master/core/parsing/binary_reader.js'"; path = "'https://cdn.jsdelivr.net/gh/tomer8007/whatsapp-web-incognito@master/core/parsing/binary_reader.js'"
13:17:55 ERROR    misc       crashsignal:_handle_early_exits:240 Uncaught exception
```

```pytb
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.4.0', 'gui_scripts', 'qutebrowser')())
  File "/usr/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 123, in run
    init(args=args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 158, in init
    _init_modules(args=args)
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 523, in _init_modules
    greasemonkey.init()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 470, in init
    gm_manager = GreasemonkeyManager()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 285, in __init__
    self.load_scripts()
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 317, in load_scripts
    self.add_script(script, force)
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 333, in add_script
    self._get_required_scripts(script, force)
  File "/usr/lib/python3.10/site-packages/qutebrowser/browser/greasemonkey.py", line 416, in _get_required_scripts
    download.requested_url = url
```

It seems... questionable for `qtnetworkdownloads.DownloadManager.get` to return `None` if the URL was invalid. Wonder if we should have a valid URL as a precondition there and handle those at the caller site. Though maybe returning `None` in such a case is required when QtWebKit is using the download manager.

cc @toofar

**Comment by The-Compiler** [comment]
Reproducer from https://crashes.qutebrowser.org/view/e15733a8:

1. run qutebrowser
2. create a greasemonkey script (~/.config/qutebrowser)
3. add this exact line to the ==UserScript== section, do not emit the quotes:
 
`// @require      "https://code.jquery.com/jquery-3.6.1.min.js"`
 
4. in qutebrowser, execute: greasemonkey-reload
