### ISSUE TITLE
Can't pase images on Discord for the browser

### ISSUE THREAD

**Issue by Lilith-In-Starlight** [qutebrowser/qutebrowser#7269]
**Version info**:
qutebrowser v2.5.1
Git commit: 1996c4d7e on HEAD (2022-05-26 14:05:30 +0200)
Backend: QtWebEngine 5.15.2, based on Chromium 83.0.4103.122
Qt: 5.15.2

**Does the bug happen if you start with `--temp-basedir`?**:
Yes

**Description**
When I use Discord on the browser, I can't paste images on the text field where you send messages. I can normally do this on any other browser.

**How to reproduce**
- Login to a discord account and enter any server
- Copy an image. This can be done by taking a screenshot, copying an image file, copying a file, or copying a selection from an image editing program
- Paste the image on the message text field on any channel in the Discord server, either by pressing CTRL + V or by right clicking on the text field and clicking "paste"
  - Expected result: The image is uploaded to discord and attached to the message being written
  - Actual result: Nothing happens

This issue doesn't happen if you copied the image from within qutebrowser (by right clicking the image and clicking "Copy Image").

After doing some testing, I realized this issue doesn't affect the text field where you write your posts in Mastodon instances, nor the github text fields (such as the one where I'm writing this issue), nor the Cinny or Element matrix clients. It seems to only really be affecting that one website.

**Comment by The-Compiler** [comment]
Any chance you could try the current git build and see if it works if you run with `--temp-basedir -s content.javascript.clipboard access-paste`?

**Comment by Lilith-In-Starlight** [comment]
How do I do that? Is it by chance these steps? https://github.com/qutebrowser/qutebrowser/blob/master/doc/install.asciidoc#installing-qutebrowser-with-virtualenv

**Comment by The-Compiler** [comment]
Yup, that would work!

**Comment by Lilith-In-Starlight** [comment]
Running `python3 -m venv .venv` errors with

```
Traceback (most recent call last):
  File "D:\qtbtests\qutebrowser\scripts\mkvenv.py", line 515, in <module>
    main()
  File "D:\qtbtests\qutebrowser\scripts\mkvenv.py", line 508, in main
    run(args)
  File "D:\qtbtests\qutebrowser\scripts\mkvenv.py", line 489, in run
    upgrade_seed_pkgs(venv_dir)
  File "D:\qtbtests\qutebrowser\scripts\mkvenv.py", line 207, in upgrade_seed_pkgs
    pip_install(venv_dir, '-U', 'pip')
  File "D:\qtbtests\qutebrowser\scripts\mkvenv.py", line 163, in pip_install
    run_venv(venv_dir, 'python', '-m', 'pip', 'install', *args)
  File "D:\qtbtests\qutebrowser\scripts\mkvenv.py", line 147, in run_venv
    return subprocess.run(
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\USER\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2] The system could not find the specified file```

**Comment by The-Compiler** [comment]
That's odd. You seem to be running `python3 scripts/mkvenv.py` or so though, not `python3 -m venv .venv`, no?

Do you have a `.venv/Scripts/python.exe` in the folder you're running this? Does `python3 -c "import os; print(os.name)"` show `nt`?

**Comment by RudraveerMandal** [comment]
Are you copying the image from outside the browser some external app or inside the browser?
Did you try doing it in pass through mode?

**Comment by Lilith-In-Starlight** [comment]
> Are you copying the image from outside the browser some external app or inside the browser? Did you try doing it in pass through mode? Also does this problem only happen on discord?

Yes to all three

> That's odd. You seem to be running `python3 scripts/mkvenv.py` or so though, not `python3 -m venv .venv`, no?
> 
> Do you have a `.venv/Scripts/python.exe` in the folder you're running this? Does `python3 -c "import os; print(os.name)"` show `nt`?

Yes, it just showed `nt`. And yes, I have that folder.

**Comment by zstg** [comment]
Could be because of Discord failing to read the HTTP canvas - this is a privacy feature in Firefox and Qutebrowser that could lead to these issues- QR codes do not always work in Firefox - this is the reason . 

Try setting `c.content.canvas_reading=True`

**Comment by Lilith-In-Starlight** [comment]
It is already true in my browser

**Comment by Iamnotagenius** [comment]
Same issue here. I can paste images copied from discord itself, though. I looked for MIME types of these images with `wl-paste -l` and here is the output:
```
application/x-qt-image
text/html
text/x-moz-url
image/png
image/bmp
image/cur
image/ico
image/jpeg
image/jpg
image/pbm
image/pgm
image/ppm
image/xbm
image/xpm
```
I experimented a bit by copying  just one type and try to paste it to discord. It seems that images with mime types 
`image/bmp` `image/jpeg` `image/jpg` `image/cur` `image/ico` `image/pbm` `image/xbm` can be pasted. But `image/png` never works. So the solution would be to change the mime type of content of the clipboard (I was copying png version as `image/jpeg` and it worked)

**Comment by Lilith-In-Starlight** [comment]
Interestingly, you can copy images directly from any page in the browser and it'll be pasteable on Discord, even if it's a PNG
