### ISSUE TITLE
`scripts/mkvenv` failing on doc generation

### ISSUE THREAD

**Issue by optik-aper** [qutebrowser/qutebrowser#7352]
**Version info**:

It's not installed so I can't run `:version`.  I'm building from master branch with head at commit `9f4e26186e1c24aea7ce2e5366276f3a6153bc19`

**Does the bug happen if you start with `--temp-basedir`?**:
Cannot start before building the venv

**Description**

**How to reproduce**

* Clone the repo
* `cd qutebrowser`
* `./scripts/mkvenv.py`
* There is an error during the asciidoc generation:
```
==================== Generating documentation ====================
venv$ python3 scripts/asciidoc2html.py
Calling asciidoc for faq.asciidoc...
/home/michael/repos/qutebrowser/.venv/bin/python3: No module named asciidoc
Command '['asciidoc', '--out-file', '/home/michael/repos/qutebrowser/qutebrowser/html/doc/faq.html', '-a', 'source-highlighter=pygments', '/tmp/tmp_xu9ky8f/tmp/faq.asciidoc']' returned non-zero exit status 1.
Keeping modified sources in /tmp/tmp_xu9ky8f.
Subprocess failed, exiting
```
This is running on Ubuntu 22.04
`asciidoc` is installed system-wide, but the script is clearly trying to run it from the venv and I don't see `asciidoc` in the `requirements.txt` file.  There is an error when importing on the python REPL:
```
michael  ~/repos/qutebrowser (master|✔)
 Φ .venv/bin/python3                                                                                                       141 ↵ 11:47
Python 3.10.4 (main, Jun 29 2022, 12:14:53) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import asciidoc
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'asciidoc'
>>> 
```

**Comment by The-Compiler** [comment]
You will need to `apt install --no-install-recommends asciidoc` to build the docs. Guess the install docs could make this a bit clearer, though.

**Comment by optik-aper** [comment]
I did do that beforehand.  You can see in the output that it's trying to import a python module in the `.venv`, though.  I don't think it's trying to use the system version.  Additionally, I passed it directly to the script with `python3 scripts/mkvenv.py --asciidoc /usr/bin/python3 /usr/bin/asciidoc` which results in this error:
```
==================== Generating documentation ====================
venv$ python3 scripts/asciidoc2html.py --asciidoc /usr/bin/python3 /usr/bin/asciidoc
usage: asciidoc2html.py [-h] [--website WEBSITE] [--asciidoc [ASCIIDOC]] [--asciidoc-python [ASCIIDOC_PYTHON]]
asciidoc2html.py: error: unrecognized arguments: /usr/bin/asciidoc
Subprocess failed, exiting
```
I'm passing that in based on the help page for the script:
```
  --asciidoc PYTHON ASCIIDOC
                        Full path to python and asciidoc.py. If not given, it's searched in PATH.
```
Is that correct?  How is `asciidoc.py` (from the help) related to the `apt install --no-install-recommends asciidoc`?

I was able to run the script with the `--skip-docs` flag but it'd be good to generate the docs as well.

**Comment by toofar** [comment]
> python3 scripts/mkvenv.py --asciidoc /usr/bin/python3 /usr/bin/asciidoc
> usage: asciidoc2html.py [-h] [--website WEBSITE] [--asciidoc [ASCIIDOC]] [--asciidoc-python [ASCIIDOC_PYTHON]]

Looks like it wants just `python3 scripts/mkvenv.py --asciidoc /usr/bin/asciidoc` or maybe `python3 scripts/mkvenv.py --asciidoc /usr/bin/asciidoc --asciidoc-python /usr/bin/python3`.

Although tbh I have *not* got asciidoc installed at the system level , just in the vrtualenv (eg `pip3 install asciidoc`) and it seems to work fine for me. I'm not sure in what situations pointing to a system level one is necessary.

**Comment by The-Compiler** [comment]
Oh, does that just work nowadays? Then I suppose we could just make `mkvenv.py` install that automatically really... (also see #6793). When the script was written, it wasn't possible to install asciidoc via pip.

Not sure why it wouldn't correctly pick up the system-wide one, however.

@optik-aper what "help page for the script" are you referring to? The two-argument `--asciidoc` form is outdated, so if that still is in the docs somewhere, those should get updated too.

**Comment by optik-aper** [comment]
Ah, that explains something to me, because I swear the first time I reported the issue I was trying just one argument to the `--asciidoc` flag.  I must have been on the `v2.0.x` tag when I tested it the second time.  Sorry for the confusion.

Nonetheless, I get errors passing the path to the system `asciidoc` binary:
```
==================== Generating documentation ====================
venv$ python3 scripts/asciidoc2html.py --asciidoc /usr/bin/asciidoc
Calling asciidoc for faq.asciidoc...
  File "/usr/bin/asciidoc", line 2
    python3 -m asciidoc "$@"
               ^^^^^^^^
SyntaxError: invalid syntax
Command '['/home/michael/repos/qutebrowser/.venv/bin/python', '/usr/bin/asciidoc', '--out-file', '/home/michael/repos/qutebrowser/qutebrowser/html/doc/faq.html', '-a', 'source-highlighter=pygments', '/tmp/tmp8t2gcx90/tmp/faq.asciidoc']' returned non-zero exit status 1.
Keeping modified sources in /tmp/tmp8t2gcx90.
Subprocess failed, exiting
```

**Comment by toofar** [comment]
It looks like there are three ways to call it:
1. system wide asciidoc and without any asciidoc related arguments - needs to be done *without* a venv activated (as you saw in the top post it'll try to run with the venv python otherwise, and fail)
2. asciidoc installed in the venv (if you are lucky?) and no asciidoc related arguments - just looks it up in PATH again
3. system wide asciidoc and with both --asciidoc and --asciidoc-python passed - can be called in a venv because it uses an explicit python to call it

> The two-argument --asciidoc form is outdated

@The-Compiler does this mean you shouldn't need to pass --asciidoc-python with --asciidoc? It [seems](https://github.com/qutebrowser/qutebrowser/blob/master/scripts/asciidoc2html.py#L230) to use the python executable you called the script with by default which sounds like it would be problematic when called from in a virtual (without asciidoc)

**Comment by optik-aper** [comment]
As a test, I added `asciidoc` to the `requirements.txt` file.  The docs generate [correctly](https://gist.github.com/optik-aper/0b472067da70ae723b6f2828b13aace5)

**Comment by gelbwald** [comment]
Similarly doing `python3 -m pip install asciidoc` before gets rid of this error for me.

**Comment by The-Compiler** [comment]
Getting this on CI now as well, since `ubuntu-latest` now means 22.04 finally, and that ships with asciidoc 10. While I still want to switch away from asciidoc, fixing this should be straightforward I hope... on it!
