### ISSUE TITLE
`qutebroser --target window` allows opening tabless windows with empty arguments.

### ISSUE THREAD

**Issue by emanuele6** [qutebrowser/qutebrowser#7359]
[**Version info**](https://paste.the-compiler.org/view/bada4cc0):
```
qutebrowser v2.5.2
Git commit: 
Backend: QtWebEngine 5.15.10, based on Chromium 87.0.4280.144
Qt: 5.15.5 (compiled 5.15.4)
```
**Does the bug happen if you start with `--temp-basedir`?**:
Yes
**Description**
`qutebrowser --target window` (or `tab-silent`, `tab-bg-silent`, `private-window`) will create a new window without tabs for every empty positional argument, except if there is only one argument because `['']` is a special case:
https://github.com/qutebrowser/qutebrowser/blob/21c82b029b141fe9d89946b0c9378538ff395b26/qutebrowser/app.py#L263

Trying to enter command mode (with either `:` or `o` for example), will cause `qutebrowser` to crash.

**How to reproduce**
* `qutebrowse --target private-window '' '' ''` (this will open three tabless private windows)
* `qutebrowser --target tab-silent '' ':message-info hi'` (this will open a new tabless window, n.b. the `:message-info` command is run in the new window!)
If you are testing with `qutebrowser -T`, remember to use `-B` to specify the basedir when sending these ipc commands; you can get the path to the temporary basedir generated by `-T` looking at the `qute://version/` page; example:
* `qutebrowser -B /tmp/qutebrowser-basedir-xktzvcke --target tab-silent '' ':set-cmd-text :' (n.b. since `:set-cmd-text :` is ran in the new window, this will crash qutebrowser)

**Comment by emanuele6** [comment]
Here a video of the bug being reproduced:

https://user-images.githubusercontent.com/20175435/186246822-7f2381c2-171a-4164-b73a-1c67d37951a3.mp4

And here is the traceback printed to the terminal after the crash:
```
000 (495116) ~ $ qutebrowser -T
21:16:21 ERROR: Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/qutebrowser/completion/completer.py", line 268, in _update_completion
    cur_tab = objreg.get('tab', scope='tab', window=self._win_id,
  File "/usr/lib/python3.10/site-packages/qutebrowser/utils/objreg.py", line 242, in get
    reg = _get_registry(scope, window, tab)
  File "/usr/lib/python3.10/site-packages/qutebrowser/utils/objreg.py", line 224, in _get_registry
    return _get_tab_registry(window, tab)
  File "/usr/lib/python3.10/site-packages/qutebrowser/utils/objreg.py", line 181, in _get_tab_registry
    raise RegistryUnavailableError('window')
qutebrowser.utils.objreg.RegistryUnavailableError: window
Fatal Python error: Segmentation fault

Current thread 0x00007f46a379f740 (most recent call first):
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 140 in qt_mainloop
  File "/usr/lib/python3.10/site-packages/qutebrowser/app.py", line 130 in run
  File "/usr/lib/python3.10/site-packages/qutebrowser/qutebrowser.py", line 245 in main
  File "/usr/bin/qutebrowser", line 33 in <module>

Extension modules: PyQt5.QtCore, PyQt5.QtGui, PyQt5.QtWidgets, markupsafe._speedups, yaml._yaml, PyQt5.QtNetwork, PyQt5.QtQml, PyQt5.QtSql, PyQt5.QtOpenGL, PyQt5.QtDBus, PyQt5.QtWebChannel, PyQt5.QtWebEngineCore, PyQt5.QtPrintSupport, PyQt5.QtWebEngineWidgets, PyQt5.QtWebKit, PyQt5.QtWebEngine, PyQt5.QtWebKitWidgets, PyQt5._QOpenGLFunctions_2_0 (total: 18)
Segmentation fault (core dumped)
```
