### ISSUE TITLE
Qt 6: navigation request gets content of base.html as url parameter

### ISSUE THREAD

**Issue by Bonoolu** [qutebrowser/qutebrowser#7412]
The renderer crashes when trying to use the search function on ebay.com. It looks like the navigaton requests gets the content of base.html as url parameter.

**Version**
qutebrowser v2.5.2
Git commit: 5e11e6c7d on makepkg (2022-09-16 15:00:19 +0200)
Backend: QtWebEngine 6.3.2, based on Chromium 94.0.4606.126 (from api)
Qt: 6.3.2

**reproducible with ---temp-basedir?**
Yes

**Steps to reproduce**
- qutebrowser -d --temp-basedir "https://www.ebay.com/"
- click search field and type "test"
- press enter
The renderer process crashes and this appears in the log:
```
18:26:29 DEBUG    webview    browsertab:_on_navigation_request:1154 navigation request: url data:text/html;charset=UTF-8,%3C%21DOCTYPE html%3E%0A%3C%21--%0Avim%3A ft%3Dhtml fileencoding%3Dutf…, type Type.typed, is_main_frame True
18:26:29 ERROR    webview    tabbedbrowser:show_error_page:1008 Renderer process crashed (status 11)
```

full log is [here](https://gist.github.com/Bonoolu/9348ab76646f98d82a17e62168bbe677)

**Comment by toofar** [comment]
Fun, it seems to only crash the first time you trigger whatever behaviour? Like if you go back from the error page and try again it works fine.
Launching it in single process mode I got the following stack trace (on 6.3.3) from the "Database thread":
```
#0  0x00007fffede9aa78 in WTF::HashTable<cppgc::internal::BasicCrossThreadPersistent<blink::Database, cppgc::internal::StrongCrossThreadPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy>, cppgc::internal::BasicCrossThreadPersistent<blink::Database, cppgc::internal::StrongCrossThreadPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy>, WTF::IdentityExtractor, WTF::MemberHash<blink::Database>, WTF::HashTraits<cppgc::internal::BasicCrossThreadPersistent<blink::Database, cppgc::internal::StrongCrossThreadPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy> >, WTF::HashTraits<cppgc::internal::BasicCrossThreadPersistent<blink::Database, cppgc::internal::StrongCrossThreadPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy> >, WTF::PartitionAllocator>::erase(cppgc::internal::BasicCrossThreadPersistent<blink::Database, cppgc::internal::StrongCrossThreadPersistentPolicy, cppgc::internal::IgnoreLocationPolicy, cppgc::internal::DisabledCheckingPolicy> const*) ()
   from /mnt/nvme/qt6.2/build_6.3-2/qtbase/lib/libQt6WebEngineCore.so.6
#1  0x00007fffede9bc86 in blink::DatabaseTracker::RemoveOpenDatabase(blink::Database*) ()
   from /mnt/nvme/qt6.2/build_6.3-2/qtbase/lib/libQt6WebEngineCore.so.6
#2  0x00007fffede8f831 in blink::Database::CloseDatabase() ()
   from /mnt/nvme/qt6.2/build_6.3-2/qtbase/lib/libQt6WebEngineCore.so.6
#3  0x0000000000000000 in ?? ()
```

Since exit code 11 is "Resource temporarily unavailable" maybe it is trying to close a DB that doesn't exist (or wasn't properly opened) and that case isn't being handled.
`CloseDatabase()` seems to only appear in a few places in the codebase, IndexedDB, "webdatabase", WebRTC.

Anyway, this is an upstream issue. So someone needs to report it to the Qt bug tracker.

**Comment by Bonoolu** [comment]
I updated to Qt 6.4 and i can no longer reproduce this bug.

**Comment by The-Compiler** [comment]
Good to hear, thanks for the follow-up! Closing this then.
