### ISSUE TITLE
can't start qutebrowser if config dir is a symlink

### ISSUE THREAD

**Issue by juantascon** [qutebrowser/qutebrowser#7505]
:**Version info**:
https://paste.the-compiler.org/view/1542c852

**Does the bug happen if you start with `--temp-basedir`?**:
yes

**Description**
If .config/qutebrowser is a symlink to another dir qutebrowser fails to start with the following error:

```
Traceback (most recent call last):
  File "/app/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.5.2', 'gui_scripts', 'qutebrowser')())
  File "/app/lib/python3.9/site-packages/qutebrowser-2.5.2-py3.9.egg/qutebrowser/qutebrowser.py", line 245, in main
    return app.run(args)
  File "/app/lib/python3.9/site-packages/qutebrowser-2.5.2-py3.9.egg/qutebrowser/app.py", line 88, in run
    standarddir.init(args)
  File "/app/lib/python3.9/site-packages/qutebrowser-2.5.2-py3.9.egg/qutebrowser/utils/standarddir.py", line 356, in init
    _init_dirs(args)
  File "/app/lib/python3.9/site-packages/qutebrowser-2.5.2-py3.9.egg/qutebrowser/utils/standarddir.py", line 343, in _init_dirs
    _init_config(args)
  File "/app/lib/python3.9/site-packages/qutebrowser-2.5.2-py3.9.egg/qutebrowser/utils/standarddir.py", line 90, in _init_config
    _create(path)
  File "/app/lib/python3.9/site-packages/qutebrowser-2.5.2-py3.9.egg/qutebrowser/utils/standarddir.py", line 335, in _create
    os.makedirs(path, 0o700, exist_ok=True)
  File "/usr/lib/python3.9/os.py", line 225, in makedirs
    mkdir(name, mode)
FileExistsError: [Errno 17] File exists: '<REMOVED>/.config/qutebrowser'
```

**How to reproduce**

```
cd ~
rm -rf .config/qutebrowser
mkdir somedir
cd .config
ln -s ../somedir ./qutebrowser
qutebrowser
```

**Comment by The-Compiler** [comment]
I cannot reproduce with your example. I can, however, reproduce this when the link is invalid (or if it's a regular file instead).

What does `ls -l .config/qutebrowser` show? Is the target of that link actually valid?

**Comment by The-Compiler** [comment]
Ah, also, if the link is indeed valid: Does this work with qutebrowser being run outside of Flatpak? Chances are that Flatpak is preventing it from accessing the destination.

**Comment by juantascon** [comment]
you are right, flatpak was denying access to the filesystem, just for future reference I fixed this by adding: --filesystem=home
