### ISSUE TITLE
Python 3.11 updates killed AUR qutebrowser-git

### ISSUE THREAD

**Issue by justinesmithies** [qutebrowser/qutebrowser#7688]
I'm using the latest Arch Linux AUR git version and since the latest Python 3.11 updates Qutebrowser no longer runs.
I get the following error:

```
Traceback (most recent call last):
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 563, in from_name
    return next(cls.discover(name=name))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==2.5.4', 'gui_scripts', 'qutebrowser')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/bin/qutebrowser", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 981, in distribution
    return Distribution.from_name(distribution_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/importlib/metadata/__init__.py", line 565, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for qutebrowser
```

**Comment by The-Compiler** [comment]
You'll need to rebuild any Python AUR packages after a Python upgrade - nothing specific to qutebrowser though. I'll do a courtesy version bump once I'm back on my laptop though.

**Comment by justinesmithies** [comment]
Thank you and I can confirm by deleting the qutebrowser-git folder from Paru .cache and reinstalling has resolved the issue.

**Comment by The-Compiler** [comment]
I pushed bumped versions for qutebrowser-git and qutebrowser-qt6-git. Something like `pacman -Qoq /usr/lib/python3.10/site-packages/* | sort | uniq` should tell you if there's any other affected packages.
