### ISSUE TITLE
Canot open Jupyter notebook: ERR_NETWORK_ACCESS_DENIED

### ISSUE THREAD

**Issue by raffaem** [qutebrowser/qutebrowser#7784]
**Version info**:

```
qutebrowser v2.5.4
Git commit: 3b04cb1d9-dirty on master (2023-07-13 09:27:19 +0200)
Backend: QtWebEngine 6.5.1, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.1

CPython: 3.11.3
PyQt: 6.5.1

Qt wrapper: PyQt6 (via default)

sip: no
colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0
adblock: 0.6.0
objc: no
PyQt6.QtWebEngineCore: 6.5.0
pdf.js: 3.7.107 (/usr/share/pdf.js/build/pdf.js)
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.1.1 30 May 2023

Style: QFusionStyle
Platform plugin: wayland
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.1.3
Platform: Linux-6.4.3-arch1-2-x86_64-with-glibc2.37, 64bit
Linux distribution: Arch Linux (arch)
Frozen: False
Imported from /usr/lib/python3.11/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib/qt6, data path: /usr/share/qt6
```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes

**Description**

I have set up xdg-open to call qutebrowser on text/html and x-scheme-handler/http.

When I try to open a Jupyter notebook, I get this screen:

![image](https://github.com/qutebrowser/qutebrowser/assets/54762742/c8ed5f9e-a458-44ef-9a5a-ff1bcdf2a2d5)

And this error message:
```
❯ jupyter-notebook 1_dplyr_rep.ipynb 

  _   _          _      _
 | | | |_ __  __| |__ _| |_ ___
 | |_| | '_ \/ _` / _` |  _/ -_)
  \___/| .__/\__,_\__,_|\__\___|
       |_|
                       
Read the migration plan to Notebook 7 to learn about the new features and the actions to take if you are using extensions.

https://jupyter-notebook.readthedocs.io/en/latest/migrate_to_notebook7.html

Please note that updating to Notebook 7 might break some of your extensions.

[W 18:35:10.432 NotebookApp] Error loading server extension jupyter_nbextensions_configurator
    Traceback (most recent call last):
      File "/usr/lib/python3.11/site-packages/notebook/notebookapp.py", line 2047, in init_server_extensions
        mod = importlib.import_module(modulename)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "/usr/lib/python3.11/importlib/__init__.py", line 126, in import_module
        return _bootstrap._gcd_import(name[level:], package, level)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
      File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
      File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
      File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
    ModuleNotFoundError: No module named 'jupyter_nbextensions_configurator'
[I 18:35:10.492 NotebookApp] Serving notebooks from local directory: /mnt/dataint/data/subjects/datascience/R/packages/dplyr
[I 18:35:10.492 NotebookApp] Jupyter Notebook 6.5.4 is running at:
[I 18:35:10.492 NotebookApp] http://localhost:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
[I 18:35:10.492 NotebookApp]  or http://127.0.0.1:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
[I 18:35:10.492 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:35:10.542 NotebookApp] 
    
    To access the notebook, open this file in a browser:
        file:///home/raffaele/.local/share/jupyter/runtime/nbserver-49667-open.html
    Or copy and paste one of these URLs:
        http://localhost:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
     or http://127.0.0.1:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
Fontconfig error: Cannot load default config file: No such file: (null)
[49701:49701:0719/183512.555829:ERROR:interface_endpoint_client.cc(694)] Message 4 rejected by interface blink.mojom.WidgetHost
18:35:12 ERROR: Load error: ERR_NETWORK_ACCESS_DENIED
```

**How to reproduce**
```
jupyter-notebook ANOTEBOOK.ipynb
```

**Comment by toofar** [comment]
>     To access the notebook, open this file in a browser:
>        file:///home/raffaele/.local/share/jupyter/runtime/nbserver-49667-open.html
>    Or copy and paste one of these URLs:
>        http://localhost:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
>     or http://127.0.0.1:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10

Which one where you on? If the file:// one try one of the http ones. Also you might have to look at one of the content.local_content_can_access* settings.
Also look in the network tab of the web inspector and check which actual requests are being blocked.

**Comment by 875d** [comment]
I *conjecture* it connects to file:// which is then redirected to https://.

Anyway it doesn't happen anymore with Jupyter Notebook 7 it seems.

Thanks!

**Comment by raffaem** [comment]
> > ```
> > To access the notebook, open this file in a browser:
> >    file:///home/raffaele/.local/share/jupyter/runtime/nbserver-49667-open.html
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Or copy and paste one of these URLs:
> > http://localhost:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
> > or http://127.0.0.1:8888/?token=442fcba88237e611ff8e540980f2fa0656c262cb7eabda10
> 
> Which one where you on? If the file:// one try one of the http ones. Also you might have to look at one of the content.local_content_can_access* settings. Also look in the network tab of the web inspector and check which actual requests are being blocked.

I conjecture it's connecting to file:// which is then redirected to the http://.

Anyway it is working after upgrading to Notebook Jupyter 7.

**Comment by The-Compiler** [comment]
Reopening as I'd still like to investigate this. I've seen this before as well, and I feel like it should work as it works fine in Chromium too. Probably an upstream QtWebEngine issue, but would still be nice if we could get a minimal example and report this upstream, there might be other applications affected by this too.

**Comment by nathanielevan** [comment]
Hi - I'm currently using Jupyter Notebook version 7.0.5 and qutebrowser 3.0.0 on Arch Linux. Just pitching in to say I'm still getting exactly the same issue and error messages that OP did.

**Comment by lockie** [comment]
I'm also getting the same error using jupyter-client 8.6.0 and qutebrowser 3.1.0 on Gentoo.

**Comment by lockie** [comment]
Having set `c.NotebookApp.use_redirect_file = False` in jupyter notebook config as per [this recommendation](https://stackoverflow.com/a/63614547/1336774) helped though, the correct link is opened the first time.
