### ISSUE TITLE
With giant count: `ValueError: Exceeds the limit (4300 digits) for integer string conversion`

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7808]
**Version info**:
qutebrowser v2.5.4
Git commit: 6d84462d6 on main (2023-07-25 11:00:33 +0200)
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.11.4
PyQt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**: yes

**Description**

```bash
qutebrowser --temp-basedir ":later 500 fake-key -g $(printf '1%.0s' {1..4301})j"
```

results in:

```pytb
Traceback (most recent call last):
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/eventfilter.py", line 100, in eventFilter
    return handler(cast(QKeyEvent, event))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/eventfilter.py", line 60, in _handle_key_event
    return man.handle_event(event)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 465, in handle_event
    return handler(cast(QKeyEvent, event))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeman.py", line 278, in _handle_keypress
    match = parser.handle(event, dry_run=dry_run)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/modeparsers.py", line 100, in handle
    match = super().handle(e, dry_run=dry_run)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 309, in handle
    self._handle_result(info, result)
  File "/home/florian/proj/qutebrowser/git/qutebrowser/keyinput/basekeyparser.py", line 318, in _handle_result
    count = int(self._count) if self._count else None
            ^^^^^^^^^^^^^^^^
ValueError: Exceeds the limit (4300 digits) for integer string conversion: value has 4301 digits; use sys.set_int_max_str_digits() to increase the limit
```

due to Python's [Integer string conversion length limitation](https://docs.python.org/3/library/stdtypes.html#integer-string-conversion-length-limitation)

**How to reproduce**

- Cat steps on keyboard
- Cat decides laptop is warm and cozy
- Cat does a long purrrrrrrrrr while resting on a number key
- Cat steps on letter key bound to some qutebrowser command

(I don't actually have a cat. But I secretly imagine this is how it happened for the person who reported this via the crashreporter.)

**Comment by pylbrecht** [comment]
Leaving this here for reference:
```
13:44:33    pylbrecht | what would be the desired behavior? Cap at Python's integer string conversion max length?
13:55:50 The-Compiler | pylbrecht: sounds good! I'd say a message.error() and ignoring the command
13:56:24 The-Compiler | see modeparsers.py for some inspiration re message.error
```

**Comment by Ingvix** [comment]
I'm hoping for the swiftest fix. I'm getting a cat in a few days and I'm scared for my browser.

**Comment by pylbrecht** [comment]
@Ingvix, apologies for the slow progress on this one. I hope your browser is ok?

My first approach was to find a cat to reproduce the issue. But this turned out to be too much effort, so I fell back onto a unit test.

**Comment by RubTalha** [comment]
https://stackoverflow.com/a/75162528/13086128
