### ISSUE TITLE
Qutebrowser crashes when click-dragging on osticket

### ISSUE THREAD

**Issue by Juliaria08** [qutebrowser/qutebrowser#7827]
**Version info**:

https://bpa.st/PKFA

**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
On some javascript bloated websites, clicking and trying to drag a link causes qutebrowser to crash

**How to reproduce**
Open a javascript bloated website in my case a osticket control pannel, (I can try to get the source for the page if wanted), and try to click and drag.

I got the core dump but I'm afraid it might contain secrets, so I sent to Floarian (@The-Compiler), however, if you know how I might get more information from the file (being able to manually redact secrets), I can do the steps required.

**Comment by The-Compiler** [comment]
> **How to reproduce** Open a javascript bloated website in my case a osticket control pannel, (I can try to get the source for the page if wanted), and try to click and drag.

Works fine for me everywhere I tried (including some [osTicket demo I could find](http://www.ostickethacks.com/demo/demo_info.php), though that doesn't seem like particularly JS heavy.

Can you be more specific? What link are you dragging where exactly on what kind of osTicket page? Since you say "some javascript bloated websites", do you have a publicly accessible example?

> I got the core dump but I'm afraid it might contain secrets, so I sent to Floarian (@The-Compiler)

Where? I didn't get anything from what I can see.

> however, if you know how I might get more information from the file (being able to manually redact secrets), I can do the steps required.

How did you get the coredump? If it shows up in `coredumpctl list`, the first step would be a `coredumpctl info PID` with the PID from the list, to get some initial information.

**Comment by Juliaria08** [comment]
> Works fine for me everywhere I tried (including some [osTicket demo I could find](http://www.ostickethacks.com/demo/demo_info.php), though that doesn't seem like particularly JS heavy.

Then I don't know really how it broke for me.

> Can you be more specific? What link are you dragging where exactly on what kind of osTicket page? Since you say "some javascript bloated websites", do you have a publicly accessible example?

I tried to drag the ticket id.

> Where? I didn't get anything from what I can see.

In a email that didn't get trough as I have a internet connection that's not fast.
 
> How did you get the coredump? If it shows up in `coredumpctl list`, the first step would be a `coredumpctl info PID` with the PID from the list, to get some initial information.

I got the coredump from the core file, as I tried to say in the email I wasn't able to send.
Then I guess I'll send it in a file hosting thing, should I publish it here or send you the link via email?

**Comment by Juliaria08** [comment]
> In the admin panel? Does that look anything like the one from the [demo page](https://www.ostickethacks.com/demo/scp/) (admin/admin)? Does it crash when you start dragging, or when you drop it somewhere? If the latter, where are you dropping it?

In the staff panel, I tried to drag the link, and I think it crashes when I start dragging it not when I drop it. I will reply to this message informing if it crashes, (as I don't want to lose the comment)

> Note that mail attachments over ~20MB or so will usually be an issue anyways with almost all mail providers.

Yeah probably my own mail server would've rejected the email, but I didn't get that so I tought it was sending the file. Probably your server would've rejected 
the email if mine tried to send the full file.
(I guess the server just keeps waiting for the entire file, and then would error out , but it took long to send it)
 
> Ah, right, Artix Linux, I missed that part. Things are going to be a bit more 
manual in that case.

Oh, I think I only wrote that on the email that I didn't send.

> It'd be good if you could get a stack trace from the coredump, I don't really need the entire file.

Ah that's better.

> Here is how that should work, hopefully:
> 
> * Install `gdb` and `debuginfod`
> * Make sure `echo $DEBUGINFOD_URLS` shows something - might need to relogin if not, or `export DEBUGINFOD_URLS="https://debuginfod.artixlinux.org"` in the shell you're using
> * Run `gdb /usr/bin/python3 yourcoredump`
> * Answer `y` when gdb asks you to download core files (might be some big downloads - if that's too much, do it without, but it will be more useful with)
> * Once you get a `(gdb)` prompt, run `set pagination off`
> * Run `bt` and hopefully get a stacktrace

Doing it now, downloading files (I don't really have a issue with that, it's just that it might take it's time)

**Comment by Juliaria08** [comment]
The link that I try to drag is the ticket link inside of a ticket.

**Comment by Juliaria08** [comment]
@The-Compiler here's the stacktrace:
```
(gdb) bt
#0  0x00007f0307e8e83c in  () at /usr/lib/libc.so.6
#1  0x00007f0307e3e668 in raise () at /usr/lib/libc.so.6
#2  0x00007f0307e3e710 in <signal handler called> () at /usr/lib/libc.so.6
#3  0x00007f03017112a5 in QDrag::dragCursor(Qt::DropAction) const () at /usr/lib/libQt6Gui.so.6
#4  0x00007f03017124dd in QBasicDrag::updateCursor(Qt::DropAction) () at /usr/lib/libQt6Gui.so.6
#5  0x00007f02e649192b in  () at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#6  0x00007f0305d911ca in  () at /usr/lib/libQt6Core.so.6
#7  0x00007f02e6493588 in non-virtual thunk to QtWaylandClient::QWaylandDataSource::data_source_action(unsigned int) ()
    at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#8  0x00007f03087e14f6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#9  0x00007f03087ddf5e in ffi_call_int
    (cif=cif@entry=0x7ffdb485a0b0, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0)
    at ../src/x86/ffi64.c:673
#10 0x00007f03087e0b73 in ffi_call (cif=0x7ffdb485a0b0, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>)
    at ../src/x86/ffi64.c:710
#11 0x00007f0306760645 in  () at /usr/lib/qt6/plugins/platforms/../../../libwayland-client.so.0
#12 0x00007f0306760e73 in  () at /usr/lib/qt6/plugins/platforms/../../../libwayland-client.so.0
#13 0x00007f030676113c in wl_display_dispatch_queue_pending () at /usr/lib/qt6/plugins/platforms/../../../libwayland-client.so.0
#14 0x00007f02e6451906 in  () at /usr/lib/qt6/plugins/platforms/../../../libQt6WaylandClient.so.6
#15 0x00007f0305d913c3 in  () at /usr/lib/libQt6Core.so.6
#16 0x00007f0305f3262c in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#17 0x00007f0305d454b3 in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () at /usr/lib/libQt6Core.so.6
#18 0x00007f0305d3f088 in QCoreApplication::exec() () at /usr/lib/libQt6Core.so.6
#19 0x00007f030275c68e in  () at /usr/lib/python3.11/site-packages/PyQt6/QtWidgets.abi3.so
#20 0x00007f03083fab18 in  () at /usr/lib/libpython3.11.so.1.0
#21 0x00007f03083d9cec in _PyObject_MakeTpCall () at /usr/lib/libpython3.11.so.1.0
#22 0x00007f03083e4279 in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.11.so.1.0
#23 0x00007f030849e37a in  () at /usr/lib/libpython3.11.so.1.0
#24 0x00007f030849dd8c in PyEval_EvalCode () at /usr/lib/libpython3.11.so.1.0
#25 0x00007f03084bbd23 in  () at /usr/lib/libpython3.11.so.1.0
#26 0x00007f03084b7bea in  () at /usr/lib/libpython3.11.so.1.0
#27 0x00007f03084cd793 in  () at /usr/lib/libpython3.11.so.1.0
#28 0x00007f03084ccfc5 in _PyRun_SimpleFileObject () at /usr/lib/libpython3.11.so.1.0
#29 0x00007f03084cc808 in _PyRun_AnyFileObject () at /usr/lib/libpython3.11.so.1.0
#30 0x00007f03084c7008 in Py_RunMain () at /usr/lib/libpython3.11.so.1.0
#31 0x00007f030849060b in Py_BytesMain () at /usr/lib/libpython3.11.so.1.0
#32 0x00007f0307e27cd0 in  () at /usr/lib/libc.so.6
#33 0x00007f0307e27d8a in __libc_start_main () at /usr/lib/libc.so.6
#34 0x0000558d01f6e045 in _start ()
```

**Comment by The-Compiler** [comment]
Ah, it looks to be Wayland specific, which explains why I couldn't reproduce.

Seems to be this issue: [[QTBUG-115757] [REG: 6.5.1-6.5.2] Drag and Drop segfaults programs - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-115757)

Looks like a fix got integrated today, I asked Archlinux to backport it: [FS#79345 : [qt6-wayland] [patch] Drag & drop crashes Wayland Qt applications](https://bugs.archlinux.org/task/79345).

**Comment by Juliaria08** [comment]
Thanks, so it'll just be waiting for the backport, and then the release right?

**Comment by Juliaria08** [comment]
> Ah, it looks to be Wayland specific, which explains why I couldn't reproduce.
> 
> Seems to be this issue: [[QTBUG-115757] [REG: 6.5.1-6.5.2] Drag and Drop segfaults programs - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-115757)
> 
> Looks like a fix got integrated today, I asked Archlinux to backport it: [FS#79345 : [qt6-wayland] [patch] Drag & drop crashes Wayland Qt applications](https://bugs.archlinux.org/task/79345).

Sorry I should've mentioned that. And that I was using the qt6 branch.

**Comment by The-Compiler** [comment]
> Thanks, so it'll just be waiting for the backport, and then the release right?

Yep, not much that qutebrowser can do. It could *maybe* block drags entirely using an event filter, but given that this issue is somewhat exotic and fixed upstream already, I don't think it'll be worth the effort.

> Sorry I should've mentioned that. And that I was using the qt6 branch.

No worries - you posted the version info, so all the information was there :)

**Comment by The-Compiler** [comment]
Getting more reports for this and Archlinux hasn't backported the fix so far. Will check if we can just prevent drag & drop on the affected Qt version as a workaround.

**Comment by The-Compiler** [comment]
Reproduced by dragging the image on https://www.w3schools.com/HTML/html5_draganddrop.asp with Wayland platform plugin.

Full stacktrace:

```gdb
#0  QDrag::dragCursor(Qt::DropAction) const (this=0x0, action=action@entry=Qt::CopyAction) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/kernel/qdrag.cpp:282
#1  0x00007ffff13124dd in QBasicDrag::updateCursor(Qt::DropAction) (this=this@entry=0x555555ba8190, action=Qt::CopyAction) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/gui/kernel/qsimpledrag.cpp:274
#2  0x00007fffd3f36914 in QtWaylandClient::QWaylandDrag::setResponse(QPlatformDropQtResponse const&) (response=..., this=0x555555ba8190) at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.5.2/src/client/qwaylanddnd.cpp:85
#3  QtWaylandClient::QWaylandDrag::setResponse(QPlatformDropQtResponse const&) (response=..., this=0x555555ba8190) at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.5.2/src/client/qwaylanddnd.cpp:80
#4  operator() (action=Qt::CopyAction, accepted=true, __closure=<optimized out>) at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.5.2/src/client/qwaylanddatadevice.cpp:105
#5  QtPrivate::FunctorCall<QtPrivate::IndexesList<0, 1>, QtPrivate::List<bool, Qt::DropAction>, void, QtWaylandClient::QWaylandDataDevice::startDrag(QMimeData*, Qt::DropActions, QtWaylandClient::QWaylandWindow*)::<lambda(bool, Qt::DropAction)> >::call (arg=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:127
#6  QtPrivate::Functor<QtWaylandClient::QWaylandDataDevice::startDrag(QMimeData*, Qt::DropActions, QtWaylandClient::QWaylandWindow*)::<lambda(bool, Qt::DropAction)>, 2>::call<QtPrivate::List<bool, Qt::DropAction>, void> (arg=<optimized out>, f=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:241
#7  QtPrivate::QFunctorSlotObject<QtWaylandClient::QWaylandDataDevice::startDrag(QMimeData*, Qt::DropActions, QtWaylandClient::QWaylandWindow*)::<lambda(bool, Qt::DropAction)>, 2, QtPrivate::List<bool, Qt::DropAction>, void>::impl(int, QtPrivate::QSlotObjectBase *, QObject *, void **, bool *) (which=<optimized out>, this_=<optimized out>, r=<optimized out>, a=<optimized out>, ret=<optimized out>) at /usr/include/qt6/QtCore/qobjectdefs_impl.h:409
#8  0x00007ffff599134a in QtPrivate::QSlotObjectBase::call(QObject*, void**) (a=0x7fffffffb740, r=0x555555dd0870, this=0x5555589833d0, this=<optimized out>, r=<optimized out>, a=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qobjectdefs_impl.h:363
#9  doActivate<false>(QObject*, int, void**) (sender=0x555557c2b330, signal_index=5, argv=0x7fffffffb740) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qobject.cpp:3992
#10 0x00007fffd3f3845f in non-virtual thunk to QtWaylandClient::QWaylandDataSource::data_source_target(QString const&) () at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.5.2/src/client/qwaylanddatasource_p.h:51
#11 0x00007fffd3f27eb4 in QtWayland::wl_data_source::handle_target(void*, wl_data_source*, char const*) (data=0x555557c2b340, object=<optimized out>, mime_type=0x7fffc8004bdc "text/plain") at /usr/src/debug/qt6-wayland/build/src/client/qwayland-wayland.cpp:734
#12 0x00007ffff7e124f6 in ffi_call_unix64 () at ../src/x86/unix64.S:104
#13 0x00007ffff7e0ef5e in ffi_call_int (cif=cif@entry=0x7fffffffb970, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>, closure=closure@entry=0x0) at ../src/x86/ffi64.c:673
#14 0x00007ffff7e11b73 in ffi_call (cif=cif@entry=0x7fffffffb970, fn=<optimized out>, rvalue=rvalue@entry=0x0, avalue=avalue@entry=0x7fffffffba40) at ../src/x86/ffi64.c:710
#15 0x00007ffff25ef645 in wl_closure_invoke (closure=closure@entry=0x7fffc8004b00, target=<optimized out>, target@entry=0x55555888e3f0, opcode=opcode@entry=0, data=<optimized out>, flags=1) at ../wayland-1.22.0/src/connection.c:1025
#16 0x00007ffff25efe73 in dispatch_event (display=display@entry=0x555555e4add0, queue=0x555555e4aec0) at ../wayland-1.22.0/src/wayland-client.c:1631
#17 0x00007ffff25f013c in dispatch_queue (queue=0x555555e4aec0, display=0x555555e4add0) at ../wayland-1.22.0/src/wayland-client.c:1777
#18 wl_display_dispatch_queue_pending (display=0x555555e4add0, queue=0x555555e4aec0) at ../wayland-1.22.0/src/wayland-client.c:2019
#19 0x00007fffd3ef6906 in QtWaylandClient::EventThread::readAndDispatchEvents() (this=0x555555e4dab0) at /usr/src/debug/qt6-wayland/qtwayland-everywhere-src-6.5.2/src/client/qwaylanddisplay.cpp:234
#20 0x00007ffff597d147 in QObject::event(QEvent*) (this=0x555555e3f190, e=0x7fffc4004600) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qobject.cpp:1391
#21 0x00007ffff197136b in QApplicationPrivate::notify_helper(QObject*, QEvent*) (this=this@entry=0x555555db6310, receiver=0x555555e3f190, receiver@entry=0x0, e=e@entry=0x7fffc4004600) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/widgets/kernel/qapplication.cpp:3287
#22 0x00007ffff1973139 in QApplication::notify(QObject*, QEvent*) (this=this@entry=0x555555cb0a70, receiver=0x0, receiver@entry=0x555555e3f190, e=e@entry=0x7fffc4004600) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/widgets/kernel/qapplication.cpp:3049
#23 0x00007ffff235e9c7 in sipQApplication::notify(QObject*, QEvent*) (this=0x555555cb0a70, a0=0x555555e3f190, a1=0x7fffc4004600) at /usr/src/debug/pyqt6/PyQt6-6.5.2/build/QtWidgets/sipQtWidgetsQApplication.cpp:243
#24 0x00007ffff593b718 in QCoreApplication::notifyInternal2(QObject*, QEvent*) (receiver=0x555555e3f190, event=event@entry=0x7fffc4004600) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1118
#25 0x00007ffff593ba9b in QCoreApplication::sendEvent(QObject*, QEvent*) (event=0x7fffc4004600, receiver=<optimized out>) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1536
#26 QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) (receiver=0x0, event_type=0, data=0x55555581b750) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1898
#27 0x00007ffff5b34854 in QCoreApplication::sendPostedEvents(QObject*, int) (receiver=0x0, event_type=0) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qcoreapplication.cpp:1757
#28 postEventSourceDispatch(GSource*, GSourceFunc, gpointer) (s=0x555555e4db00) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventdispatcher_glib.cpp:243
#29 0x00007ffff66cda31 in g_main_dispatch (context=0x7fffcc000fc0) at ../glib/glib/gmain.c:3460
#30 g_main_context_dispatch (context=0x7fffcc000fc0) at ../glib/glib/gmain.c:4200
#31 0x00007ffff672acc9 in g_main_context_iterate.isra.0 (context=context@entry=0x7fffcc000fc0, block=block@entry=1, dispatch=dispatch@entry=1, self=<optimized out>) at ../glib/glib/gmain.c:4276
#32 0x00007ffff66cb0e2 in g_main_context_iteration (context=0x7fffcc000fc0, may_block=1) at ../glib/glib/gmain.c:4343
#33 0x00007ffff5b32794 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x555555a58960, flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventdispatcher_glib.cpp:393
#34 0x00007ffff5945623 in QEventLoop::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) (flags=..., this=0x7fffffffc070) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventloop.cpp:100
#35 QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) (this=0x7fffffffc070, flags=...) at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/kernel/qeventloop.cpp:182
#36 0x00007ffff593f1f8 in QCoreApplication::exec() () at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/corelib/global/qflags.h:74
#37 0x00007ffff196defa in QApplication::exec() () at /usr/src/debug/qt6-base/qtbase-everywhere-src-6.5.2/src/widgets/kernel/qapplication.cpp:2566
#38 0x00007ffff235c68e in meth_QApplication_exec(PyObject*, PyObject*) (sipSelf=<optimized out>, sipArgs=<optimized out>) at /usr/src/debug/pyqt6/PyQt6-6.5.2/build/QtWidgets/sipQtWidgetsQApplication.cpp:1283
#39 0x00007ffff79f9fc8 in  () at /usr/lib/libpython3.11.so.1.0
#40 0x00007ffff79d870c in _PyObject_MakeTpCall () at /usr/lib/libpython3.11.so.1.0
#41 0x00007ffff79e32bd in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.11.so.1.0
#42 0x00007ffff7aa0a34 in  () at /usr/lib/libpython3.11.so.1.0
#43 0x00007ffff7aa0428 in PyEval_EvalCode () at /usr/lib/libpython3.11.so.1.0
#44 0x00007ffff7ab715e in  () at /usr/lib/libpython3.11.so.1.0
#45 0x00007ffff79f1f26 in  () at /usr/lib/libpython3.11.so.1.0
#46 0x00007ffff79f10b3 in PyObject_Vectorcall () at /usr/lib/libpython3.11.so.1.0
#47 0x00007ffff79e32bd in _PyEval_EvalFrameDefault () at /usr/lib/libpython3.11.so.1.0
#48 0x00007ffff7a0a8c0 in _PyFunction_Vectorcall () at /usr/lib/libpython3.11.so.1.0
#49 0x00007ffff7ac9507 in  () at /usr/lib/libpython3.11.so.1.0
#50 0x00007ffff7ac8e11 in Py_RunMain () at /usr/lib/libpython3.11.so.1.0
#51 0x00007ffff7a92f77 in Py_BytesMain () at /usr/lib/libpython3.11.so.1.0
#52 0x00007ffff7427cd0 in __libc_start_call_main (main=main@entry=0x555555555120, argc=argc@entry=5, argv=argv@entry=0x7fffffffc948) at ../sysdeps/nptl/libc_start_call_main.h:58
#53 0x00007ffff7427d8a in __libc_start_main_impl (main=0x555555555120, argc=5, argv=0x7fffffffc948, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffc938) at ../csu/libc-start.c:360
#54 0x0000555555555045 in _start ()
```


Workaround that triggers according to the log but doesn't actually fix the issue sadly:

```diff
diff --git i/qutebrowser/browser/eventfilter.py w/qutebrowser/browser/eventfilter.py
index 1cff11ac4..107635661 100644
--- i/qutebrowser/browser/eventfilter.py
+++ w/qutebrowser/browser/eventfilter.py
@@ -5,12 +5,13 @@
 """Event handling for a browser tab."""
 
 from qutebrowser.qt import machinery
-from qutebrowser.qt.core import QObject, QEvent, Qt, QTimer
+from qutebrowser.qt.core import QObject, QEvent, Qt, QTimer, qVersion
 from qutebrowser.qt.widgets import QWidget
 
 from qutebrowser.config import config
 from qutebrowser.utils import log, message, usertypes, qtutils
 from qutebrowser.keyinput import modeman
+from qutebrowser.misc import objects
 
 
 class ChildEventFilter(QObject):
@@ -95,10 +96,27 @@ def __init__(self, tab, *, parent=None):
             QEvent.Type.MouseButtonPress: self._handle_mouse_press,
             QEvent.Type.MouseButtonRelease: self._handle_mouse_release,
             QEvent.Type.Wheel: self._handle_wheel,
+            QEvent.Type.DragEnter: self._handle_drag,
+            QEvent.Type.DragMove: self._handle_drag,
+            QEvent.Type.DragLeave: self._handle_drag,
         }
         self._ignore_wheel_event = False
         self._check_insertmode_on_release = False
 
+    def _handle_drag(self, e):
+        """Ignore drag events on Wayland with Qt 6.5.2.
+
+        WORKAROUND for https://bugreports.qt.io/browse/QTBUG-115757
+
+        Return:
+            True if the event should be filtered, False otherwise.
+        """
+        if objects.qapp.platformName() == "wayland" and qVersion() == "6.5.2":
+            log.mouse.warning("Ignoring drag event to prevent Qt crash")
+            return True
+        breakpoint()
+        return False
+
     def _handle_mouse_press(self, e):
         """Handle pressing of a mouse button.
 
```

**Comment by The-Compiler** [comment]
Another attempt:

```diff
diff --git i/qutebrowser/misc/nativeeventfilter.py w/qutebrowser/misc/nativeeventfilter.py
index 9b1bbb97c..d61957c45 100644
--- i/qutebrowser/misc/nativeeventfilter.py
+++ w/qutebrowser/misc/nativeeventfilter.py
@@ -96,7 +96,26 @@ class xcb_query_extension_reply_t(ctypes.Structure):  # noqa: N801
     _PointerRetType = int
 
 
-class NativeEventFilter(QAbstractNativeEventFilter):
+class WaylandNativeEventFilter(QAbstractNativeEventFilter):
+
+    """Event filter for Qt 6.5.2 Wayland drag/drop crash."""
+
+    # Return values for nativeEventFilter.
+    #
+    # Tuple because PyQt uses the second value as the *result out-pointer, which
+    # according to the Qt documentation is only used on Windows.
+    _PASS_EVENT_RET = (False, cast(_PointerRetType, 0))
+    _FILTER_EVENT_RET = (True, cast(_PointerRetType, 0))
+
+    def nativeEventFilter(
+        self, eventType: Union[bytes, QByteArray], message: Optional[sip.voidptr]
+    ) -> Tuple[bool, _PointerRetType]:
+        """Handle Wayland events."""
+        breakpoint()
+        return self._FILTER_EVENT_RET
+
+
+class XcbNativeEventFilter(QAbstractNativeEventFilter):
 
     """Event filter for XCB messages to work around Qt 6.5.1 crash."""
 
@@ -179,9 +198,11 @@ def init() -> None:
     qt_version = qVersion()
     log.misc.debug(f"Platform {platform}, Qt {qt_version}")
 
-    if platform != "xcb" or qt_version != "6.5.1":
-        return
-
-    log.misc.debug("Installing native event filter to work around Qt 6.5.1 crash")
-    _instance = NativeEventFilter()
-    objects.qapp.installNativeEventFilter(_instance)
+    if platform == "xcb" and qt_version == "6.5.1":
+        log.misc.debug("Installing native event filter to work around Qt 6.5.1 crash")
+        _instance = XcbNativeEventFilter()
+        objects.qapp.installNativeEventFilter(_instance)
+    elif platform == "wayland" and qt_version == "6.5.2":
+        log.misc.debug("Installing native event filter to work around Qt 6.5.2 crash")
+        _instance = WaylandNativeEventFilter()
+        objects.qapp.installNativeEventFilter(_instance)

```

but that just doesn't get called by Qt at all. Will take another look at the Qt Wayland code tomorrow, but it might well be that we just can't work around this.

**Comment by deprecated-dot** [comment]
Gentoo has backported a segfault fix for this drag & drop issue, see: 
https://gitweb.gentoo.org/repo/gentoo.git/commit/dev-qt/qtwayland?id=69c8497c982a6e82cd1c1762e27c3cdfe52436ed

Perhaps this is a way forward without the recent qutebrowser commit, and might be of use to @The-Compiler and others. I'm reverting to the previous qutebrowser commit now, with the updated version of dev-qt/qtwayland-6.5.2. Will report back.

**Comment by The-Compiler** [comment]
That commit only fixes the crash, I believe drag & drop is still somewhat broken after it. So the backport and the workaround in qutebrowser aren't mutually exclusive.
