### ISSUE TITLE
Building an arm build on macOS results in path issues

### ISSUE THREAD

**Issue by hpfmn** [qutebrowser/qutebrowser#7859]
**Version info**:
qutebrowser v3.0.0
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

**Does the bug happen if you start with `--temp-basedir`?**:

yes

**Description**

If you build on an arm macOS the universal/arm version of all libraries are used - resulting an an arm build. But if you try to run it it seems something with the path resolution is wrong. The executable doesn't detect the needed resources regards of running inside `dist/qutebrowser` or `dist/qutebrowser.app`. Output looks something like that:

```
❯ ./qutebrowser
[16865] Error loading Python lib '/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser/Python': dlopen: dlopen(/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser/Python, 0x000A): tried: '/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser/Python' (no such file), '/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser/Python' (no such file)
```

```
❯ ./dist/qutebrowser.app/Contents/MacOS/qutebrowser
[18299] Error loading Python lib '/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser.app/Contents/MacOS/Python': dlopen: dlopen(/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser.app/Contents/MacOS/Python, 0x000A): tried: '/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser.app/Contents/MacOS/Python' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser.app/Contents/MacOS/Python' (no such file), '/Users/hpfmn/GIT/qutebrowser/dist/qutebrowser.app/Contents/MacOS/Python' (no such file)
```

**How to reproduce**

Run inside the qutebrowser source code folder on arm macOS:

```
❯ python -m venv venv
❯ . venv/bin/activate
❯ python -m pip install -U -r misc/requirements/requirements-tox.txt
❯ tox -e build-release
```

Now you should already see something like this:

```
pyinstaller: 27545 I exit 0 (21.77 seconds) /Users/hpfmn/GIT/qutebrowser> .tox/pyinstaller/bin/pyinstaller --noconfirm misc/qutebrowser.spec pid=17573 [tox/execute/api.py:279]
  pyinstaller: OK (27.43=setup[5.66]+cmd[21.77] seconds)
  congratulations :) (27.48 seconds)

==================== Verifying .app ====================
dist/qutebrowser.app: valid on disk
dist/qutebrowser.app: satisfies its Designated Requirement

==================== Running pre-dmg smoke test ====================
Traceback (most recent call last):
  File "/Users/hpfmn/GIT/qutebrowser/scripts/dev/build_release.py", line 741, in <module>
    main()
  File "/Users/hpfmn/GIT/qutebrowser/scripts/dev/build_release.py", line 709, in main
    artifacts = build_mac(
                ^^^^^^^^^^
  File "/Users/hpfmn/GIT/qutebrowser/scripts/dev/build_release.py", line 292, in build_mac
    smoke_test(_mac_bin_path(dist_path), debug=debug, qt5=qt5)
  File "/Users/hpfmn/GIT/qutebrowser/scripts/dev/build_release.py", line 184, in smoke_test
    proc = _smoke_test_run(executable)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/hpfmn/GIT/qutebrowser/scripts/dev/build_release.py", line 124, in _smoke_test_run
    return subprocess.run(argv, check=True, capture_output=True)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/Cellar/python@3.11/3.11.4_1/Frameworks/Python.framework/Versions/3.11/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '[PosixPath('dist/qutebrowser.app/Contents/MacOS/qutebrowser'), '--no-err-windows', '--nowindow', '--temp-basedir', 'about:blank', ':cmd-later 500 quit']' returned non-zero exit status 255.
build-release: exit 1 (37.99 seconds) /Users/hpfmn/GIT/qutebrowser> .tox/build-release/bin/python /Users/hpfmn/GIT/qutebrowser/scripts/dev/build_release.py pid=17495
  build-release: FAIL code 1 (38.02=setup[0.03]+cmd[37.99] seconds)
  evaluation failed :( (38.05 seconds)
```

**How to work around**

for non-app

```
❯ cd dist/qutebrowser
❯ mv qutebrowser _internal/qutebrowser_bin
❯ ln -s _internal/qutebrowser_bin qutebrowser
```

for app

```
❯ cd dist/qutebrowser.app/Contents/MacOS
❯ mv qutebrowser ../Resources/qutebrowser_bin
❯ ln -s ../Resources/qutebrowser_bin qutebrowser
```

Also here is diff in file-structure for official build vs my build:

```
❯ diff <(tree) <(tree /Applications/qutebrowser.app/)
1c1
< .
---
> /Applications/qutebrowser.app/
1536,1539c1536,1538
<     │   ├── libcrypto.3.dylib
<     │   ├── liblzma.5.dylib
<     │   ├── libmpdec.3.dylib
<     │   ├── libssl.3.dylib
---
>     │   ├── libcrypto.1.1.dylib
>     │   ├── libncursesw.5.dylib
>     │   ├── libssl.1.1.dylib
3190,3193c3189,3191
<     │   ├── libcrypto.3.dylib -> ../Frameworks/libcrypto.3.dylib
<     │   ├── liblzma.5.dylib -> ../Frameworks/liblzma.5.dylib
<     │   ├── libmpdec.3.dylib -> ../Frameworks/libmpdec.3.dylib
<     │   ├── libssl.3.dylib -> ../Frameworks/libssl.3.dylib
---
>     │   ├── libcrypto.1.1.dylib -> ../Frameworks/libcrypto.1.1.dylib
>     │   ├── libncursesw.5.dylib -> ../Frameworks/libncursesw.5.dylib
>     │   ├── libssl.1.1.dylib -> ../Frameworks/libssl.1.1.dylib
3766c3764
< 737 directories, 3027 files
---
> 737 directories, 3025 files
```

**Comment by hpfmn** [comment]
Just to let you know - the workaround is still needed for current v3.0.2 release.

**Comment by The-Compiler** [comment]
Unfortunately haven't gotten around to looking at this yet. That being said, this sounds more of a PyInstaller thing than a qutebrowser thing?

**Comment by hpfmn** [comment]
I have good news - just did a build with the v3.1.0 tagged code and now the workaround is not necessary. It used pyinstaller 6.2.0 - so probably there were some changes there as well.

**Comment by The-Compiler** [comment]
Nice, so I guess one more down! Thanks for the update!
