### ISSUE TITLE
`AssertionError` for `assert model is not None` in `completionwidget.py`

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7901]
**Version info**:
```
qutebrowser v3.0.0
Git commit: 
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2
```

**Does the bug happen if you start with `--temp-basedir`?**: unknown

**Description**

```pytb
14:18:17 DEBUG    commands   command:run:511 command called: mode-leave
14:18:17 DEBUG    commands   command:run:525 Calling qutebrowser.keyinput.modeman.ModeManager.mode_leave(<qutebrowser.keyinput.modeman.ModeManager mode=<KeyMode.command: 3>>)
14:18:17 DEBUG    modes      modeman:leave:428 Leaving mode KeyMode.command (reason: leave current)
14:18:17 DEBUG    statusbar  bar:set_mode_active:333 Setting command flag to False
14:18:17 DEBUG    completion completer:schedule_completion_update:216 Scheduling completion update.
14:18:17 DEBUG    completion completer:schedule_completion_update:213 Ignoring update because there were no changes.
14:18:17 DEBUG    statusbar  bar:_hide_cmd_widget:367 Hiding cmd widget
14:18:17 DEBUG    misc       app:on_focus_object_changed:566 Focus object changed: <qutebrowser.mainwindow.mainwindow.MainWindow, className='MainWindow'>
14:18:17 DEBUG    misc       app:on_focus_object_changed:566 Focus object changed: <qutebrowser.mainwindow.statusbar.textbase.TextBase text='', className='TextBase'>
14:18:17 ERROR    misc       crashsignal:_handle_early_exits:226 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qutebrowser/completion/[completionwidget.py](http://completionwidget.py/)", line 417, in on_clear_completion_selection
    selmod = self._selection_model()
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qutebrowser/completion/[completionwidget.py](http://completionwidget.py/)", line 152, in _selection_model
    assert model is not None
           ^^^^^^^^^^^^^^^^^
AssertionError
```

`169382990767.21833.4507454517096083506@crashes.qutebrowser.org`

**How to reproduce**
unknown

**Comment by The-Compiler** [comment]
Seem to be seeing this more in crash reports. Not sure what's happening there, and I don't think someone has come up with a reproducer yet. Might be some sort of race condition?
