### ISSUE TITLE
`check_qdatastream`: OSError: The data stream has read past the end of the data in the underlying device.

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#7913]
**Version info**:
qutebrowser v3.0.0, Qt 6.5.1/6.5.2

**Does the bug happen if you start with `--temp-basedir`?**: unknown

**Description**

Getting more reports than usual with Qt 6.5 about a crash here:

https://github.com/qutebrowser/qutebrowser/blob/b070cf45dbed27771578d98f3f4129d1f52a28f3/qutebrowser/utils/qtutils.py#L166-L177

via

```pytb
Traceback (most recent call last):
  ...
  File "/usr/lib/python3.11/site-packages/qutebrowser/browser/commands.py", line 870, in undo
    self._tabbed_browser.undo(depth)
  File "/usr/lib/python3.11/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 562, in undo
    newtab.history.private_api.deserialize(entry.history)
  File "/usr/lib/python3.11/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 619, in deserialize
    qtutils.deserialize(data, self._history)
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/qtutils.py", line 200, in deserialize
    deserialize_stream(stream, obj)
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/qtutils.py", line 216, in deserialize_stream
    check_qdatastream(stream)
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/qtutils.py", line 177, in check_qdatastream
    raise OSError(status_to_str[stream.status()])
OSError: The data stream has read past the end of the data in the underlying device.
```

![image](https://github.com/qutebrowser/qutebrowser/assets/625793/3dbcd365-f437-454d-9572-d9023670913b)

cc @emanuele6 

**How to reproduce**

Unclear. Seems to happen with `:undo` and `:tab-clone`, but only rarely. Should probably make it a non-fatal error and show a message instead of crashing.

**Comment by The-Compiler** [comment]
Got a more detailed report:

> - Opened https://filecrypt.co/Container/77EDE83746.html
> - Clicked on the page, opening some kind of inline advertisement (in a separate tab)
> - Pressed d, closing the current tab
> - Pressed u, expecting to re-open the tab, but instead causing a crash
> 
> This can be reproduced consistently on my machine.

Unfortunately still no luck here. Could someone try reproducing with the steps above? I believe the clicking (opening an ad) is after you did the security question part.

**Comment by The-Compiler** [comment]
Heh, I ended up running into this while trying to `gC` a tab that was still loading, and then was able to reduce it to this:

```
qutebrowser --debug --temp-basedir about:blank :tab-clone
```

Looks like a Qt 6.5 regression, works fine in older Qt versions.

**Comment by The-Compiler** [comment]
```diff
diff --git i/qutebrowser/browser/commands.py w/qutebrowser/browser/commands.py
index 83a846b85..5a65bc7ff 100644
--- i/qutebrowser/browser/commands.py
+++ w/qutebrowser/browser/commands.py
@@ -394,6 +394,7 @@ def tab_clone(self, bg=False, window=False, private=False):
             history = curtab.history.private_api.serialize()
         except browsertab.WebTabError as e:
             raise cmdutils.CommandError(e)
+        print(history)
 
         if window or private:
             new_tabbed_browser = self._new_tabbed_browser(
```

results in:

```
b'\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x00'
```

while a valid serialization would look like:

```
b'\x00\x00\x00\x04\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x0babout:blank\x00\x00\x00\x00\x00\x00\x02D@\x02\x00\x00\x1f\x00\x00\x008\x02\x00\x00\x18\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x88\x00\x00\x00\x05\x00\x00\x00\x80\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa0\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xa8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x06\x00\x00\x00\xa0\x00\x00\x00\x00\x00\x00\x00-\xbaXb\x1e\x06\x06\x00.\xbaXb\x1e\x06\x06\x00\xe0\x00\x00\x00\x00\x00\x00\x00\xf8\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf0\x00\x00\x00\x00\x00\x00\x00H\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x1e\x00\x00\x00\x0b\x00\x00\x00a\x00b\x00o\x00u\x00t\x00:\x00b\x00l\x00a\x00n\x00k\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x008\x00\x00\x00\x01\x00\x00\x000\x00\x00\x00\x00\x00\x00\x008\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00 \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00\x10\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00P\x00\x00\x00$\x00\x00\x003\x001\x001\x007\x00c\x003\x00f\x00a\x00-\x004\x00f\x009\x005\x00-\x004\x00e\x001\x000\x00-\x008\x001\x00d\x00d\x00-\x005\x000\x00d\x006\x004\x001\x004\x00e\x007\x002\x008\x00b\x00\x10\x00\x00\x00\x00\x00\x00\x00\x08\x00\x00\x00\x00\x00\x00\x00P\x00\x00\x00$\x00\x00\x00d\x006\x003\x00a\x00b\x009\x00f\x006\x00-\x003\x002\x00b\x00e\x00-\x004\x00f\x004\x008\x00-\x00a\x002\x007\x008\x00-\x009\x00b\x00f\x007\x008\x00a\x00f\x00b\x00a\x001\x00e\x003\x
```

looking at [the QtWebEngine logic](https://github.com/qt/qtwebengine/blob/v6.5.2/src/core/web_contents_adapter.cpp#L213-L333), this is:

```python
00 00 00 04  # kHistoryStreamVersion
00 00 00 01  # count
00 00 00 00  # currentIndex
```

notably, QtWebEngine doesn't *serialize* invalid entries:

```cpp
    // Logic taken from SerializedNavigationEntry::WriteToPickle.
    for (int i = 0; i < count; ++i) {
        content::NavigationEntry* entry = (i == pendingIndex)
            ? controller.GetPendingEntry()
            : controller.GetEntryAtIndex(i);
        if (entry->GetVirtualURL().is_valid()) {
            // ...
        }
    }
```

but then *does* read things according to `count` only when deserializing:

```cpp
    // Logic taken from SerializedNavigationEntry::ReadFromPickle and ToNavigationEntries.
    for (int i = 0; i < count; ++i) {
        // ...
        input >> virtualUrl;
```

What confuses me, though, is that this code [didn't really change much](https://github.com/qt/qtwebengine/blame/v6.5.2/src/core/web_contents_adapter.cpp#L213-L333) in the past couple of years...

**Comment by The-Compiler** [comment]
Ah, with Qt 6.4, the serializing results in:

```python
00 00 00 04  # kHistoryStreamVersion
00 00 00 00  # count
ff ff ff ff  # currentIndex
```

which makes more sense.

This is probably the Chromium change that needs an adoption from Qt:

[Create initial NavigationEntry on FrameTree initialization (3237491) · Gerrit Code Review](https://chromium-review.googlesource.com/c/chromium/src/+/3237491)

**Comment by The-Compiler** [comment]
[[QTBUG-117489] [REG 6.4 -> 6.5] Invalid QDataStream data when serializing uninited QWebEngineHistory - Qt Bug Tracker](https://bugreports.qt.io/browse/QTBUG-117489)
