### ISSUE TITLE
Fedora 39: crash at startup with qt6

### ISSUE THREAD

**Issue by sanjayankur31** [qutebrowser/qutebrowser#7927]
3.0.0 just landed in Fedora 39. I was asked if I wanted to use Qt6 etc., and when chose to proceed, it crashed. But it seems to be a general issue where it crashes even when using `-T` to ensure none of my config bits were causing the issue.

I'll also file a bug at Fedora, but wanted to see if you had any hints? (Fedora 39 is being released soon, so it'll be good to make sure qutebrowser works on it properly before then)

**Version info**:
==== Version info ====
```
         ______     ,,
    ,.-"`      | ,-` |
  .^           ||    |
 /    ,-*^|    ||    |
;    /    |    ||    ;-*```^*.
;   ;     |    |;,-*`         \
|   |     |  ,-*`    ,-"""\    \
|    \   ,-"`    ,-^`|     \    |
 \    `^^    ,-;|    |     ;    |
  *;     ,-*`  ||    |     /   ;;
    `^^`` |    ||    |   ,^    /
          |    ||    `^^`    ,^
          |  _,"|        _,-"
          -*`   ****"""``

qutebrowser v3.0.0
Backend: QtWebEngine 6.5.2, based on Chromium 108.0.5359.220 (from api)
Qt: 6.5.2

CPython: 3.12.0rc3
PyQt: 6.5.2

Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)

colorama: 0.4.6
jinja2: 3.1.2
pygments: 2.15.1
yaml: 6.0.1
adblock: no
objc: no
PyQt6.QtWebEngineCore: 6.5.0
PyQt6.sip: 6.6.2
pdf.js: no
sqlite: 3.42.0
QtNetwork SSL: OpenSSL 3.1.1 30 May 2023

Style: QFusionStyle
Platform plugin: xcb
OpenGL: Intel, 4.6 (Compatibility Profile) Mesa 23.2.0-rc3
Platform: Linux-6.5.4-300.fc39.x86_64-x86_64-with-glibc2.38, 64bit
Linux distribution: Fedora Linux 39 (CompNeuro Prerelease) (fedora)
Frozen: False
Imported from /usr/lib/python3.12/site-packages/qutebrowser
Using Python from /usr/bin/python3
Qt library executable path: /usr/lib64/qt6/libexec, data path: /usr/share/qt6

Paths:
cache: /tmp/qutebrowser-basedir-cppohkrv/cache
config: /tmp/qutebrowser-basedir-cppohkrv/config
data: /tmp/qutebrowser-basedir-cppohkrv/data
runtime: /tmp/qutebrowser-basedir-cppohkrv/runtime

Autoconfig loaded: yes
Config.py: no config.py was loaded
Uptime: 0:00:00

```

**Does the bug happen if you start with `--temp-basedir`?**:

Yes
**Description**

Crashes immediately

**How to reproduce**
Run `qutebrowser -T`

==== Exception ====
```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==3.0.0', 'gui_scripts', 'qutebrowser')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/qutebrowser.py", line 231, in main
    return app.run(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 108, in run
    init(args=args)
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 155, in init
    _process_args(args)
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 200, in _process_args
    new_window = mainwindow.MainWindow(private=private)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/mainwindow.py", line 227, in __init__
    self.tabbed_browser: tabbedbrowser.TabbedBrowser = tabbedbrowser.TabbedBrowser(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 203, in __init__
    self.widget = tabwidget.TabWidget(win_id, parent=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabwidget.py", line 45, in __init__
    bar = TabBar(win_id, self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabwidget.py", line 397, in __init__
    self._our_style = TabBarStyle()
                      ^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QProxyStyle(style: typing.Optional[QStyle] = None): not enough arguments
  QProxyStyle(key: Optional[str]): not enough arguments

```
==== Timestamps ====
Launch: Thu Sep 21 12:10:02 2023
Crash: Thu Sep 21 12:10:02 2023

==== Config ====
<Default configuration>

==== Environment ====

```
DESKTOP_SESSION = gnome-xorg
LANG = en_GB.UTF-8
PATH = /usr/share/Modules/bin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/asinha/.local/bin:/home/asinha/bin:/home/asinha/.node_modules_global/bin/:/usr/lib64/ccache:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/bin:/sbin:/home/asinha/.local/bin:/home/asinha/bin:/home/asinha/.node_modules_global/bin/
QTWEBENGINE_DICTIONARIES_PATH = /tmp/qutebrowser-basedir-cppohkrv/data/qtwebengine_dictionaries
QT_IM_MODULE = ibus
QT_QPA_PLATFORM = xcb
XDG_CURRENT_DESKTOP = GNOME
XDG_DATA_DIRS = /home/asinha/.local/share/flatpak/exports/share:/var/lib/flatpak/exports/share:/usr/local/share/:/usr/share/
XDG_MENU_PREFIX = gnome-
XDG_RUNTIME_DIR = /run/user/1000
XDG_SESSION_CLASS = user
XDG_SESSION_DESKTOP = gnome-xorg
XDG_SESSION_TYPE = x11
XMODIFIERS = @im=ibus
```
==== Commandline args ====
-T

==== Open Pages ====

==== Command history ====

==== Objects ====

==== Debug log ====
```
12:10:02 DEBUG    init       earlyinit:init_log:287 Log initialized.
12:10:02 DEBUG    init       machinery:init:299 Qt wrapper info:
  PyQt6: success
  PyQt5: not imported
  -> selected: PyQt6 (via autoselect)
12:10:02 DEBUG    init       earlyinit:init_qtlog:298 Qt log initialized.
12:10:02 DEBUG    init       app:run:70 Main process PID: 576902
12:10:02 DEBUG    init       app:run:72 Initializing directories...
12:10:02 DEBUG    init       standarddir:init:341 Base directory: /tmp/qutebrowser-basedir-cppohkrv
12:10:02 DEBUG    init       app:run:76 Initializing config...
12:10:02 DEBUG    init       app:run:79 Initializing application...
12:10:02 DEBUG    init       darkmode:settings:347 Darkmode variant: qt_63
12:10:02 DEBUG    init       app:__init__:538 Commandline args: ['-T']
12:10:02 DEBUG    init       app:__init__:539 Parsed: Namespace(basedir='/tmp/qutebrowser-basedir-cppohkrv', config_py=None, version=False, temp_settings=[], session=None, override_restore=False, target=None, backend=None, qt_wrapper=None, desktop_file_name='org.qutebrowser.qutebrowser', untrusted_args=False, json_args=None, temp_basedir_restarted=False, loglevel=None, logfilter=None, loglines=2000, debug=False, json_logging=False, color=True, force_color=False, nowindow=False, temp_basedir=True, no_err_windows=False, qt_arg=None, qt_flag=None, debug_flags=[], command=[], url=[])
12:10:02 DEBUG    init       app:__init__:540 Qt arguments: ['--webEngineArgs', '--enable-features=WebRTCPipeWireCapturer,OverlayScrollbar']
12:10:02 DEBUG    init       app:__init__:545 Initializing application...
12:10:02 DEBUG    ipc        ipc:send_to_running_instance:477 Connecting to /tmp/qutebrowser-basedir-cppohkrv/runtime/ipc-01bf06d7a481801b979aae22558f59d4
12:10:02 DEBUG    ipc        ipc:send_to_running_instance:507 No existing instance present (ServerNotFoundError)
12:10:02 DEBUG    init       ipc:send_or_listen:537 Starting IPC server...
12:10:02 DEBUG    ipc        ipc:__init__:195 Not calling setSocketOptions
12:10:02 DEBUG    ipc        ipc:listen:207 Listening as /tmp/qutebrowser-basedir-cppohkrv/runtime/ipc-01bf06d7a481801b979aae22558f59d4
12:10:02 DEBUG    init       app:init:130 Starting init...
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.adblockcommands
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.braveadblock
12:10:02 DEBUG    extensions loader:_load_component:145 Running init hook 'init'
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.caretcommands
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.hostblock
12:10:02 DEBUG    extensions loader:_load_component:145 Running init hook 'init'
12:10:02 DEBUG    network    hostblock:_should_be_used:68 Configured adblock method auto, adblock library usable: False
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.misccommands
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.readlinecommands
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.scrollcommands
12:10:02 DEBUG    extensions loader:_load_component:137 Importing qutebrowser.components.zoomcommands
12:10:02 DEBUG    init       app:_init_modules:436 Initializing logging from config...
12:10:02 DEBUG    init       log:init_from_config:368 Configuring RAM loglevel to debug
12:10:02 DEBUG    init       log:init_from_config:375 Configuring console loglevel to info
12:10:02 DEBUG    init       app:_init_modules:440 Initializing save manager...
12:10:02 DEBUG    init       app:_init_modules:446 Checking backend requirements...
12:10:02 DEBUG    init       app:_init_modules:449 Initializing prompts...
12:10:02 DEBUG    init       app:_init_modules:452 Initializing network...
12:10:02 DEBUG    init       app:_init_modules:455 Initializing proxy...
12:10:02 DEBUG    init       app:_init_modules:459 Initializing downloads...
12:10:02 DEBUG    init       app:_init_modules:465 Initializing web history...
12:10:02 DEBUG    sql        sql:run:360 pragma user_version
12:10:02 DEBUG    sql        sql:run:360 PRAGMA journal_mode=WAL
12:10:02 DEBUG    sql        sql:run:360 PRAGMA synchronous=NORMAL
12:10:02 DEBUG    sql        sql:run:360 CREATE TABLE IF NOT EXISTS History (url NOT NULL, title NOT NULL, atime NOT NULL, redirect NOT NULL)
12:10:02 DEBUG    sql        sql:run:360 CREATE TABLE IF NOT EXISTS CompletionHistory (url PRIMARY KEY, title NOT NULL, last_atime NOT NULL)
12:10:02 DEBUG    sql        sql:run:360 CREATE INDEX IF NOT EXISTS CompletionHistoryAtimeIndex ON CompletionHistory (last_atime)
12:10:02 DEBUG    sql        sql:run:360 CREATE TABLE IF NOT EXISTS CompletionMetaInfo (key PRIMARY KEY, value )
12:10:02 DEBUG    sql        sql:run:360 SELECT EXISTS(SELECT * FROM CompletionMetaInfo WHERE key = :val)
12:10:02 DEBUG    sql        sql:run:364     {':val': 'excluded_patterns'}
12:10:02 DEBUG    sql        sql:run:360 REPLACE INTO CompletionMetaInfo (key, value) values(:key, :value)
12:10:02 DEBUG    sql        sql:run:364     {':key': 'excluded_patterns', ':value': ''}
12:10:02 DEBUG    sql        sql:run:360 SELECT EXISTS(SELECT * FROM CompletionMetaInfo WHERE key = :val)
12:10:02 DEBUG    sql        sql:run:364     {':val': 'force_rebuild'}
12:10:02 DEBUG    sql        sql:run:360 REPLACE INTO CompletionMetaInfo (key, value) values(:key, :value)
12:10:02 DEBUG    sql        sql:run:364     {':key': 'force_rebuild', ':value': False}
12:10:02 DEBUG    sql        sql:run:360 SELECT value FROM CompletionMetaInfo WHERE key = :key
12:10:02 DEBUG    sql        sql:run:364     {':key': 'force_rebuild'}
12:10:02 DEBUG    sql        sql:__enter__:270 Starting a transaction
12:10:02 DEBUG    sql        sql:run:360 DELETE FROM History WHERE url LIKE 'data:%' OR url LIKE 'view-source:%' OR url LIKE 'qute://back%' OR url LIKE 'qute://pdfjs%'
12:10:02 DEBUG    sql        history:_cleanup_history:274 Cleanup removed 0 items
12:10:02 DEBUG    sql        sql:upgrade_user_version:245 Migrating from version 0.0 to 0.4
12:10:02 DEBUG    sql        sql:run:360 PRAGMA user_version = 4
12:10:02 DEBUG    sql        sql:__exit__:287 Committing a transaction
12:10:02 DEBUG    sql        sql:run:360 SELECT value FROM CompletionMetaInfo WHERE key = :key
12:10:02 DEBUG    sql        sql:run:364     {':key': 'excluded_patterns'}
12:10:02 DEBUG    sql        sql:run:360 SELECT 1 FROM History LIMIT 1
12:10:02 DEBUG    init       debug:__exit__:333 Initializing sql/history took 0.003332 seconds.
12:10:02 DEBUG    init       app:_init_modules:474 Initializing command history...
12:10:02 DEBUG    init       app:_init_modules:477 Initializing websettings...
12:10:02 DEBUG    init       webenginesettings:init:516 Initializing qute://* handler...
12:10:02 DEBUG    init       webenginesettings:init:520 Initializing request interceptor...
12:10:02 DEBUG    init       webenginesettings:init:525 Initializing QtWebEngine downloads...
12:10:02 DEBUG    init       webenginesettings:init:531 Initializing notification presenter...
12:10:02 DEBUG    init       webenginesettings:init:534 Initializing global settings...
12:10:02 DEBUG    init       webenginesettings:init:538 Initializing profiles...
12:10:02 DEBUG    config     webenginesettings:set_dictionary_language:325 Found dicts: []
12:10:02 DEBUG    config     webenginesettings:set_dictionary_language:325 Found dicts: []
12:10:02 DEBUG    init       webenginesettings:init:543 Misc initialization...
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.headers.user_agent = Mozilla/5.0 ({os_info}) AppleWebKit/{webkit_version} (KHTML, like Gecko) {upstream_browser_key}/{upstream_browser_version} Safari/{webkit_version}
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.headers.user_agent = Mozilla/5.0 ({os_info}; rv:90.0) Gecko/20100101 Firefox/90.0
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.headers.user_agent = Mozilla/5.0 ({os_info}) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99 Safari/537.36
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.headers.accept_language = 
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.javascript.enabled = True
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.javascript.enabled = True
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.images = True
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.images = True
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.cookies.accept = all
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.cookies.accept = all
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.local_content_can_access_remote_urls = True
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.local_content_can_access_file_urls = False
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.javascript.enabled = True
12:10:02 DEBUG    config     config:_set_value:336 Config option changed: content.javascript.enabled = True
12:10:02 DEBUG    init       app:_init_modules:481 Initializing sessions...
12:10:02 DEBUG    init       app:_init_modules:487 Initializing quickmarks...
12:10:02 DEBUG    save       savemanager:save:80 Save of quickmark-manager requested - dirty True, save_on_exit False, is_exit False, force False -> True
12:10:02 DEBUG    destroy    lineparser:_after_save:66 Saved to /tmp/qutebrowser-basedir-cppohkrv/config/quickmarks
12:10:02 DEBUG    init       app:_init_modules:491 Initializing bookmarks...
12:10:02 DEBUG    save       savemanager:save:80 Save of bookmark-manager requested - dirty True, save_on_exit False, is_exit False, force False -> True
12:10:02 DEBUG    destroy    lineparser:_after_save:66 Saved to /tmp/qutebrowser-basedir-cppohkrv/config/bookmarks/urls
12:10:02 DEBUG    init       app:_init_modules:495 Initializing cookies...
12:10:02 DEBUG    init       app:_init_modules:498 Initializing cache...
12:10:02 DEBUG    init       app:_init_modules:501 Initializing downloads...
12:10:02 DEBUG    init       networkmanager:__init__:145 Initializing NetworkManager
12:10:02 DEBUG    init       networkmanager:__init__:152 NetworkManager init done
12:10:02 DEBUG    init       app:_init_modules:504 Initializing Greasemonkey...
12:10:02 DEBUG    greasemonkey greasemonkey:load_scripts:323 Reading scripts from: /tmp/qutebrowser-basedir-cppohkrv/data/greasemonkey
12:10:02 DEBUG    greasemonkey greasemonkey:load_scripts:323 Reading scripts from: /tmp/qutebrowser-basedir-cppohkrv/config/greasemonkey
12:10:02 DEBUG    init       app:_init_modules:507 Misc initialization...
12:10:02 DEBUG    misc       nativeeventfilter:init:180 Platform xcb, Qt 6.5.2
12:10:02 DEBUG    init       app:init:149 Initializing eventfilter...
12:10:02 DEBUG    init       app:init:152 Connecting signals...
12:10:02 DEBUG    init       app:_process_args:190 Initializing main window...
12:10:02 DEBUG    init       mainwindow:_init_downloadmanager:353 Initializing downloads...
12:10:02 ERROR    misc       crashsignal:_handle_early_exits:226 Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==3.0.0', 'gui_scripts', 'qutebrowser')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/qutebrowser.py", line 231, in main
    return app.run(args)
           ^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 108, in run
    init(args=args)
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 155, in init
    _process_args(args)
  File "/usr/lib/python3.12/site-packages/qutebrowser/app.py", line 200, in _process_args
    new_window = mainwindow.MainWindow(private=private)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/mainwindow.py", line 227, in __init__
    self.tabbed_browser: tabbedbrowser.TabbedBrowser = tabbedbrowser.TabbedBrowser(
                                                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 203, in __init__
    self.widget = tabwidget.TabWidget(win_id, parent=self)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabwidget.py", line 45, in __init__
    bar = TabBar(win_id, self)
          ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabwidget.py", line 397, in __init__
    self._our_style = TabBarStyle()
                      ^^^^^^^^^^^^^
TypeError: arguments did not match any overloaded call:
  QProxyStyle(style: typing.Optional[QStyle] = None): not enough arguments
  QProxyStyle(key: Optional[str]): not enough arguments
12:10:02 ERROR    destroy    crashsignal:_get_exception_info:196 Error while recovering pages: 'tabbed-browser'
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qutebrowser/misc/crashsignal.py", line 194, in _get_exception_info
    pages = self._recover_pages(forgiving=True)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/misc/crashsignal.py", line 118, in _recover_pages
    tabbed_browser = objreg.get('tabbed-browser', scope='window',
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/utils/objreg.py", line 233, in get
    return reg[name]
           ~~~^^^^^^
  File "/usr/lib64/python3.12/collections/__init__.py", line 1134, in __getitem__
    raise KeyError(key)
KeyError: 'tabbed-browser'
12:10:02 ERROR    destroy    crashsignal:_get_exception_info:208 Error while getting objects
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/qutebrowser/misc/crashsignal.py", line 206, in _get_exception_info
    all_objects = debug.get_all_objects()
                  ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/utils/debug.py", line 365, in get_all_objects
    widget_lines = _get_widgets()
                   ^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/qutebrowser/utils/debug.py", line 349, in _get_widgets
    widgets.sort(key=repr)
  File "/usr/lib/python3.12/site-packages/qutebrowser/mainwindow/tabbedbrowser.py", line 253, in __repr__
    return utils.get_repr(self, count=self.widget.count())
                                      ^^^^^^^^^^^
AttributeError: 'TabbedBrowser' object has no attribute 'widget'. Did you mean: 'widgets'?
12:10:02 DEBUG    sql        sql:run:360 pragma user_version
12:10:02 DEBUG    sql        sql:run:360 PRAGMA journal_mode=WAL
12:10:02 DEBUG    sql        sql:run:360 PRAGMA synchronous=NORMAL
12:10:02 DEBUG    sql        sql:run:360 select sqlite_version()

```

The crash reporter asked me to mail it etc., have done that too. Here are the Fedora package versions, in case it's caused by some package conflicts etc?

```
 rpm -qa \*qutebrowser\* \*qt\* \*qgnomeplatform\* | sort
adwaita-qt5-1.4.2-5.fc39.x86_64
adwaita-qt6-1.4.2-5.fc39.x86_64
dbusmenu-qt-0.9.3-0.32.20160218.fc39.x86_64
gstreamer1-plugins-good-qt-1.22.5-1.fc39.x86_64
gstreamer1-plugins-good-qt6-1.22.5-1.fc39.x86_64
ibus-qt-1.3.4-8.fc39.x86_64
libadwaita-qt5-1.4.2-5.fc39.x86_64
libadwaita-qt6-1.4.2-5.fc39.x86_64
poppler-qt5-23.08.0-1.fc39.x86_64
python3-matplotlib-qt5-3.8.0-1.fc39.x86_64
python3-pyqt5-sip-12.12.2-1.fc39.x86_64
python3-pyqt6-6.5.2-2.fc39.x86_64
python3-pyqt6-base-6.5.2-2.fc39.x86_64
python3-pyqt6-sip-13.4.0-5.fc39.x86_64
python3-pyqt6-webengine-6.5.0-3.fc39.x86_64
python3-qt5-5.15.9-6.fc39.x86_64
python3-qt5-base-5.15.9-6.fc39.x86_64
python3-qt5-webkit-5.15.9-6.fc39.x86_64
python3-sphinxcontrib-qthelp-1.0.3-15.fc39.noarch
python-pyqt6-rpm-macros-6.5.2-2.fc39.noarch
python-qt5-rpm-macros-5.15.9-6.fc39.noarch
qadwaitadecorations-qt5-0.1.1-1.fc39.x86_64
qadwaitadecorations-qt6-0.1.1-1.fc39.x86_64
qgnomeplatform-qt5-0.9.2-1.fc39.x86_64
qgnomeplatform-qt6-0.9.2-1.fc39.x86_64
qscintilla-qt5-2.13.4-3.fc39.x86_64
qt-4.8.7-74.fc39.x86_64
qt5-qtbase-5.15.10-9.fc39.x86_64
qt5-qtbase-common-5.15.10-9.fc39.noarch
qt5-qtbase-devel-5.15.10-9.fc39.x86_64
qt5-qtbase-gui-5.15.10-9.fc39.x86_64
qt5-qtconnectivity-5.15.10-2.fc39.x86_64
qt5-qtdeclarative-5.15.10-2.fc39.x86_64
qt5-qtgamepad-5.15.10-2.fc39.x86_64
qt5-qtgraphicaleffects-5.15.10-2.fc39.x86_64
qt5-qtlocation-5.15.10-3.fc39.x86_64
qt5-qtmultimedia-5.15.10-2.fc39.x86_64
qt5-qtquickcontrols2-5.15.10-2.fc39.x86_64
qt5-qtscript-5.15.10-2.fc39.x86_64
qt5-qtscxml-5.15.10-2.fc39.x86_64
qt5-qtsensors-5.15.10-2.fc39.x86_64
qt5-qtserialport-5.15.10-2.fc39.x86_64
qt5-qtsvg-5.15.10-2.fc39.x86_64
qt5-qttools-common-5.15.10-3.fc39.noarch
qt5-qttools-libs-designer-5.15.10-3.fc39.x86_64
qt5-qttools-libs-help-5.15.10-3.fc39.x86_64
qt5-qtwayland-5.15.10-4.fc39.x86_64
qt5-qtwebchannel-5.15.10-2.fc39.x86_64
qt5-qtwebkit-5.212.0-0.78alpha4.fc39.x86_64
qt5-qtwebsockets-5.15.10-2.fc39.x86_64
qt5-qtx11extras-5.15.10-2.fc39.x86_64
qt5-qtxmlpatterns-5.15.10-2.fc39.x86_64
qt5-rpm-macros-5.15.10-2.fc39.noarch
qt5-srpm-macros-5.15.10-2.fc39.noarch
qt6-qtbase-6.5.2-5.fc39.x86_64
qt6-qtbase-common-6.5.2-5.fc39.noarch
qt6-qtbase-gui-6.5.2-5.fc39.x86_64
qt6-qtconnectivity-6.5.2-1.fc39.x86_64
qt6-qtdeclarative-6.5.2-1.fc39.x86_64
qt6-qtmultimedia-6.5.2-1.fc39.x86_64
qt6-qtpdf-6.5.2-2.fc39.x86_64
qt6-qtpositioning-6.5.2-1.fc39.x86_64
qt6-qtquick3d-6.5.2-1.fc39.x86_64
qt6-qtquicktimeline-6.5.2-1.fc39.x86_64
qt6-qtremoteobjects-6.5.2-1.fc39.x86_64
qt6-qtsensors-6.5.2-1.fc39.x86_64
qt6-qtserialport-6.5.2-1.fc39.x86_64
qt6-qtshadertools-6.5.2-1.fc39.x86_64
qt6-qtspeech-6.5.2-3.fc39.x86_64
qt6-qtspeech-speechd-6.5.2-3.fc39.x86_64
qt6-qtsvg-6.5.2-1.fc39.x86_64
qt6-qttools-common-6.5.2-1.fc39.noarch
qt6-qttools-libs-designer-6.5.2-1.fc39.x86_64
qt6-qttools-libs-help-6.5.2-1.fc39.x86_64
qt6-qtwayland-6.5.2-3.fc39.x86_64
qt6-qtwebchannel-6.5.2-1.fc39.x86_64
qt6-qtwebengine-6.5.2-2.fc39.x86_64
qt6-qtwebengine-devtools-6.5.2-2.fc39.x86_64
qt6-qtwebsockets-6.5.2-1.fc39.x86_64
qt6-srpm-macros-6.5.2-3.fc39.noarch
qt-common-4.8.7-74.fc39.noarch
qtpass-1.4.0-1.fc39.x86_64
qt-settings-39.0-1.fc39.noarch
qt-x11-4.8.7-74.fc39.x86_64
quazip-qt5-1.4-5.fc39.x86_64
qutebrowser-3.0.0-2.fc39.noarch
sni-qt-0.2.7-0.13.20170217.fc39.x86_64
vimiv-qt-0.9.0-1.fc39.x86_64

```

**Comment by The-Compiler** [comment]
It's a bug in PyQt (or possibly Python). I already [reported it there](https://www.riverbankcomputing.com/pipermail/pyqt/2023-September/045510.html) and pushed a workaround in 90d16b5.

I'll release qutebrowser v3.0.1 as soon as Qt/PyQt 6.5.3 is out, with [the former planned](https://wiki.qt.io/Qt_6.5_Release) for next Wednesday, and PyQt hopefully following shortly after.

**Comment by sanjayankur31** [comment]
Thanks for your quick reply. I'll let the Fedora maintainers know and see if they want to carry the workaround now or wait for 3.0.1 + Qt 6.5.3.
