### ISSUE TITLE
 sip module implements ABI v13.0 to v13.5 but the PyQt6.QtCore module requires ABI v13.6

### ISSUE THREAD

**Issue by foxyseta** [qutebrowser/qutebrowser#7985]
**Version info**:

`qutebrowser-3.0.2-r0` (can't start QuteBrowser. Sorry!)
**Does the bug happen if you start with `--temp-basedir`?**: Yes

**Description**
QuteBroswer will not start. Stack:
```
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==3.0.2', 'gui_scripts', 'qutebrowser')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qutebrowser/qutebrowser.py", line 227, in main
    earlyinit.early_init(args)
  File "/usr/lib/python3.11/site-packages/qutebrowser/misc/earlyinit.py", line 341, in early_init
    init_qtlog(args)
  File "/usr/lib/python3.11/site-packages/qutebrowser/misc/earlyinit.py", line 296, in init_qtlog
    from qutebrowser.utils import log, qtlog
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/qtlog.py", line 15, in <module>
    from qutebrowser.qt import core as qtcore, machinery
  File "/usr/lib/python3.11/site-packages/qutebrowser/qt/core.py", line 25, in <module>
    from PyQt6.QtCore import *
RuntimeError: the sip module implements ABI v13.0 to v13.5 but the PyQt6.QtCore module requires ABI v13.6
```

`py3-sip` and `py3-piqt5-sip` are already up to date on my Alpine Linux system though: I got `py3-sip-6.7.12-r0` and `py3-pyqt5-sip-12.13.0-r0` installed. Is this a packaging problem? Should I be contacting the `qutebrowser` package maintainer instead?

**Comment by foxyseta** [comment]
Nvermind! This problem popped out yesterday, and today and update for `py3-pyqt6-sip` was out:
`Upgrading py3-pyqt6-sip (13.5.2-r0 -> 13.6.0-r0)`
I guess when using edge repositories sometimes these problems can happen?
