### ISSUE TITLE
Guard against `QSocketNotifier` socket being `None`

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#8070]
Got a couple of crash reports lately (since December 3rd), with Qt 6.6.1 (but also one on 5.15.11):

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/qutebrowser/misc/crashsignal.py", line 386, in handle_signal_wakeup
    os.read(int(read_fd), 1)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

```pytb
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qutebrowser/misc/crashsignal.py", line 366, in deactivate
    os.close(int(rfd))
             ^^^^^^^^
TypeError: int() argument must be a string, a bytes-like object or a real number, not 'NoneType'
```

Not quite sure how this can happen, given that we pass in the result from `os.pipe` right when constructing it... Can't see anything in Qt that would be setting this to `nullptr`. Only relevant Qt change is over 3 years old: [QSocketNotifier: extend API to provide more flexible startup (I2eb2edf3) · Gerrit Code Review](https://codereview.qt-project.org/c/qt/qtbase/+/326378)

But maybe Python is (weirdly) returning `None` here?

https://github.com/python/cpython/blob/v3.12.1/Modules/posixmodule.c#L11226-L11235

That only happens if the system doesn't have `pipe2`, or it returns `ENOSYS`:

https://github.com/python/cpython/blob/v3.12.1/Modules/posixmodule.c#L11213-L11245

The systems in question are:

- FreeBSD 14 (also running as root...)
- Alpine Linux (so musl?)
- Void Linux (possibly musl?)
- Alpine again
- FreeBSD 15 again

So possibly something strange with `pipe` on those systems indeed...

Guess we should either make the code handle this, or make the init code catch this case and log a warning instead of initializing the `QSocketNotifier`. This is only used to handle Ctrl-C correctly, and we can fallback on using a QTimer instead, like we do on Windows:

https://github.com/qutebrowser/qutebrowser/blob/c9910c3dfe5966d3c15ea3c6b96e03550ee51e94/qutebrowser/misc/crashsignal.py#L339-L355

**Comment by Parkerrino** [comment]
Hey, if this Issue is still "untouched" I would like to try to write a catch and fallback to QTimer for this ^^

**Comment by The-Compiler** [comment]
@Parkerrino sounds good to me!

**Comment by The-Compiler** [comment]
This still seems present, got another crash report about this with Qt 6.8.1 and Python 3.13.1.

**Comment by 7gtz** [comment]
Hi, has this issue been resolved? I'd like to write code that handles this case gracefully logging a warning instead of crashing.

**Comment by The-Compiler** [comment]
Last report for this was in January 2025, with Qt 6.7. Assuming this was fixed upstream at some point, so I'm closing this.
