### ISSUE TITLE
No module named 'PyQt6' after 3.02 update

### ISSUE THREAD

**Issue by rukh-debug** [qutebrowser/qutebrowser#8220]
**Version info**:
[here](https://bpa.st/XVVA)
**Does the bug happen if you start with `--temp-basedir`?**:
Yes, but only for `PyQt6`

**Description**
It does not launch after recent update.
```bash
qutebrowser --qt-wrapper PyQt6 --temp-basedir
Traceback (most recent call last):
  File "/sbin/qutebrowser", line 33, in <module>
    sys.exit(load_entry_point('qutebrowser==3.2.0', 'gui_scripts', 'qutebrowser')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qutebrowser/qutebrowser.py", line 228, in main
    earlyinit.early_init(args)
  File "/usr/lib/python3.11/site-packages/qutebrowser/misc/earlyinit.py", line 341, in early_init
    init_qtlog(args)
  File "/usr/lib/python3.11/site-packages/qutebrowser/misc/earlyinit.py", line 296, in init_qtlog
    from qutebrowser.utils import log, qtlog
  File "/usr/lib/python3.11/site-packages/qutebrowser/utils/qtlog.py", line 15, in <module>
    from qutebrowser.qt import core as qtcore
  File "/usr/lib/python3.11/site-packages/qutebrowser/qt/core.py", line 25, in <module>
    from PyQt6.QtCore import *
ModuleNotFoundError: No module named 'PyQt6'
```

**How to reproduce**
launch qutebrowser?

**Comment by The-Compiler** [comment]
The only issue in qutebrowser here is that it only shows this in the terminal, instead of showing an error via a window - that's now fixed.

As for why this is happening for you, it looks like you did a partial upgrade, [which is not supported](https://wiki.archlinux.org/title/System_maintenance#Partial_upgrades_are_unsupported).
