### ISSUE TITLE
end2end test screenshots cause internal pytest error

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#8333]
Original comment from #8243:

> Locally I'm seeing errors like this during teardown sometimes. Not quite sure how to reproduce because I wasn't seeing these when developing it, and it's happily putting screenshots on at least some failed CI jobs.
> 
> Potentially it's due to using the take_x11_screenshot fixture from after_test, which looks like it's during teardown? Not 100% sure what's going on there because that fixture should have been called earlier in the request already. Could be related to pytest-dev/pytest#9984, but I don't know why the assertion error has so much stuff in it.
> Not sure what to do about that apart from move the screenshot stuff back to not being in a pytest fixture.

Update with `--tb=native`:

> Ah, thank you. That does show where the assertion is.
> 
> <details>
> <summary>Here's a stack trace with `--tb=native` as is</summary>
> 
> ```pytb
> ________ ERROR at teardown of test_sandboxing[disable-seccomp-bpf-True-False-True-You are NOT adequately sandboxed.] _________
> Traceback (most recent call last):
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
>     result: TResult | None = func()
>                              ^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 242, in <lambda>
>     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
>     raise exception.with_traceback(exception.__traceback__)
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/threadexception.py", line 97, in pytest_runtest_teardown
>     yield from thread_exception_runtest_hook()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
>     yield
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 100, in pytest_runtest_teardown
>     yield from unraisable_exception_runtest_hook()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
>     yield
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/logging.py", line 853, in pytest_runtest_teardown
>     yield from self._runtest_for(item, "teardown")
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/logging.py", line 829, in _runtest_for
>     yield
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/capture.py", line 885, in pytest_runtest_teardown
>     return (yield)
>             ^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/pytestqt/plugin.py", line 207, in pytest_runtest_teardown
>     result = yield
>              ^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
>     res = hook_impl.function(*args)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 189, in pytest_runtest_teardown
>     item.session._setupstate.teardown_exact(nextitem)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 557, in teardown_exact
>     raise exceptions[0]
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 546, in teardown_exact
>     fin()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1032, in finish
>     raise exceptions[0]
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1021, in finish
>     fin()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 907, in _teardown_yield_fixture
>     next(it)
>   File "/work/tests/end2end/fixtures/quteprocess.py", line 984, in quteproc_new
>     proc.after_test()
>   File "/work/tests/end2end/fixtures/quteprocess.py", line 552, in after_test
>     self._take_x11_screenshot_of_failed_test()
>   File "/work/tests/end2end/fixtures/quteprocess.py", line 881, in _take_x11_screenshot_of_failed_test
>     fixture = self.request.getfixturevalue('take_x11_screenshot')
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 532, in getfixturevalue
>     fixturedef = self._get_active_fixturedef(argname)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 617, in _get_active_fixturedef
>     fixturedef.execute(request=subrequest)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1047, in execute
>     fixturedef = request._get_active_fixturedef(argname)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 617, in _get_active_fixturedef
>     fixturedef.execute(request=subrequest)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1094, in execute
>     request.node.addfinalizer(finalizer)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/nodes.py", line 391, in addfinalizer
>     self.session._setupstate.addfinalizer(fin, self)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 526, in addfinalizer
>     assert node in self.stack, (node, self.stack)
>            ^^^^^^^^^^^^^^^^^^
> AssertionError: (<Function test_sandboxing[disable-seccomp-bpf-True-False-True-You are NOT adequately sandboxed.]>, {<Session  exitstatus=<ExitCode.OK: 0> testsfailed=3 testscollected=3>: ([<bound method Node.teardown of <Session  exitstatus=<ExitCode.OK: 0> testsfailed=3 testscollected=3>>, functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='check_display' scope='session' baseid='tests'>>, request=<SubRequest 'check_display' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='check_yaml_c_exts' scope='session' baseid='tests'>>, request=<SubRequest 'check_yaml_c_exts' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='fail_on_logging' scope='session' baseid='tests'>>, request=<SubRequest 'fail_on_logging' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='qapp_args' scope='session' baseid='tests'>>, request=<SubRequest 'qapp_args' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='qapp_cls' scope='session' baseid=''>>, request=<SubRequest 'qapp_cls' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='pytestconfig' scope='session' baseid=''>>, request=<SubRequest 'pytestconfig' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='qapp' scope='session' baseid=''>>, request=<SubRequest 'qapp' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='qapp' scope='session' baseid='tests'>>, request=<SubRequest 'qapp' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='server' scope='session' baseid='tests/end2end'>>, request=<SubRequest 'server' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>), functools.partial(<bound method FixtureDef.finish of <FixtureDef argname='tmp_path_factory' scope='session' baseid=''>>, request=<SubRequest 'tmp_path_factory' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>)], None), <Dir work>: ([<bound method Node.teardown of <Dir work>>], None), <Dir tests>: ([<bound method Node.teardown of <Dir tests>>], None), <Dir end2end>: ([<bound method Node.teardown of <Dir end2end>>], None), <Module test_invocations.py>: ([<bound method Node.teardown of <Module test_invocations.py>>], None)})
> ```
> </details>
> 
> <details>
> <summary>And one with the parameterize mark removed, just in case it was that (doesn't look like it)</summary>
> 
> ```pytb
> Traceback (most recent call last):
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 341, in from_call
>     result: TResult | None = func()
>                              ^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 242, in <lambda>
>     lambda: runtest_hook(item=item, **kwds), when=when, reraise=reraise
>             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_hooks.py", line 513, in __call__
>     return self._hookexec(self.name, self._hookimpls.copy(), kwargs, firstresult)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_manager.py", line 120, in _hookexec
>     return self._inner_hookexec(hook_name, methods, kwargs, firstresult)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 139, in _multicall
>     raise exception.with_traceback(exception.__traceback__)
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/threadexception.py", line 97, in pytest_runtest_teardown
>     yield from thread_exception_runtest_hook()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/threadexception.py", line 68, in thread_exception_runtest_hook
>     yield
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 100, in pytest_runtest_teardown
>     yield from unraisable_exception_runtest_hook()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/unraisableexception.py", line 70, in unraisable_exception_runtest_hook
>     yield
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/logging.py", line 853, in pytest_runtest_teardown
>     yield from self._runtest_for(item, "teardown")
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/logging.py", line 829, in _runtest_for
>     yield
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/capture.py", line 885, in pytest_runtest_teardown
>     return (yield)
>             ^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 122, in _multicall
>     teardown.throw(exception)  # type: ignore[union-attr]
>     ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/pytestqt/plugin.py", line 207, in pytest_runtest_teardown
>     result = yield
>              ^^^^^
>   File "/usr/lib/python3.12/site-packages/pluggy/_callers.py", line 103, in _multicall
>     res = hook_impl.function(*args)
>           ^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 189, in pytest_runtest_teardown
>     item.session._setupstate.teardown_exact(nextitem)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 557, in teardown_exact
>     raise exceptions[0]
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 546, in teardown_exact
>     fin()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1032, in finish
>     raise exceptions[0]
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1021, in finish
>     fin()
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 907, in _teardown_yield_fixture
>     next(it)
>   File "/work/tests/end2end/fixtures/quteprocess.py", line 984, in quteproc_new
>     proc.after_test()
>   File "/work/tests/end2end/fixtures/quteprocess.py", line 552, in after_test
>     self._take_x11_screenshot_of_failed_test()
>   File "/work/tests/end2end/fixtures/quteprocess.py", line 881, in _take_x11_screenshot_of_failed_test
>     fixture = self.request.getfixturevalue('take_x11_screenshot')
>               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 532, in getfixturevalue
>     fixturedef = self._get_active_fixturedef(argname)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 617, in _get_active_fixturedef
>     fixturedef.execute(request=subrequest)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1047, in execute
>     fixturedef = request._get_active_fixturedef(argname)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 617, in _get_active_fixturedef
>     fixturedef.execute(request=subrequest)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1094, in execute
>     request.node.addfinalizer(finalizer)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/nodes.py", line 391, in addfinalizer
>     self.session._setupstate.addfinalizer(fin, self)
>   File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 526, in addfinalizer
>     assert node in self.stack, (node, self.stack)
>            ^^^^^^^^^^^^^^^^^^
> AssertionError: (<Function test_sandboxing>, {})
> ```
> </details>
> 
> This is with `tox -e py -- tests/end2end/test_invocations.py -k sandboxing -s --tb=native` within a `archlinux-webengine-unstable-qt6` docker container. Haven't tried comparing it to other configurations yet.
> 
> I'll probably just ignore this for a week, or two, to give me time to focus on the 6.8 permissions stuff which is higher priority (and also seeing [weird failures](https://github.com/qutebrowser/qutebrowser/tree/feat/68_permissions_askeverytime), surely unrelated). We can revert this if it causes issues and I'll add it back even better later :)

**Comment by The-Compiler** [comment]
So the assertion failure is here:

https://github.com/pytest-dev/pytest/blob/8.3.3/src/_pytest/runner.py#L519-L527

and pytest is complaining because apparently the "The node must be currently active in the stack." invariant explained in the docstring is violated. Here is the whole output of the assert a bit reformatted:

```python
(
    # node
    <Function test_sandboxing[disable-seccomp-bpf-True-False-True-You are NOT adequately sandboxed.]>,
    # stack
    {
        <Session  exitstatus=<ExitCode.OK: 0> testsfailed=3 testscollected=3>: (
            [
                <bound method Node.teardown of <Session  exitstatus=<ExitCode.OK: 0> testsfailed=3 testscollected=3>>,
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='check_display' scope='session' baseid='tests'>>,
                    request=<SubRequest 'check_display' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='check_yaml_c_exts' scope='session' baseid='tests'>>,
                    request=<SubRequest 'check_yaml_c_exts' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='fail_on_logging' scope='session' baseid='tests'>>,
                    request=<SubRequest 'fail_on_logging' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='qapp_args' scope='session' baseid='tests'>>,
                    request=<SubRequest 'qapp_args' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='qapp_cls' scope='session' baseid=''>>,
                    request=<SubRequest 'qapp_cls' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='pytestconfig' scope='session' baseid=''>>,
                    request=<SubRequest 'pytestconfig' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='qapp' scope='session' baseid=''>>,
                    request=<SubRequest 'qapp' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='qapp' scope='session' baseid='tests'>>,
                    request=<SubRequest 'qapp' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='server' scope='session' baseid='tests/end2end'>>,
                    request=<SubRequest 'server' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                ),
                functools.partial(
                    <bound method FixtureDef.finish of <FixtureDef argname='tmp_path_factory' scope='session' baseid=''>>,
                    request=<SubRequest 'tmp_path_factory' for <Function test_sandboxing[enable-all-True-True-True-You are adequately sandboxed.]>>
                )
            ],
            None
        ),
        <Dir work>: (
            [<bound method Node.teardown of <Dir work>>],
            None
        ),
        <Dir tests>: (
            [<bound method Node.teardown of <Dir tests>>],
            None
        ),
        <Dir end2end>: (
            [<bound method Node.teardown of <Dir end2end>>],
            None
        ),
        <Module test_invocations.py>: (
            [<bound method Node.teardown of <Module test_invocations.py>>],
            None
        )
    }
)
```

Relevant part of the traceback:

```pytb
  File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 189, in pytest_runtest_teardown
    item.session._setupstate.teardown_exact(nextitem)
  [...]
  File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 907, in _teardown_yield_fixture
    next(it)
  File "/work/tests/end2end/fixtures/quteprocess.py", line 984, in quteproc_new
    proc.after_test()
  File "/work/tests/end2end/fixtures/quteprocess.py", line 552, in after_test
    self._take_x11_screenshot_of_failed_test()
  File "/work/tests/end2end/fixtures/quteprocess.py", line 881, in _take_x11_screenshot_of_failed_test
    fixture = self.request.getfixturevalue('take_x11_screenshot')
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  [...]
  File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 617, in _get_active_fixturedef
    fixturedef.execute(request=subrequest)
  File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/fixtures.py", line 1094, in execute
    request.node.addfinalizer(finalizer)
  File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/nodes.py", line 391, in addfinalizer
    self.session._setupstate.addfinalizer(fin, self)
  File "/home/user/.tox/py/lib/python3.12/site-packages/_pytest/runner.py", line 526, in addfinalizer
    assert node in self.stack, (node, self.stack)
```

So from what I can gather:

- We request a fixture during teardown
- Doing that causes pytest to register a new teardown step (cleaning up the `take_x11_screenshot` fixture) for the test that's currently already being torn down
- But (maybe depending on teardown order?), said current test node has already been cleaned up, so pytest gives up because we're trying to add a teardown step to something that doesn't exist anymore?

If this is something that can be reproduced more trivially, we certainly should report this to pytest as the error message leaves a lot to be desired as-is! It does seem similar to https://github.com/pytest-dev/pytest/issues/9984 but perhaps with another layer of indirection (the situation described in the issue is a fixture using another one that was previously used in the test directly, but is now unavailable - while we try to request a brand new fixture, and registering the teardown fails because the test is already gone or something).

I'll look at what we can do. Maybe be can just request the fixture earlier (even if we don't end up actually using it). Though I suppose that'd lead to a lot of tmp_path creating? Not sure.

**Comment by The-Compiler** [comment]
Trivially reproduced and reported to pytest: https://github.com/pytest-dev/pytest/issues/12882

I think I can see why pytest errors out here, but it should certainly show a better error message!

I also don't get yet:

1) Why we were not getting a full traceback
2) Why this only happens sometimes (I couldn't reproduce it myself)

Will look through #8243 next and see how we can avoid requesting a new fixture during teardown. Maybe my suggestion to use `tmp_path` here (2fcd6eafc4e74899caca09a8a76e9b16c54b4c1e) was misguided :confused:. I still hope we can find a way to make it work with `tmp_path` anyways, because it sure does make things easier!

**Comment by The-Compiler** [comment]
I was surprised by this [turning up](https://github.com/qutebrowser/qutebrowser/actions/runs/12003193458/job/33456294402#step:10:640) in #8397, which updated `pytest-rerunfailures` to 15.0, which [fully supports](https://github.com/pytest-dev/pytest-rerunfailures/blob/master/CHANGES.rst) pytest 8.2/8.3. Relevant change here:

- https://github.com/pytest-dev/pytest-rerunfailures/pull/278

and indeed I can now easily reproduce this locally, e.g. with

```patch
diff --git i/tests/end2end/test_invocations.py w/tests/end2end/test_invocations.py
index 5f65041c7..5ede2c821 100644
--- i/tests/end2end/test_invocations.py
+++ w/tests/end2end/test_invocations.py
@@ -395,6 +395,7 @@ def test_qute_settings_persistence(short_tmpdir, request, quteproc_new):
 
     quteproc_new.start(args)
     assert quteproc_new.get_setting('search.ignore_case') == 'always'
+    quteproc_new.wait_for(message='provoking timeout')
 
     quteproc_new.send_cmd(':quit')
     quteproc_new.wait_for_quit()

```


and `tox -e py312-pyqt67 -- tests/end2end/test_invocations.py -k qute_settings`.
