### ISSUE TITLE
See if we can run the WPT testsuite

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#8371]
Inspired by #8370.

See:

- [web-platform-tests documentation — web-platform-tests documentation](https://web-platform-tests.org/)
- [web-platform-tests/wpt: Test suites for Web platform specs — including WHATWG, W3C, and others](https://github.com/web-platform-tests/wpt)

Can we somehow run those, at least one-time, but maybe even as part of the CI (nightly or something?). I assume some will fail due to Chromium/QtWebEngine, but maybe we can compare with the Qt simplebrowser and "xfail" them accordingly?

**Comment by The-Compiler** [comment]
I tried https://wpt.live/tools/runner/index.html and in both Chromium (!) and qutebrowser, it seems to hang as soon as [/IndexedDB/serialize-sharedarraybuffer-throws.https.html](http://wpt.live/IndexedDB/serialize-sharedarraybuffer-throws.https.html) runs. The test tab shows that it passed, but stops working.

**Comment by The-Compiler** [comment]
Looks like that HTML runner is indeed broken for some tests. I tried the regex mentioned at https://github.com/web-platform-tests/wpt/issues/44267 but still have some timeout issues with some tests where qutebrowser didn't recover.

I then tried:

```bash
QTWEBENGINE_REMOTE_DEBUGGING=9998 ./wpt run chromium --webdriver-binary /usr/lib/qt6/webenginedriver --binary /home/florian/proj/qt/dev6/qt5/qtwebengine/examples/webenginewidgets/simplebrowser/simplebrowser 
```

which seems to come with two issues: For one, `simplebrowser` doesn't handle `--version` so you need to close it (twice?) before wpt tries to run the actual test cases, but also, it then fails with:

```pytb
Traceback (most recent call last):
  File "/home/florian/tmp/wpt/tools/wptrunner/wptrunner/executors/base.py", line 321, in run_test
    result = self.do_test(test)
             ^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/wpt/tools/wptrunner/wptrunner/executors/executorwebdriver.py", line 1014, in do_test
    self.protocol.webdriver.window.position = (0, 0)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/wpt/tools/webdriver/webdriver/client.py", line 22, in inner
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/wpt/tools/webdriver/webdriver/client.py", line 355, in position
    self.session.send_session_command("POST", "window/rect", body)
  File "/home/florian/tmp/wpt/tools/webdriver/webdriver/client.py", line 603, in send_session_command
    return self.send_command(method, url, body, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/florian/tmp/wpt/tools/webdriver/webdriver/client.py", line 567, in send_command
    raise err
webdriver.error.UnknownCommandException: unknown command (404): unknown command: 'Browser.getWindowForTarget' wasn't found
```

I also tried with qutebrowser and a wrapper script to pass args and such correctly:

```bash
#!/bin/bash

qb() {
    PYTHONPATH=~/proj/qutebrowser/git/ /usr/bin/python3 -m qutebrowser --temp-basedir "$@"
}

if [[ $1 == --version ]]; then
    qb --version | grep -o 'Chromium .*'
elif [[ $1 == --webEngineArgs ]]; then
    shift 1
    QTWEBENGINE_CHROMIUM_FLAGS="$@" qb about:blank
else
    echo "Invalid arguments" >&2
    exit 1
fi
```

and

```bash
QTWEBENGINE_REMOTE_DEBUGGING=9999 xvfb-run ./wpt run chromium --webdriver-binary /usr/lib/qt6/webenginedriver --binary qb-wpt-wrapper
```

but that seems to fail in the same way too. I suppose QtWebEngine needs to improve/fix their WebDriver implementation for this to work, or we'd need to implement a custom driver/executor that passes those commands as qutebrowser commands (even then I suppose only a subset of tests would work).
