### ISSUE TITLE
Deleted C++ object: WebEngineView in find_focused

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#8400]
> I am hitting this bug again but things have changed slightly on qutebrowser since.
> 
> ```
> Traceback (most recent call last):
>   File "/usr/lib/python3.12/site-packages/qutebrowser/browser/browsertab.py", line 911, in <lambda>
>     65, lambda: self._tab.elements.find_focused(_auto_insert_mode_cb))
>                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 789, in find_focused
>     self._tab.run_js_async(js_code, js_cb)
>   File "/usr/lib/python3.12/site-packages/qutebrowser/browser/webengine/webenginetab.py", line 1378, in run_js_async
>     self._widget.page().runJavaScript(code, world_id, callback)
>     ^^^^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.12/site-packages/qutebrowser/browser/webengine/webview.py", line 137, in page
>     maybe_page = super().page()
>                  ^^^^^^^^^^^^^^
> RuntimeError: wrapped C/C++ object of type WebEngineView has been deleted
> ```
> It looks like I only hit the crash when opening and closing a tab too fast (or sometimes swithcing to a tab and closing it quickly - only for tabs opened in the background I think)
> 
> I have fixed™ it temporarly on my side by wrapping the if/else block that calls `runJavascript` in a try/except block, but that's probably to broad and could ignore other RuntimeExceptions which could be important.
> 
> It is very random, so difficult to reproduce but it happened at least once a week/every 2 weeks before I patched it out locally.
> I am running the latest qutebrowser v3.3.1.
>
> The last of the logs before the crash if it can be of any use: https://paste.sr.ht/~nicolai_dagestad/81749d002d46d18e515bd6342668eb8de31d7eda

_Originally posted by @NDagestad in https://github.com/qutebrowser/qutebrowser/issues/6826#issuecomment-2501376788_

**Comment by NDagestad** [comment]
I can reproduce it quite reliably thanks to your explanations. 
1. Change the code to have a 2s delay instead of 65ms.
   (Install in a venv because I don't want my normal qutebrowser instance to crash 🙃)
2. Start a new instance with -T
3. Add `c.input.insert_mode.auto_load = True` to it's configuration
4. Open https://start.duckduckgo.com/ in a new tab and close it before 2s have elapsed.

This produces a crash every time.

Do you want me to do something specific to get more detailed logs or something ?

**Comment by The-Compiler** [comment]
Ah whoops, I didn't consider that this setting is `false` by default! Now I have a reliable reproducer (on my system at least):

```
qutebrowser --debug --temp-basedir  -s input.insert_mode.auto_load true about:blank ":cmd-later 200 open -t about:blank" ":cmd-later 260 tab-close" 
```

Nothing more you can do at this point (unless you want to think about how a proper fix would look like), thanks for asking!

The fix itself is probably straightforward - as you briefly mentioned already, the tricky part is to find a nice way to fix this without actually potentially catching unrelated issues. The easy solution would be for e.g. `find_focused` or even `run_js_async` to just abort if the page is gone, but I don't really like more generic utility functions just silently ignoring error conditions.

Maybe the timer could be connected to a helper method (instead of the lambda) which checks `self._tab.pending_removal` and does nothing if that's set to `true`. Will also need a (probably end2end) test to make sure it works and doesn't regress.

Will need to take care of other stuff for today (and possibly the rest of this week) unfortunately.

**Comment by The-Compiler** [comment]
I couldn't resist, here is a proper fix:

```diff
diff --git i/qutebrowser/browser/browsertab.py w/qutebrowser/browser/browsertab.py
index 74eacfcd0..18cf07f49 100644
--- i/qutebrowser/browser/browsertab.py
+++ w/qutebrowser/browser/browsertab.py
@@ -882,6 +882,24 @@ class AbstractTabPrivate:
         """Return the widget events should be sent to."""
         raise NotImplementedError
 
+    def _handle_auto_insert_mode_delayed(self) -> None:
+        def _auto_insert_mode_cb(elem: Optional["webelem.AbstractWebElement"]) -> None:
+            """Called from JS after finding the focused element."""
+            if elem is None:
+                log.webview.debug("No focused element!")
+                return
+            if elem.is_editable():
+                modeman.enter(self._tab.win_id, usertypes.KeyMode.insert,
+                              'load finished', only_if_normal=True)
+
+        if self._tab.pending_removal:
+            # tab being closed, no web page available anymore to run JS with
+            log.webview.debug("Ignoring auto insert mode as tab is being closed")
+            return
+
+        self._tab.elements.find_focused(_auto_insert_mode_cb)
+
+
     def handle_auto_insert_mode(self, ok: bool) -> None:
         """Handle `input.insert_mode.auto_load` after loading finished."""
         if not ok or not config.cache['input.insert_mode.auto_load']:
@@ -891,24 +909,12 @@ class AbstractTabPrivate:
         if cur_mode == usertypes.KeyMode.insert:
             return
 
-        def _auto_insert_mode_cb(
-                elem: Optional['webelem.AbstractWebElement']
-        ) -> None:
-            """Called from JS after finding the focused element."""
-            if elem is None:
-                log.webview.debug("No focused element!")
-                return
-            if elem.is_editable():
-                modeman.enter(self._tab.win_id, usertypes.KeyMode.insert,
-                              'load finished', only_if_normal=True)
-
         # There seems to be a race between loadFinished being called,
         # and the autoload attribute on websites actually focusing anything.
         # Thus, we delay this by a bit. Locally, a delay of 13ms caused no races
         # with 5000 test reruns (even with simultaneous CPU stress testing),
         # so 65ms should be a safe bet and still not be too noticeable.
-        QTimer.singleShot(
-            65, lambda: self._tab.elements.find_focused(_auto_insert_mode_cb))
+        QTimer.singleShot(65, self._handle_auto_insert_mode_delayed)
 
     def clear_ssl_errors(self) -> None:
         raise NotImplementedError

```

will still need a test though.

**Comment by The-Compiler** [comment]
Note to self, this was introduced in 982b8bdcecfba6fc1687a6a4942b9e3ab3221eb7 / v3.2.0.
