### ISSUE TITLE
FileNotFoundError in ipc.update_atime

### ISSUE THREAD

**Issue by The-Compiler** [qutebrowser/qutebrowser#996]
I can reproduce this somewhat reliably by running the tests in a loop on the Debian Jessie and Ubuntu Trusty buildbots:

```
============================= ERRORS =============================
________ ERROR at teardown of TestListen.test_atime_update _______
Qt exceptions in virtual methods:
________________________________________________________________________________
  File "/home/buildbotx/qutebrowser/qutebrowser/misc/ipc.py", line 368, in update_atime
    os.utime(path)

FileNotFoundError: [Errno 2] No such file or directory
________________________________________________________________________________

============================ FAILURES ============================
__________________ TestListen.test_atime_update __________________

self = <test_ipc.TestListen object at 0x7f08de08cac8>, qtbot = <pytestqt.qtbot.QtBot object at 0x7f08ddf01a90>, ipc_server = <qutebrowser.misc.ipc.IPCServer object at 0x7f08dec18288>

    @pytest.mark.posix
    def test_atime_update(self, qtbot, ipc_server):
        ipc_server._atime_timer.setInterval(500)  # We don't want to wait 6h
        ipc_server.listen()
        old_atime = os.stat(ipc_server._server.fullServerName()).st_atime_ns

        with qtbot.waitSignal(ipc_server._atime_timer.timeout, timeout=2000,
                              raising=True):
            pass

        # Make sure the timer is not singleShot
        with qtbot.waitSignal(ipc_server._atime_timer.timeout, timeout=2000,
                              raising=True):
            pass

>       new_atime = os.stat(ipc_server._server.fullServerName()).st_atime_ns
E       FileNotFoundError: [Errno 2] No such file or directory: '/tmp/qute-test'

tests/unit/misc/test_ipc.py:357: FileNotFoundError
-------------------------- Captured log --------------------------
ipc.py                     193 DEBUG    Not calling setSocketOptions
ipc.py                     204 DEBUG    Listening as qute-test
ipc.py                     367 DEBUG    Touching /tmp/qute-test
ipc.py                     367 DEBUG    Touching /tmp/qute-test
```

**Comment by The-Compiler** [comment]
So it seems the file is gone with the second `os.utime` and the subsequent `os.stat`... but how would it get lost in between? I don't see how without another test running in parallel...

**Comment by The-Compiler** [comment]
I got three reports on v0.4.1 and two on v0.4.0 of this happening so far. Seems to happen out of the blue.

**Comment by The-Compiler** [comment]
Here it even happened right after initializing:

```
==== Debug log ====
01:31:51 DEBUG    init       earlyinit:init_log:280 Log initialized.
01:31:51 DEBUG    init       app:__init__:736 Qt arguments: [...]
01:31:51 DEBUG    init       app:__init__:739 Initializing application...
01:31:51 DEBUG    ipc        ipc:_has_legacy_server:403 Trying to connect to qutebrowser-paschoal
01:31:51 DEBUG    ipc        ipc:_has_legacy_server:410 Socket error: QLocalSocket::connectToServer: Invalid name (2)
01:31:51 DEBUG    ipc        ipc:send_to_running_instance:451 Connecting to /run/user/1003/qutebrowser/ipc-ea0c4dc31bb97b52735f9398ec2acf4a
01:31:51 DEBUG    ipc        ipc:send_to_running_instance:484 No existing instance present (error 2)
01:31:51 DEBUG    init       ipc:send_or_listen:514 Starting IPC server...
01:31:51 DEBUG    ipc        ipc:__init__:192 Not calling setSocketOptions
01:31:51 DEBUG    ipc        ipc:listen:203 Listening as /run/user/1003/qutebrowser/ipc-ea0c4dc31bb97b52735f9398ec2acf4a
01:31:51 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.4.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 153, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 97, in run
    server = ipc.send_or_listen(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/ipc.py", line 516, in send_or_listen
    server.listen()
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/ipc.py", line 222, in listen
    os.chmod(self._server.fullServerName(), 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1003/qutebrowser/ipc-ea0c4dc31bb97b52735f9398ec2acf4a'
```

**Comment by The-Compiler** [comment]
Another one:

```
14:00:12 DEBUG    init       earlyinit:init_log:283 Log initialized.
14:00:12 DEBUG    init       app:__init__:749 Qt arguments: ['/usr/bin/qutebrowser'], based on Namespace(basedir=None, cachedir=None, color=True, command=[], confdir=None, datadir=None, debug=False, debug_exit=False, harfbuzz='auto', json_args=None, logfilter=None, loglevel='info', loglines=2000, no_err_windows=False, nowindow=False, override_restore=False, pdb_postmortem=False, qt_name=None, qt_qmljsdebugger=None, qt_reverse=None, qt_style=None, qt_stylesheet=None, qt_widgetcount=None, relaxed_config=False, session=None, target=None, temp_basedir=False, temp_basedir_restarted=None, temp_settings=[], url=[], version=False)
14:00:12 DEBUG    init       app:__init__:752 Initializing application...
14:00:12 DEBUG    ipc        ipc:_has_legacy_server:406 Trying to connect to qutebrowser-sune
14:00:12 DEBUG    ipc        ipc:_has_legacy_server:413 Socket error: QLocalSocket::connectToServer: Invalid name (2)
14:00:12 DEBUG    ipc        ipc:send_to_running_instance:454 Connecting to /run/user/1000/qutebrowser/ipc-82823c66542ee7d5533e58017052e3c4
14:00:12 DEBUG    ipc        ipc:send_to_running_instance:487 No existing instance present (error 2)
14:00:12 DEBUG    init       ipc:send_or_listen:517 Starting IPC server...
14:00:12 DEBUG    ipc        ipc:__init__:192 Not calling setSocketOptions
14:00:12 DEBUG    ipc        ipc:listen:203 Listening as /run/user/1000/qutebrowser/ipc-82823c66542ee7d5533e58017052e3c4
14:00:12 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/bin/qutebrowser", line 9, in <module>
    load_entry_point('qutebrowser==0.5.1', 'gui_scripts', 'qutebrowser')()
  File "/usr/lib/python3.5/site-packages/qutebrowser/qutebrowser.py", line 154, in main
    return app.run(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/app.py", line 97, in run
    server = ipc.send_or_listen(args)
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/ipc.py", line 519, in send_or_listen
    server.listen()
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/ipc.py", line 222, in listen
    os.chmod(self._server.fullServerName(), 0o700)
FileNotFoundError: [Errno 2] No such file or directory: '/run/user/1000/qutebrowser/ipc-82823c66542ee7d5533e58017052e3c4'
```

**Comment by The-Compiler** [comment]
> Notebook war die nacht über an und zugeklappt.
> Hab es eben aufgeklappt und die Meldung gesehen.

```
03:42:22 DEBUG    destroy    lineparser:_after_save:87 Saved to /home/fritz/.local/share/qutebrowser/cmd-history
09:35:20 DEBUG    ipc        ipc:update_atime:367 Touching /home/fritz/tmp/run/qutebrowser/ipc-8c63feed8b89ea9a6496ed92ed818ac2
09:35:20 ERROR    misc       crashsignal:exception_hook:211 Uncaught exception
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qutebrowser/misc/ipc.py", line 368, in update_atime
    os.utime(path)
FileNotFoundError: [Errno 2] No such file or directory
```

/cc @V155

**Comment by The-Compiler** [comment]
I just got the first report with launch/crash times, and it crashed after running *exactly* 6 hours... :worried:

From the [XDG basedir spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> Files in this directory MAY be subjected to periodic clean-up. To ensure that your files are not removed, they should have their access time timestamp modified at least **once every 6 hours** of monotonic time or the 'sticky' bit should be set on the file.

So either some desktop environment (?) is not following the spec, or we aren't updating the atime correctly...

**Comment by The-Compiler** [comment]
Some of the comments were actually in `ipc.listen` - I split them off to #1530.

**Comment by The-Compiler** [comment]
In some more crash reports (on Archlinux, one with xmonad) this happened after 6h and in another one after 24h...

**Comment by The-Compiler** [comment]
@JonathanReeve this is the bug you reported mid-december

**Comment by The-Compiler** [comment]
From the [XDG basedir specs](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html):

> Files in this directory MAY be subjected to periodic clean-up. To ensure that your files are not removed, they should have their access time timestamp modified at least once every 6 hours of monotonic time or the 'sticky' bit should be set on the file.

But when qutebrowser does that after 6h, the file is gone...

**Comment by fiete201** [comment]
So Perhaps do this every 3 hours?

**Comment by The-Compiler** [comment]
I'd expect it to be deleted after 6h and 5min or something if the spec says it should be updated at least once all 6h... But I did that now, let's see if it helps.

**Comment by The-Compiler** [comment]
I wonder if this is related somehow...

http://stackoverflow.com/questions/43051667
https://bugreports.qt.io/browse/QTBUG-60828

**Comment by fiete201** [comment]
Hmm, i didnt checked "our" code but it sounds interesting. Lets see what
the Qt dev concludes after getting the needed Information from the
reporter.

--

**Comment by The-Compiler** [comment]
Haven't seen this happen anymore since 99c7301fb4eb2679163675819e724eb65b2d2652 @The-Compiler so far.

**Comment by The-Compiler** [comment]
Still exists in v0.11: https://crashes.qutebrowser.org/view/5d39acc5

**Comment by xtaran** [comment]
And 1.6.0 as it seems. Happened to me twice this night.

**Comment by The-Compiler** [comment]
From talking to @xtaran:

- He was also getting this error when trying to restart:

![image](https://user-images.githubusercontent.com/625793/54022485-e4baf880-4192-11e9-9b72-1f1034fd926f.png)

- sysvinit and cron, no systemd
- started happening when upgrading to qutebrowser v1.6.0 (likely unrelated) and uninstalling `cgroupfs-mount`
